### ISSUE TITLE
issue: unknown issue with data transform

### ISSUE THREAD

**Issue by ribeaud** [react-hook-form/react-hook-form#7488] opened 2022-01-10 18:28 UTC
### Version Number

7.22.5

### Codesandbox/Expo snack

https://gitlab.com/biomedit/next-widgets/-/commit/6c4e1480402700fd08f375d0151ef4760a6ad81a

### Steps to reproduce

Hello folks,

sorry, this is my first bug report in **React** world and I am not very used to **Codesandbox**. For me it was quicker providing an example in a dedicated branch of our project. I hope this is OK.

In the link above, there is a self contained component named `MyHiddenField` (no external dependency). I provided a test file as well, named `MyHiddenField.test.tsx`.

If I run the test, it is green with _7.22.4_, and becomes red with _7.22.5_.

Thank you very much for your help... 💪 

### Expected behaviour

`NaN` should be converted into `undefined`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment] 2022-01-10 22:34
> `NaN` should be converted into `undefined`.

I don't think we have used functionality, which is potentially an edge case which you are running to. The only commit which could be related to is this: https://github.com/react-hook-form/react-hook-form/commit/8e6c495737c4df67706d4f134141b000975dbd99 which is the correct fix for the issue and pass all our tests.

i have also seen consume logic inside your component which worth for you to double-check too.

**Comment by ribeaud** [comment] 2022-01-11 10:30
Hi @bluebill1049. Thanks for your answer.

The commit you pointed to is the one I came across as well (although I do not fully understand which role exactly it should be playing in my case).

> Worth to mention we don't support `undefined` for input value as well.

What do you mean exactly? Is this new? What would be the right behaviour then?

**Comment by bluebill1049** [comment] 2022-01-11 10:59
> What do you mean exactly? Is this new? What would be the right behaviour then?

No, that's not new. This is by design from the very beginning.

**Comment by ribeaud** [comment] 2022-01-11 13:53
Thank you for the reminder.

I managed to create a **Codesandbox** [example](https://codesandbox.io/s/vigorous-merkle-o4jeb) reproducing my problem:
1. Click on _Submit_: `{hiddenField: "Hello"}` is displayed
1. Click on _Change_, followed by a _Submit_ click: `{hiddenField: undefined}` is displayed
1. Adapt **react-hook-form** version to _7.22.5_ and repeat first two steps

I am not saying that the current behaviour is wrong but we now have a discrepancy between both _7.22.4_ and _7.22.5_. If I now got you right, setting value to `undefined` does no longer work and I should use _empty_ string or `null` instead, correct?

Thank you so much for the great work and your time helping me to sort this out.

**Comment by bluebill1049** [comment] 2022-01-12 00:57
I can confirm the issue was fixed by: https://github.com/react-hook-form/react-hook-form/discussions/7341 and this is correct and expected behavior. It was "working" due to the bug inside the codebase, and as the documentation stated `undefined` is going to have another issue in your application with react hook form.

### why

`undefined` is reserved for input doesn't have a `defaultValue`, which allow hook form to refer to `defaulValues` at the `useForm` level, this is one of the convenient things about react hook form, so you can have inline `defaultValue` by not providing a global `defualtValues`.

### conclusion

Thank you for your detailed issue report and reproducible CSB, however, This is expected behavior and will not be changed.

**Comment by bluebill1049** [comment] 2022-01-13 22:09
closing this as its expected behavior.

**Closed by bluebill1049** 2022-01-13 22:09 UTC
Labels: question

**Comment by ribeaud** [comment] 2022-01-17 08:58
Just this short notice to let you know that, with the lastest version (_7.24.0_), we are back to the previous behaviour on our side.

**Comment by bluebill1049** [comment] 2022-01-17 09:04
Thanks for the heads up, although everything I have stated above still remains true to this library, and as far as I know no fix was made regarding this issue.
