### ISSUE TITLE
Invalid formState after reset

### ISSUE THREAD

**Issue by gdbrown** [react-hook-form/react-hook-form#3026] opened 2020-09-28 22:56 UTC
After reset has been called the formState becomes unreliable.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-forked-5ng3o?file=/src/index.js
2. Click `submit`, this is merely going to reset the form with the values currently present.
3. Touch some of the fields but don't change anything.
4. Notice that the form is now reporting it's dirty and has dirty fields but they have no changed.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-5ng3o?file=/src/index.js

**Expected behavior**
The formState should still be correct after reset has been called and further form actions have taken place.

**Desktop (please complete the following information):**
- OS: MacOS Catalina
- Browser: Firefox and Chrome show the issue
- Version: Firefox (80.0.1) and Chrome (85.0.4183.102)

**Additional context**
You can also experience some odd behavior if you append and remove items, sometimes it seems like it will get in sync but I haven't pinned down how to reproduce it the same every time.

e.g. submit the form, touch some fields (notice it's invalid), then append an item, then delete that item you just appended, now it seems correct again.  but it's not consistent.

**Comment by bluebill1049** [comment] 2020-09-28 23:01
`handleSubmit` is async, which means `onSubmit` callback will be invoked in parallel.

- option 1:
```
const onSubmit = (data) => {
    console.log("data", data);
    setTimeout(() => reset(data));
};
```
- option 2: trigger reset at `useEffect` eg: with `isSubmitSuccesfull`

**Comment by gdbrown** [comment] 2020-09-28 23:19
@bluebill1049 i tried option 1 to no avail...  updated the codesandbox.
```
  const onSubmit = (data) => {
    console.log("data", data);
    setTimeout(() => reset(data));
  };
```

**Comment by bluebill1049** [comment] 2020-09-28 23:42
<img width="666" alt="Screen Shot 2020-09-29 at 9 42 19 am" src="https://user-images.githubusercontent.com/10513364/94496566-147b9680-0238-11eb-9ef3-1f89c1184aea.png">

works for me.

**Comment by gdbrown** [comment] 2020-09-28 23:47
@bluebill1049 check this video https://recordit.co/vL4eFnC9A6
1. made a change
2. submitted it
3. focused on the first  field, then tabbed out, shows dirty but nothing has changed since last reset (with the setTimeout)

**Comment by bluebill1049** [comment] 2020-09-29 02:06
Take a look at the following example: 

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-prfw0?file=/src/index.js

- decouple reset with `handleSubmit`, it's troublesome when `reset` and `handleSubmit` both have update state and async problem, so `useEffect` is much safer, I will update the doc to reflect this as well.
- when invoke reset with value, it's important to supply all the `defaultValues`, otherwise dirty compare is difficult to predict the undeclared input value.

let me know if those above make sense. thanks for the issue report.

**Comment by gdbrown** [comment] 2020-09-29 04:19
@bluebill1049 i think I got it, thank you.  curious, without this reset after submit is it expected for the form to remain dirty?  meaning the formState remains with dirtyFields, isDirty, touched, etc. until you call reset at some point?

My scenario is that a user will make changes and likely stay on the form, they have options like save, save and close, save and publish, etc.

**Comment by bluebill1049** [comment] 2020-09-29 04:24
> @bluebill1049 i think I got it, thank you. curious, without this reset after submit is it expected for the form to remain dirty? meaning the formState remains with dirtyFields, isDirty, touched, etc. until you call reset at some point?

I think it's better to leave that decision to the users, rather hard code that logic internally.

> My scenario is that a user will make changes and likely stay on the form, they have options like save, save and close, save and publish, etc.

Yea, i think it's better to follow what i did above. The problem is basically this

```
handleSubmit(
  // updateState internally
    // async callback 
      // reset() updateState
  // updateState internally
)
```

To

```
handleSubmit(// do formState unrelated work)
reset() // reset the form
```

**Comment by gdbrown** [comment] 2020-09-29 04:26
got it, thank you!  feel free to close this issue.  left open in case you planned on updating any docs. 👍

**Comment by bluebill1049** [comment] 2020-09-29 04:36
thanks, @gdbrown for the issue report. let me know below is good enough for others, feel free to add your points or even submit a PR too 👍 
<img width="922" alt="Screen Shot 2020-09-29 at 2 36 32 pm" src="https://user-images.githubusercontent.com/10513364/94513098-2cb3db80-0261-11eb-8583-d2c4692243fd.png">

**Comment by bluebill1049** [comment] 2020-09-30 04:47
going to close this issue, feel free to leave your request or PR 👍

**Closed by bluebill1049** 2020-09-30 04:47 UTC
Labels: improve documentation

**Comment by gdbrown** [comment] 2020-09-30 05:00
@bluebill1049 right on, ty sir.  slammed with work atm.
