### ISSUE TITLE
Form Crashes On Error  in StorybookJS when using default validation... but works fine when using yup resolver

### ISSUE THREAD

**Issue by aaronksaunders** [react-hook-form/react-hook-form#4449] opened 2021-03-17 01:55 UTC
**Describe the bug**
When there is an error on submitting the form, the story crashes, see screenshot below. The code works as expected when all fields are filled out.

I found that if I replace validation with yup, then everything works as expected

**To Reproduce**

**Github Link (Required)**
https://github.com/aaronksaunders/react-hook-form-storybook

The component
```
import React from "react";
import { Controller, useFormContext } from "react-hook-form";

/**
 * Primary UI component for user interaction
 */
export const TestInputForm: React.FC<any> = () => {
  const methods = useFormContext();
  return (
    <>
      <input
        name="user"
        type="text"
        ref={methods.register({ required: true, maxLength: 80 })}
      />

      {/* <Controller
        control={methods.control}
        name="user"
        render={(
          { onChange, onBlur, value, name, ref },
          { invalid, isTouched, isDirty }
        ) => (
          <input
            name="user"
            type="text"
            onChange={onChange}
            ref={methods.register({ required: true, maxLength: 80 })}
          />
        )}
      /> */}

      <button type="submit">SAVE</button>
    </>
  );
};

```

The story
```
import React from "react";
// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
import { Story, Meta } from "@storybook/react/types-6-0";
import {  FormProvider, useForm } from "react-hook-form";
import { TestInputForm } from "./TestInputForm";

export default {
  title: "CMS/TestInputForm",
  component: TestInputForm,
} as Meta;

const Template: Story<any> = (args) => {
  const methods = useForm({
    defaultValues: { user: "", password: "" },
    mode: "onBlur",
  });
  const { handleSubmit } = methods;

  const onSubmit = (data: any) => {
    console.log(data);
  };

  return (
    <FormProvider {...methods}>
      <form onSubmit={handleSubmit(onSubmit)}>
        <TestInputForm />
      </form>
    </FormProvider>
  );
};

export const Default = Template.bind({});
Default.args = {};
```

**Expected behavior**
This works when using yup
The Story
```
import React from "react";
// also exported from '@storybook/react' if you can deal with breaking changes in 6.1
import { Story, Meta } from "@storybook/react/types-6-0";
import {  FormProvider, useForm } from "react-hook-form";
import { TestInputForm } from "./TestInputForm";

import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from "yup";

export default {
  title: "CMS/TestInputForm",
  component: TestInputForm,
} as Meta;

const Template: Story<any> = (args) => {

  const schema = yup.object().shape({
    user: yup.string().required(),
  });

  const methods = useForm({
    defaultValues: { user: ""  },
    mode: "onBlur",
    resolver: yupResolver(schema)
  });
  const { handleSubmit } = methods;

  const onSubmit = (data: any) => {
    debugger;
    console.log(data);
  };

  console.log(methods.errors)

  return (
    <FormProvider {...methods}>
      <form onSubmit={handleSubmit(onSubmit)}>
        <TestInputForm />
      </form>
    </FormProvider>
  );
};

export const Default = Template.bind({});
Default.args = {};

```

The Component
```
import React from "react";
import { useFormContext } from "react-hook-form";

export const TestInputForm: React.FC<any> = () => {
  const methods = useFormContext();
  return (
    <>
      <input
        name="user"
        type="text"
        ref={methods.register}
      />
      <button type="submit">SAVE</button>
    </>
  );
};

```

**Screenshots**

<img width="1334" alt="Screen Shot 2021-03-16 at 8 55 59 PM" src="https://user-images.githubusercontent.com/524953/111399610-13caa580-869c-11eb-8c9a-086154476460.png">

**Desktop (please complete the following information):**

- OS: Catalina 10.15.7
- Browser Edge - Version 87.0.664.75 (Official build) (64-bit)

**Additional context**

**Comment by bluebill1049** [comment] 2021-03-17 05:46
Do you have a repo of us to reproduce this?

could you provide more detail on which line is causing this error?
<img width="364" alt="Screen Shot 2021-03-17 at 4 46 04 pm" src="https://user-images.githubusercontent.com/10513364/111420963-44fcb180-8740-11eb-997e-ecbd980614ca.png">

**Comment by aaronksaunders** [comment] 2021-03-17 20:48
@bluebill1049 I have added a project link - https://github.com/aaronksaunders/react-hook-form-storybook

**Comment by bluebill1049** [comment] 2021-03-18 06:37
hey, @aaronjensen I think it's worth raising an issue at storybook. I couldn't figure out why this is causing the issue and here is the issue:

<img width="677" alt="Screen Shot 2021-03-18 at 5 37 26 pm" src="https://user-images.githubusercontent.com/10513364/111583479-9e341600-8810-11eb-98f9-9f8c0b628fcf.png">

**Comment by bluebill1049** [comment] 2021-03-19 23:48
any update on this issue?

**Comment by aaronksaunders** [comment] 2021-03-20 00:10
I wasn’t sure if I was to take action or whomever @aaronjensen is... or was that a typo?

Also this issue wasn’t in critical path, this week was going to figure out how to log it with storybooks this weekend

**Comment by leapful** [comment] 2021-03-21 14:24
@aaronksaunders @bluebill1049 

The root cause of this problem: 

Storybook is using react-element-to-jsx-string to transform story component and this library has method sortObject to sort prop values of the component.

Every prop values from story component will be sorted including "formState.errors" of react-hook-form.

With resolver (in this case is yup), after executing validation, "formState.errors" will be a plain object.

For example:
```

formState.errors = {  user: { message: 'error from yup' } }

```

Without resolver, default validation of react-hook-form is executing and produce a error object that also includes "ref" element (the target input element).

For example:
```
formState.errors = { user: { message: 'error', ref: input } }
```

At that time, method "sortObject" will try to sort input element too but this one is a mutated DOM element by React, it has a prop "_debugOwner" which is React Fiber node and a circular node object.

That's why the sample code got maximum call stack error.

@bluebill1049 :

It is possible to exclude "ref" for error object when using "validateField" ?

**Comment by bluebill1049** [comment] 2021-03-21 22:12
Thanks very much, @leapful for the detailed investigation. I don't think we can change that, this is one of the features from the hook form which errors will have an association with input (DOM) reference. I would seek help from the storybook instead of us.

**Comment by bluebill1049** [comment] 2021-03-21 22:13
I will leave this issue open for a couple more days and closing this as this is not something that we could tackle or change.

**Comment by bluebill1049** [comment] 2021-03-21 22:44
> I wasn’t sure if I was to take action or whomever @aaronjensen is... or was that a typo?
> 
> Also this issue wasn’t in critical path, this week was going to figure out how to log it with storybooks this weekend

sorry, I have tagged the wrong person. 🙏

**Closed** 2021-03-23 10:23 UTC
Labels: dependency, wont be worked on

**Comment by karrui** [comment] 2021-08-18 07:57
For those who came here after facing the exact same issue, Storybook has a workaround on their issue:
https://github.com/storybookjs/storybook/issues/12747
