### ISSUE TITLE
issue: isValid not consistent with errors while validation

### ISSUE THREAD

**Issue by blingblingredstar** [react-hook-form/react-hook-form#9454] opened 2022-11-28 03:59 UTC
### Version Number

7.39.6

### Codesandbox/Expo snack

https://codesandbox.io/s/empty-morning-j0yr37?file=/src/App.tsx

### Steps to reproduce

1. input 'aaaa', you can see there is an error message but the button is still enabled due to `isValid` is true

### Expected behaviour

1. If there is an error message, the button should be disabled

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nghieptiki** [comment] 2022-11-28 06:04
Something changed in `7.39.6`  the errors get from `formState.errors` always is empty 
```
const {formState} = useFormContext()
```

**Comment by bluebill1049** [comment] 2022-11-28 06:15
> Something changed in `7.39.6` the errors get from `formState.errors` always is empty
> 
> ```
> const {formState} = useFormContext()
> ```

https://github.com/react-hook-form/react-hook-form/issues/9455

**Comment by bluebill1049** [comment] 2022-11-28 06:26
This issue won't give an immediate fix, as promised race conditions will need to be planned and considered carefully.

**Comment by bluebill1049** [comment] 2022-11-28 07:20
@blingblingredstar https://codesandbox.io/s/wonderful-jang-i6xvt7?file=/src/App.tsx have a play with this dev build and see if you still can pick up edge cases, this won't be a patch, so probably will be released later on (if it works).

**Comment by f0-x** [comment] 2022-11-28 07:55
I was about to redo all of my forms using Context Provider. Thanks, guys 💙

**Comment by blingblingredstar** [comment] 2022-11-28 08:04
@bluebill1049 The link you provide still uses the 7.39.6, and I can't open the web editor in https://github.com/react-hook-form/react-hook-form/pull/9457
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/43870278/204224901-29a72a94-c06d-4ba6-8c31-41a3686a900c.png">
How can I help to verify this problem

**Comment by bluebill1049** [comment] 2022-11-28 08:21
> I was about to redo all of my forms using Context Provider. Thanks, guys 💙

sorry about the context api regression...

**Comment by bluebill1049** [comment] 2022-11-28 08:24
> @bluebill1049 The link you provide still uses the 7.39.6, and I can't open the web editor in #9457 <img alt="image" width="1494" src="https://user-images.githubusercontent.com/43870278/204224901-29a72a94-c06d-4ba6-8c31-41a3686a900c.png"> How can I help to verify this problem?

thanks, https://codesandbox.io/s/wonderful-jang-i6xvt7?file=/src/App.tsx try to hit that link again, it's using the latest build not 7.39.6

https://user-images.githubusercontent.com/10513364/204228940-2b8d916f-46c4-4f39-a51b-10ddd0bf5263.mov

**Comment by blingblingredstar** [comment] 2022-11-28 08:30
@bluebill1049 Just open the link https://codesandbox.io/s/wonderful-jang-i6xvt7?file=/src/App.tsx, seems it still uses 7.39.6 and the issue still exist
<img width="3170" alt="image" src="https://user-images.githubusercontent.com/43870278/204230016-0fe4d137-3afa-4f57-b444-49b636492bcb.png">

**Comment by bluebill1049** [comment] 2022-11-28 08:30
@blingblingredstar see the import statement it's pointing at local `./src` folder

**Comment by bluebill1049** [comment] 2022-11-28 08:34
@blingblingredstar please refer to the following: 



### Here are the key points:

- sync validation error will show an error right away because it aborts early by default
  - `criteriaMode` - `firstError` (If this is not desired, the developer will have to switch on `all`, so all validation on field level will be running against)
- `isValid` will evaluate the entire form validity and abort the previous validation result

**Comment by bluebill1049** [comment] 2022-11-28 08:45
nvm, the build is still buggy, but what I state above stays valid.

**Comment by blingblingredstar** [comment] 2022-11-28 08:54
@bluebill1049 Seems we have an issue while we have both sync validation and async validation. As a developer, I assume the isValid should be false if there is an error no matter how it comes.

**Comment by blingblingredstar** [comment] 2022-11-28 09:23
@bluebill1049 I just tried the new approach, seems it solves the case, great job!
But I see a weird thing when I input `aaaa`, there should be an error, but actually, it's not. I try to find a way to reproduce but it didn't show like that every time. I think it may involve some race condition about sync/async validation.
<img width="3195" alt="image" src="https://user-images.githubusercontent.com/43870278/204240221-fdfbc398-7f38-4754-9554-b63e64c2e80e.png">

**Comment by Segev95** [comment] 2022-11-28 09:55
Hey, I ran into the same issue in my app.
I'm using an async function for the validation.
The `isValid` field is true but the `errors` field has some errors.

![Uploading Screen Shot 2022-11-28 at 11.51.01.png…]()

**Comment by bluebill1049** [comment] 2022-11-28 10:05
> Hey, I ran into the same issue in my app. I'm using an async function for the validation. The `isValid` field is true but the `errors` field has errors. ![Screen Shot 2022-11-28 at 11.51.01.png](https://user-images.githubusercontent.com/29043050/204249456-29704ef1-a36c-4ad2-aa5e-4d05a74b1bdd.png)

This is a regression introduced in the last path, i am looking for a better solution before roll it back.

**Comment by bluebill1049** [comment] 2022-11-28 10:06
Another enhanced version: https://codesandbox.io/s/heuristic-brown-0qxrsc?file=/src/App.tsx I think we can draw the line up to this point, this should resolve most of the async combine with sync valdiation.

**Comment by bluebill1049** [comment] 2022-11-28 23:01
@blingblingredstar let me know if you want to verify the fix before I close this issue with PR.

**Closed** 2022-11-29 02:48 UTC
Labels: enhancement, regression

**Comment by blingblingredstar** [comment] 2022-11-29 03:00
@bluebill1049 This works for me, thanks for you work!

**Comment by bluebill1049** [comment] 2022-11-29 03:07
> @bluebill1049 This works for me, thanks for you work!

Thanks for the confirmation and testing! Will add you as contributor into the release note.
