### ISSUE TITLE
Watched inputs with `null` value cause TypeError

### ISSUE THREAD

**Issue by alexgoldz** [react-hook-form/react-hook-form#2255] opened 2020-07-16 09:48 UTC
**Describe the bug**
Watching an input component with a null default value causes an TypeError in `utils/getPath`

**To Reproduce**
1. Go to 'https://codesandbox.io/s/react-hook-form-useform-template-28yig?file=/src/index.js'
2. Click on 'Submit'
3. See error

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-useform-template-28yig?file=/src/index.js

**Expected behavior**
Expect that you can watch an input with null values

**Additional context**
Bug was introduced in version 6.0.6

**Comment by bluebill1049** [comment] 2020-07-16 09:55
Thanks @alexgoldz fix is already merged https://github.com/react-hook-form/react-hook-form/pull/2248 will release soon.

**Comment by pixel-mattp** [comment] 2020-07-17 13:00
We are getting this issue in V 6.0.7 (latest release), when using `watch`.  
If we load an entry, come out of it and reload another entry, we get this error.....

<img width="1085" alt="Screenshot 2020-07-17 at 13 42 06" src="https://user-images.githubusercontent.com/14015763/87788727-c01a6a80-c835-11ea-9224-0121a02f8ba5.png">
<img width="1056" alt="Screenshot 2020-07-17 at 13 42 15" src="https://user-images.githubusercontent.com/14015763/87788730-c27cc480-c835-11ea-8575-90610127c2f0.png">

This only started to happen on latest versions.

**Comment by bluebill1049** [comment] 2020-07-17 13:02
hey @pixel-mattp that's bad, can you help to reproduce this in a codesandbox?

**Comment by pixel-mattp** [comment] 2020-07-17 13:04
@bluebill1049 - I will try, but this is all hooked up to our API etc so may be difficult to reproduce....  Let me try and see if I can get it to error on Sandbox.

**Comment by bluebill1049** [comment] 2020-07-17 13:05
what's `calculations`? is that an inptu?

**Comment by pixel-mattp** [comment] 2020-07-17 13:06
@bluebill1049 - calculations is an object being returned from an endpoint.  It's not a 'field' so to speak - but we are 'watching` the values as we run some calculations based on them and populate other fields with the result.

**Comment by bluebill1049** [comment] 2020-07-17 13:09
oh i see, could you please help reproduce a codesandbox, i am working on a fix. thanks very much or helping out in advance.

**Comment by bluebill1049** [comment] 2020-07-17 13:12
i have a fix in place, just need to verify the fix now.

**Comment by pixel-mattp** [comment] 2020-07-17 13:13
To confirm, I am registering the input `calculations`.  It seems to fix when you hard refresh the page, so may be caused when data from the API is being set in the form, replacing previous values.

**Comment by bluebill1049** [comment] 2020-07-17 13:14
it's definitely a bug, i will write unit test to prove it and iron down the problem. lucky it's friady night here.

**Comment by pixel-mattp** [comment] 2020-07-17 13:15
@bluebill1049 - great stuff!  Thanks for your prompt support.

**Comment by bluebill1049** [comment] 2020-07-17 13:16
oh man, i am sorry to breaking this...

**Comment by bluebill1049** [comment] 2020-07-17 13:18
hmmm i couldn't reproduce this in a unit test, please keep helping see if you can reproduce this.

**Comment by bluebill1049** [comment] 2020-07-17 13:20
how did undefined/null getting into this part.

<img width="508" alt="Screen Shot 2020-07-17 at 11 19 59 pm" src="https://user-images.githubusercontent.com/10513364/87790538-0a2a3d00-c884-11ea-8597-f0e4ea4c9ef1.png">

**Comment by bluebill1049** [comment] 2020-07-17 13:22
falsy alarm @pixel-mattp you had a cache 👍 
<img width="574" alt="Screen Shot 2020-07-17 at 11 22 24 pm" src="https://user-images.githubusercontent.com/10513364/87790746-6ee59780-c884-11ea-9cca-deb281b1ba5a.png">

**Comment by bluebill1049** [comment] 2020-07-17 13:23
look at your screenshot above, it's old version.

**Closed by bluebill1049** 2020-07-17 13:22 UTC

**Comment by pixel-mattp** [comment] 2020-07-17 13:31
<img src="https://media.giphy.com/media/yvBAuESRTsETqNFlEl/giphy.gif" />

**Comment by pixel-mattp** [comment] 2020-07-17 13:32
Damn!!!  Sorry.  Thanks v much for looking into this so quick

**Comment by bluebill1049** [comment] 2020-07-17 13:33
no worries, however, I did find an improvement so it's not all for nothing. 👍
