### ISSUE TITLE
Why is Controller fieldState naming inconsistent?

### ISSUE THREAD

**Issue by GollyJer** [react-hook-form/react-hook-form#8195] opened 2022-04-15 18:12 UTC
In formState 👉  `isValid` - boolean - Set to true if the form doesn't have any errors.
In fieldState 👉 `invalid` - boolean - Invalid state for current input.

This threw me off a bit. Had to go to the docs to find the `invalid` return object.

Just curious if this is a purposeful difference, and if so what is the reason?

Best,
Jeremy

**Comment by Moshyfawn** [comment] 2022-04-15 18:45
Hey, @GollyJer!

I've updated the API to include `isValid` convention for the field's validation state.

@bluebill1049 u can freely reject my PR if he API is supposed to be different between the form validation state and the field's one

**Comment by bluebill1049** [comment] 2022-04-15 23:25
Thanks, guys for the input. @Moshyfawn I think this will be introducing a breaking change to the existing version. This is actually by design, we have form level state `isValid` which leads by when the user subscribes to the form validity.  For field level, at the moment we don't trigger every field input and flush down errors that include `onChange` mode, that's why the initial state of input will remain invalid as `false` unless an error state appears. I understand this is not a consistent API, but unless we start to support another form state such as `validateFields`, we will have to keep the API as `invalid` for now.

**Closed** 2022-04-16 08:19 UTC
Labels: waiting-up-vote, feature request

**Comment by Moshyfawn** [comment] 2022-04-16 08:26
I see your point, @bluebill1049! It is a breaking change and having V8 on the horizon, I understand how inconvenient it would be.

Maybe we can re-visit the API consistency once the V8 is out the door.

One additional thing, tho: what's the point of `fieldState.invalid` again? In docs it's usually show to check for the `errors.fieldName` and not much of `fieldState.invalid` usage. Is the invalid state really necessary?
```jsx
{errors.fieldName && <p role="alert">{errors.fieldName.message}</p>}
```

**Comment by bluebill1049** [comment] 2022-04-16 09:13
yes, @Moshyfawn let's deprecate that field state, I don't think it's server too much value. if you want to adjust your PR and point to v8?

**Comment by Moshyfawn** [comment] 2022-04-16 09:16
Sounds good!
