### ISSUE TITLE
Skip validations if a field is not required

### ISSUE THREAD

**Issue by dandv** [react-hook-form/react-hook-form#1781] opened 2020-06-04 20:49 UTC
**Is your feature request related to a problem? Please describe.**
I have registered an optional text field with several validators. I think the validators should not run if the field is empty, because it's optional, and an empty optional field is by definition valid.

[The sandbox](https://codesandbox.io/s/react-hook-form-required-false-should-bypass-validate-u88tm?file=/src/index.js) illustrates just one validation for simplicity.

**Describe the solution you'd like**
**If** a field is empty and it was registered with `required: false` or without `required` specified, **then** skip running the `validate` functions.

Logical reasoning:

Here are all 6 combinations of a field (empty vs. non-empty) and `required` (true, false, undefined):

* field empty
  * (1) required: true -> error already, no need to run validators
  * (2) required: false -> no error, no need to run validators because there's nothing to validate
  * (3) required not specified -> no error, no need to run validators because there's nothing to validate
* field non-empty
  * (4) required: true -> no error yet, run validators for further validation
  * (5) required: false -> no error yet, run validators for further validation
  * (6) required not specified: no error yet, run validators for further validation

My proposal is to not run validators in cases (2) and (3). Validators should be run in all other cases.

The only exception I can think of for cases (2) and (3) is if the field has a validator that checks for content (minimum length, regexp match etc.), but that means **the field should have been declared with `{ required: true }` in the first place**, which falls under cases (1) or (4), and validators should be run in those cases.

**Describe alternatives you've considered**

Currently, I have to prefix each validator to return true if the field value is empty:

```js
validate: {
  rule1: value => value === '' || actualValidationLogic(value) || message;
  rule2(value) {
    if (value === '')
      return true;
    // ... actual validation logic
  }
  ...
}
```

This is redundant and inelegant.

**Additional context**

![image](https://user-images.githubusercontent.com/33569/83808796-3ee28c00-a66a-11ea-8aee-72e9be69231e.png)

**Benefits of adopting this proposal**

* Cleaner code. Validators no longer need to check for empty values.
* Faster validation for empty non-required fields by skipping validation altogether.

**Comment by bluebill1049** [comment] 2020-06-04 22:52
hey @dandv why not write that logic inside `validate` function, probably not a lot easier that way?

**Comment by dandv** [comment] 2020-06-05 04:42
The reason not to check for `''` in every validator is that it's repetitive and inelegant. Currently I do have this in my code and it doesn't look that nice :)

```js
validate: {
  rule1: value === '' || actualValidationLogic(value) || message;
  rule2(value {
    if (value === '')
      return true;
    // ... actual validation logic
  }
  ...
}
```

It would also be faster if RHF skipped calling each validator for optional fields that are empty.

**Comment by bluebill1049** [comment] 2020-06-05 04:48
what about the following: 

```
validate: (value) => {
  if (value === '') return true;

  return actualValidationLogic(value) || message;
}
```

**Comment by dandv** [comment] 2020-06-05 09:00
Yes, that's pretty much what I wrote in [my comment](https://github.com/react-hook-form/react-hook-form/issues/1781#issuecomment-639254914), sorry for the syntax errors, edited now.

The problems remain, repetitive unnecessary ugly code.

Semantically, if a field is empty, what is the point of running validators? What content can they validate?

**Comment by bluebill1049** [comment] 2020-06-05 09:13
I disagree, `required: false` is by default, it should treat differently when it's been specified to be `false`.

**Comment by dandv** [comment] 2020-06-05 09:20
I'm not sure I understand... what should be treated differently and how, if `require` is omitted, vs. if `require` is explicitly set to `false`?

As far as I currently understand (but I'm new to RHF so I might be missing something), here are all 6 combinations of a field (empty vs. non-empty) and `required` (true, false, undefined):

* field empty
  * (1) required: true -> error already, no need to run validators
  * (2) required: false -> no error, no need to run validators because there's nothing to validate
  * (3) required not specified -> no error, no need to run validators because there's nothing to validate
* field non-empty
  * (4) required: true -> no error yet, run validators for further validation
  * (5) required: false -> no error yet, run validators for further validation
  * (6) required not specified: no error yet, run validators for further validation

Is the above table of truth correct?

If so, I'll continue my argument. If I'm mistaken, I will revise my understanding of validation. Thanks :)

**Comment by bluebill1049** [comment] 2020-06-05 09:22
> I'm not sure I understand... what should be treated differently and how, if `require` is omitted, vs. if `require` is explicitly set to `false`?

make no difference, you shouldn't need to specify `required: false`.

**Comment by bluebill1049** [comment] 2020-06-05 09:23
by the way, I am more than happy to discuss this, by default `required: false`.

```
<input ref={regsiter}  /> // required: false which you should declare
<input ref={regsiter({ required: true })}  /> // required: false which you should declare
```

**Comment by dandv** [comment] 2020-06-05 09:32
There seems to be some communication problem here... One hand you said

> I disagree, `required: false` is by default, it should treat differently when it's been specified to be `false`.

When I asked *how* it should be treated differently and what "it" is, the reply was

> make no difference, you shouldn't need to specify `required: false`.

??? It's late here, I'll go sleep and read the whole thread in the morning :)

**Comment by bluebill1049** [comment] 2020-06-05 09:40
have a good night. 

**Summarise:**

you don't need `{required: false}`, because it doesn't make any difference when you did not specify `required`.

`<input ref={register} /> === <input ref={register({ required: false })} />`

I understand that you want to skip validation with `required: false`, however, that's not the currently expected behavior and we are not going to change that.

**Comment by dandv** [comment] 2020-06-05 20:48
Hi @bluebill1049, I've completely rewritten my proposal, clarifying the logical reasoning behind it. Please take another look? Also, if someone else might want to take a look in case I wasn't clear and another perspective would help, or maybe they can find a counter-example - @JeromeDeLeon , @kotarella1110? Thanks everyone for your time.

**Comment by bluebill1049** [comment] 2020-06-05 23:16
Thanks for updating @dandv the description. I will vote for no change for now.

**Comment by bluebill1049** [comment] 2020-06-09 11:50
closing this feature request and added to pending.

**Closed by bluebill1049** 2020-06-09 11:50 UTC
Labels: feature request, waiting-up-vote

**Comment by dandv** [comment] 2020-06-09 19:00
> I will vote for no change for now.

I'm curious about the reasons.

But if it's just a matter of style / personal preference, no problem, you da boss @bluebill1049 ! Thanks again for all the work on the library.

**Comment by bluebill1049** [comment] 2020-06-09 22:45
> I'm curious about the reasons.

I didn't like it when required = false does something different and have dependency between validation logic. 

I am monitoring all the feature requests, if many people want this feature, we will implement it.
you can take a look at the list here: https://github.com/react-hook-form/react-hook-form/projects/1 definitely not killing your idea here.

**Comment by dandv** [comment] 2020-06-29 04:44
![image](https://user-images.githubusercontent.com/33569/85973710-8669e880-b988-11ea-8b3a-0e7a1aef60f8.png)

The tooltip for that label should be "Waiting for more upvotes"?

**Comment by bluebill1049** [comment] 2020-06-29 05:02
updating all the descriptions. Thanks

**Comment by gauravkrp** [comment] 2020-08-24 13:07
> > I'm curious about the reasons.
> 
> I didn't like it when required = false does something different and have dependency between validation logic.
> 
> I am monitoring all the feature requests, if many people want this feature, we will implement it.
> you can take a look at the list here: https://github.com/react-hook-form/react-hook-form/projects/1 definitely not killing your idea here.

https://github.com/react-hook-form/react-hook-form/issues/1691

Awaiting @bluebill1049 you to please implement this...

**Comment by risardi123** [comment] 2020-09-01 04:18
I think it's a bug. I was implement validation form using yup object and still got validation error without place .required()
Here is the proof @bluebill1049.

<img width="1050" alt="Screen Shot 2020-09-01 at 11 17 34" src="https://user-images.githubusercontent.com/29408156/91794245-c6797000-ec44-11ea-89ad-c2037c4b729d.png">

<img width="469" alt="Screen Shot 2020-09-01 at 11 16 13" src="https://user-images.githubusercontent.com/29408156/91794187-9fbb3980-ec44-11ea-81bd-fedd55da8037.png">

**Comment by bluebill1049** [comment] 2020-09-01 04:22
> I think it's a bug. I was implement validation form using yup object and still got validation error without place .required()
> Here is the proof @bluebill1049.
> 
> <img alt="Screen Shot 2020-09-01 at 11 17 34" width="1050" src="https://user-images.githubusercontent.com/29408156/91794245-c6797000-ec44-11ea-89ad-c2037c4b729d.png">
> 
> <img alt="Screen Shot 2020-09-01 at 11 16 13" width="469" src="https://user-images.githubusercontent.com/29408156/91794187-9fbb3980-ec44-11ea-81bd-fedd55da8037.png">

This is not related to this issue, please send a question at Discussion with codesandbox and really need more details then a screenshot.

**Comment by risardi123** [comment] 2020-09-01 04:40
Here is the example of code @bluebill1049 .
https://codesandbox.io/s/elastic-moser-9r033?file=/src/App.js

**Comment by bluebill1049** [comment] 2020-09-01 04:45
> Here is the example of code @bluebill1049 . When i use .length() but without .required(). the validation still running.
> https://codesandbox.io/s/elastic-moser-9r033?file=/src/App.js

That's because you are set the input be the exact length of 6 right?

<img width="1247" alt="Screen Shot 2020-09-01 at 2 44 38 pm" src="https://user-images.githubusercontent.com/10513364/91795700-ac01bf80-ec61-11ea-8bd9-35983cb0408e.png">

I would test your schema with raw data.

**Comment by risardi123** [comment] 2020-09-01 04:50
I think for the example, when we dont use .required(), the validation form should skip to the next step.

But, Thanks @bluebill1049

**Comment by risardi123** [comment] 2020-09-03 03:04
Any update for this bill?


@bluebill1049

**Comment by risardi123** [comment] 2020-09-09 04:15
I got the solution @bluebill1049, I am realize that yup object is promise(), so if i place .min(), it's still run the validation. So i use this solution like this. here is the codeSanbox link: https://codesandbox.io/s/boring-ramanujan-q3c54?file=/src/App.js

**Comment by Tymek** [comment] 2020-09-12 21:01
Boolean with 3 different states (`true`, `false`, `undefined`) has a potential to be *very* confusing. :thinking: In my personal opinion, and from what I've seen in other software, using additional parameter like `allowEmpty: true` is a good alternative to this proposal. What do you think @dandv?

**Comment by Wippy** [comment] 2020-12-30 04:25
> > > I'm curious about the reasons.
> > 
> > 
> > I didn't like it when required = false does something different and have dependency between validation logic.
> > I am monitoring all the feature requests, if many people want this feature, we will implement it.
> > you can take a look at the list here: https://github.com/react-hook-form/react-hook-form/projects/1 definitely not killing your idea here.
> 
> #1691
> 
> Awaiting @bluebill1049 you to please implement this...

Please implement this, I'm creating a dynamic Yup schema from a JSON response and it would very helpful to skip validations just by not adding required() rule when the key "required" on the form element object comes with the value "false":

<img width="218" alt="Screen Shot 2020-12-29 at 22 24 25" src="https://user-images.githubusercontent.com/4733191/103329909-a4da9a80-4a24-11eb-9aa5-e299b491f55b.png">

**Comment by paufar** [comment] 2021-02-09 03:22
Is there a way to validate a field without it being required? Adding validation to the Controller is stopping the form from submitting. Would be good to be able to add both properties to the rules like this so that the validation can occur when the field is full but does not stop the form from submitting if the field is empty. 
 
`rules={{
            required: false,
            validate: () => {
              return getValues("firstName") === "bill";
            }
          }}` 

https://codesandbox.io/s/controller-rules-forked-okk7e?file=/src/App.tsx

**Comment by bluebill1049** [comment] 2021-02-09 03:27
> @bluebill1049 Is there a way to validate a field without it being required? Adding validation to the Controller is stopping the form from submitting. Would be good to be able to add both properties to the rules like this so that the validation can occur when the field is full but does not stop the form from submitting if the field is empty.
> 
> `rules={{ required: false, validate: () => { return getValues("firstName") === "bill"; } }}`
> 
> https://codesandbox.io/s/controller-rules-forked-okk7e?file=/src/App.tsx

I believe you can write them inside `validate` function and remove that `required`.

**Comment by paufar** [comment] 2021-02-09 03:30
> > @bluebill1049 Is there a way to validate a field without it being required? Adding validation to the Controller is stopping the form from submitting. Would be good to be able to add both properties to the rules like this so that the validation can occur when the field is full but does not stop the form from submitting if the field is empty.
> > `rules={{ required: false, validate: () => { return getValues("firstName") === "bill"; } }}`
> > https://codesandbox.io/s/controller-rules-forked-okk7e?file=/src/App.tsx
> 
> I believe you can write them inside `validate` function and remove that `required`.

Can you show example please? cause i couldn't get it to work since i'm not sure what the correct syntax is. thanks

**Comment by bluebill1049** [comment] 2021-02-09 03:34
```
validate: (data: string) => {
   if (!data) return true;
   
   if (data) {
     return datta === 'yes'
   }
}
```

**Comment by paufar** [comment] 2021-02-09 05:07
Thanks!

**Comment by paufar** [comment] 2021-02-09 06:26
@bluebill1049 What if the validation of the input is to check whether there is a value !== "" ? 
If i want to set the input as not required so that it doesn't stop the form from submitting, but then i want to validate it to check whether the fields are all full?

**Comment by ramirezsandin** [comment] 2021-11-04 11:10
> **Is your feature request related to a problem? Please describe.** I have registered an optional text field with several validators. I think the validators should not run if the field is empty, because it's optional, and an empty optional field is by definition valid.
> 
> [The sandbox](https://codesandbox.io/s/react-hook-form-required-false-should-bypass-validate-u88tm?file=/src/index.js) illustrates just one validation for simplicity.
> 
> **Describe the solution you'd like** **If** a field is empty and it was registered with `required: false` or without `required` specified, **then** skip running the `validate` functions.
> 
> Logical reasoning:
> 
> Here are all 6 combinations of a field (empty vs. non-empty) and `required` (true, false, undefined):
> 
> * field empty
>   
>   * (1) required: true -> error already, no need to run validators
>   * (2) required: false -> no error, no need to run validators because there's nothing to validate
>   * (3) required not specified -> no error, no need to run validators because there's nothing to validate
> * field non-empty
>   
>   * (4) required: true -> no error yet, run validators for further validation
>   * (5) required: false -> no error yet, run validators for further validation
>   * (6) required not specified: no error yet, run validators for further validation
> 
> My proposal is to not run validators in cases (2) and (3). Validators should be run in all other cases.
> 
> The only exception I can think of for cases (2) and (3) is if the field has a validator that checks for content (minimum length, regexp match etc.), but that means **the field should have been declared with `{ required: true }` in the first place**, which falls under cases (1) or (4), and validators should be run in those cases.
> 
> **Describe alternatives you've considered**
> 
> Currently, I have to prefix each validator to return true if the field value is empty:
> 
> ```js
> validate: {
>   rule1: value => value === '' || actualValidationLogic(value) || message;
>   rule2(value) {
>     if (value === '')
>       return true;
>     // ... actual validation logic
>   }
>   ...
> }
> ```
> 
> This is redundant and inelegant.
> 
> **Additional context**
> 
> ![image](https://user-images.githubusercontent.com/33569/83808796-3ee28c00-a66a-11ea-8aee-72e9be69231e.png)
> 
> **Benefits of adopting this proposal**
> 
> * Cleaner code. Validators no longer need to check for empty values.
> * Faster validation for empty non-required fields by skipping validation altogether.

I've been using Formik with Yup for quite a while now and decided to try this react-hook-form. At first it seemed nice, but then I run into problems like this one.

I have an optional field in the form with some rules to validate if the user enters something. The thing is that the validation fails when nothing is written in the field.

This behaviour is odd, the Yup schema is the same, and it was working as expected with Formik. After @dandv opened this, I don't understand why this issue was not corrected.

This is the schema example. name and description are required fields, subtitle is optional. Validation fails when subtitle is left blank with ".min(3, 'The subtitle must have at least 3 characters.')"
```
const formValidationSchema = object({
    name: string()
        .min(3, 'The name must have at least 3 characters.')
        .max(128, 'The name cannot be longer than 128 characteres.')
        .required('Please enter a name.'),
    subtitle: string()
        .min(3, 'The subtitle must have at least 3 characters.')
        .max(128, 'The subtitle cannot be longer than 128 characteres'),
    description: string()
        .required('Please enter a description.'),
})
```

**Comment by abdurrahimkh** [comment] 2022-08-09 05:05
is This Feature Added ?

**Comment by abdurrahimkh** [comment] 2022-08-09 05:06
Is this feature  added ? i also want Skip validations if a field is not required

**Comment by jordanlesich** [comment] 2022-08-17 20:11
Yeah, agree with most folks on this thread. We should skip validation checks for empty, non-required fields.

**Comment by craigmcc** [comment] 2022-08-17 20:42
I don't know if this applies to your use case, but I also use Yup for validation -- and had to add ".nullable()" to my validation rules for optional fields, wherever I included a null value in defaultValues (which as fairly common for me, since my database is designed that way).

It looks like the underlying issue is that RHF renders such values as "" when it renders the form (which makes sense) -- but Javascript thinks that "" is falsy.
