### ISSUE TITLE
How to properly setValue() to custom controlled components after calling reset() ?

### ISSUE THREAD

**Issue by dadouam** [react-hook-form/react-hook-form#683] opened 2019-12-18 13:20 UTC
**Describe the question?**
Hello,
First of all, let me thank you for this awesome lib, we've been using it with great success so far in our application and we find it very easy to use and even the integration with custom components has been easy so far! 👍

I came across a strange behavior just today with the reset() method but I'm unsure whether to call it a bug or if I'm just doing it wrong.
For context, we send a form to the server, and the server responds with an updated form, which we use to reset the form with `reset(myServerForm)` (we use this mainly to reset the `dirty` formState).

According to the docs (https://react-hook-form.com/api#reset), the `reset` method does not work with controlled components, and indeed in our case, the controlled component value went back to the initial value (we set the initial value in a `useEffect` hook, just after the `register` by using the value provided by `watch`, this works pretty well). It suggests to use `setValue` instead, but I'm unsure where and how.

I tried different things :
```typescript
const myValue = watch("name");
useEffect(() => {
    register(...);
    setValue("name", myValue);
}, [register]);
```
This works for initialization, but does not work on reset(), it takes the default value.

```typescript
reset(myServerForm);
setValue("name", myServerForm.name);
```
This does not work either. Actually, to get it to work, I had to either use setTimeout or store the "initial" form data in a state, and call setValue in a `useEffect` when it changes from the server response (in both cases, I can see the form flickering a bit since it goes back to the default value).

Thanks again for this great lib!

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-reset-react-native-and-controlled-components-f73us?fontsize=14&hidenavigation=1&theme=dark

In the attached Codesandbox, I try to change the default values of controlled components by clicking on the "Reset" button, I try that by calling reset() directly and then by calling setValue (both methods don't work). 
Also, when I retried later this day, I noticed that if I input something after clicking on the button, the form values change!

**Comment by bluebill1049** [comment] 2019-12-18 21:08
Hey @dadouam thanks for the kind words. have you tried RHFInput (we are thinking of moving it into the main repo) for this issue (i assumed you are using controlled component)? I will read a bit more on your issue later today.

**Comment by bluebill1049** [comment] 2019-12-19 05:24
here is a working version: https://codesandbox.io/s/react-hook-form-reset-react-native-and-controlled-components-qij3f

Note: on V4 we are moving RHFInput into the main repo and it's much easier to use too

right now: https://github.com/react-hook-form/react-hook-form-input

V4 
```
import { RHFInput } from 'react-hook-form';

const { control } =  useForm();

<RHFInput name="test" as={<Select />} control={control} />
```

**Comment by dadouam** [comment] 2019-12-19 10:14
Thank you for your quick reply, I took a look at RHFInput and got it to work with our custom component! 👍 

So my understanding is that there's no simple way to reset the form for controlled components without using RHFInput ?

**Comment by bluebill1049** [comment] 2019-12-19 10:15
with controlled component, you would need to RHFInput, however with uncontrolled you can reset() easily, as long as RHF can capture the input `ref`. By the way, there is a hidden gem with RHFInput, you should see your form is no longer re-render while typing. :)

**Closed** 2019-12-19 10:24 UTC
Labels: question

**Comment by ppulwey** [comment] 2021-07-09 12:51
I also stumbled upon this problem today. After the reset, setValue no longer shows any effect.
Since the issue is quite old, is there a solution by now that I have overlooked?

My solution at the moment looks like this:

``` TypeScript
const { handleSubmit, formState, control, setValue, register, getValues } =
    useForm<ComponentFormData>({
      mode: "onBlur",
      defaultValues: {
        name: "",
      },
      shouldFocusError: true,
    });

const handleCancel = () => {
    props.onModalClose();
    resetForm(getValues());    
  };

  const resetForm = (formFields: Object) => {
    for (const currKey of Object.keys(formFields)) {
      setValue<any>(currKey, "");
    }
  };

```
