### ISSUE TITLE
Move from useFieldArray reset my nested fields.

### ISSUE THREAD

**Issue by Benjpoirier** [react-hook-form/react-hook-form#1765] opened 2020-06-03 14:53 UTC
**Describe the bug**
Hi,

First of all, sorry if there are some points not quite understandable, i’m not English, so I will do my best.

I’m currently working on a form with 2 levels of dynamic nested fields.
I handle the first one with `useFormField` which gives me good behavior.
The problem is on the second level of nested fields when I try to move down using move or swap function the nested fields are rested

I also experiment with a bug with the "answers" default value, I quickly fix it with: 

```js
React.useEffect(() => {
    if (fields.length === 0) {
        append(["", ""])
    }
}, [fields, append])
```
But it's a quite bad approach imo

it is a bug or I’m doing it the wrong way?

Thx for your answer
**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-02cr1

**Expected behavior**
When I move down the first field I should keep my "answers"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac Catalina 10.15.5
 - Browser chrome
 - Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by bluebill1049** [comment] 2020-06-03 22:55
hey @Benjpoirier your English is fine. :)

this is expected behavior, each `useFieldArray` hold it's own reference and inputs, so when you move the children will get potentially gets unmounted. I will give it a try myself and see if it's capable. worse case you will have to implement this yourself.

**Comment by bluebill1049** [comment] 2020-06-04 00:13
looks like it's working: https://codesandbox.io/s/react-hook-form-usefieldarray-template-88bnd?file=/src/index.js

**Comment by Benjpoirier** [comment] 2020-06-04 07:09
thx for this working example,

My version was up to date on my app, so I dug into my problem, and, in fact, I was displaying the nested fields with a condition based on a watch. `watch(`(${props.name}[${index}].type`)`
https://codesandbox.io/s/react-hook-form-usefieldarray-template-xm6c6

I think `watch` lost the reference on unmount, but how can I handle this kind of behavior properly?

**Comment by bluebill1049** [comment] 2020-06-04 07:13
> thx for this working example,
> 
> My version was up to date on my app, so I dug into my problem, and, in fact, I was displaying the nested fields with a condition based on a watch.
> https://codesandbox.io/s/react-hook-form-usefieldarray-template-xm6c6
> 
> I think `watch` lost the reference on unmount, but how can I handle this kind of behavior properly?

can you try to watch before the `render`?

**Comment by Benjpoirier** [comment] 2020-06-04 07:25
I watch with the index on the map, what do you mean before the render? I try outside the return with a static number as an index and I try before map return. This is what you meant?

**Comment by bluebill1049** [comment] 2020-06-04 07:43
> I watch with the index on the map, what do you mean before the render? I try outside the return with a static number as an index and I try before map return (not working). This is what you meant?

watch the entire Field Array. The index is probably not reliable with your use case.

**Comment by Benjpoirier** [comment] 2020-06-04 07:54
it seems not working and cause a render in each letter.

**Comment by bluebill1049** [comment] 2020-06-04 08:03
> thx for this working example,
> 
> My version was up to date on my app, so I dug into my problem, and, in fact, I was displaying the nested fields with a condition based on a watch.
> https://codesandbox.io/s/react-hook-form-usefieldarray-template-xm6c6
> 
> I think `watch` lost the reference on unmount, but how can I handle this kind of behavior properly?

ok, since this is completely different issue, can you please put down the steps to reproduce the problem? I am confused and my answer is off track as well.

**Comment by bluebill1049** [comment] 2020-06-04 08:17
going to close this issue, and let's create a separate issue, with steps to reproduce (what you reported above).

**Closed by bluebill1049** 2020-06-04 08:17 UTC
Labels: question
