### ISSUE TITLE
useFieldArray resets form values after deleting item

### ISSUE THREAD

**Issue by caged** [react-hook-form/react-hook-form#892] opened 2020-01-22 22:27 UTC
**Describe the bug**
All items appended to a field array are reset to the value given at `append` time when you delete an item from the stack. 

**To Reproduce**
1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv
2. Click on the append button a few times
3. Change the text value of the second item
4. Delete the last item

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv

**Expected behavior**
I would expect the value I entered into the textbox to remain after deleting another item from the array. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 10.14.6
 - Browser: Chrome
 - Version 79.0.3945.13

**Additional context**
Interestingly enough, if you change the `li` key to `test[${index}]`, it will retain the values when you delete an item from the stack.  Unfortunately, this appears to have a similar issue.  If you click append a couple of times, change the values to a, b, and c and then delete b, it will delete c instead. 

Thank you for this wonderful little library! 🍻

**Comment by kotarella1110** [comment] 2020-01-23 08:32
Why is `defaultValue` attr commented out?

```js
<input
  name={`test[${index}].name`}
  // defaultValue={`${item.name}`}
  ref={register}
/>
```

It works correctly if you remove the comment out.

```js
<input
  name={`test[${index}].name`}
  defaultValue={`${item.name}`}
  ref={register}
/>
```

**Comment by bluebill1049** [comment] 2020-01-23 08:37
FYI: @kotarella1110 i think there r some issue with useFieldArray, i am busy working over all the issues. next release should make it more solid, that's also the reason i haven't response most of the issues today.

also you want to help to send a PR on those issue you reported on one of the PR. 👍

**Comment by caged** [comment] 2020-01-23 16:15
> It works correctly if you remove uncomment the line.

Confirmed this works in my local code.  I'm almost certain I had `defaultValue`  set before and the bug was still present, but I've been hacking away on my code in different areas, so it's likely I missed when the break occurred.   I upgraded from 4.5.6 to 4.6.2 in the process of making these changes.  It's possible setting `defaultValue` didn't work as expected in the earlier version. 

Not completely sure why `defaultValue` was commented out.  The codesandbox is one linked from the official docs [here](https://react-hook-form.com/api#useFieldArray) (the codesandbox link in the second code block under `useFieldArray`). 

Thanks for looking into this ⭐️

**Comment by bluebill1049** [comment] 2020-01-24 04:55
There is a beta version, feel free to help on testing.

**Comment by bluebill1049** [comment] 2020-01-24 04:56
FYI: also it's safer to inject `defaultValues` than defaultValue, because defaultValue will overwrite value after each re-render.

**Comment by caged** [comment] 2020-01-24 18:35
Looks like this might still be broken.  Here's the sandbox from earlier, updated to 4.7.0-beta.1 and simplified to include only the basics https://codesandbox.io/s/react-hook-form-usefieldarray-23851.  If you follow the same steps to reproduce the original report, you should see it empties all values now.   Setting `defaultValue` "fixes" the issue, but it seems like we should avoid this based on your suggestion.

**Comment by bluebill1049** [comment] 2020-01-24 20:48
hey @caged it's not really broken. I guess it's a trade-off of being uncontrolled. 

with Controlled state represent the shape of the input, however it does require everything to be in sync, which why each input required a re-render and map every keystroke.

with Uncontrolled, if set default value for individual input, it will get injected each re-render caused by action eg: pre-pend, swap, move and etc. I will update the documentation to reflect that and hence it's better to set up your defaultValues at the `form` level. hope these make sense and feel free to follow up with more questions.

**Comment by caged** [comment] 2020-01-24 21:12
@bluebill1049 Thanks for the update and the explanation.  I'm OK with using `defaultValue` as a way to get this to work, however I can't imagine a real-world scenario where the default behavior seems desired.  Removing an item completely clears the array inputs.   It doesn't reset back to the `defaultValues` at the form level. 

To be sure I'm understanding you, [this behavior](https://streamable.com/eq71w) is the expected behavior if you don't set `defaultValue` on the input?  It's 100% possible I'm misunderstanding [your previous comment](https://github.com/react-hook-form/react-hook-form/issues/892#issuecomment-577991119). If an end-user is entering a list of 10 items, and decides to remove one, _all_ values will be cleared. 

P.S. Feel free to close this and move on if you consider this working as expected.  I have a sufficient workaround.  👍

**Comment by bluebill1049** [comment] 2020-01-24 21:16
actually let me spend sometimes today, see if we can work around this issue as well. I do have an idea and will check it out today to see if it works.

worse case you will have to stick around with setting default value at `useForm` level or `reset`

eg:
```
useForm({
  defaultValues: {}
})
// or
reset({})
```

**Comment by bluebill1049** [comment] 2020-01-25 01:53
want to try out this beta: `4.7.0-beta.2`?

**Comment by bluebill1049** [comment] 2020-01-25 10:19
hey @caged I have released the latest minor update with useFieldArray. let me know if this improve things.

**Comment by caged** [comment] 2020-01-25 19:22
4.7.0 appears to behave the same way 😢.  I feel like I'm taking up too much of your time with this, since I have a workaround.  I also have a sneaking suspicion, we might have our wires crossed and the workaround isn't a workaround at all, but the correct way to use the field array hook.  

To sum it up:
* [This codesandbox](https://codesandbox.io/s/react-hook-form-usefieldarray-23851) perfectly demonstrates the default behavior with the suggested use, and the behavior when you uncomment `defaultValue` on the input.  Without `defaultValue` set on the input, `append` doesn't actually set the input value and removing an item clears the form.
* You need to set `defaultValues` (plural) at the form level (`useForm`) _and_ `defaultValue`  the input level (`<input defaultValue={field.value} />`) for `useFieldArray` to work reasonably well (e.g. not delete a users previously entered content).  
* This doesn't appear to have any negative drawbacks, and it's almost as if it's the intended use.  If this is the case, nothing is broken and all is right.  
* My confusion stems from your comment discouraging adding `defaultValue` at the input level.  Even if it's set to the values passed in with `fields`.  Without doing this, the behavior appears to be broken.

Thanks again for your time and have a great weekend! 🍻

**Comment by bluebill1049** [comment] 2020-01-25 20:38
<img width="759" alt="Screen Shot 2020-01-26 at 7 37 31 am" src="https://user-images.githubusercontent.com/10513364/73127047-c2ca9e80-400e-11ea-8eb9-abaeb9a25d7a.png">

This is the reason why I said you are super kind and understanding. I will take another closer look above today :) 

You have a great weekend too ✌🏻

**Comment by bluebill1049** [comment] 2020-01-25 20:53
> This codesandbox perfectly demonstrates the default behavior with the suggested use, and the behavior when you uncomment defaultValue on the input. Without defaultValue set on the input, append doesn't actually set the input value and removing an item clears the form.

You are right if you want to re-populate things at runtime. my bad for not reading your question clearly.

**Comment by bluebill1049** [comment] 2020-01-25 20:55
> You need to set defaultValues (plural) at the form level (useForm) and defaultValue the input level (<input defaultValue={field.value} />) for useFieldArray to work reasonably well (e.g. not delete a users previously entered content).

I think it should work fine without `defaultValues`, when you are building an empty form right? also you can use `reset()` API to set the Field Array async.

**Comment by bluebill1049** [comment] 2020-01-25 20:56
> My confusion stems from your comment discouraging adding defaultValue at the input level. Even if it's set to the values passed in with fields. Without doing this, the behavior appears to be broken.

Apologize on that part, i don't think i clearly understand your question and scenario while i was reading the issue. Try to solve too many issues at the same time does loose up my focus point. 🙏

**Comment by bluebill1049** [comment] 2020-01-25 20:57
I think we are in a pretty good position for FieldArray now after reading your comments. I am going to close this issue and feel free to follow up more questions 👍 again thanks for being nice and understanding.

**Closed by bluebill1049** 2020-01-25 20:58 UTC
Labels: question

**Comment by bluebill1049** [comment] 2020-01-26 10:37
hey, @caged I just saw your donation towards RHF from my email. I have spent you a private email to appreciated your support and love towards the project. again much appreciated.

**Comment by AndrewAllison** [comment] 2020-06-11 06:33
Hi @bluebill1049, Sorry to be a pain but has this regressed in newer versions? (i'm using v 5.7.2) I've followed all of the advise in this thread but still can't get things working.  I still lose all of the elements in the array when I remove one. The fields array is ok with the correct items but the `getValues()` returns no `children[]` values.

I've checked the code sandbox that was mentioned earlier that was said to work but I've noticed you get similar issue even on that [Sandbox](https://codesandbox.io/s/react-hook-form-usefieldarray-23851).

I'll prep a sandbox of my own if it's needed.

I'm going to pull the code and see if I can help in anyway but as I'm pretty new to react and never really helped out on an OS project I'm not sure how much use I can be.

**Comment by bluebill1049** [comment] 2020-06-11 06:36
> Hi @bluebill1049, Sorry to be a pain but has this regressed in newer versions? (i'm using v 5.7.2) I've followed all of the advise in this thread but still can't get things working. I still lose all of the elements in the array when I remove one. The fields array is ok with the correct items but the `getValues()` returns no `children[]` values.
> 
> I've checked the code sandbox that was mentioned earlier that was said to work but I've noticed you get similar issue even on that [Sandbox](https://codesandbox.io/s/react-hook-form-usefieldarray-23851).
> 
> I'll prep a sandbox of my own if it's needed.
> 
> I'm going to pull the code and see if I can help in anyway but as I'm pretty new to react and never really helped out on an OS project I'm not sure how much use I can be.

make sure you have defaultValue for your input. 👍 let me know if that solves the problem. This should resolve the problem.

**Comment by AndrewAllison** [comment] 2020-06-11 10:31
Thanks for the reply I had done. What I think is the issue though is using the Material UI TextField input.  After forking and running the tests / app local it looked like everything should work.  I removed all the material UI elements and just did it with raw inputs and it seems to have worked fine with them.

I had set the `inputRef` on the TextField component and the data was updating correctly. I'll keep digging seeing as how this looks to be more my set up than an issue with the library

**Comment by bluebill1049** [comment] 2020-06-11 11:03
> Thanks for the reply I had done. What I think is the issue though is using the Material UI TextField input. After forking and running the tests / app local it looked like everything should work. I removed all the material UI elements and just did it with raw inputs and it seems to have worked fine with them.
> 
> I had set the `inputRef` on the TextField component and the data was updating correctly. I'll keep digging seeing as how this looks to be more my set up than an issue with the library

make sure you are using Controller for MUI component/external controlled components.

**Comment by miletich** [comment] 2020-07-01 09:55
had the same problem; fixed it by passing defaults **AND** `ref={register()}` (it didn't work correctly with `register` acquired in the component via `useFormContext`.

**Comment by amirofy2002** [comment] 2020-08-08 13:28
by adding `key={item.id} `for each field my problem **solved**
thanks for helpful comments

**Comment by gregoryrey** [comment] 2020-08-14 14:36
> by adding `key={item.id} `for each field my problem **solved**
> thanks for helpful comments

This solved my problem, I was setting key={index} and was getting very frustrated with it always deleting the last item

**Comment by Sphinxs** [comment] 2020-08-28 22:08
What about `setFieldValue('', '')` being used to register the fields and not `register` like `ref={register}` or `ref={register()}`?

When `remove()` is invoked it reflect at the interface, for the first item removed, but not on `fields` and after remove the second item `TypeError: data.slice is not a function or its return value is not iterable` is issued... I tried to update from 5.3.1 to version 5.7.2, but it didn't fixed

**Comment by NoobTW** [comment] 2020-09-12 06:53
> had the same problem; fixed it by passing defaults AND ref={register()} (it didn't work correctly with register acquired in the component via useFormContext.

Using `ref={register()}` instead of `ref={register}` works for me.

**Comment by bluebill1049** [comment] 2020-09-12 08:50
> What about `setFieldValue('', '')` being used to register the fields and not `register` like `ref={register}` or `ref={register()}`?
> 
> When `remove()` is invoked it reflect at the interface, for the first item removed, but not on `fields` and after remove the second item `TypeError: data.slice is not a function or its return value is not iterable` is issued... I tried to update from 5.3.1 to version 5.7.2, but it didn't fixed

Do you have a codesandbox with the issue?

**Comment by tomerbarak** [comment] 2020-10-03 12:00
remove(index), index should be **Number**, not a string.

**Comment by Sphinxs** [comment] 2020-10-08 01:20
> > What about `setFieldValue('', '')` being used to register the fields and not `register` like `ref={register}` or `ref={register()}`?
> > When `remove()` is invoked it reflect at the interface, for the first item removed, but not on `fields` and after remove the second item `TypeError: data.slice is not a function or its return value is not iterable` is issued... I tried to update from 5.3.1 to version 5.7.2, but it didn't fixed
> 
> Do you have a codesandbox with the issue?

Sorry, I just saw the reply now. I don't have access to the code anymore. I fixed it, first of all I needed to update the entire thing from 5.0 to the latest version (holy shit, you update this library a lot ^ - ^), by doing this a lot of things were fixed and then I needed to fix the rest of the s**t that the other developers had done: 1 form composed of 6 files and a messy state management, from this library and from React, but to sumarize my problem was that the `useFieldArray` was not receiving an `defaultValue`, then I added it:

```
const buyers = buyerFields.length ? watch('buyers', buyerFields): []
```

The previous developer rendered a list of buyers where each buyer was a render of a `form`, when I removed one buyer the entire thing was not registered anymore - for all buyers, to fix it I needed to listen to the remove method that I receive from `useArrayField` to register the fields again, using `useEffect`, but this generated a third problem, which was the reset of the other buyers after the remotion of one buyer, then on the redefinition after the remotion I checked if it had value for the `buyer[ * ].field` and set it there.

Don't **f-----g** use `useArrayField` if you have not read the documentation, thanks.

**Comment by bluebill1049** [comment] 2020-10-08 01:35
> > > What about `setFieldValue('', '')` being used to register the fields and not `register` like `ref={register}` or `ref={register()}`?
> > > When `remove()` is invoked it reflect at the interface, for the first item removed, but not on `fields` and after remove the second item `TypeError: data.slice is not a function or its return value is not iterable` is issued... I tried to update from 5.3.1 to version 5.7.2, but it didn't fixed
> > 
> > 
> > Do you have a codesandbox with the issue?
> 
> Sorry, I just saw the reply now. I don't have access to the code anymore. I fixed it, first of all I needed to update the entire thing from 5.0 to the latest version (holy shit, you update this library a lot ^ - ^), by doing this a lot of things were fixed and then I needed to fix the rest of the s**t that the other developers had done: 1 form composed of 6 files and a messy state management, from this library and from React, but to sumarize my problem was that the `useFieldArray` was not receiving an `defaultValue`, then I added it:
> 
> ```
> const buyers = buyerFields.length ? watch('buyers', buyerFields): []
> ```
> 
> The previous developer rendered a list of buyers where each buyer was a render of a `form`, when I removed one buyer the entire thing was not registered anymore - for all buyers, to fix it I needed to listen to the remove method that I receive from `useArrayField` to register the fields again, using `useEffect`, but this generated a third problem, which was the reset of the other buyers after the remotion of one buyer, then on the redefinition after the remotion I checked if it had value for the `buyer[ * ].field` and set it there.
> 
> Don't use `useArrayField` if you have not read the documentation, thanks.

I am glad you worked it out! indeed useFieldArray is something you should read the doc before implement. I do work on the lib pretty much every day so do expect patch and fixes. 🙏

**Comment by kpnigalye** [comment] 2021-03-03 11:39
![image](https://user-images.githubusercontent.com/8084464/109798728-20cdaa80-7c41-11eb-90df-7fc65bf41d50.png)
I am coming across this issue. 

This code example helps you to add a recipe. I added ingredients. When I say ingredient, it includes 2 textboxes, and a select box. 
![image](https://user-images.githubusercontent.com/8084464/109799954-a0a84480-7c42-11eb-8b5e-c2a6c3356aa1.png)
Using 'append' I added few more ingredients boxes. When I remove an ingredient, that ingredient is removed. Now other ingredient textboxes retain their values but not select box. You can see the value in the select box but it shows validation error as well.
![image](https://user-images.githubusercontent.com/8084464/109800278-f7ae1980-7c42-11eb-8197-7f8f6c9b21a9.png)
Here is my code for select box. This is using material UI's TextField component.
![image](https://user-images.githubusercontent.com/8084464/109800414-27f5b800-7c43-11eb-8d30-90104db8812d.png)
Please help!

**Comment by bluebill1049** [comment] 2021-03-03 11:56
> ![image](https://user-images.githubusercontent.com/8084464/109798728-20cdaa80-7c41-11eb-90df-7fc65bf41d50.png)
> I am coming across this issue.
> 
> This code example helps you to add a recipe. I added ingredients. When I say ingredient, it includes 2 textboxes, and a select box.
> ![image](https://user-images.githubusercontent.com/8084464/109799954-a0a84480-7c42-11eb-8b5e-c2a6c3356aa1.png)
> Using 'append' function of 'useFieldArray', I added few more ingredients boxes. When I remove an ingredient, that ingredient is removed. Now other ingredient textboxes retain their values but not select box. You can see the value in the select box but it shows validation error as well.
> ![image](https://user-images.githubusercontent.com/8084464/109800278-f7ae1980-7c42-11eb-8197-7f8f6c9b21a9.png)
> Here is my code for select box. This is using material UI's TextField component.
> ![image](https://user-images.githubusercontent.com/8084464/109800414-27f5b800-7c43-11eb-8d30-90104db8812d.png)
> Please help!

provide a codesandbox before we can take a look at it.

**Comment by kpnigalye** [comment] 2021-03-03 12:03
Sorry for the trouble. I did this by following one of the posts on stackoverflow. This was a basic issue with input. I changed my code a little bit and it worked. 'Name' attribute should be mentioned outside the inputRef and we can pass the required attribute inside inputRef. It worked fine. Thanks anyways.

![image](https://user-images.githubusercontent.com/8084464/109802920-680a6a00-7c46-11eb-9bd9-d457f5ddcfde.png)

**Comment by kpnigalye** [comment] 2021-03-03 14:56
> > ![image](https://user-images.githubusercontent.com/8084464/109798728-20cdaa80-7c41-11eb-90df-7fc65bf41d50.png)
> > I am coming across this issue.
> > This code example helps you to add a recipe. I added ingredients. When I say ingredient, it includes 2 textboxes, and a select box.
> > ![image](https://user-images.githubusercontent.com/8084464/109799954-a0a84480-7c42-11eb-8b5e-c2a6c3356aa1.png)
> > Using 'append' function of 'useFieldArray', I added few more ingredients boxes. When I remove an ingredient, that ingredient is removed. Now other ingredient textboxes retain their values but not select box. You can see the value in the select box but it shows validation error as well.
> > ![image](https://user-images.githubusercontent.com/8084464/109800278-f7ae1980-7c42-11eb-8197-7f8f6c9b21a9.png)
> > Here is my code for select box. This is using material UI's TextField component.
> > ![image](https://user-images.githubusercontent.com/8084464/109800414-27f5b800-7c43-11eb-8d30-90104db8812d.png)
> > Please help!
> 
> provide a codesandbox before we can take a look at it.

Sorry I havent tried putting on codesandbox yet. Is there any other way to showcase the code.

I can tell you for sure that this issue defiantly exist with React **TextField Select**. I replaced it with **Select component using Controller** and it worked fine. I could figure it out because of the React hook form DevTools. Amazing tool!!! Thanks.
