### ISSUE TITLE
Correct usage of react-select?

### ISSUE THREAD

**Issue by rvision** [react-hook-form/react-hook-form#1619] opened 2020-05-12 11:07 UTC
I am using react-hook-form for adding and editing data. To make it work with react-select, I am using following code :

```
import Select from 'react-select';

useEffect(() => {
 	register({ name: 'color' });
}, []);

<Select
	options={colors}
	getOptionValue={option => option.id}
	getOptionLabel={option => {
		return (
			<div className="color-picker">
				<span className="color-picker__color" style={{background: option.id }} />
				<span className="color-picker__name">{option.name}</span>
			</div>
		)
	}}
	defaultValue={colors.find(option => option.id == model.color)}
	onChange={option => {
		setValue('color', option.id);
	}}
/>
```

By using defaultValue I am making the option to edit selected and that works as expected.

But this prop is valid only when I render the component only if I have all required data before (color options, model and model.color). If I render the form without this, it will be invalid because defaultValue will not be set properly if colors/options array is empty.

My question: is this correct usage? To suspend rendering before getting all required data?

Thanks

**Comment by bluebill1049** [comment] 2020-05-12 11:26
please have a read at the Controller section: https://react-hook-form.com/api#Controller

there is a codesandbox as well.

**Comment by rvision** [comment] 2020-05-12 11:45
@bluebill1049 
Thanks, I know about Controller, but I wasn't able to make it work like I wanted. I also tried it right now, options are not displayed, selected value also...
FYI, I am using "react-select": "^3.1.0",

**Comment by bluebill1049** [comment] 2020-05-12 11:47
i have updated to 3.1.0 in the CSB and it's still working. https://codesandbox.io/s/react-hook-form-controller-079xx?file=/src/index.js

can you take a look there and see if you can use Controller with react-select.

**Comment by marconucara** [comment] 2020-05-12 16:13
I have some problem with react-select too and I can't understand how to use Controller with validation, I can't see it in examples, I can't see it in documentation.

I really like the api and the implementation but generally I see a lot of example without validation and I have to say that this package without validation almost do nothing.

I'm trying without Controller, as uncontrolled component, using register inside effect and I can get the correct value on submit but the select is not validated even if I called register with `required: true`.

If there is some examples with validation (at least required) would be very appreciated, thanks.

**Comment by bluebill1049** [comment] 2020-05-12 23:07
closing this issue @rvision  feel free to follow up with questions, the example is in that code sandbox as @marconucara got it working by following the example.

**Comment by rvision** [comment] 2020-05-13 09:44
@bluebill1049 

Thanks, your example works, but my case is bit more complicated - default value is still not set. I've omitted details for the sake of example, but I am working with array of objects. Initial values are set from array and still doesn't work.

```
const { control, register, unregister, handleSubmit, errors, clearError, setError, getValues, setValue, formState } = useForm({
		defaultValues: model.map(item => {
			return {
				...item,
				color: colors.find(option => option.id == item.color)
			}
		}),
	});

	const { fields, append, prepend, remove } = useFieldArray({
		control,
		name: 'items'
	});

...
(model || []).map((job, idx) => {
const namePrefix = `items[${idx}].`;

<Controller
	as={Select}
	options={colors}
	name={`${namePrefix}color`}
	isMulti={false}
	isClearable={false}
	className="custom-select-blue-triangle"
	styles={customSelectStyles}
	control={control}
	getOptionValue={option => option.id}
	getOptionLabel={option => {
		return (
			<div className="color-picker">
				<span className="color-picker__color" style={{background: `#${option.id}`}} />
				<span className="color-picker__name">{option.name}</span>
			</div>
		)
	}}
/>

```

**Comment by bluebill1049** [comment] 2020-05-13 09:46
can you supply a simple codesandbox for your issue?

**Comment by rvision** [comment] 2020-05-15 09:32
@bluebill1049 

Thanks a lot for library and support, however I am currently super busy with the project I am working on - if I get some time I will definately make codesandbox demo.

**Comment by rvision** [comment] 2020-05-21 12:54
@bluebill1049 

I've had some time and created a codesandbox example. It took me a while because I had to be sure what actions to execute to replicate this:

https://codesandbox.io/s/react-hook-form-usefieldarray-cfcfc?file=/src/index.js

Validation rules are (yup is used):
- at least 1 job added
- no jobs without title
- no jobs with same name

Steps to reproduce:
- delete all 3 default jobs
- click on Save & continue, validation says at least 1 job is needed
- add 3 jobs
- give 2 of them same name, erase name of 1
- click on Save & continue, validation occurs
- now try to delete any of them via delete button (remove)

Maybe I'm doing something wrong here: I've commented code that triggers validation (via useEffect), and bug is the same

**Comment by bluebill1049** [comment] 2020-05-22 02:44
Thanks for spending your time with this CSB @rvision 🙏 

i can see the alert 'error: Cannot read property 'call' of undefined'.

**Comment by bluebill1049** [comment] 2020-05-22 02:44
I will take a closer look on this one.

**Comment by bluebill1049** [comment] 2020-05-22 03:09
Ok, why is React Select not using Controller?

**Comment by bluebill1049** [comment] 2020-05-22 03:29
ok I found out the problem, because errors where suppose to be an array, while yup is return a single node.

<img width="668" alt="Screen Shot 2020-05-22 at 1 28 08 pm" src="https://user-images.githubusercontent.com/10513364/82628406-18672e80-9c30-11ea-8404-39e7e18c1597.png">

I think i will do a check to prevent the error from throwing.

**Comment by bluebill1049** [comment] 2020-05-22 04:21
updated: https://codesandbox.io/s/react-hook-form-usefieldarray-ug8qg?file=/src/src/useFieldArray.ts

**Comment by rvision** [comment] 2020-05-22 09:28
> updated: https://codesandbox.io/s/react-hook-form-usefieldarray-ug8qg?file=/src/src/useFieldArray.ts

Now it throws "value.filter is not a function" -  in order to reproduce it, try something like I've described previously.

**Comment by rvision** [comment] 2020-05-22 09:31
Now I am getting error in my project:

Uncaught TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at __read (react-hook-form.ie11.js:2739)
    at __spread (react-hook-form.ie11.js:2757)
    at getDefaultValues (react-hook-form.ie11.js:5518)
    at useFieldArray (react-hook-form.ie11.js:5521)
    at JobTitleScheduleColorForm (JobTitleScheduleColorForm.jsx:85)
    at renderWithHooks (react-dom.development.js:16260)
    at mountIndeterminateComponent (react-dom.development.js:18794)
    at beginWork$1 (react-dom.development.js:20162)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:38

**Comment by bluebill1049** [comment] 2020-05-22 09:32
@rvision i did the steps as you described, there is no error anymore. the error is due to your Yup schema is return errors in `object` instead of `array`.

**Comment by bluebill1049** [comment] 2020-05-22 09:32
can you make sure do a hard refresh?

**Comment by rvision** [comment] 2020-05-22 09:34
I've just reproduced it in incognito window, please try as I've described.

**Comment by bluebill1049** [comment] 2020-05-22 09:40
![ezgif-6-82438cd54dee](https://user-images.githubusercontent.com/10513364/82654448-1a4ae500-9c64-11ea-9596-cd2ab9e89a01.gif)

**Comment by rvision** [comment] 2020-05-22 09:42
@bluebill1049 

You forgot to click on Submit when creating duplicate names (or no name). After that try to click on delete and it will throw error.

**Comment by bluebill1049** [comment] 2020-05-22 09:49
Thanks, i will take a look again, but the issue is due to error message returned as `object`, instead of `array` for array field, however, i do understand the rationale behind. will come up with a solution for this.

**Comment by rvision** [comment] 2020-05-22 09:54
Aha, you mean custom validation (yup.addMethod(yup.array, 'uniqueBy') should return array?
Then it's error on my end, will have to see how to return this error.

Thanks a lot!

**Comment by bluebill1049** [comment] 2020-05-22 09:55
Nah @rvision still we should get it working for non-array errors anyhow. I will solve the problem for you, so you don't have to change.

**Comment by rvision** [comment] 2020-05-22 10:00
btw, yupResolver doesn't work on my end - no validation is triggered. With validationSchema set it works.

**Comment by bluebill1049** [comment] 2020-05-22 10:02
`yupResolver` is V6. I am just testing out the new version.

**Comment by bluebill1049** [comment] 2020-05-22 11:33
make sure you double check your yup schema as well, and take a look my update codesandbox above.

**Closed** 2020-05-22 11:42 UTC
Labels: enhancement

**Comment by rvision** [comment] 2020-05-25 12:46
@bluebill1049  I've checked, schema is ok. All examples for yup's addMethod I've found online do return true/false only, no arrays or something like that.

How can I use updated code for react-hook-form that you fixed for this issue?

Thanks

**Comment by bluebill1049** [comment] 2020-05-25 12:47
@rvision we are planning to release V6 this week. this will be part of it.
