### ISSUE TITLE
issue: Generic type for useForm fails typecheck in `register`

### ISSUE THREAD

**Issue by villesau** [react-hook-form/react-hook-form#9920] opened 2023-02-11 15:56 UTC
### Version Number

7.43.1

### Codesandbox/Expo snack

https://codesandbox.io/s/gifted-pasteur-fpkgv6?file=/src/App.tsx

### Steps to reproduce

1. See the difference of Component1 & Component2
2. Component2 fails the typecheck eventhough the actual type should be the same.

The same issue happens with `useFormContext`. I'd like to ensure some type contract this way, but does not seem to be possible.

### Expected behaviour

It should not fail the typecheck

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsUndefined** [comment] 2023-02-11 23:46
Duplicate of: https://github.com/react-hook-form/react-hook-form/issues/6726

**Comment by villesau** [comment] 2023-02-12 15:04
Unfortunately the other issue is locked which limits the conversation trying to find a solution.

**Comment by bluebill1049** [comment] 2023-02-14 22:32
The other issue is unclocked.

**Closed** 2023-03-05 00:05 UTC
Labels: duplicated, TS, design limitation
