### ISSUE TITLE
watch() updates too often

### ISSUE THREAD

**Issue by mikestopcontinues** [react-hook-form/react-hook-form#661] opened 2019-12-12 21:10 UTC
**Describe the bug**
It seems when using watch with syntax `watch([<props>])`, the return object is recreated fairly often, resulting in numerous (albeit short) refreshes, even when no form fields are touched.

**To Reproduce**
1. Create a form.
2. Set a watch().
3. Monitor lifecycles.

**Expected behavior**
I suspect using a deep equals comparison (such as `fast-deep-equal`) and defaulting to the previous results would ensure watch didn't introduce extra lifecycles.

**Comment by bluebill1049** [comment] 2019-12-12 21:25
Do you have a codesandbox for this issue?

**Comment by bluebill1049** [comment] 2019-12-13 22:54
closing this :) that's expected behavior for `watch()`, (because you are watching everything) IMOH I don't think we need an extra dependency for this. keep this lib simple and light.

**Comment by mikestopcontinues** [comment] 2019-12-15 19:32
Hey, I just got some spare time to pick this up.

I honestly don't think this should be the desired behavior of the array usage. When selecting which props you want to watch, you really only want to watch those particular props, not the others. Beside, react-hook-form's value proposition is causing as few refreshes as possible. Says so on the homepage. ;)

The real issue seems to be when one of the props is an array. There's no reason the dom should re-render if all of the elements of the array are exactly as they were before. 

I'm also not arguing to add a dependency. I was just citing it as a code example for a fast and recursive comparison. A more rudimentary version would be sufficient, as react-hook-form only works with primitives anyway. 

Anyway, I hope you'll reconsider. Thanks!

**Comment by bluebill1049** [comment] 2019-12-15 20:39
good points above :) can you supply a code sandbox for this particular issue?

**Comment by bluebill1049** [comment] 2019-12-15 20:53
> A more rudimentary version would be sufficient, as react-hook-form only works with primitives anyway.

not really :)

**Comment by mikestopcontinues** [comment] 2019-12-16 15:31
Hey, thanks for looking into this. I really appreciate it. Here's a codesandbox...

https://codesandbox.io/s/react-hook-form-watch-zoqql?autoresize=1&expanddevtools=1&fontsize=14&hidenavigation=1

> > A more rudimentary version would be sufficient, as react-hook-form only works with primitives anyway.

> not really :)

^^^ Good to know! :D

**Comment by bluebill1049** [comment] 2019-12-17 09:41
Hi @mikestopcontinues. thanks for the codesandbox. that really helps.

when you watching an array object, any one of them is changing will trigger re-render. How can we prevent it from re-render? I don't see how we can optimise the re-render in here. feel free to provide your suggestion tho.

**Comment by mikestopcontinues** [comment] 2019-12-17 14:55
I might be misunderstanding your question, so please forgive any confusion in my response...

If you mean the updating when the array itself changes, I think it's ok to do so when the array props actually change. But I think it's wrong that the watch updates when values outside the array change. In the example, when you toggle the select element, the array watcher updates, and it should only update when the checkboxes update.

But if you mean how do you handle the new objects created inside `watch`, maybe you could optimize the watch function by caching the previous results in a ref (something like `watchCacheRef.current[fieldNames.sort().join(',')]`), then doing a deep comparison of the values for each watched key. If the objects are equal, return the previous result, otherwise update the cache and return the new result. And if you didn't want to do a deep equal, going just one-level deep on each watched element I think would be fair. At least then you could use more specific fieldNames to prevent re-renders. The trouble is that without any depth comparison, no fieldName will prevent them.

**Comment by bluebill1049** [comment] 2019-12-19 05:26
hey @mikestopcontinues thanks for the detailed reply again. I may leave this in the backlog for now as i am busy working on the next major version. we will come back to this tho. I am adding this ticket into the project.

**Comment by bluebill1049** [comment] 2019-12-19 05:28
<img width="372" alt="Screen Shot 2019-12-19 at 4 27 44 pm" src="https://user-images.githubusercontent.com/10513364/71147303-82903780-227c-11ea-83a7-9e245a09505f.png">

FYI above

**Closed** 2019-12-19 05:27 UTC
Labels: question

**Comment by mikestopcontinues** [comment] 2019-12-19 16:27
Thanks! I really appreciate it!

**Comment by JeromeDeLeon** [comment] 2019-12-27 04:33
> I might be misunderstanding your question, so please forgive any confusion in my response...
> 
> If you mean the updating when the array itself changes, I think it's ok to do so when the array props actually change. But I think it's wrong that the watch updates when values outside the array change. In the example, when you toggle the select element, the array watcher updates, and it should only update when the checkboxes update.
> 
> But if you mean how do you handle the new objects created inside `watch`, maybe you could optimize the watch function by caching the previous results in a ref (something like `watchCacheRef.current[fieldNames.sort().join(',')]`), then doing a deep comparison of the values for each watched key. If the objects are equal, return the previous result, otherwise update the cache and return the new result. And if you didn't want to do a deep equal, going just one-level deep on each watched element I think would be fair. At least then you could use more specific fieldNames to prevent re-renders. The trouble is that without any depth comparison, no fieldName will prevent them.

I'm having the same scenario when dealing with form fields array before, and I kinda did a lot of things like creating custom hook, adding react-fast-compare and such, but at the end, I gave up :laughing: and just used `use-deep-compare-effect`.

**Comment by bluebill1049** [comment] 2019-12-27 04:36
@JeromeDeLeon thanks :) i do hesitate on introduce complexity to this simple lib. anyway it's on our to do list

**Comment by JeromeDeLeon** [comment] 2019-12-27 04:37
Welcome, that's why I didn't bother bringing it up before because I thought that although, it's not the right behavior, it can be solved by many packages like what I mentioned above or `immutable` package.
