### ISSUE TITLE
Regression: reset followed by setValues of an array unexpectedly merges

### ISSUE THREAD

**Issue by cameron-subskribe** [react-hook-form/react-hook-form#5220] opened 2021-05-16 18:57 UTC
**Describe the bug**
Prior to version 7.6.0, calling setValue of an array would overwrite the array.  Version 7.6.0 instead merges the arrays.  This causes the problem of having no way to shrink an array with setValue.

**To Reproduce**

1. Call reset and define an array
2. Call setValue to update with an array of fewer elements

**Codesandbox link (Required)**
https://codesandbox.io/s/confident-panini-g43eq?file=/src/App.js

**Expected behavior**
["newValue1"]

**Actual behavior**
["newValue1","oldValue2"]

**Desktop (please complete the following information):**

- OS: MacOS 11.3.1
- Browser: Chrome
- Version: 90.0.4430.212

**Comment by bluebill1049** [comment] 2021-05-16 22:53
please fix the codesandbox first.

**Comment by bluebill1049** [comment] 2021-05-17 07:30
I can confirm this is a duplicate of https://github.com/react-hook-form/react-hook-form/issues/5219#issuecomment-842082188 discuss over there instead.

**Closed** 2021-05-17 07:30 UTC
Labels: duplicated
