### ISSUE TITLE
useFieldArray inconsistencies

### ISSUE THREAD

**Issue by schettino** [react-hook-form/react-hook-form#1254] opened 2020-03-20 18:46 UTC
**Describe the bug**
While working in a feature that has a more elaborated form, I found a few problems that became unfortunately a blocker. Unless I'm missing something (which I might be, not discarding this option), those problems can be dangerous enough to not use the current lib implementation.

The feature is to have a form in a Grid shape, where fields (from useFieldArray) are the rows, and for each column I have a Controller with the name being `rows[row-index].column`.  All the inputs are conditionally rendered based on a "Edit" toggle. Thus, instead of wrapping the Input element in the Controller, I'm wrapping the "Cell" container, so I can have access to the field errors to display them if "edit mode" is off.

**Codesandbox**: https://codesandbox.io/s/react-hook-form-usefieldarray-3-gy0dw
(I've also imported the library in case you find this necessary)

**Removing rows make fields to have staled value.**

1. Click on the load data button.
2. Click on Append
3. Delete the previous item (Ben)
4. Recently created row, age field, will be updated to the one we removed.

**Staled default values**

1. Click on the load data button.
2. Remove all the rows
3. Click on Append

All rows based on the values from the last `reset` call will be regenerated. Even if that's the expected behaviour, calling `getValues` after clearing the whole form will return the latest default state. I'd argue that it should return empty as well to reflect the actual form state the user is seeing. You can verify that on line 161.

**Staled object return from `watch` after calling `reset()`**
You can verify this from line 53 to 58.

As a side note, I've noted in most cases that we need to use the current field values, the recommended way is to call `watch` on those fields. However, I found this to impact heavily on performance, and checking the website, we don't have any comparison with other libraries and RHF + watch. Right now, it's comparing uncontrolled vs controlled components, which might not be fair if I may say that, because we can not notice the same experience when watching fields (specially array fields).

I appreciate if you have the time to go through this, and I'm sorry if I messed something up that is causing any of this. In this case, I'd also appreciate some guidance as I think it might be useful for others that may face this in the future.

**Comment by bluebill1049** [comment] 2020-03-20 22:23
Thanks for your detailed issue report. It's under investigation.

> As a side note, I've noted in most cases that we need to use the current field values, the recommended way is to call watch on those fields. However, I found this to impact heavily on performance, and checking the website, we don't have any comparison with other libraries and RHF + watch. Right now, it's comparing uncontrolled vs controlled components, which might not be fair if I may say that, because we can not notice the same experience when watching fields (specially array fields).

**Comment by bluebill1049** [comment] 2020-03-20 22:46
Under a quick look, looks like there is a bug... strange one too. I will spend more time on this over the weekend.

**Comment by schettino** [comment] 2020-03-20 22:56
Hi Bill, thanks for your quick response.

> I am not running a competition here.

I understand that, sorry if my comment about this sounded off. The docs are clear and no issues with that. My concern is that watching field arrays might bring an overhead in terms of performance, that can can be more harmful than a fully controlled form. I don't what would be a good solution for this right now but I'd be happy to do further investigations. Thanks

**Comment by bluebill1049** [comment] 2020-03-20 23:18
> My concern is that watching field arrays might bring an overhead in terms of performance, that can can be more harmful than a fully controlled form. 

I agree as I said above the right tool for the right job. if users need constantly watch every input, it makes sense to go controlled input, that's what it good at. I will add an FAQ section to highlight this point as well.

**Comment by bluebill1049** [comment] 2020-03-21 00:45
damn it! it's a bug that i introduced... https://codesandbox.io/s/react-hook-form-usefieldarray-3-kid8d
switch to this ./src you will see the problem. lucky i haven't published the version during the week.

**Comment by xiaoyu-tamu** [comment] 2020-03-22 01:44
Looks like the problem still exist?

**Comment by bluebill1049** [comment] 2020-03-22 01:47
@xiaoyu-tamu can you use this CSB: https://codesandbox.io/s/react-hook-form-usefieldarray-3-6onju and let me know if there is still issue.

**Comment by xiaoyu-tamu** [comment] 2020-03-22 01:49
@bluebill1049 Yes, the problem still exist,

1. Click Load data,
2. Remove last item (Ben)
3. Click append

The inserted row still have age 51

**Comment by bluebill1049** [comment] 2020-03-22 01:54
yes, @xiaoyu-tamu I think this a separate issue. The original issue was (delete everything) click append will have all the defaultValues' item include the new row. 

I think this issue could be resolved with reset default values. let me come back to you with this after lunch.

Solutions: 
1. whether we mutate the defaultValues during deletion
2. let the user delete from useEffect

**Comment by xiaoyu-tamu** [comment] 2020-03-22 01:57
Sure, just FYI, the author of this issue mentioned this under the codesandbox link.

> Removing rows make fields to have staled value.

Click on the load data button.
Click on Append
Delete the previous item (Ben)
Recently created row, age field, will be updated to the one we removed.

**Comment by bluebill1049** [comment] 2020-03-22 02:04
oops, i miss the second part. what's your thoughts over 1 or 2?

**Comment by bluebill1049** [comment] 2020-03-22 02:44
I get very confused with the example: so i did on top of mine (a simpler version) https://codesandbox.io/s/react-hook-form-usefieldarray-3-kid8d 
i still going to release a new minor version today, we can continue the discussion here.

**Comment by xiaoyu-tamu** [comment] 2020-03-22 04:16
@bluebill1049 
The problem could resolved by passing `age: null` when append new values.

change line 189 to  `append({ nickname: `append ${fields.length}`,age: null });`

Looks like the form use staled value if value is undefined

**Comment by bluebill1049** [comment] 2020-03-22 04:18
Thanks @xiaoyu-tamu! I got a bit confused with that example, would be nice if we can reproduce in this example: https://codesandbox.io/s/react-hook-form-usefieldarray-3-kid8d

**Comment by xiaoyu-tamu** [comment] 2020-03-22 04:23
Try this one

https://codesandbox.io/s/react-hook-form-usefieldarray-3-ix34q

I add an **age field** and **change input to <Controller />**. Please notice, the bug only occur when **age field** not have **defaultValue**.

**Comment by bluebill1049** [comment] 2020-03-22 05:47
Thanks! I will investigate for solution or else we shall update the document to address this issue.

**Comment by bluebill1049** [comment] 2020-03-22 06:36
yes, defaultValue can solve this problem. thanks @xiaoyu-tamu 

**Suggestion:**

1) maybe we should mutate the `defaultValues` after form finish renders `input` & `value`. The only problem is when you want to reset the form, you will probably have to supply `defaultValues` (eg: `reset({ test: 'test' })`), because the `defaultValues` will be mutated by the time. Honestly, i think that would probably be a better DX than asking the user to supply `defaultValue`.

2) always asking the user to supply defaultValue when working with `useFieldArray`. This is actually applied to native input as well. 

let me know what you think. 🤔

FYI: @JeromeDeLeon @kotarella1110 @stramel

**Comment by xiaoyu-tamu** [comment] 2020-03-22 15:08
I agree with you, solution 1 probably be a better DX.

**Comment by bluebill1049** [comment] 2020-03-22 22:02
> I agree with you, solution 1 probably be a better DX.

Thanks @xiaoyu-tamu for your feedback, however, I am worried by implemented solution 1 will lead to more side effects, which is the reason why I am leaner towards 2, and info users always provide a `defaultValue` while using `useFieldArray`

**Comment by schettino** [comment] 2020-03-23 17:49
Unfortunately, I've been experiencing staled data with default values for all fields as well.

The problem of appending a row causing the default values to recreated rows could be easily solved by not allowing the user to remove a row if there was just one, aka not allowing the state to be empty. As I described, the bug consists in three parts that might be related to each other. I don't think they've been solved yet.

Besides the above, what is happening is

1) when we remove rows, depending on a certain form state, the other existing rows would reference the removed one, sometimes that only happens for a few fields/columns. (That's why age 51 is carried on to the next row). A way to debug that is checking the data coming from `getValues` on each iteration.

2) Calling `reset` doesn't update watched fields.

Also, I'd argue that changing the example to show that something has been fixed is not the right approach. You're leaving out features that might point to the right direction to detect some underlying problems in the current implementation. It's not confusing, but complex because it reflects a real use case, especially the use of multiple fields per row. This is critical to reproduce the bug as not all fields are staled, but some.

**Comment by bluebill1049** [comment] 2020-03-23 21:55
> Unfortunately, I've been experiencing staled data with default values for all fields as well.
> 
> The problem of appending a row causing the default values to recreate rows could be easily solved by not allowing the user to remove a row if there was just one, aka not allowing the state to be empty. As I described, the bug consists in three parts that might be related to each other. I don't think they've been solved yet.
> 
> Besides the above, what is happening is
> 
> 1. when we remove rows, depending on a certain form state, fields from other existing row would reference the removed ones, sometimes that only happens for a few fields/columns (not the entire row). (That's why age 51 is carried on to the next row). A way to debug that is checking the data coming from `getValues` on each iteration.
> 2. Calling `reset` doesn't update watched fields.
> 
> Also, I'd argue that changing the example to show that something has been fixed is not the right approach. You're leaving out features that might point to the right direction to detect some underlying problems in the current implementation. It's not confusing, but complex because it reflects a real use case, especially the use of multiple fields per row. This is critical to reproduce the bug as not all fields are staled, but some.

First of all, Thanks for your feedback @schettino. Here is my feedback, some of them may sound negative, but they are honest and real. 

1. I have worked on this issue over the weekend using your example and it confused **me** because it''s not set up clearly. so I used a clear example for **me** to diagnose the problem I think the most helpful person I got out from the issue is @xiaoyu-tamu who is assisting, reproducing the issue and even identify the root cause, so thank you @xiaoyu-tamu 

2. I would appreciate if you can reproduce the problem with a simpler example (the example which I have to provide) It doesn't matter real-world example or fake world example, we all know application it's like a puzzle its build piece by piece on top of each other. Any problem can be produced by an isolated and small example. This helps me because then I can easily find a root cause, and that's what I always ask people to help me with a simple and easy reproducible example.

3. **Note:** The last point is not thrown the thing out the door. 
If none of this helps, then let's move on. because this lib is simply not suitable for your requirements. I am not trying to build a swiss knife in here. If I can solve 80% of the problems, I am happy already.

**Comment by schettino** [comment] 2020-03-23 23:14
Just to clarify, I'm not bringing a new use case or trying to adapt it to something new. The example I shared covers:
- conditional inputs
- array fields
- multiple fields per row
- async loading data, and
- default values restoration.

That's why changing the example might not a good option, if we're leaving some of that out we could not be reproducing the bug anymore, which would give us the false confidence that it has been fixed. All these use cases are extensively discussed throughout the docs and the spectrum community. The problem begins when we start using all the lib can provide, and nothing else. Notice I'm importing stuff **only** from RHF (aside from TextInput from MUI which is pretty common). On the other hand perhaps we can organize it better, there's always room for improvement.

Last but not least, I'm not asking you to make it to work according to my requirements. I'm here to help. I'm stressing out a use case based only on what the library provides, that might be leading us a potential bug. You may not care about those 20% problems out there, but I'm putting the effort to create a reproducible code, so that if it's a bug, it won't affect the 80% you're aiming at.

**Comment by bluebill1049** [comment] 2020-03-23 23:29
> Just to clarify, I'm not bringing a new use case or trying to adapt it to something new. The example I shared covers:
> 
> * conditional inputs
> * array fields
> * multiple fields per row
> * async loading data, and
> * default values restoration.

Thank you for putting your time into reporting the issue. I don't think we will merge into a right approach to solve this issue, and certainly there is no right or wrong approach in here. I will raise a seperate issue to address what @xiaoyu-tamu and myself have discover and we will move on with this.

**Closed by bluebill1049** 2020-03-23 23:29 UTC
Labels: Discussion, question

**Comment by schettino** [comment] 2020-03-23 23:33
what a welcoming community  :)
