### ISSUE TITLE
State is not maintained on Wizard Form/Funnel back navigation

### ISSUE THREAD

**Issue by PedroLamas** [react-hook-form/react-hook-form#1120] opened 2020-02-28 14:03 UTC
**Describe the bug**
When using the recommended approach for [Wizard Form/Funnel](https://react-hook-form.com/advanced-usage#WizardFormFunnel), I can see that state is only updated when we move forward, but it is not maintained on back navigation as it would be with controlled components.

**To Reproduce**
1. Go to https://codesandbox.io/s/form-wizard-pages-kkg7m
2. Fill in the 'First Name' and 'Last name'
3. Click on 'Submit'
4. Fill in 'Age' and 'Years of experience'
5. Click on the CodeSandbox browser "<" button (this will take us back to step 1)
6. Observe that 'First Name' and 'Last name' have the same values we previously filled in
7. Click on 'Submit'
8. Observe that 'Age' and 'Years of experience' are now empty, even though we previously filled them in.

**Codesandbox link**
https://codesandbox.io/s/form-wizard-pages-kkg7m

**Expected behavior**
State should be preserved when navigating back (just like it would if we had controlled components)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 82.0

**Comment by bluebill1049** [comment] 2020-02-28 21:36
i couldn't reproduce what you mentioned above with chrome, can you try under chrome and see if we can isolate the issue.

**Comment by bluebill1049** [comment] 2020-02-28 21:43
By the way, global state is holding inside little-state-machine, with controlled component you will need global state lib as well :)

**Comment by PedroLamas** [comment] 2020-02-28 21:43
Confirmed, had the same issue on both Chrome desktop and Android phone just a few moments ago.

I can reproduce consistently the issue! 😕

**Comment by PedroLamas** [comment] 2020-02-28 21:45
The main issue here is that global state is only updated when data is validated correctly and then submitted, but if we navigate back, no event is raised so data is just lost.

**Comment by bluebill1049** [comment] 2020-02-28 21:47
oh wait, you didn't submit the form?

**Comment by bluebill1049** [comment] 2020-02-28 21:48
if you want such behavior then that's a usage problem then, you probably want to attach onChagne and update store each change.

**Comment by bluebill1049** [comment] 2020-02-28 21:48
you want to leverage from this API: https://react-hook-form.com/api#getValues

**Comment by PedroLamas** [comment] 2020-02-28 21:54
Fair enough! I kind of expected that and just wanted to ensure I didn't miss anything!

Thank you for your help and your work on this project! 🙂

**Comment by bluebill1049** [comment] 2020-02-28 21:55
my pleasure @PedroLamas 👍 going to close this issue, feel free to follow up more questions at our spectrum channel.

**Closed by bluebill1049** 2020-02-28 21:55 UTC
Labels: not valid, question

**Comment by yonusbakhshi** [comment] 2020-09-02 15:29
We had the same bug. We updated the react-hook-form to 6.7.0 and used `useForm({ shouldUnregister: false })` . This fixed our issue.
