### ISSUE TITLE
mateiral ui checkbox and switch default values not working

### ISSUE THREAD

**Issue by xiaoyu-tamu** [react-hook-form/react-hook-form#459] opened 2019-11-04 22:25 UTC
**Describe the bug**

These two controls does not work as expected.

**Codesandbox link**

https://codesandbox.io/s/modest-wilson-9xfs2?fontsize=14

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOs
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22]  latest

**Comment by bluebill1049** [comment] 2019-11-04 22:33
The reason is due to material UI doesn't support uncontrolled components. You may need to use custom register, which means register during `useEffect` and update value with `setValue`. I hope material UI will support uncontrolled components one day...

这是因为MUI不支持不受控制组件， 最好在他们哪里发个issue

**Comment by stocksp** [comment] 2019-11-05 01:31
@xiaoyu-tamu I forked your code and fixed just the Switch (developer2) they all can be fixed in a similar fashion.

@bluebill1049  Hey Bill not sure if this can be fixed on your end (its NOT a big deal and easy to process) or I'm doing something wrong ... but if you look at the developer2 property you will see that submit sets/reads the control  as false or "true" (boolean if false and a string if true).

**Comment by stocksp** [comment] 2019-11-05 01:38
And here is the code
https://codesandbox.io/s/solitary-wood-ir6hq

**Comment by bluebill1049** [comment] 2019-11-05 01:42
thanks @stocksp I think it's due to the default value.

defaultValues: {
      isDeveloper1: true,
      isDeveloper2: true,
      isDeveloper3: true
}

**Comment by stocksp** [comment] 2019-11-05 01:48
If you toggle the switch you will see that when the switch is 'off' the value is a boolean when it is on the value is a string "true".   This is the same with default value.  Set the default isDeveloper2 to false AND set the useState to false and you get the same thing.  false is a boolean true is a string

**Comment by bluebill1049** [comment] 2019-11-05 04:32
it really depends if the input provides a value attribute or not, which I believe its an HTML thing.

`<input type="checkbox" value="lol" />`
vs
`<input type="checkbox" />`

**Comment by stocksp** [comment] 2019-11-05 05:01
In my app I'm  seeing checked is
`<input class="PrivateSwitchBase-input-327 MuiSwitch-input" name="hasMeeting" type="checkbox" value="true" checked="">`
not checked is
`<input class="PrivateSwitchBase-input-327 MuiSwitch-input" name="hasMeeting" type="checkbox" value="false" checked="">`

Anyway its trivial to check and force the string to a boolean,  thanks again for your work.  This is so much simpler than FinalForm and Formix (I've done projects with both)

**Comment by bluebill1049** [comment] 2019-11-05 05:03
that's really glad to hear @stocksp 

maybe you can help with this or even a PR

```
if (isCheckBox(type)) {
    if (checked) {
      return ref.attributes && ref.attributes.value
        ? isUndefined(value) || value === ''
          ? true
          : value
        : true;
    }
    return false;
  }
```
here is the code to determine the value, let me know if you have a better solution for it.

**Comment by stocksp** [comment] 2019-11-05 16:11
The code will definitely produce the results we are seeing:
unchecked is always a boolean and checked May end up as a string.
As don't understand why we EVER return value (which will be a string),  I'd need to spend some time looking at non MaterialUI check boxes.
  Adding  || value === 'true'  would 'fix' this for MaterialUI but probably break cases I'm not familiar with.
I'll have some time this weekend and I'll see if I can understand whats going on ... I've not worked with TypeScript so the exercise will be good for me..

**Comment by bluebill1049** [comment] 2019-11-05 20:07
> As don't understand why we EVER return value (which will be a string

This is actually followed native HTML input.

**Comment by bluebill1049** [comment] 2019-11-06 02:29
going to close this issue for now. feel free to submit a PR @stocksp if you find a better solution for the checkbox one :)

**Closed by bluebill1049** 2019-11-06 02:29 UTC
Labels: dependency

**Comment by TheMoonDawg** [comment] 2020-03-19 19:31
So is the current solution still to use a custom register and keep track of the form values via `setValue`?

We just ran into this issue using Material UI checkboxes as well.

**Comment by bluebill1049** [comment] 2020-03-19 21:23
@TheMoonDawg use Controller :)

**Comment by bluebill1049** [comment] 2020-03-19 21:24
actually @TheMoonDawg yes sorry for the earlier reply, unless you can group them with another component and using with Controller, i am not too familiar with MUI.

**Comment by TheMoonDawg** [comment] 2020-03-20 14:11
Cool, I made a custom component to wrap all of that stuff for me then. Here's the code in case it helps someone else!

`
import React, { useEffect, useState } from 'react'
import PropTypes from 'prop-types'
import { Checkbox as MuiCheckbox } from '@material-ui/core'

const Checkbox = ({ name, register, setValue, value }) => {
  const [checked, setChecked] = useState(false)

  const onChange = e => {
    const checked = e.target.checked

    setChecked(checked)
    setValue(name, checked)
  }

  useEffect(() => {
    register({ name })
  }, [name, register])

  useEffect(() => {
    if (value !== checked) {
      setChecked(value)
      setValue(name, value)
    }
  }, [name, value, setChecked, setValue])

  return <MuiCheckbox name={name} checked={checked} onChange={onChange} />
}

Checkbox.propTypes = {
  name: PropTypes.string.isRequired,
  register: PropTypes.func.isRequired,
  setValue: PropTypes.func.isRequired,
  value: PropTypes.bool,
}

export default Checkbox
`

**Comment by bluebill1049** [comment] 2020-03-20 22:08
awesome! thanks for sharing @TheMoonDawg

**Comment by TheMoonDawg** [comment] 2020-03-23 15:17
I actually ended up getting this working with Controller! Here's a new wrapper component that adds a label for the checkbox as well. I think I was passing `FormControlLabel` into `Controller` directly which obviously wouldn't work as intended.

```
import React from 'react'
import { Controller } from 'react-hook-form'
import PropTypes from 'prop-types'
import { FormControlLabel, Checkbox as MuiCheckbox } from '@material-ui/core'

const Checkbox = ({ label, ...props }) => (
  <FormControlLabel
    control={<Controller as={MuiCheckbox} {...props} />}
    label={label}
  />
)

Checkbox.propTypes = {
  control: PropTypes.object.isRequired,
  name: PropTypes.string.isRequired,
  label: PropTypes.string.isRequired,
}

export default Checkbox
```

**Comment by MrBlue9** [comment] 2020-05-29 10:49
@TheMoonDawg Do you have a short snippet how you implemented the custom checkbox component in the form? If I try to use this component I get "undefined" as value for all checkboxes on submit :-(

**Comment by Sphinxs** [comment] 2020-07-15 19:30
Here's my solution:

```
<Box display="inline-flex" alignItems="center">
  <Checkbox
    defaultChecked={checked} /* Use state or request */
    inputProps={{ "aria-label": "primary checkbox" }}
    inputRef={register} /* Cause using <Controller .../> the values are not registered or are wrong registered, be it in value or data type */
    name="name"
  />

  <Typography variant="body3">Text</Typography>
</Box>;
```

**Comment by bluebill1049** [comment] 2020-07-15 23:15
@Sphinxs try to use `Controller` render prop, it's pretty simple.

**Comment by Sphinxs** [comment] 2020-07-15 23:16
Yeah, I tried, actually with `render` and 'as`

**Comment by bluebill1049** [comment] 2020-07-15 23:18
There is an example here: https://codesandbox.io/s/react-hook-form-v6-controller-qsd8r

**Comment by 97morningstar** [comment] 2020-11-19 09:02
@TheMoonDawg I am a beginner with react and I'm trying to implement your solution, but I don't know how. Do you have a working example or code that works? Thank you so much

**Comment by bluebill1049** [comment] 2020-11-19 09:25
@97morningstar check my comment above, there is a codesandbox there.

**Comment by lukas-warrify** [comment] 2021-04-24 19:58
I know I am a bit late to the party, but one could also use the form context React hook and define watch on the desired value:

```typescript
import React from "react";
import {
  FieldValues,
  useController,
  UseControllerProps,
  useFormContext,
} from "react-hook-form";
import { Flex, FlexProps } from "src/components/flex";
import MUICheckbox from "@material-ui/core/Checkbox";
import FormControlLabel from "@material-ui/core/FormControlLabel";

export const Checkbox: React.FC<
  UseControllerProps<FieldValues> & { flexProps: FlexProps; label: string }
> = (props) => {
  const { watch } = useFormContext();
  const { label, flexProps, ...rest } = props;
  const { name } = props;
  const {
    field: { ref, ...inputProps },
  } = useController(rest);

  return (
    <Flex {...flexProps} alignItems="center">
      <FormControlLabel
        control={
          <MUICheckbox ref={ref} {...inputProps} checked={watch(name)} />
        }
        label={label}
      />
    </Flex>
  );
};
```

**Comment by ViieeS** [comment] 2021-06-25 19:41
How to use it with useController hook?

**Comment by leonlogli** [comment] 2021-07-13 22:47
> How to use it with useController hook?

for react-hook-form v7 + typescript

`import React from 'react'
import FormControl, { FormControlProps } from '@material-ui/core/FormControl'
import FormControlLabel from '@material-ui/core/FormControlLabel'
import FormHelperText from '@material-ui/core/FormHelperText'
import { useController, UseControllerProps, useForm } from 'react-hook-form'
import Checkbox from '@material-ui/core/Checkbox'

// create reusable FormCheckbox component

export type FormCheckboxProps = FormControlProps &
  UseControllerProps & {
    helperText?: React.ReactNode
    label?: React.ReactNode
  }

const FormCheckbox = (props: FormCheckboxProps) => {
  const {
    name,
    control,
    rules,
    helperText,
    fullWidth = true,
    label,
    size = 'small',
    margin = 'normal',
    ...other
  } = props

  const { field, fieldState } = useController({ name, control, rules })

  return (
    <FormControl
      {...other}
      fullWidth={fullWidth}
      size={size}
      margin={margin}
      error={fieldState.invalid}
    >
      <FormControlLabel
        control={
          <Checkbox {...field} checked={field.value} inputRef={field.ref} />
        }
        label={label}
      />
      {(fieldState.error?.message || helperText) && (
        <FormHelperText>
          {fieldState.error?.message || helperText}
        </FormHelperText>
      )}
    </FormControl>
  )
}

// and later
const { handleSubmit, ...form } = useForm()
<FormCheckbox {...form} name="check" label="check" />


`
