### ISSUE TITLE
issue: isValid changes from false to true on first render when react strictMode enabled

### ISSUE THREAD

**Issue by AlexanderKositsyn** [react-hook-form/react-hook-form#9765] opened 2023-01-12 21:01 UTC
### Version Number

7.40.0

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-controller-ts-forked-8ikori?file=/src/index.tsx

### Steps to reproduce

1. Go to console
2. See isValid changes from `false` to `true`

### Expected behaviour

isValid is false, because input is required 
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/28633471/212180409-3cb3a697-4797-4636-882f-27aa693cf105.png">

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexanderKositsyn** [comment] 2023-01-12 21:05
The same on latest version (7.41.5)
LInk https://codesandbox.io/s/react-hook-form-v7-controller-ts-forked-8ikori?file=/package.json:391-397

**Comment by Moshyfawn** [comment] 2023-01-12 21:07
`formState` is initiated with `isValid: false` by default _(we can't know the "correct" value until both the hook and the components are rendered in that order)_. As you're using a field level validation _(`Controller` `rules`)_, form needs to "evaluate" the inputs in the form and their "rules" and set the correct `isValid` value on next re-render

**Comment by AlexanderKositsyn** [comment] 2023-01-12 21:13
You can remove React.StrictMode component and isValid stays false 
https://codesandbox.io/s/react-hook-form-v7-controller-ts-forked-8ikori?file=/src/index.tsx

**Comment by AlexanderKositsyn** [comment] 2023-01-12 21:14
@Moshyfawn is isValid changing from false to true expected behaviour?

**Comment by Moshyfawn** [comment] 2023-01-12 21:15
> @Moshyfawn is isValid changing from false to true expected behaviour?

My bad, I read the `true` & `false` values wrong. Let's see..

**Comment by Moshyfawn** [comment] 2023-01-12 22:20
@bluebill1049 it seems like whatever is causing it is fixed in `origin/master` and was related to [this executeBuiltInValidation call](https://github.com/react-hook-form/react-hook-form/blob/master/src/logic/createFormControl.ts#L165).

You can checkout [this codespace](https://codesandbox.io/p/github/react-hook-form/react-hook-form/fix/9765?create=true&file=%2Fapp%2Fsrc%2Fbasic.tsx&selection=%5B%7B%22endColumn%22%3A26%2C%22endLineNumber%22%3A24%2C%22startColumn%22%3A26%2C%22startLineNumber%22%3A24%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl7ifn02s003yloi3cdqdgc0e%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fapp%252Fsrc%252Fbasic.tsx%2522%252C%2522%252Fapp%252Fsrc%252Fmain.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clctnaj5r001d2e69czcfw6uw%2522%253A%257B%2522key%2522%253A%2522clctnaj5r001d2e69czcfw6uw%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522url%2522%253A%2522cktvkw-3000.preview.csb.app%2522%252C%2522key%2522%253A%2522clctneuyn020y2e69gj3126k5%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clctnau7n00038vjoe27hg1hk%2522%252C%2522key%2522%253A%2522clctnau1300bg2e693exwlzr9%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clctnaj5r001d2e69czcfw6uw%2522%252C%2522spacesOrder%2522%253A%255B%2522clctnaj5r001d2e69czcfw6uw%2522%255D%257D): navigate to [Basic `onChange` test](https://cktvkw-3000.preview.csb.app/basic/onChange) and see that `isValid` is `false`

**Comment by bluebill1049** [comment] 2023-01-12 22:38
thanks a lot @Moshyfawn I will release the minor update today.

**Comment by AlexanderKositsyn** [comment] 2023-01-13 07:32
@bluebill1049 
Not fixed in 7.42.0
https://codesandbox.io/s/react-hook-form-v7-controller-ts-forked-8ikori?file=/src/index.tsx

**Comment by leapful** [comment] 2023-01-13 09:00
@bluebill1049 

It seems the root cause is from line 97 in `useController.ts` when `useEffect` hook performs clean up callback twice in React.StrictMode that causes setting flag `mount` to false.

https://github.com/react-hook-form/react-hook-form/blob/4b4f1d8a5436ba84b9316a82788852adbd240db2/src/useController.ts#L76-L99

With `mount=false`, validation will be stopped and always return valid state.

https://github.com/react-hook-form/react-hook-form/blob/4b4f1d8a5436ba84b9316a82788852adbd240db2/src/logic/validateField.ts#L54-L55

**Comment by bluebill1049** [comment] 2023-01-13 09:23
thanks, @leapful for your help! Finally, figure out a solution for this.

**Closed** 2023-01-13 09:32 UTC
Labels: bug

**Comment by AlexanderKositsyn** [comment] 2023-01-13 10:01
@bluebill1049  Thanks! 
When it will be released?
