### ISSUE TITLE
Issue: Cannot add property 0: object is not extensible

### ISSUE THREAD

**Issue by vanyadymousky** [react-hook-form/react-hook-form#6999] opened 2021-11-09 10:59 UTC
### Version Number

7.19.1

### Codesandbox/Expo snack

Unfortunately, no codesandbox reproduction

### Steps to reproduce

I'm really sorry for not having codesandbox repro, as I'm unable to reproduce there. My project is pretty complex and uses useFieldArray heavily. After migrating to 7.19.1 version I'm having such error on ...register('levels.0.deeperField.0.levelID') call (actually there are many fields starting from 0 till ~40-50):

```
Unhandled Runtime Error
TypeError: Cannot add property 0, object is not extensible
```

These are only stack parts that refer to react-hook-form: 
```
Call Stack
set
node_modules/react-hook-form/dist/index.esm.js (201:0)

handleChange
node_modules/react-hook-form/dist/index.esm.js (1404:0)
```

### Expected behaviour

Please help me to understand for what reason this error may happen. I was not able to find any code in react-hook-form repo that does Object.preventExtensions (maybe in some deps of the project this code exists?) so I'm not sure how to proceed. 

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Next.js full error stack:

Unhandled Runtime Error
TypeError: Cannot add property 0, object is not extensible

Call Stack
set
node_modules/react-hook-form/dist/index.esm.js (201:0)
handleChange
node_modules/react-hook-form/dist/index.esm.js (1404:0)
handleBlur
node_modules/@mui/material/InputBase/InputBase.js (340:0)
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js (3945:0)
Object.invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (3994:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (4056:0)
invokeGuardedCallbackAndCatchFirstError
node_modules/react-dom/cjs/react-dom.development.js (4070:0)
executeDispatch
node_modules/react-dom/cjs/react-dom.development.js (8243:0)
processDispatchQueueItemsInOrder
node_modules/react-dom/cjs/react-dom.development.js (8275:0)
processDispatchQueue
node_modules/react-dom/cjs/react-dom.development.js (8288:0)
dispatchEventsForPlugins
node_modules/react-dom/cjs/react-dom.development.js (8299:0)
eval
node_modules/react-dom/cjs/react-dom.development.js (8508:0)
batchedEventUpdates$1
node_modules/react-dom/cjs/react-dom.development.js (22396:0)
batchedEventUpdates
node_modules/react-dom/cjs/react-dom.development.js (3745:0)
dispatchEventForPluginEventSystem
node_modules/react-dom/cjs/react-dom.development.js (8507:0)
attemptToDispatchEvent
node_modules/react-dom/cjs/react-dom.development.js (6005:0)
dispatchEvent
node_modules/react-dom/cjs/react-dom.development.js (5924:0)
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js (468:0)
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js (11276:0)
discreteUpdates$1
node_modules/react-dom/cjs/react-dom.development.js (22413:0)
discreteUpdates
node_modules/react-dom/cjs/react-dom.development.js (3756:0)
dispatchDiscreteEvent
node_modules/react-dom/cjs/react-dom.development.js (5889:0)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment] 2021-11-09 11:03
what's the working version prior to that? It's hard to reproduce the issue without a codesandbox as well.

**Comment by vanyadymousky** [comment] 2021-11-09 11:05
> what's the working version prior to that? It's hard to reproduce the issue without a codesandbox as well.

7.12.2

**Comment by vanyadymousky** [comment] 2021-11-09 11:06
Will try again to repro in codesandbox

**Comment by bluebill1049** [comment] 2021-11-09 11:08
> The one notice I may admit is i'm calling new fieldArray's method replace before this register error occurs

maybe we can focus on this for reproducible codesandbox?

**Comment by bluebill1049** [comment] 2021-11-09 11:09
It indicate to me that you are try to set an deeply nested value which may not exists yet.

**Comment by vanyadymousky** [comment] 2021-11-09 12:06
@bluebill1049 This is an approximate example of my case: https://codesandbox.io/s/suspicious-lovelace-711e1?file=/src/App.tsx
And in code sandbox it's working fine (notice **deeperFields** is an empty array, but registering deeperFields.0.levelID doesn't cause an error)

**Comment by vanyadymousky** [comment] 2021-11-09 12:10
@bluebill1049 Tried 7.15.4 (as I need replace method I can't go far behind than 7.15.x) - the same issue persists

**Comment by bluebill1049** [comment] 2021-11-09 12:10
can you try what's the last version still works for you? from 7.12.2 onwards

**Comment by bluebill1049** [comment] 2021-11-09 12:12
I thought 7.12.2 is working fine?

**Comment by vanyadymousky** [comment] 2021-11-09 12:15
> I thought 7.12.2 is working fine? <img alt="Screen Shot 2021-11-09 at 11 12 21 pm" width="956" src="https://user-images.githubusercontent.com/10513364/140922197-1f46cd7f-30f8-4864-850e-2983bdb76efc.png">

I was working fine, but I was not using replace there, as this method was only introduced in 7.15.x. I was using .remove() .append() instead

**Comment by bluebill1049** [comment] 2021-11-09 12:21
so it's an issue related to the `replace` API?

**Comment by vanyadymousky** [comment] 2021-11-09 12:26
@bluebill1049 Nope
Just checked 7.19.1 with previous code (remove, append - exactly how it worked with 7.12.2)

**Comment by vanyadymousky** [comment] 2021-11-09 12:37
Was going down in versions to 7.13 - 7.15.3, got the weird error, but different 

Unhandled Runtime Error
TypeError: Cannot assign to read only property '__typename' of object '#<Object>'

Call Stack
set
node_modules/react-hook-form/dist/index.esm.js (156:0)
_updateValues
node_modules/react-hook-form/dist/index.esm.js (1291:0)
_updateValues
node_modules/react-hook-form/dist/index.esm.js (1288:0)
_updateValues
node_modules/react-hook-form/dist/index.esm.js (1288:0)
Object._updateValues
node_modules/react-hook-form/dist/index.esm.js (1288:0)

**Comment by vanyadymousky** [comment] 2021-11-09 12:40
@bluebill1049 Don't want to waste your time, I know it's extremely hard to assume what may be wrong in concrete complex project cases, so if you don't have any other assumptions (other than registering on missing object) - feel free to close the issue, I will continue debugging locally. When I find something I'll get back to you. Thanks

**Comment by bluebill1049** [comment] 2021-11-09 22:00
@vanyadymousky i will see if i can reproduce this today as well 👍

**Comment by bluebill1049** [comment] 2021-11-10 11:30
Is your data have invoked with `Object.preventExtensions(obj);`? or immutable data, if that's case, perhaps you want to provided a clone copy of your data to hook form.

**Comment by vanyadymousky** [comment] 2021-11-11 11:09
@bluebill1049 Bill, I'm afraid that's the case - I'm using @apollo/client, and it looks like .replace(dataFromApollo) prevents **set** hook form method from setting default objects into array, that's marked not extensible by apollo. Looks like I need to deep copy such arrays when calling replace. 
Thanks for help digging this out. Guess issue may be closed.

**Comment by vanyadymousky** [comment] 2021-11-11 11:20
Wait... Array cannot be marked as not extensible...

**Comment by vanyadymousky** [comment] 2021-11-11 11:29
https://codesandbox.io/s/purple-fire-89jp1 - I'm able to reproduce, but the issue is floating: 
When I suddenly change index in "levels.0.deeperFields.4.id" (e.g. from 4 to 31) - I see crashing with 'object is not extensible' error, but it happens from time to time

**Comment by t0x1c123** [comment] 2021-11-11 15:49
Same issue here. I have classic usage of useFieldArray. When I unmount the container (I have form wizard) i got same app crash...

**Comment by vanyadymousky** [comment] 2021-11-11 20:53
> +1 Same issue here. I have classic usage of useFieldArray. When I unmount the container (I have form wizard) i got same app crash...

So the answer is to call replace() with **cloned** (or something) array object ensuring there's no **preventExtensions object** inside. Otherwise hook form is unable to do it's job for safely and effectively managing field array data.

**Comment by bluebill1049** [comment] 2021-11-11 21:57
It's due to `immutable object`, clone the object during replacement is the way to resolve this issue. I am going to close this issue as this is expected usage when working with immutable data.

**Closed by bluebill1049** 2021-11-11 21:57 UTC
Labels: status: need more detail, Status: under investigation

**Comment by t0x1c123** [comment] 2021-11-12 07:46
Well I don't use replace. I just have defaultData initialized in form then I jsust add some items. After that I submit form and redirect somwhere else and boom I got error.

**Comment by bluebill1049** [comment] 2021-11-12 08:37
provide a codesandbox @t0x1c123

**Comment by t0x1c123** [comment] 2021-11-12 09:11
Ok so I manage to fix it. It would be complicated to provice codesandbox but my usage was pretty simple fetch data via react query add them as default. Then I pushed new route and it crashed. I manage to fix it by adding replace like this.

  useEffect(() => {
    replace([...fields]);
  }, [fields]);

**Comment by vanyadymousky** [comment] 2021-11-12 09:14
@t0x1c123 "was pretty simple fetch data via react query add them as default" - Add cloned data as default: 
```tsx
const fetched = await fetch(...)
const formMethods = useForm({
  defaultValues: {
    ...fetched,
    items: fetched.items.map((item) => ({ ...item }))
  }
})
const fieldArrayMethods = useFieldArray({ name: 'items', control })
```
