### ISSUE TITLE
prevent double submit

### ISSUE THREAD

**Issue by tafelito** [react-hook-form/react-hook-form#834] opened 2020-01-14 17:09 UTC
What's the best way to prevent double submitting a form? 

I thought isSubmitting from formState is was meant for that, but it does not. Having a submit button, clicking on it twice makes the isSubmitting go from true to false, even tho the form has already been submitted

**Comment by bluebill1049** [comment] 2020-01-14 20:52
can you give a sandbox to reproduce this? I am not clear on the double submitting.

**Comment by tafelito** [comment] 2020-01-14 21:09
the onSubmit handler is being called multiple times, even tho the form has already been submitted. So what I was doing is checking if `formState.isSubmitting` is true not to do anything, and that makes the flag to keep changing from true to false

you can see it here https://codesandbox.io/s/react-hook-form-async-submit-validation-d2jcu

**Comment by JeromeDeLeon** [comment] 2020-01-14 22:08
Inatead of reading it on your `handleSubmit`, you could do is

```js
<button type="submit" disabled={formState.isSubmitting} />
```

**Comment by bluebill1049** [comment] 2020-01-14 22:39
that's the answer :) thanks @JeromeDeLeon going to close this issue, feel free to ask more questions.

**Comment by tafelito** [comment] 2020-01-14 22:39
that's what I ended up doing, but I was wondering why just but adding that would trigger such behavior

Anyway, thanks!

**Closed by bluebill1049** 2020-01-14 22:39 UTC
Labels: resolved

**Comment by camilosw** [comment] 2020-05-19 12:28
> Inatead of reading it on your `handleSubmit`, what you could do is
> 
> ```js
> <button type="submit" disabled={formState.isSubmitting} />
> ```

Be aware that a form can also be submitted with the Enter key on any field, so you must also need to disable all input fields on the form.

**Comment by JeromeDeLeon** [comment] 2020-05-19 12:32
> > Inatead of reading it on your `handleSubmit`, what you could do is
> > ```js
> > <button type="submit" disabled={formState.isSubmitting} />
> > ```
> 
> Be aware that a form can also be submitted with the Enter key on any field, so you must also need to disable all input fields on the form.

RIght! What I do is create a form blocking component that show a loading state on top of the form. Something like [react-block-ui](https://availity.github.io/react-block-ui/) made.

**Comment by camilosw** [comment] 2020-05-19 12:39
> > > Inatead of reading it on your `handleSubmit`, what you could do is
> > > ```js
> > > <button type="submit" disabled={formState.isSubmitting} />
> > > ```
> > 
> > 
> > Be aware that a form can also be submitted with the Enter key on any field, so you must also need to disable all input fields on the form.
> 
> RIght! What I do is create a form blocking component that show a loading state on top of the form. Something like [react-block-ui](https://availity.github.io/react-block-ui/) made.

I think that's not enough. If the user submitted with Enter, the field is still focused and the user can press Enter again.

**Comment by JeromeDeLeon** [comment] 2020-05-19 12:41
Is adding `isSubmitting` on formSubmit not enough, like below snippet:

```js
const handleSubmit = (data) => {
  if(formState.isSubmitting) {
    return;
  }

  // rest of your logic
}
```

**Comment by JeromeDeLeon** [comment] 2020-05-19 12:50
I tried creating your scenario with [codesandbox](https://codesandbox.io/s/nifty-morning-jew89), but failed to replicate it. Seems like when you disabled that submit button, it won't be submitted even if you pressed `Enter` key to any field.

**Comment by camilosw** [comment] 2020-05-19 13:11
> Is adding `isSubmitting` on formSubmit not enough, like below snippet:
> 
> ```js
> const handleSubmit = (data) => {
>   if(formState.isSubmitting) {
>     return;
>   }
> 
>   // rest of your logic
> }
> ```

That will not work because the `handleSubmit` function returned by `useForm` memoize the function passed to it, so `formState.isSubmitthing` will have the initial value on every submit. Look at the code of `handleSubmit` here: https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L1007

About your codesandbox, I didn't know that, but it's not working that way on the code of my current project. I'll check again and come back if I see something new. Thanks.

**Comment by JeromeDeLeon** [comment] 2020-05-19 13:40
Yes, regarding my previous statement, on haste, I thought it would work. That's why I deleted it.

What about creating your own state? When you hit submit, you will change the state of it and use that to check if its already in submitting state. Haven't come across problem with this double submit prevention so I couldn't think of anything else at the moment. If you could provide a better solution for everyone, that would be great as well. Many thanks.

**Comment by camilosw** [comment] 2020-05-19 14:20
> What about creating your own state? When you hit submit, you will change the state of it and use that to check if its already in submitting state.

Too much work and disabling the submit button is enough. And also, I found my problem, when `handleFormSubmit` is called by `handleSubmit`, it sets `formState.isSubmitting` to true and sets it to false again after `handleFormSubmit` returns:

```js
const handleFormSubmit = (data) => {
  verySlowApi(data);  // returns Promise
}
```

The problem is that `verySlowApi` returns immediately, so the user can submit the form again before the api sends a response. To solve that, I just need to wait for the api response:

```js
const handleFormSubmit = async (data) => {
  await verySlowApi(data);
}
```

**Comment by JeromeDeLeon** [comment] 2020-05-19 14:34
Good that you found it useful. 👍👍

**Comment by NurbekGithub** [comment] 2021-02-08 07:48
Wouldn't it be great to have an bool option to prevent calling submitting function if promise of previous submit is not resolved yet? Just  curious. Any pitfalls?

**Comment by EliseiNicolae** [comment] 2022-09-27 03:25
> > What about creating your own state? When you hit submit, you will change the state of it and use that to check if its already in submitting state.
> 
> Too much work and disabling the submit button is enough. And also, I found my problem, when `handleFormSubmit` is called by `handleSubmit`, it sets `formState.isSubmitting` to true and sets it to false again after `handleFormSubmit` returns:
> 
> ```js
> const handleFormSubmit = (data) => {
>   verySlowApi(data);  // returns Promise
> }
> ```
> 
> The problem is that `verySlowApi` returns immediately, so the user can submit the form again before the api sends a response. To solve that, I just need to wait for the api response:
> 
> ```js
> const handleFormSubmit = async (data) => {
>   await verySlowApi(data);
> }
> ```

keep in mind, that in the 
```
const handleFormSubmit = async (data) => {
  await verySlowApi(data);
}
```
you must have all functions with `await`. In my case, I had an animation that had 700ms duration, and after adding `await` to that function, then it works perfectly.
