### ISSUE TITLE
issue: error when using `useWatch` with a name array and default values as object

### ISSUE THREAD

**Issue by adesurirey** [react-hook-form/react-hook-form#9530] opened 2022-12-05 16:11 UTC
### Version Number

v7.40.0

### Codesandbox/Expo snack

https://stackblitz.com/edit/react-ts-beok4h?file=App.tsx

### Steps to reproduce

1. Modify the TS doc example for `useWatch` so it uses an array as `name`, as mentioned in the comment next to it
2. Update `defaultValues` to an object following TS directives

```ts
function FirstNameWatched({ control }: { control: Control<FormInputs> }) {
  const [firstName, lastName] = useWatch({
    control,
    name: ['firstName', 'lastName'],
    defaultValue: { firstName: 'default', lastName: 'default' },
  });

  return (
    <p>
      Watch: {firstName} {lastName}
    </p>
  );
}
```
3. See the runtime error
```
object is not iterable (cannot read property Symbol(Symbol.iterator))
```

No errors when passing an array as defaultValues but then it generates other TS errors. 

### Expected behaviour

Should not crash, or type should be updated 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment] 2022-12-05 22:30
thanks a lot will try to get it fixed today.

**Comment by bluebill1049** [comment] 2022-12-05 23:00
This is actually not a bug, the return type of the useWatch is actually `array` instead of `object`.

```tsx
function FirstNameWatched({ control }: { control: Control<FormValues> }) {
  const [a,b] = useWatch({
    control,
    name: ['firstName', 'lastName'],
    defaultValue: { firstName: '', lastName: ''},
  });

  return (
    <p>
      Watch: {a} {b}
    </p>
  );
}
```

![Screenshot 2022-12-06 at 10 00 33 am](https://user-images.githubusercontent.com/10513364/205761473-3ceaa746-f4e2-4ee7-9571-9855c5451895.png)

**Comment by adesurirey** [comment] 2022-12-06 08:27
So it's a typing error?

**Comment by bluebill1049** [comment] 2022-12-06 08:48
I tested it on my end and it's fine (the screenshot above).

**Comment by adesurirey** [comment] 2022-12-06 13:12
Yes the type if fine but it produces a runtime error as reproduced here: https://stackblitz.com/edit/react-ts-beok4h?file=App.tsx

**Comment by neerajkrbansal1996** [comment] 2022-12-06 14:07
seems like a bug to me, once you will confirm that it is a bug please let me know if I can take this issue! @bluebill1049

**Comment by bluebill1049** [comment] 2022-12-06 21:06
> seems like a bug to me, once you will confirm that it is a bug please let me know if I can take this issue! @bluebill1049

Yes, please. Let me know if you need some assit.

**Comment by neerajkrbansal1996** [comment] 2022-12-06 21:15
Can you please assign this to me on Github, just to be sure that no one else starts working on the same?

<img width="159" alt="image" src="https://user-images.githubusercontent.com/22657452/206024244-2a45d04e-f042-40d4-a208-215bcfe206d0.png">

**Comment by bluebill1049** [comment] 2022-12-06 21:29
Thank you very much for the help @neerajkrbansal1996 in advance.

**Comment by adesurirey** [comment] 2022-12-08 15:38
@bluebill1049 @neerajkrbansal1996 From mu understanding it comes form this: 

https://github.com/react-hook-form/react-hook-form/blob/master/src/useWatch.ts#L183-L187

When `defaultValue` is an object it is set as `value` returned without any transformation. So then when deconstructing the result as if it was an array, the error is thrown. 

I think it should be something like this: 
```diff
const [value, updateValue] = React.useState<unknown>(
    isUndefined(defaultValue)
      ? control._getWatch(name as InternalFieldName)
-      : defaultValue,
+     : control._getWatch(name as InternalFieldName, defaultValue)
  );
```

**Comment by bluebill1049** [comment] 2022-12-08 21:39
thanks a lot, @adesurirey that's correct!

**Closed** 2022-12-08 22:10 UTC
Labels: bug

**Comment by bluebill1049** [comment] 2022-12-08 22:12
thanks, @neerajkrbansal1996 for the willingness to fix the issue, if you are interested I can ping you with other issues in the near future thanks a lot @adesurirey for the report and also fixing the issue.

**Comment by neerajkrbansal1996** [comment] 2022-12-09 09:20
thanks @bluebill1049 , let me know if can be of some help with other issues!
