### ISSUE TITLE
[Bug]: Controller in a FieldArray results in memory leak warning

### ISSUE THREAD

**Issue by paul-fg** [react-hook-form/react-hook-form#6830] opened 2021-10-18 04:01 UTC
### Version Number

7.17.2

### Codesandbox/Expo snack

https://codesandbox.io/s/upbeat-payne-0q3r5

### Steps to reproduce

1. Go to https://codesandbox.io/s/upbeat-payne-0q3r5
2. Click on "Add Field"
3. Click on "Reset"
4. Click on "Add Field" a second time
5. See error in console about update on an unmounted component

Notes: 
- the error is similar to [6731](https://github.com/react-hook-form/react-hook-form/issues/6731)
- it occurs when using a Controller with a material ui field in a FieldArray

Thanks!

### Expected behaviour

Functionality is correct, however the memory leak should not occur.

### What browsers are you seeing the problem on?

FF, Chrome

### Relevant log output

```shell
index.js:27 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Controller (https://0q3r5.csb.app/node_modules/react-hook-form/dist/index.esm.js:287:35)
    at div 
    in Controller (created by App)
    in App
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by trumbitta** [comment] 2021-11-15 14:51
@bluebill1049 Hi 👋 and thanks for all the astounding work <3

I have this same bug. I found this issue after hours of debugging on my side, when I was finally sure the issue was `Controller` in the `FieldArray`.

v7.17.5 fixes it, but there must be a regression somewhere after that because with v7.19.5 I have the bug again.

**Comment by bluebill1049** [comment] 2021-11-15 21:44
hi @trumbitta can you share a codesandbox for this issue?

**Comment by yaeSakuras** [comment] 2021-11-16 08:13
I have same question。
I use  useFieldArray and Controller with v7.19.5 I have the bug again.

![image](https://user-images.githubusercontent.com/7360502/141946364-26b2446a-c09c-465f-a6a4-c995bdccc8bc.png)

**Comment by bluebill1049** [comment] 2021-11-16 08:23
I can confirm one thing, there is no memory leak here. This warning indicates state update is happening in unmounted inputs.

- this issue related to strict mode
- this issue is related to subscribing at render instead of useEffect, reason for this behavior is so we can kick in the subscription early, if this is an issue, happy to revert such behaviors so we don't see this warning.

**Comment by trumbitta** [comment] 2021-11-16 08:30
If I get to vote, my vote goes to revert it :)

Reasoning:

- I always use strict mode whenever there's one available anywhere
- I'd rather not have to periodically explain what that warning is to the rest of the team :D

**Comment by bluebill1049** [comment] 2021-11-16 08:37
Thanks @trumbitta the only downside is if the user writes code like such:


```
setValue('somethingNotMoun', 'whatever')

useWatch('somethingNotMoun') // will not work unless useEffect is kicked in
```

`useWatch` will not report, which I am fine with that and document as a limitation.

**Comment by bluebill1049** [comment] 2021-11-16 09:06
will be released in the next minor, you shouldn't have to worry about this warning for your product. 👍

**Closed by bluebill1049** 2021-11-16 09:06 UTC
Labels: Status: under investigation

**Comment by vidit-sh** [comment] 2021-11-26 19:05
can confirm the warning is still not fixed in v7.20.4 but was ok in v7.17.5 as mentioned by @trumbitta

**Comment by Seijinx** [comment] 2021-12-01 01:23
Can confirm the same happens in `7.20.5`. Have to still keep using `7.17.5` to prevent this.

@bluebill1049 Do you think it should be reopened ?

**Comment by bluebill1049** [comment] 2021-12-01 01:26
can we provide a codesandbox for the issue?

**Comment by Seijinx** [comment] 2021-12-01 03:34
Sadly I cannot make a codesandbox with Next 11 at this time (broken build for now on codesandbox).

I just found a workaround for the latest `7.20.5` in my case. Since I'm using `FormProvider` I can replace `useController`/`Controller` by `useWatch` and the `field.onChange` by `setValue`.
 
No console warning anymore with this workaround

![image](https://user-images.githubusercontent.com/16969395/144166147-96d9fa62-9aec-47ac-a258-df369cd94fe1.png)

**Comment by ianschmitz** [comment] 2021-12-02 23:23
> will be released in the next minor, you shouldn't have to worry about this warning for your product. 👍

That's fair, however in unit/integration tests it can be common to force tests to fail when console errors or warnings are logged via https://www.npmjs.com/package/jest-fail-on-console or other mechanisms.
