### ISSUE TITLE
Infinite re-renders in Controller [5.4.0]

### ISSUE THREAD

**Issue by val-o** [react-hook-form/react-hook-form#1398] opened 2020-04-12 15:10 UTC
**Describe the bug**
Using a Controller component leads to infinite re-renders on server side, I suspect due to setState in render, can be found here:
https://github.com/react-hook-form/react-hook-form/blob/5097cbe4bf6fb6d61563e7e756acbcf9218e5e4f/src/controller.tsx#L131

Code: 
```
 <Controller
          name="code"
          rules={{
            validate: lengthValidator,
          }}
          control={control}
          as={
            <RifmWrap accept={/\d/g} format={formatCode} onChange={noop} value="">
              {({ value, onChange, rest }) => (
                <TextField
                  {...rest}
                  label={t('identify_code_placeholder')}
                  classes={{ root: classes.inputRoot }}
                  error={!!errors.code || !!codeError}
                  helperText={codeFieldError}
                  fullWidth
                  value={value}
                  disabled={inProgess || isDone}
                  onChange={onChange}
                />
              )}
            </RifmWrap>
          }
        ></Controller>
```

**Comment by bluebill1049** [comment] 2020-04-12 22:42
oops, i will investigate this one and fix it soon.

**Comment by bluebill1049** [comment] 2020-04-12 22:51
hey @val-o do you have a CSB for this issue? so i can verify the fix.

**Comment by bluebill1049** [comment] 2020-04-12 22:52
What's RifmWrap?

**Comment by bluebill1049** [comment] 2020-04-12 22:53
`if (!fieldsRef.current[name]) {` 

This should prevent the re-render tho 🤔

**Comment by asciant** [comment] 2020-04-13 03:06
Can confirm this started happening as soon as I updated to 5.4.0 in NextJS.

I don't use RifmWrap either.

Will try create a CSB.

**Comment by bluebill1049** [comment] 2020-04-13 03:20
Thanks a lot, @asciant will sort out as soon as I can grab a CSB.

**Comment by bluebill1049** [comment] 2020-04-13 03:20
Oh i get it now. is it SSR?

**Comment by bluebill1049** [comment] 2020-04-13 03:21
that's why automation didn't pick it up.

**Comment by asciant** [comment] 2020-04-13 03:21
Yes it appears to be on the server render, as in NextJS you can follow the stack trace down the the _document.js file (only used on SSR).

**Comment by bluebill1049** [comment] 2020-04-13 03:24
cool i will wrap the logic inside `useEffect`. patch is coming.

**Comment by bluebill1049** [comment] 2020-04-13 03:26
can you test this beta: 5.4.1-beta.1?

**Comment by asciant** [comment] 2020-04-13 03:29
The issue is resolved in `5.4.1-beta.1` in my application.

**Comment by bluebill1049** [comment] 2020-04-13 03:29
cool publishing now. thanks a lot @asciant

**Comment by bluebill1049** [comment] 2020-04-13 03:30
waiting for the build to pass...

**Closed** 2020-04-13 03:45 UTC
Labels: bug
