### ISSUE TITLE
formState.isSubmitting doesn't change if error throws in handleSubmit callback

### ISSUE THREAD

**Issue by victorlitvinenko** [react-hook-form/react-hook-form#9827] opened 2023-01-24 06:50 UTC
### Version Number

7.42.1

### Codesandbox/Expo snack

https://codesandbox.io/s/loving-panna-l73h0o?file=/src/App.jsx

### Steps to reproduce

1. Go to the sandbox
2. Click on 'Submit' button
3. Wait for 1 second for error and close the dev overlay
4. See Submitting status didn't change

### Expected behaviour

If you change `react-hook-form` version to **7.41.5** the behaviour will be correct.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by marcalexiei** [comment] 2023-01-24 09:51
Unfortunately now this is the expected behaviour. See #9821

**Comment by victorlitvinenko** [comment] 2023-01-24 11:45
This is very sad news. In our project, `react-query` handles errors. With the new approach, we have to wrap each `onSubmit` handler with an additional `try/catch`.

**Comment by giovannipiller** [comment] 2023-01-24 13:29
> This is very sad news. In our project, react-query handles errors. With the new approach, we have to wrap each onSubmit handler with an additional try/catch.

Same here, and it will require quite some effort to fix and test every form in our app.

As a side note, this breaking change should probably be added to [the release summary](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.42.0), as it can be easily missed (as I did 😅).

**Comment by Moshyfawn** [comment] 2023-01-24 17:49
> As a side note, this breaking change should probably be added to [the release summary](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.42.0), as it can be easily missed (as I did 😅).

We have [a `CHANGELOG.md` file](https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md#changed) for this as well. But we probably should either unify the notes between it and the release summary or simply link to the file, like Vite does

**Comment by Moshyfawn** [comment] 2023-01-24 17:53
@bluebill1049 explains the reason for this change in https://github.com/react-hook-form/react-hook-form/issues/9821#issuecomment-1401009802

I'm gonna close this issue at this time

**Closed by Moshyfawn** 2023-01-24 17:53 UTC

**Comment by amalitsky** [comment] 2023-01-31 05:10
So, as long as you don't care about `formState.isSubmitted` you can resolve the promise (or `catch` exception in your callback) and do your thing (i.e. update local state variable).

If you **do** care about `isSubmitted` **or** are using _react-hook-form_ errors, then the recommended approach with `setError` and `clearErrors` is the only way to go. You will also have to add the nonexistent `serverSide` (or `customError`) property to you formState generic (type).

In later case if you want form to be ready for re-submission wo user touching values (i.e. if server was temporarily down hence server error) you might have to use a `setTimeout` with `clearErrors` and `trigger` calls in you `catch` statement. So that form could consider itself valid right away and be ready for another submission attempt.

```ts
.catch(() => {
  // @ts-ignore
  setError('server error', {
    type: 'server',
    message: 'error',
  });

  setTimeout(() => {
    clearErrors(); // removes server error
    trigger(); // kick off the render
  });
});
```

**Comment by bluebill1049** [comment] 2023-01-31 23:11
@amalitsky let me know your thoughts on this PR: https://github.com/react-hook-form/react-hook-form/pull/9849
