### ISSUE TITLE
react-router breaks fieldArray dirtiness

### ISSUE THREAD

**Issue by webartoli** [react-hook-form/react-hook-form#5185] opened 2021-05-13 15:17 UTC
**Describe the bug**
In a form with field array, dirty fields are always true when redirecting page is performed with react-router after submission.

This unexpected behavior was introduced in 6.15.2

**To Reproduce**

We have implemented 3 different use cases.

  - case 1 - redirect inside validSubmitHandler
  - case 2 - redirect on handleSubmit promise resolved
 - case 3 - no-redirect

Steps to reproduce the behavior for each usecase:

1. Go to case `i`
2. Edit first textbox (Jane) value
3. Submit
3. fieldArray values appear dirty

this occurs in:
- react-hook-form >= 6.15.2
  - ❌case 1 - redirect inside validSubmitHandler
  - ❌case 2 - redirect on handleSubmit promise resolved

this unexpected behavior does not occur:
- ✔️case 3 - no-redirect (any react-hook-form version)
-  with react-hook-form < 6.15.2

**Codesandbox link (Required)**

V6
https://codesandbox.io/s/repro-steps-dirty-field-array-brnv0?file=/src/App.tsx

**Expected behavior**
Only edited fields should be marked as dirty.

**Desktop (please complete the following information):**

- OS: Windows 10 H2
- Browser Chrome, Edge
- Version Latest

**Comment by leapful** [comment] 2021-05-14 01:06
@webartoli @bluebill1049 

The root cause is related to clean up callback of "useEffect" for "useFieldArray" hook.

When using react-router, "history.push" will trigger re-rendering new component related to new route path and also trigger unmount clean up of "useEffect" for old component (in this case it's useFieldArray). When cleaning up field array, react-hook-form will need to remove field array in case "shouldUnregister: true" which is true by default in version >= 6.15.2. 

Setting "shouldUnregister: false" will fix the issue.

Working sample: http://codesandbox.io/s/repro-steps-dirty-field-array-forked-sitmh?file=/src/App.tsx

**Comment by bluebill1049** [comment] 2021-05-14 05:45
Thank very much for the investigation!

**Comment by webartoli** [comment] 2021-05-14 13:08
The first test I made was to add an additional state to trigger an intermediate render as follows.

1. Submit -> onSumbitHandler -> logs dirty values -> setGoingHomeState
2. goingHomeState -> Redirecting to home
3. render home (unmount old components, unregister collection etc...)

Sample:
https://codesandbox.io/s/repro-steps-dirty-field-array-status-redirect-j7js6?file=/src/App.tsx

I was expecting to see the correct dirty values in this case, what am I missing ?
Please consider an example in docs, or defaults for a  more straightforward path.


BTW: Really thanks for your investigation: my issue was solved.

**Comment by bluebill1049** [comment] 2021-05-15 07:25
Let me know how can I improve the doc on v6, so this is clear to the rest of the developers. closing this issue, as it's expected, will follow up on the doc update.

**Closed by bluebill1049** 2021-05-15 07:25 UTC
Labels: V6, question
