### ISSUE TITLE
empty array after using remove methood from useFiledArray

### ISSUE THREAD

**Issue by alonbentura** [react-hook-form/react-hook-form#871] opened 2020-01-20 13:36 UTC
i use filed array to control my array in the form ,  but after i delete one obj in the array and submitting 
all of the array is disappearing and not shown in form "getValues" method

**Comment by bluebill1049** [comment] 2020-01-20 20:22
can you please submit a CSB?

**Comment by alonbentura** [comment] 2020-01-20 20:27
what is it cbs?

**Comment by bluebill1049** [comment] 2020-01-20 20:28
codesandbox, it's in a our issue template (when you submit an issue).

**Comment by rguinea** [comment] 2020-01-20 20:41
@bluebill1049 it's not working when I'm using `useEffect` to register a field. 

https://codesandbox.io/s/react-hook-form-usefieldarray-94uoe?fontsize=14&hidenavigation=1&theme=dark

**Comment by bluebill1049** [comment] 2020-01-20 20:52
why are you register at `useEffect`? @rguinea

**Comment by bluebill1049** [comment] 2020-01-20 20:53
if you doing the custom register, you would need to unregister yourself.

**Comment by rguinea** [comment] 2020-01-20 20:54
Well on the CBS I submitted I don't need it but I'm using select and time pickers which need the custom register. I'm doing the unregister as well.

**Comment by rguinea** [comment] 2020-01-20 20:55
Thing is when I do the `remove`, values from other objects in the array appear as `undefined`

**Comment by bluebill1049** [comment] 2020-01-20 20:56
> Thing is when I do the `remove`, values from other objects in the array appear as `undefined`

why not using `Controller`? I wouldn't recommend doing register/unregister manually.

**Comment by bluebill1049** [comment] 2020-01-20 20:58
> Thing is when I do the `remove`, values from other objects in the array appear as `undefined`

you have a codesandbox for that? (without custom register)

**Comment by bluebill1049** [comment] 2020-01-20 20:59
If you insist on building a Field Array using the custom register, I recommend you build your own Field Array component. https://react-hook-form.com/advanced-usage#FieldArrays

**Comment by rguinea** [comment] 2020-01-21 05:07
Using `Controller` did the trick for me. Thanks!

**Comment by bluebill1049** [comment] 2020-01-21 20:50
closing issue unless you have more question or supply a Codesandbox to reproduce such issue.

**Closed** 2020-01-21 20:49 UTC
Labels: status: need more detail

**Comment by julo15** [comment] 2020-02-04 01:19
@rguinea @bluebill1049 Can you guys explain how `Controller` fixes the issue?

I see the following comment in the Advanced Usage documentation:
>if your application requires functionality such as: Delete, Insert, Append, Preprend. Here is the link for such implementation. with Controller.
Does that mean that `useFieldArray` cannot be used whenever you want to delete/insert/append/prepend? That seems wrong..

**Comment by bluebill1049** [comment] 2020-02-04 02:04
> @rguinea @bluebill1049 Can you guys explain how `Controller` fixes the issue?
> 
> I see the following comment in the Advanced Usage documentation:
> 
> > if your application requires functionality such as: Delete, Insert, Append, Preprend. Here is the link for such implementation. with Controller.
> 
> Does that mean that `useFieldArray` cannot be used whenever you want to delete/insert/append/prepend? That seems wrong..

no, you can use Controller and native input :)

**Comment by julo15** [comment] 2020-02-04 05:50
@bluebill1049 i believe i have found the bug in `useFieldArray`
https://github.com/react-hook-form/react-hook-form/blob/master/src/useFieldArray.ts#L59-L61

`remove` calls `resetFields()` with a new array to reset to:
```
const remove = (index?: number) => {
    if (!isUndefined(index)) {
      mapCurrentFieldsValueWithState();
    }

    resetFields(
      // ***Here we pass in a new array to reset fields***
      removeArrayAt(getFieldValueByName(fieldsRef.current, name), index),
    );
    ...
```

... but `resetFields` ignores the array that was passed in:
```
  const resetFields = (
    flagOrFields?: WithFieldId<Partial<FormArrayValues>>[],
  ) => {
    if (readFormStateRef.current.dirty) {
      isDirtyRef.current = isUndefined(flagOrFields)
        ? true
        : getIsFieldsDifferent(flagOrFields, memoizedDefaultValues.current);
    }

    for (const key in fieldsRef.current) {
      if (isMatchFieldArrayName(key, name) && fieldsRef.current[key]) {
        // ***This part ignores the array that was passed into this function***
        removeFieldEventListener(fieldsRef.current[key] as Field, true);
      }
    }
  };
```

---

Locally, I updated `resetFields` to be the following, and it fixed the issue for me:
```
    const resetFields = (flagOrFields) => {
        if (readFormStateRef.current.dirty) {
            isDirtyRef.current = isUndefined(flagOrFields)
                ? true
                : getIsFieldsDifferent(flagOrFields, memoizedDefaultValues.current);
        }
        const flatFields = flagOrFields && typeof(flagOrFields) === 'object' ? flatten(flagOrFields, name) : undefined;
        for (const key in fieldsRef.current) {
            if (isMatchFieldArrayName(key, name) && fieldsRef.current[key]) {
                if (flatFields[key] === undefined) {
                    removeFieldEventListener(fieldsRef.current[key], true);
                }
            }
        }
    };

function flatten(obj, name) {
    var result = {};
    function recurse (cur, prop) {
        if (Object(cur) !== cur) {
            result[prop] = cur;
        } else if (Array.isArray(cur)) {
              for(var i=0, l=cur.length; i<l; i++)
                  recurse(cur[i], prop + "[" + i + "]");
            if (l == 0)
                result[prop] = [];
        } else {
            var isEmpty = true;
            for (var p in cur) {
                isEmpty = false;
                recurse(cur[p], prop ? prop+"."+p : p);
            }
            if (isEmpty && prop)
                result[prop] = {};
        }
    }
    recurse(obj, name);
    return result;
  }
}

**Comment by bluebill1049** [comment] 2020-02-04 06:03
> @bluebill1049 i believe i have found the bug in `useFieldArray`
> https://github.com/react-hook-form/react-hook-form/blob/master/src/useFieldArray.ts#L59-L61
> 
> `remove` calls `resetFields()` with a new array to reset to:
> 
> ```
> const remove = (index?: number) => {
>     if (!isUndefined(index)) {
>       mapCurrentFieldsValueWithState();
>     }
> 
>     resetFields(
>       // ***Here we pass in a new array to reset fields***
>       removeArrayAt(getFieldValueByName(fieldsRef.current, name), index),
>     );
>     ...
> ```
> 
> ... but `resetFields` ignores the array that was passed in:
> 
> ```
>   const resetFields = (
>     flagOrFields?: WithFieldId<Partial<FormArrayValues>>[],
>   ) => {
>     if (readFormStateRef.current.dirty) {
>       isDirtyRef.current = isUndefined(flagOrFields)
>         ? true
>         : getIsFieldsDifferent(flagOrFields, memoizedDefaultValues.current);
>     }
> 
>     for (const key in fieldsRef.current) {
>       if (isMatchFieldArrayName(key, name) && fieldsRef.current[key]) {
>         // ***This part ignores the array that was passed into this function***
>         removeFieldEventListener(fieldsRef.current[key] as Field, true);
>       }
>     }
>   };
> ```
> 
> Locally, I updated `resetFields` to be the following, and it fixed the issue for me:
> 
> ```
>     const resetFields = (flagOrFields) => {
>         if (readFormStateRef.current.dirty) {
>             isDirtyRef.current = isUndefined(flagOrFields)
>                 ? true
>                 : getIsFieldsDifferent(flagOrFields, memoizedDefaultValues.current);
>         }
>         const flatFields = flagOrFields && typeof(flagOrFields) === 'object' ? flatten(flagOrFields, name) : undefined;
>         for (const key in fieldsRef.current) {
>             if (isMatchFieldArrayName(key, name) && fieldsRef.current[key]) {
>                 if (flatFields[key] === undefined) {
>                     removeFieldEventListener(fieldsRef.current[key], true);
>                 }
>             }
>         }
>     };
> 
> function flatten(obj, name) {
>     var result = {};
>     function recurse (cur, prop) {
>         if (Object(cur) !== cur) {
>             result[prop] = cur;
>         } else if (Array.isArray(cur)) {
>               for(var i=0, l=cur.length; i<l; i++)
>                   recurse(cur[i], prop + "[" + i + "]");
>             if (l == 0)
>                 result[prop] = [];
>         } else {
>             var isEmpty = true;
>             for (var p in cur) {
>                 isEmpty = false;
>                 recurse(cur[p], prop ? prop+"."+p : p);
>             }
>             if (isEmpty && prop)
>                 result[prop] = {};
>         }
>     }
>     recurse(obj, name);
>     return result;
>   }
> }
> ```

thanks for looking into this, are you having issue with `getValues` because it's the next render? I would recommend to use `watch` instead. Let me know if that's the problem.

**Comment by julo15** [comment] 2020-02-04 07:05
IMO, the core problem is that `remove` ends up deleting the entire array out of `fieldsRef.current`; instead, it should just delete the one element out of the array, and update the other refs accordingly. Does that make sense?

Ultimately, my biggest wish for `react-hook-form` is that `getValues` always and dependably returns the current form values. Right now, I'm having some trouble trying to figure out when to use `watch` and when to use `getValues`. I think it would be simpler if `getValues` was always the source of truth.

**Comment by DarkSouls101** [comment] 2020-02-04 07:20
GetValue is meant to read value after. Use watch instead is correct.

**Comment by julo15** [comment] 2020-02-04 09:38
Well, I ended up fixing my issue by iterating on the solution I proposed above (which was incomplete). I really wanted to get `useFieldArray` working, and my change fixed my scenario (where I have a field that is an array of non-simple objects).

I have only done some minimal testing, but it seems to work. See commit [here](https://github.com/julo15/react-hook-form/commit/6d0fc72cb3a84a7e6106d1995bbf5031cdad58ce).

**Comment by bluebill1049** [comment] 2020-02-04 09:40
supply a CSB with your issue, i will take a look there.

**Comment by julo15** [comment] 2020-02-04 10:05
[![Edit React Hook Form - useFieldArray](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-hook-form-usefieldarray-ik0rf?fontsize=14&hidenavigation=1&theme=dark)

Repro:
- press 'append'
- press 'delete' on either element in the list
- press 'submit'

Expected: the submit data should contain `test` = an array of one element
Actual: the submit data is empty

**Comment by bluebill1049** [comment] 2020-02-04 10:14
why do you wrap your fields with memo?

https://codesandbox.io/s/react-hook-form-usefieldarray-zs5n6

**Comment by julo15** [comment] 2020-02-04 11:37
ah, the `useMemo` was not needed. sorry, i took the CSB from somewhere else and modified it. didn't notice the useMemo.

okay interesting... yes `register()` does fix it for standard inputs! that is good. i'm still having problems, though, with custom inputs.
https://codesandbox.io/s/react-hook-form-usefieldarray-w6sjx

in this new example, i have a `FruitComponent` which uses `setValue`. i'm having the following problem:

Repro steps:
1) Press 'append', then select a fruit name
2) Repeat step 1 to add a second fruit
3) Press 'remove' on one of the fruits
4) Press 'submit'

In this case, the data will be missing the fruit name, and I'm not sure why. Is there something I am missing with custom inputs?

**Comment by bluebill1049** [comment] 2020-02-04 11:39
> Using Controller did the trick for me. Thanks!

use Controller should help.

**Comment by julo15** [comment] 2020-02-04 19:55
Thank you for the help @bluebill1049 !

I'm trying now with Controller, can't seem to get it working.

https://codesandbox.io/s/react-hook-form-field-array-advanced-with-delete-insert-append-edit-c8ei3
(I took [this](https://codesandbox.io/s/react-hook-form-field-array-advanced-with-delete-insert-append-edit-l19pz) example and made it slightly more complicated.)

Repro:
1) Append two times
2) Enter a value into the second row's input
3) Delete the first row
4) Append one row
5) Submit

Result: Form data has some stale data in the second element of the array.

If you have time to take a quick look, that would be appreciated. Thanks so much for the help so far :).

**Comment by bluebill1049** [comment] 2020-02-04 20:33
use our custom hook if you can, save the headache.

use this example and uncomment native input with controller

https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv

**Comment by goodpixels** [comment] 2021-02-26 23:27
I am having the same issue as @julo15, @bluebill1049 .

When I remove field from an array of fields, the `isMatchFieldArrayName` incorrectly removes all child fields.

If my form has 3 inputs in an array (for example `tags[0].name`, `tags[1].name` and `tags[0].name`, if I remove the middle one `remove(1)`, the entire `tags` key is removed from the data on submission.

I actually have found this GitHub issue by debugging my code when I discovered that `isMatchFieldArrayName` removes the entire array.

I don't have a Codesandox to share, but I think this is an actual bug, because like I said, I only discovered this thread after debugging `isMatchFieldArrayName`.

Also, in regards to using Controller, well, everything works as expected without the Controller, except when you remove an item from the array not in order.

**Comment by bluebill1049** [comment] 2021-03-22 11:03
> I am having the same issue as @julo15, @bluebill1049 .
> 
> When I remove field from an array of fields, the `isMatchFieldArrayName` incorrectly removes all child fields.
> 
> If my form has 3 inputs in an array (for example `tags[0].name`, `tags[1].name` and `tags[2].name`, if I remove the middle one `remove(1)`, the entire `tags` key is removed from the data on submission.
> 
> I actually have found this GitHub issue by debugging my code when I discovered that `isMatchFieldArrayName` removes the entire array.
> 
> I don't have a Codesandox to share, but I think this is an actual bug, because like I said, I only discovered this thread after debugging `isMatchFieldArrayName`.
> 
> Also, in regards to using Controller, well, everything works as expected without the Controller, except when you remove an item from the array not in order. It seems others have also this problem: #1179

looks like I miss this question that you asked, could you provide a codesandbox for the problem?
