### ISSUE TITLE
Support for input type="file"

### ISSUE THREAD

**Issue by friggeri** [react-hook-form/react-hook-form#127] opened 2019-07-11 19:59 UTC
**Is your feature request related to a problem? Please describe.**
I am trying to put together an upload form using react-hook-form but the value passed to the handle submit callback is the file path, not the actual files object

**Describe the solution you'd like**
For input type="file", return an object containing both file paths and file objects

**Describe alternatives you've considered**
Hacking together a custom input component, manually calling setValue

**Comment by bluebill1049** [comment] 2019-07-11 23:25
I will take a look at this issue this weekend :)

**Comment by bluebill1049** [comment] 2019-07-12 22:54
ok @friggeri what about this for a solution, for input file when you want more than just a file path:

```
useEffect({
  regsiter({ name: 'file' }, { required: true }) // still have validation for required
}, [regsiter])

const handleChange = (e) => {
  setValue('file', e.target.value.files); // you get all the files object here
}

<input name="file" onChnage={handleChange} />
```

**Comment by friggeri** [comment] 2019-07-12 22:56
That's pretty much what I've been doing yes, but I feel like the UX could be smoother🤔

**Comment by bluebill1049** [comment] 2019-07-12 23:16
yea I thought about the issue last night, right now I am more towards consistency because all input during submit is referred to the value/checked attribute (submitted as string). if I am making except with input file (return as an object), it kinda going the opposite. I will leave as it is for now until more ppl raise up concerns over the input file, and then we can come up with a better solution towards file. 👍

**Comment by bluebill1049** [comment] 2019-07-16 03:11
hey @friggeri you happy for me to close this issue for now? I will look at this issue again if more people having concern over the input file.

**Comment by friggeri** [comment] 2019-07-17 06:26
I think that's a reasonable solution!

**Comment by stramel** [comment] 2019-09-20 21:39
@bluebill1049 I ran into this today when I decided to play around with auto registering the input using ref. I don't think it would be too hard to say `if (type === 'file') { return ref.files }` instead of using `value`.

I _think_ at a quick glance we could easily improve this DX.

**Comment by bluebill1049** [comment] 2019-09-20 21:43
@stramel yes, is there any chance people will assume they will get the value?

**Comment by stramel** [comment] 2019-09-20 21:46
@bluebill1049 I **highly** doubt it. The value is essentially worthless. 

![image](https://user-images.githubusercontent.com/855184/65360595-2149c100-dbc6-11e9-8ccc-eef11a08f97e.png)

**Comment by bluebill1049** [comment] 2019-09-20 21:47
@stramel good point

**Comment by bluebill1049** [comment] 2019-09-20 23:34
patched on `3.23.11-beta.1`

**Comment by bluebill1049** [comment] 2019-09-23 02:09
Patched with latest version

**Closed by bluebill1049** 2019-09-23 02:09 UTC
Labels: question

**Comment by stramel** [comment] 2019-09-23 13:50
Thanks @bluebill1049! I will be playing around with this today.

**Comment by stramel** [comment] 2019-09-23 14:33
There is still some stuff missing from providing first-class support for file inputs but this works for just a basic file input.

**Comment by bluebill1049** [comment] 2019-09-23 21:18
@stramel let me know what's the missing piece

**Comment by jinocj** [comment] 2020-05-12 05:49
Hey @bluebill1049  ,  will there be any support for input type file planned  in react-hook-form planned for future releases? currently in docs , there is nothing given on it ,

**Comment by bluebill1049** [comment] 2020-05-12 05:51
hey @jinocj we support input type file, give it a try and let me know if you have questions.

**Comment by jinocj** [comment] 2020-05-12 06:02
@bluebill1049  Can u share the link of sample code or of docs

**Comment by bluebill1049** [comment] 2020-05-12 06:17
`<input type="file" ref={register} />` should be just as standard.

**Comment by alx-ppv** [comment] 2020-05-21 06:51
@bluebill1049 Is it possible to clean the file input?
First I tried setting it to an empty FileList like this:
`setValue('fileList', new DataTransfer().files);`
But the DataTransfer constructor has limited browser support.

AFAIK you can reset the input by giving it an empty string as a value. But when I pass empty string, the library sets it to the **ref.files** instead of **ref.value**
Code from library: 
` else if (isFileInput(ref)) {
            if (isEmptyString(value) ||
                isFileListObject(value)) {
                ref.files = value; // <- calls this when value is empty string
            }
            else {
                ref.value = value;
            }
        }`

Is this intentional or a bug?
Thanks in advance, great library!

**Comment by bluebill1049** [comment] 2020-05-21 06:53
> @bluebill1049 Is it possible to clean the file input?
> First I tried setting it to an empty FileList like this:
> `setValue('fileList', new DataTransfer().files);`
> But the DataTransfer constructor has limited browser support.
> 
> AFAIK you can reset the input by giving it an empty string as a value. But when I pass empty string, the library sets it to the **ref.files** instead of **ref.value**
> Code from library:
> ` else if (isFileInput(ref)) { if (isEmptyString(value) || isFileListObject(value)) { ref.files = value; // <- calls this when value is empty string } else { ref.value = value; } }`
> 
> Is this intentional or a bug?
> Thanks in advance, great library!

can you try this:
`setValue('fileList', '')`

**Comment by alx-ppv** [comment] 2020-05-21 06:58
Thank you for the quick response.
I did and it crashes with error
```
Uncaught TypeError: Failed to set the 'files' property on 'HTMLInputElement': The provided value is not of type 'FileList'
```
It shoud probably set the value property insead of the files property.

**Comment by bluebill1049** [comment] 2020-05-21 07:00
which version are you on? it should reset the input with an empty string. can you supply a CSB with this too?

**Comment by alx-ppv** [comment] 2020-05-21 07:15
Oh, my bad, I was with an older version: 5.1.3.
I updated to 5.7.2 and it works like a charm.
Thank you again for the quick response!

**Comment by MirzaMBaig** [comment] 2020-05-31 23:47
Hi 
Im having the same problem when I use MS fluentui. 
When I use RHF for file upload it returns file path rather than the actual file object.
here is the repo - https://github.com/MirzaMBaig/react-hook-form-file-input. 
Can you please let me know if I'm doing something wrong.

Thanks
mb

**Comment by h0jeZvgoxFepBQ2C** [comment] 2020-06-03 18:51
For me its also not working somehow.. I only get an empty hash like ```{"0" => {}}````

```jsx
<input type="file" ref={register} name="video_waiting_screen_image"/>
```

Also with 5.7.2

**Comment by nativ3-io** [comment] 2020-06-11 21:19
The result data upon submission is in json, this wont work with axios or similar. When submitting, it should use new FormData()

`let formData = new FormData();`

then use 

`formData.append('file_field', data['file_field'][0]);`

or loop append to convert json to FormData.

I wish there's a parameter to convert data, so we dont have to do this.

**Comment by h0jeZvgoxFepBQ2C** [comment] 2020-06-11 21:59
Is there a way that i can query react-hook-form so it generates fuch a form-data object? 
Would be cool if you don't have to do it by yourself

Maybe extend the ```onSubmit``` signature, so that the first parameter is data as object and a new second parameter with the same data, but already converted to a FormData-object?

**Comment by Jossnaz** [comment] 2020-08-12 04:38
not solved yet? 😢 

so bottom line, rhf doesnt work well with axios? I'm losing my time here trying to figure how to upload a simple file...

**Comment by Jossnaz** [comment] 2020-08-12 21:10
it _seems_ like this is a good package to do object -> form data : https://github.com/therealparmesh/object-to-formdata

I tried several functions, they all were not able to translate properly, causing a hiccup when using name attributes with arrays e.g.
```
<input type="field" name={`myfield[${i}]`}/>
```
was causing problems when using for example the solution from https://stackoverflow.com/a/22783314/533426

but  https://github.com/therealparmesh/object-to-formdata seems to do fine

**Comment by isaacdchan** [comment] 2020-12-11 20:46
Not sure if this is the right thread:

I get all the relevant data when I console.log() the input data in my onSubmit handler AND the data is the correct type (FileList).
However, all FileList methods fail or return undefined.
![Capture](https://user-images.githubusercontent.com/33741008/101953219-d6431180-3bae-11eb-8a05-ea207ae17a0d.PNG)

Any guidance appreciated. Thanks!

**Comment by bluebill1049** [comment] 2020-12-11 23:17
> Not sure if this is the right thread:
> 
> I get all the relevant data when I console.log() the input data in my onSubmit handler AND the data is the correct type (FileList).
> However, all FileList methods fail or return undefined.
> ![Capture](https://user-images.githubusercontent.com/33741008/101953219-d6431180-3bae-11eb-8a05-ea207ae17a0d.PNG)
> 
> Any guidance appreciated. Thanks!

can you reproduce that in a codesandbox?

**Comment by isaacdchan** [comment] 2020-12-12 00:24
@bluebill1049

Here's the [link](https://codesandbox.io/s/mystifying-https-4246c?file=/src/App.tsx)

File successfully uploads. When I try printing the length (undefined) and printing the first item() of the FileList (TypeError).

**Comment by bluebill1049** [comment] 2020-12-12 00:30
<img width="1051" alt="Screen Shot 2020-12-12 at 11 30 44 am" src="https://user-images.githubusercontent.com/10513364/101966866-7b242400-3c6d-11eb-82b7-1ba3959b8e6b.png">

@isaacdchan

**Comment by isaacdchan** [comment] 2020-12-12 00:47
![image](https://user-images.githubusercontent.com/33741008/101967558-d43d7a80-3bcf-11eb-89d3-8c94058a22d8.png)
![image](https://user-images.githubusercontent.com/33741008/101967579-e6b7b400-3bcf-11eb-91f5-37316f36513c.png)

As shown in my first screenshot I have also been able to console.log the actual FileList object, but none of the FileList attributes/methods are working.

Am I making an obvious mistake? Can I triple check that FileList is the correct type?

Thanks @bluebill1049

**Comment by bluebill1049** [comment] 2020-12-12 01:12
> ![image](https://user-images.githubusercontent.com/33741008/101967558-d43d7a80-3bcf-11eb-89d3-8c94058a22d8.png)
> ![image](https://user-images.githubusercontent.com/33741008/101967579-e6b7b400-3bcf-11eb-91f5-37316f36513c.png)
> 
> As shown in my first screenshot I have also been able to console.log the actual FileList object, but none of the FileList attributes/methods are working.
> 
> Am I making an obvious mistake? Can I triple check that FileList is the correct type?
> 
> Thanks @bluebill1049

`const test = (d) => console.log(d.file[0]);`

**Comment by h0jeZvgoxFepBQ2C** [comment] 2020-12-12 01:15
> it _seems_ like this is a good package to do object -> form data : https://github.com/therealparmesh/object-to-formdata

This worked also pretty fine for me after playing around for a long time, it's quickly implemented with the object-to-formdata library.

@isaacdchan Feel also free to post your question here, maybe you get more answers there also: https://github.com/react-hook-form/react-hook-form/discussions

**Comment by isaacdchan** [comment] 2020-12-12 01:32
If I set the input type to `any` and use `input.file[0]` I am able to access the file's attributes. 

This works as temporary solution but

1. contradicts Mozilla's own [documentation ](https://developer.mozilla.org/en-US/docs/Web/API/FileList#Attributes) on FileList
2. still gives the following error if I restrict the input type to `FileList`:

![image](https://user-images.githubusercontent.com/33741008/101968772-b83cd780-3bd5-11eb-816d-805edc94cebc.png)

Thanks for the help @bluebill1049. @h0jeZvgoxFepBQ2C I'll check out that package and post my question on the forums if it doesn't satisfy my use case. Hope my confusion makes things clearer for someone else.

**Comment by akshaykumar771** [comment] 2020-12-18 09:14
> > it _seems_ like this is a good package to do object -> form data : https://github.com/therealparmesh/object-to-formdata
> 
> This worked also pretty fine for me after playing around for a long time, it's quickly implemented with the object-to-formdata library.
> 
> @isaacdchan Feel also free to post your question here, maybe you get more answers there also: https://github.com/react-hook-form/react-hook-form/discussions

Hello, I am using formdata for first time and would like to know if you have a codesandbox link which consists of object-to-formdata with react hook form. It will really help me to solve my problem much quicker and i hope it helps others also who does not know how to integrate these two libraries. Thanks in advance

**Comment by h0jeZvgoxFepBQ2C** [comment] 2020-12-21 13:46
You can use it like following code:

```javascript
import {serialize} from "object-to-formdata";
...

const sendForm = (data) => {
    setSending(true)

    axios({
      method: "post",
      url: myUrl
      data: serialize({myData: data})
    })

```

**Comment by akshaykumar771** [comment] 2020-12-21 13:58
> You can use it like following code:
> 
> ```js
> import {serialize} from "object-to-formdata";
> ...
> 
> const sendForm = (data) => {
>     setSending(true)
> 
>     axios({
>       method: "post",
>       url: myUrl
>       data: serialize({myData: data})
>     })
> ```

I tried this but does not seem to work. I am not sure if there is any mistake in what I did. COuld you please have a look at this codesandbox link[]( https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-forked-ln34x?file=/src/index.js) and let me know what is wrong here. Thank you so much for your help.

**Comment by orber3** [comment] 2021-03-12 19:44
hey.
i wrote a stepper form using react material ui with react hook form context.
all of the form inputs works fine,  except in the file type=file , the register isnt working at all and no data is being saved for this input.
any suggestion ? 
thanks.

**Comment by ali-garajian** [comment] 2021-06-09 14:18
@bluebill1049 Hey there. I don't know if this is the greatest place to ask this, but ... I'm using useFieldArray, and I have an input of type 'file'. The docs say all inputs must have a defaultValue, but providing a defaultValue for file inputs causes the following error:

> InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.

Is it ok not to provide a defaultValue for file inputs? I'm experiencing problems using file inputs with useFieldArray, and I wanna know if this could be the cause of it

**Comment by rootsher** [comment] 2021-11-09 07:32
I created a quick snippet for handling `input type="file"` via `react-hook-form` and `zod` in 3 different ways: `via register`, `via control` and `via useController` - feel free to use https://stackblitz.com/edit/input-file-react-hook-form?file=src/Form.js :)

**Comment by bluebill1049** [comment] 2021-11-09 08:43
thanks for sharing @rootsher

**Comment by rootsher** [comment] 2021-11-09 09:25
@bluebill1049 I also added: default value (`new File`), schema validation (`z.instanceof`) and file deletion (using `useFormContext`)

**Comment by simplenotezy** [comment] 2021-11-30 18:05
@bluebill1049 would you have time at some point to update examples with File upload? I've been knocking my head against the wall, trying to get it working properly.
