### ISSUE TITLE
[Bug]: Not updating isDirty form state on date comparison

### ISSUE THREAD

**Issue by garthtee** [react-hook-form/react-hook-form#6703] opened 2021-10-04 10:03 UTC
### Version Number

7.15.3

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-v7-controller-forked-pfs0q?file=/src/index.js

### Steps to reproduce

1. Go to the [code sandbox](https://codesandbox.io/s/react-hook-form-v7-controller-forked-pfs0q?file=/src/index.js).
2. Select a different date and see the dirty field change as expected. (e.g. 27th)
3. Select the default date again (28th) and see the dirty state not change as expected
 

### Expected behaviour

IsDirty should update when the date object returns to the same date. This issue persists when using setValue with a `shouldDirty` option.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment] 2021-10-04 10:06
hi there, thanks for the detailed issue report. currently, this is expected behavior, please refer to this issue/feature request for the reason why this is the case: https://github.com/react-hook-form/react-hook-form/issues/6657

**Comment by bluebill1049** [comment] 2021-10-04 11:27
going to close this and address it in the feature request above, looks like there are quite a few upvotes.

**Closed by bluebill1049** 2021-10-04 11:27 UTC
Labels: question
