### ISSUE TITLE
issue: When removing an element from a field array, other elements should not be marked as dirty

### ISSUE THREAD

**Issue by LeonmanRolls** [react-hook-form/react-hook-form#11605] opened 2024-03-08 01:48 UTC
### Version Number

7.51.0

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/compassionate-knuth-ch46dj?file=%2Fsrc%2Findex.tsx

### Steps to reproduce

1. Open up the code sandbox 
2. Click 'remove' on the first or second element
3. See other elements get marked as dirty

### Expected behaviour

Other elements have not been touched and so should not be marked as dirty. 

I beleive this is due to the way `getDirtyFieldsFromDefaultValues` works.
Since it compares with defaultValues by index, once there is an array length mismatch due to an element being removed, the comparison will not give the expected result. 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment] 2024-03-08 01:52
Duplicate of #11605

**Closed by Moshyfawn** 2024-03-08 01:52 UTC

**Comment by LeonmanRolls** [comment] 2024-03-08 01:54
Sorry which issue is this a duplicate of? 11605 is this issue.

**Comment by Moshyfawn** [comment] 2024-03-08 01:55
Oops, my bad 😰 Updated

**Comment by LeonmanRolls** [comment] 2024-03-08 01:56
No problem, thanks!
