### ISSUE TITLE
Prepend is causing an extra render when used with Controller

### ISSUE THREAD

**Issue by ymor** [react-hook-form/react-hook-form#4272] opened 2021-02-24 15:14 UTC
**Describe the bug**
Prepend is causing an extra render when used with Controller.

**To Reproduce**
Using the example here: https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv click prepend and the render count will jump to 3.  If you change the Controller to another standard input like the firstname it does however correctly re-render once.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-usefieldarray-vy8fv

**Expected behavior**
Only one extra render to occur 

**Screenshots**
![image](https://user-images.githubusercontent.com/2701844/109021013-65da6580-76b2-11eb-9275-72ca254d315b.png)

**Desktop:**

- OS: Windows 10
- Browser Chrome
- Version 88.0.4324.182

**Comment by leapful** [comment] 2021-02-24 17:33
@ymor @bluebill1049 

It seems the issue is caused by line 771 of src/useForm.ts where the form state is forced to be updated when unregistering input element.

https://github.com/react-hook-form/react-hook-form/blob/253f57d9d41952df31c2a5e02bbd65d16cbce517/src/useForm.ts#L762-L783

Prepending new field item (inserting at the beginning) always shifts all item indexes in the field array and forces React to destroy old input elements and re-render new one.

With native input element, there is no life cycle handling, that's why there is no issue of multiple re-rendering. 

With Controller component, cleaning up life cycle of "useEffect" inside "useController" will be performed when destroying the old Controller, it will trigger method "unregister" which also calls method "removeFieldEventListenerAndRef" in src/useForm.ts and causes the following multiple re-rendering when: 

1. Adding new field item to field array => Expected
2. Force update form state when unregistering old Controller component => Unexpected

https://github.com/react-hook-form/react-hook-form/blob/253f57d9d41952df31c2a5e02bbd65d16cbce517/src/useController.ts#L155


@bluebill1049 

It seems the "formStateRef.current.dirtyFields" is set but "formStateRef.current.isDirty" is not updated in this case and always equals true.

I've tested OK after adding a check before force updating formState with isDirty value.

For example
```
const isDirty = isFormDirty();

if (isDirty !== formStateRef.current.isDirty) { updateFormState({ isDirty }); }
```

Do you remember why we need to set "formStateRef.current.dirtyFields" when unregistering field ?

The change is from https://github.com/react-hook-form/react-hook-form/commit/1b3a26e44cd5831eff089c250f66563fe1dec267

**Comment by bluebill1049** [comment] 2021-02-25 07:26
thanks, @leapful for the detailed investigation, i think all we need is to make sure only trigger re-render when dirty is subscribed. sending a pr now.

**Comment by bluebill1049** [comment] 2021-02-25 07:51
Ok, I think I am going to skip this PR, the updateFormState actually serves two `formstate`

- build-in validation isValid
- update form state dirty

I think for that extra single re-render we will live with it in v6, this should be fixed in v7. Thanks for your detailed investigation @leapful

**Closed** 2021-02-25 21:54 UTC
Labels: wont be worked on
