### ISSUE TITLE
Forms can be submitted even when a field is invalid

### ISSUE THREAD

**Issue by ccnokes** [react-hook-form/react-hook-form#3079] opened 2020-10-05 03:37 UTC
**Describe the bug**
On v5.7.2 and v6.9.0, a form can be submitted when a field is invalid. 

**To Reproduce**

1. Go to one of the sandboxes below (first one is v5, second is v6)
2. Enter more than 3 chars in the field (it'll show an error message in the UI)
3. Submit the form

It still submits 😢. I would say it should not. (Side note: if this is not a bug, how do I make it not submit?). It seems like when I use `setError`, the form can still be submitted, but not if I use the standard `required` or `pattern`. 

**Codesandbox link (Required)**
Broken:
https://codesandbox.io/s/react-hook-form-get-started-forked-ug8q0?file=/src/index.js
https://codesandbox.io/s/react-hook-form-get-started-forked-yibkp?file=/src/index.js

I'm hoping to get this fixed in v5 too. I'm happy to help with any of this if you point me in the right direction. If there's a temporary workaround that you know of that'd be great too.

**Desktop (please complete the following information):**
Chrome 85, macOS

**Additional context**
I ❤️  react-hook-form

**Comment by ccnokes** [comment] 2020-10-05 15:54
Thanks for the response @bluebill1049. I'm still confused. So, even if I remove the `name` property from the input and don't `register` it, the form still submits when an error is set (and if I don't `register` it somehow, the value is never set so the submit handler never gets the data). Here's a sandbox of what I'm looking at: https://codesandbox.io/s/react-hook-form-get-started-forked-ug8q0?file=/src/index.js

My use case is that I'm wrapping a customer DateTimePicker with validation and it's not working. I've tried `Controller` and this approach, but I'm still seeing the form submit even though there are errors. I think I'm not understanding `if you want error to be persist then you should assign error to non input names:`. Even the docs example has the same problem: https://codesandbox.io/s/react-hook-form-v6-seterror-forked-47341. Maybe I'm misunderstanding how `setError` and `clearError` are intended to be used, but I'm not sure why you'd want to set an error and allow a form to be submitted.

**Comment by bluebill1049** [comment] 2020-10-06 09:21
> Thanks for the response @bluebill1049. I'm still confused. So, even if I remove the `name` property from the input and don't `register` it, the form still submits when an error is set (and if I don't `register` it somehow, the value is never set so the submit handler never gets the data). Here's a sandbox of what I'm looking at: https://codesandbox.io/s/react-hook-form-get-started-forked-ug8q0?file=/src/index.js

Yes, because in that case, there is no input found hence no validation to match and hence the form passed.

**Comment by bluebill1049** [comment] 2020-10-06 09:22
> My use case is that I'm wrapping a customer DateTimePicker with validation and it's not working. I've tried `Controller` and this approach, but I'm still seeing the form submit even though there are errors. I think I'm not understanding `if you want error to be persist then you should assign error to non input names:`. Even the docs example has the same problem: https://codesandbox.io/s/react-hook-form-v6-seterror-forked-47341. Maybe I'm misunderstanding how `setError` and `clearError` are intended to be used, but I'm not sure why you'd want to set an error and allow a form to be submitted.

any chance you can write that logic into `validate` function?

**Comment by bluebill1049** [comment] 2020-10-06 09:23
which codesandbox is that (in the doc)? I will get it sorted.

**Comment by bluebill1049** [comment] 2020-10-06 09:24
`setError` doesn't persist input field error, because in react hook form that build-in validator is the source of truth for validation.

**Comment by ccnokes** [comment] 2020-10-07 22:18
I found a workaround using a hidden input field like you suggested. I'm still trying to wrap my head around all this behavior. Still just need to make time to dig deeper into it. It's still strange to me that `setError` sets a temporary error. I can value in that, but I guess the name suggested to me that it would persist an error, much like `setValue` seems to persist a value in the form.

**Comment by bluebill1049** [comment] 2020-10-07 22:25
> I found a workaround using a hidden input field like you suggested. I'm still trying to wrap my head around all this behavior. Still just need to make time to dig deeper into it. It's still strange to me that `setError` sets a temporary error. I can value in that, but I guess the name suggested to me that it would persist an error, much like `setValue` seems to persist a value in the form.

yea, I agree with you on some perspective, but the thing I have to consider DX at the same time if you `setError` manually against an input with also have validation against it, which source of truth should you considered to take, do you expect user has to clear that error manually before running against the rules which associate with that input?  I think it's annoying for the user, it's better to have a single source of truth for validation at the field level. That was the decision was made on v6, setError will only persist any none input error.

**Comment by bluebill1049** [comment] 2020-10-10 02:27
Going to close this issue as it's as expected behavior, happy to keep discuss further on this topic.

**Closed by bluebill1049** 2020-10-10 02:27 UTC
Labels: question
