### ISSUE TITLE
Validation applies regex pattern when non-required input is left empty

### ISSUE THREAD

**Issue by dccarta** [react-hook-form/react-hook-form#470] opened 2019-11-06 14:02 UTC
**Describe the bug**
Non-required input fields requiring a regex pattern (that doesn't account for empty) which are left empty by the user cause pattern validation to fail.

It feels like the case where a non-required input is left empty should not trigger validation of that input at all. I get that it's possible to instead use the `validate` prop and include a condition allowing for an empty string or falsy value, but that seems somewhat counterintuitive when the `required` prop is available - surely this should override.

**To Reproduce**
Steps to reproduce the behaviour:
1. Navigate to codesandbox
2. Hit submit without entering anything into non-required field
3. Error state is encountered (with console log of error object showing 'pattern' type error)

**Codesandbox link**
[codesandbox](https://codesandbox.io/s/react-hook-form-get-started-yugr1)

**Expected behavior**
Leaving a non-required input empty should always allow submit regardless of the need for regex validation when the input is actually used

**Comment by bogdaniy** [comment] 2019-11-06 16:25
+1 faced the same issue, I think the problem is `react-hook-form` process `required` like a simple non-empty validator, while we expect it to be rather a validation strategy which skips validation for empty fields.  Maybe there are some workarounds for such behavior?

**Comment by bluebill1049** [comment] 2019-11-06 20:32
@dccarta @bogdaniy how about just use validate function if you have an issue around pattern? it's much flexible. 

```
validate: (value) => value.match('xxxx')
```

**Comment by bluebill1049** [comment] 2019-11-07 01:03
going to close this issue now :) `validate` should be able to achieve what you after. feel free to ask more questions or re-open if this doesn't solve your problem.

**Comment by bluebill1049** [comment] 2019-11-07 01:04
don't forget to leave a little ⭐️ to support the lib too :) thank you

**Comment by dccarta** [comment] 2019-11-07 08:12
I get that `validate` is able to handle this case - but by extension it's also able to handle the cases where an input is either required or non-required, so why even have the `required` prop at all? Just feels like if you're going to have it, it may as well fully work as expected.

It'd be a very simple addition to the if logic in the `pattern` func that I'd be happy to submit a PR for...but no worries if you don't think it's necessary.

**Comment by bluebill1049** [comment] 2019-11-07 08:30
hey @dccarta you have a valid point! I will update that and it will be in the next patch.

**Comment by bluebill1049** [comment] 2019-11-07 08:37
i will add you in the PR too @dccarta

**Comment by bluebill1049** [comment] 2019-11-07 08:41
@dccarta https://github.com/react-hook-form/react-hook-form/pull/474

**Comment by bluebill1049** [comment] 2019-11-07 09:19
it's merged and will be in the next patch. 👍

**Closed by bluebill1049** 2019-11-07 09:19 UTC
Labels: bug

**Comment by dccarta** [comment] 2019-11-07 10:00
looks good to me, cheers for the quick response! keep up the good work, lib is 🔥

**Comment by bluebill1049** [comment] 2019-11-07 10:09
awesome @dccarta thanks for the issue report and feedback mate :) I would love to see you contribute this lib in the near future as well, next time just send a PR with an issue like that. again thanks for helping to make this lib better 👍 (i will release this patch over the weekend when it is bit quieter :)

**Comment by vimalmurugan89** [comment] 2020-07-30 02:35
@bluebill1049: was this changes available in latest vesrsion. Still I see not giving required attribute validation is happening. Could you please confirm. Or confirm react hook form version which we need to use.

**Comment by bluebill1049** [comment] 2020-07-30 02:42
This is last year @vimalmurugan89's issue, what's the problem? please provide more context as well.

**Comment by nivibhat** [comment] 2020-11-27 19:37
I am new to this, it could be that I am doing something wrong.
<View style={styles.inputView}>
                    <Controller name='emailId' control={control} render={(props) => (
                        <TextInput {...props}
                            style={styles.inputText}
                            maxLength={256}
                            placeholder="Email.."
                            autoCapitalize="none"
                            value={signupFields.emailId}
                            autoCorrect={false}
                            aria-invalid={errors.emailId ? "true" : "false"}
                            returnKeyType="next"
                            onChangeText={this.onEmailIdChange}
                            onSubmitEditing={()=> Keyboard.dismiss()}
                            underlineColorAndroid="transparent"
                            placeholderTextColor="#003f5c"
                        ></TextInput>
                    )}
                        rules={{required: true,  pattern: {
                            value: emailPattern,
                            message: 'Email must be a valid email address',
                          }, }}
                        //rules = {{required: true, validate: value => !!value && value.match('/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/') || "Nice try!"}}
                        defaultValue=""
                        />
                    </View>
                    <Text>
                    {errors.emailId && errors.emailId.message}
                    </Text>
                          }, }}

I have tried using both pattern and validate function, my errors object still has "invalid email " message even after entering the correct email address.. I don't think the regEx is an issue, not able to figure it out. Any help is appreciated. thanks

**Comment by bluebill1049** [comment] 2020-11-27 22:57
@nivibhat you may want to create a question at the discussion with a codesandbox.

**Comment by klokie** [comment] 2021-01-20 10:56
@nivibhat you've probably already solved this long ago, but I just came across this issue wanted to point out for any future seekers that `match` takes a regexp object as argument, not a string. So this should have worked:

```
const pattern = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
rules={{required: true, validate: value => !!value && value.match(pattern)}}
```

**Comment by bluebill1049** [comment] 2021-01-20 11:13
thanks for sharing solutions @klokie
