### ISSUE TITLE
[useFieldArray] Appended but removed fields reappear in dirtyFields after an other append

### ISSUE THREAD

**Issue by legareszter** [react-hook-form/react-hook-form#3158] opened 2020-10-12 17:23 UTC
**Describe the bug**
When I append (or prepend or insert) a row to a fieldArray, the dirtyFields are also populated with it. When I reset the form, the dirtyFields become empty again. So far so good.
But when I append (or prepend or insert) a new row to the fieldArray, **two rows** are added to dirtyFields. If I repeat reset and append, more and more rows appear in dirtyFields.

**To Reproduce**

1. Go to [forked CodeSandbox example](https://codesandbox.io/s/react-hook-form-usefieldarray-forked-os2r7)
2. Click on Append (or prepend or insert at)
3. Click on Reset
4. Click on Append (or prepend or insert at)
5. Optionally repeat as many times as you like
6. Scroll down to the last paragraph about the formState.dirtyFields
4. See the always growing array in it

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-os2r7

**Expected behavior**
reset **permanently** resets form state, dirtyFields only contains the current fields' dirtiness state

**Desktop (please complete the following information):**

- OS: Win 10
- Browser: Chrome
- Version 85

**Additional context**
react-hook-form version 6.9.2

**Comment by bluebill1049** [comment] 2020-10-12 22:23
Thanks 👍

**Comment by bluebill1049** [comment] 2020-10-12 23:47
looks like this issue is already resolved by the latest commits at master
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-6c9e0?file=/src/index.js

**Comment by bluebill1049** [comment] 2020-10-12 23:47
👨🏻‍💻 fix useFieldArray delete dirty fields (#3119)
👨🏻‍💻 improve field array dirty fields checking (#3127)

let me know if the CSB is working as expected.

**Comment by legareszter** [comment] 2020-10-13 08:48
'Append' is OK, but 'prepend' and 'insert at' still seems to be buggy. Using them not only adds multiple rows to the the dirtyFields, but sets the corresponding values of the initial, unchanged fields to dirty too.

'Delete' is also inconsistent. If I remove then reset the initial fields, everything is OK. If I append a row and reset the form it's fine too. But if I remove a row, reset the form, then append a new one both the new one and the previously deleted and reset rows are marked dirty.

**Comment by bluebill1049** [comment] 2020-10-13 08:52
> Using them not only adds multiple rows to the the dirtyFields, but sets the corresponding values of the initial, unchanged fields to dirty too.

if defaultValue is 3, 2, 1 prepend means to push all the item down 0, 3, 2, 1 which makes all dirty.

**Comment by bluebill1049** [comment] 2020-10-13 08:53
> 'Delete' is also inconsistent. If I remove then reset the initial fields, everything is OK. If I append a row and reset the form it's fine too. But if I remove a row, reset the form, then append a new one both the new one and the previously deleted and reset rows are marked dirty.

can you list out the steps to reproduce? Happy to investigate if there is an issue with it.

**Comment by legareszter** [comment] 2020-10-13 08:56
> > 'Delete' is also inconsistent. If I remove then reset the initial fields, everything is OK. If I append a row and reset the form it's fine too. But if I remove a row, reset the form, then append a new one both the new one and the previously deleted and reset rows are marked dirty.
> 
> can you list out the steps to reproduce? Happy to investigate if there is an issue with it.

1. Remove the second row (Or the first, or all)
2. reset the form
3. append a row

Actual behaviour: 
The second and the third rows are marked dirty

Expected behaviour:
Only the third row is marked dirty, since the previous modifications were undid by reset.

**Comment by bluebill1049** [comment] 2020-10-13 08:58
> > > 'Delete' is also inconsistent. If I remove then reset the initial fields, everything is OK. If I append a row and reset the form it's fine too. But if I remove a row, reset the form, then append a new one both the new one and the previously deleted and reset rows are marked dirty.
> > 
> > 
> > can you list out the steps to reproduce? Happy to investigate if there is an issue with it.
> 
> 1. Remove the second row (Or the first, or all)
> 2. reset the form
> 3. append a row
> 
> Actual behaviour:
> The second and the third rows are marked dirty
> 
> Expected behaviour:
> Only the third row is marked dirty, since the previous modifications were undid by reset.

Thanks. this issue is valid, will investigate for a fix.

**Comment by legareszter** [comment] 2020-10-13 09:06
> > Using them not only adds multiple rows to the the dirtyFields, but sets the corresponding values of the initial, unchanged fields to dirty too.
> 
> if defaultValue is 3, 2, 1 prepend means to push all the item down 0, 3, 2, 1 which makes all dirty.

I'm not sure if I agree with this behaviour. The fields have id-s. Even if I prepend a new field, the ids of the old fields remain the same. And that's cool because I think they are unchanged, they are the same, just moved one position further. Why do the fields have ids if only their position is considered when marked dirty?

**Comment by legareszter** [comment] 2020-10-13 09:09
> if defaultValue is 3, 2, 1 prepend means to push all the item down 0, 3, 2, 1 which makes all dirty.

Even accepting this logic 'insert at' is buggy. Check the CBS example. 'Insert at' inserts a row at position 2, but field at position 0 is marked as dirty too.

**Comment by bluebill1049** [comment] 2020-10-13 09:10
> > if defaultValue is 3, 2, 1 prepend means to push all the item down 0, 3, 2, 1 which makes all dirty.
> 
> Even accepting this logic 'insert at' is buggy. Check the CBS example. 'Insert at' inserts a row at position 2, but field at position 0 is marked as dirty too.

will fix that as well, thanks.

**Comment by bluebill1049** [comment] 2020-10-13 09:11
each input has a unique name, by shifting or changing the position. the input value needs/should validate against the `defaultValues`.

**Comment by legareszter** [comment] 2020-10-13 09:13
> each input has a unique name, by shifting or changing the position. the input value needs/should validate against the `defaultValues` to produce `dirtyFields`.

Oh, I see. Thanks for the explanation.

**Closed** 2020-10-13 10:55 UTC
Labels: bug
