### ISSUE TITLE
Is Valid is not turning to false if you settled an error imperatively

### ISSUE THREAD

**Issue by erickbelfy** [react-hook-form/react-hook-form#1676] opened 2020-05-22 19:58 UTC
**Describe the bug**

isValid attribute is not changing if you set an error imperatively if you previosly set a defaultSchema using yup.

Scenario:
Created a form instance using `useForm` hook, following the requirements of this particular edge case:
* first name is required
* if a question is provided then an answer has to be provided
* if an answer is provided then a question has to be provided

**To Reproduce**

1. type something in the first name;

2. observe that the button that was disabled now it is enabled;

3. type an answer;

4. observe that the question has an error

**Expected behavior**
isValid should be false, hence the button has to be disabled due to the errors object contains some errors in it.

**Actual behavior**
isValid stays true, hence the button has to be enabled even though the error object contains some invalid fields to be validated.

**Screenshots**

<img width="226" alt="Screen Shot 2020-05-22 at 3 50 28 PM" src="https://user-images.githubusercontent.com/1584725/82704672-1313df00-9c44-11ea-90c7-736afcb78ba0.png">

<img width="242" alt="Screen Shot 2020-05-22 at 3 50 36 PM" src="https://user-images.githubusercontent.com/1584725/82704688-1c04b080-9c44-11ea-9eaa-f652f63b0de6.png">

<img width="263" alt="Screen Shot 2020-05-22 at 3 50 46 PM" src="https://user-images.githubusercontent.com/1584725/82704695-1dce7400-9c44-11ea-9677-f58a91de4450.png">

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - Version [83.0.4103.61 (Official Build) (64-bit)]

**Codesandbox link (Required)**
https://codesandbox.io/s/spring-pond-85dgq?file=/src/App.js

**Comment by bluebill1049** [comment] 2020-05-22 22:25
Thanks for the bug report. This will be fixed as part of V6 release.

**Comment by bluebill1049** [comment] 2020-05-22 23:59
I think I see the problem now, I am afraid this is a bug but not a bug with your use-case. lol.

I am still going to patch it anyhow.

The reason is that you are using schema, so the validation source of truth is there and your validation mode is `onChange`. so this is what's going to happen:

1. type some text
2. setError
3. isValid false
4. onChange mode kick in
5. validate against the schema
6. yes it's working isValid: true

so if you are using schema, it's better to leave your validation rule at the schema before it conflicts with setError during onChange mode with isValid.

**Closed** 2020-05-23 00:18 UTC
Labels: bug

**Comment by erickbelfy** [comment] 2020-05-23 11:10
This edge case happened because in some scenarios yup doens't have support for cyclic dependencies, meaning that in a scenario where one fields relies on the other field, Yup raises an error hence i am not able to validate the form properly, so that's why i had to use setError. I undersrtand that the validationSchema is the source of truth, i'd love to not use setError at alll, but in a scenario like this, is pratically impossible to not use.

look:
```
{   
          qna: yup.object().shape({
            answer: yup.string().when('question', {
              is: value => value !== '',
              then: yup.string().required(),
              otherwise: yup.string().notRequired(),
            }),
            question: yup.string().when('answer', {
              is: value => value !== '',
              then: yup.string().required(),
              otherwise: yup.string().notRequired(),
            }),
          })
}
```
this schema will raise an error with yup

**Comment by bluebill1049** [comment] 2020-05-23 11:13
For dependant inputs validation, I would use `triggerValidation` instead of `setError`.

**Comment by erickbelfy** [comment] 2020-05-23 11:18
I will take a look at `triggerValidation` api, thanks for the super fast response! <3

**Comment by erickbelfy** [comment] 2020-05-23 11:22
triggerValidation
> To manually trigger an input/select validation in the form.
> Note: When validation fails, the errors object will be updated.

in a given yup schema:

```
{   
          qna: yup.object().shape({
            answer: yup.string().when('question', {
              is: value => value !== '',
              then: yup.string().required(),
              otherwise: yup.string().notRequired(),
            }),
            question: yup.string(),
          })
}
```

i cant trigger a validation of a field that does't subscribe an error, correct? i had to put the question not required because yup, as far as i can tell, doest support cyclic dependencies, so i have to add that optional error myself, in a scenario where `question` is require *only* when `answer` has a value and vice versa

**Comment by erickbelfy** [comment] 2020-05-23 11:48
But you're right, i guess that can handle some edge cases using validationResolver instead of validationSchema, i will try to migrate it and see how it works

**Comment by bluebill1049** [comment] 2020-05-23 11:52
React Hook Form's `formstate` isValid is driven by schema against form `data` (when not using the build-in validation). So `setError` is not going to be the solution, and we can't make it work against validation schema result, because it will conflict the source of the truth.

Since schema validation `isValid` is going to drive by schema result (or kind has to), at the same time I see your concern as well when an error is not associated with the form. a situation like this I can't see any other workaround than calling `triggerValdiation()` to validate the entire form, or you will have to use `resolver` to write some custom logic.
