### ISSUE TITLE
Lagging field states in formState demo

### ISSUE THREAD

**Issue by dandv** [react-hook-form/react-hook-form#2002] opened 2020-07-01 06:45 UTC
**Describe the bug**
In the [formState codesandbox](https://codesandbox.io/s/7o2wrp86k6?file=/src/index.js), I've noticed that the field state displayed at the bottom of the form lags one click behind the user's actions.

Is this because that demo uses v5? The code also mentions to check the console for dirtyFields being a set.

**To Reproduce**
1. Go to https://codesandbox.io/s/7o2wrp86k6?file=/src/index.js
2. Click inside 'First name'
3. "Touched" should include "First name", but is empty.
3. Type "bill"
4. `dirtyFields` is empty, but should include "First name"

**Codesandbox link (Required)**
https://codesandbox.io/s/7o2wrp86k6?file=/src/index.js

**Additional information**
~~With v6, I noticed that `isDirty` doesn't become `false` after submitting the form. I expected it to become false, because all values have been committed, so the fields are no longer dirty.~~

**Comment by bluebill1049** [comment] 2020-07-01 07:00
I couldn't reproduce the problem you stated above, what steps am i missing?

`dirty` Set to true after a user interacted with any of the input, i think you are after `isSubmitted `.

**Comment by dandv** [comment] 2020-07-01 07:23
Sorry for talking about two different problems in one issue. I filed a separate Discussion for the isDirty issue, https://github.com/react-hook-form/react-hook-form/discussions/2004. This is only a bug report now.

> `dirty` Set to true after a user interacted with any of the input

I'm talking about v6, so `dirty` was replaced by `isDirty`. Also, as noted in [my recent PR](https://github.com/react-hook-form/documentation/pull/326), `isDirty` set to true after any input has been **modified**, not just interacted with - that's what I see by using the component, is that intended?

Anyway, here is a screencast reproducing the bug I've mentioned, by following exactly steps 1 through 5:

![dirtyFields stays empty](https://user-images.githubusercontent.com/33569/86214967-cbc91a00-bb30-11ea-91ea-2bd695542a1f.gif)

You can see that `dirtyFields` stays empty.

Anyway, that demo uses v5, so maybe these bugs have been solved in v6.

**Comment by bluebill1049** [comment] 2020-07-01 10:14
`dirtyFields` in V5 is a `Set`, you will need to check that in the console, fixed that in V6 tho. (to object)

**Comment by dandv** [comment] 2020-07-01 12:37
I can confirm that dirtyFields is an object in v6. What about the other issues?

**Comment by bluebill1049** [comment] 2020-07-01 12:41
You mean `touched`? it is triggered after onBlur.

**Comment by bluebill1049** [comment] 2020-07-02 23:19
going to close this issue, because it's expected behavior for `touch`.

**Closed by bluebill1049** 2020-07-02 23:19 UTC
Labels: question
