### ISSUE TITLE
watch() does not update when removing an array input

### ISSUE THREAD

**Issue by nfantagossi-asapp** [react-hook-form/react-hook-form#660] opened 2019-12-12 16:27 UTC
**Describe the bug**
When an array input leaves the dom, the watch method doesn't update. I looked in the issues to find if anyone had a similar issue, but the only one I've found somewhat related is https://github.com/react-hook-form/react-hook-form/issues/643 but his example didn't rely on removing any input.

**To Reproduce**
1. Go to
2. Create two inputs
3. Add some data to them
4. Remove one

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-watch-with-array-input-71cw8

**Expected behavior**
When the input is removed from the dom, the return value of the watch method should be updated to reflect that the input doesn't exist anymore.

**Comment by bluebill1049** [comment] 2019-12-13 02:14
hey @nfantagossi-asapp that's actually not a bug. because `watch()` only watch inputs changes, not when input removed. what's your use case like?

**Comment by nfantagossi-asapp** [comment] 2019-12-13 12:39
Hi @bluebill1049, thank you very much for the quick response.

I have a dynamic form generator that builds a form from a config object that's not known beforehand. For the generated form, I need to perform some validations (which are also dynamic) on the resulting value (the configuration adds validations to single inputs registering with the `register` method, but some validations are more complex and requires multiple input values in order to run).
I have a component which is listening to changes through `watch` and it uses the `getValues({ nested: true })` and run those validations against that result, and reports the error to the user.
Up until now it worked perfectly for that use case, but now I have a validation on array values that is not working properly due to not being called after a user removes a value.

I currently have a sort of a hack to solve this, where I register a custom input just to report a value change when an array element is removed, but I don't think that's the best approach.

Do you have any pointers or recommendations to solve this use case?

**Comment by bluebill1049** [comment] 2019-12-13 12:47
no worries @nfantagossi-asapp :) is there any way you can combine the validation with `state` (which control the size of the values). because `watch` holds the source of truth of each input value, and that local state holds the number of values on the screen. Let me know your thoughts.

**Comment by nfantagossi-asapp** [comment] 2019-12-13 12:54
@bluebill1049 I'm sorry, but with `state` you mean the `formState` object? And if it's that, you mean using the `touched` array?

**Comment by bluebill1049** [comment] 2019-12-13 12:55
I was referring to those states:
```
const [counter, setCounter] = useState(0);
 const [inputsIds, setInputsIds] = useState([]);
```

**Comment by nfantagossi-asapp** [comment] 2019-12-13 13:42
Oh right, the thing is that in my use case, those states belong to the component that renders an array input, which is far down the tree from the actual dynamic form.
I think that would imply doing something like passing down a callback just to report if there were any changes to an array input, which would end up coupling those components (the only coupling so far is just that each input type requires the form context, which seems fair enough)

But I'll go ahead and try to figure out something. I might be able to use the `touched` array to filter the values that are no longer in the dom.

Either way, I wonder, would there be any chance of using `watch` for all inputs and get "notified" of any input removals? I mean, besides my very specific use case, removing inputs from the DOM given some circumstances is a very common pattern I think.

**Comment by bluebill1049** [comment] 2019-12-13 23:28
> Either way, I wonder, would there be any chance of using `watch` for all inputs and get "notified" of any input removals? I mean, besides my very specific use case, removing inputs from the DOM given some circumstances is a very common pattern I think.

hey @nfantagossi-asapp I don't think it's `watch`'s job, render input is taking care via React `state` not input value.

1. watch : input value
2. local state: what to render on your screen.

**Comment by bluebill1049** [comment] 2019-12-13 23:37
my recommendation would be combining with the local state with watch result

**Comment by bluebill1049** [comment] 2019-12-16 10:00
i am going to close this issue for now, feel free to leave your questions and i will try to answer ASAP.

**Closed by bluebill1049** 2019-12-16 10:00 UTC
Labels: not valid

**Comment by nfantagossi-asapp** [comment] 2019-12-16 10:25
Alright, I will use local state to perform these custom validations.

Thank you for your help!

**Comment by bluebill1049** [comment] 2019-12-16 10:31
thanks for understanding @nfantagossi-asapp my pleasure to help

**Comment by bluebill1049** [comment] 2019-12-16 10:32
if you find the lib to be useful in the future, plz consider to leave us a star to support too ❤️

**Comment by vgribdev** [comment] 2020-05-31 12:58
Hi thanks for you awesome library, is there a way to get the correct data at least onSubmit?

**Comment by bluebill1049** [comment] 2020-05-31 13:03
> Hi thanks for you awesome library, is there a way to get the correct data at least on submit?

What do you mean? I need more context and perhaps a codesandbox?

**Comment by vgribdev** [comment] 2020-05-31 14:23
[CodeSandbox](https://codesandbox.io/s/infallible-hill-8cw17?file=/src/App.tsx)
Steps to reproduce: 

1. Add two inputs.
2. write something in input1 and something else in input 2.
3. remove input 1
4. submit

You should see that the content of input 2 is duplicated
changing ref={register({ maxLength: 50 })} with ref={register} seems to fix the problem

**Comment by bluebill1049** [comment] 2020-05-31 22:55
> [CodeSandbox](https://codesandbox.io/s/infallible-hill-8cw17?file=/src/App.tsx)
> Steps to reproduce:
> 
> 1. Add two inputs.
> 2. write something in input1 and something else in input 2.
> 3. remove input 1
> 4. submit
> 
> You should see that the content of input 2 is duplicated
> changing ref={register({ maxLength: 50 })} with ref={register} seems to fix the problem

please take  look at `useFieldArray`

**Comment by vgribdev** [comment] 2020-05-31 23:19
it works fine with useFieldArray thanks.
