### ISSUE TITLE
V7 Bug - useFieldArray's append removing previous values and not inserting correctly

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4314] opened 2021-03-01 07:22 UTC
**Describe the bug**
If a component is conditionally rendered and `append` is called in the conditionally rendered component, then append's behavior will be incorrect. The two issues I am noticing right now are: 

1. Default values of the field array will be removed from form values. 
2. Only inputs that are mounted will have their values added to the new array element.

**To Reproduce**

1. Go to the code sandbox
2. Click on the show element button
3. Click the add button 
4. Notice that the output of the watch shows the first element of the field array as `undefined` (was a default value) and the newly added element is missing the "somethingElse" value that was part of the `append` argument. 

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-pzz1b?file=/src/index.js:502-515

**Expected behavior**
I would expend that regardless of where append was it called it would:

1. Not remove form values
2. Add all values regardless of whether they are currently mounted (as this is the new design we are using)

**Comment by bluebill1049** [comment] 2021-03-01 07:29
Thanks for the issue report @wdfinch 

That's because `defaultValues: { names: [{ name: "will" }] }` was not registered, I don't think we should divide into too deep with "invisible" field array, hook form was meant to grab what's in the view, I think we are already stretching the limited on what hook form was originally designed for. I don't think we should start going work on the register `defaultValues`. 

so i think it would be safer to at least register those input with custom register with Controller

**Comment by wdfinch** [comment] 2021-03-01 07:55
Hmm, I see. I guess the issue here is what do you do if you have a large conditionally rendered form (wizard form) that's represented as a field array?

In my case, I have a very large wizard form that is represented as one element in a field array. I can only show one element at a time and I can only show a slice of the element (small group of input). There's no way I could use display none to have every element registered on the screen for multiple reasons. Therefore how could I use this UI and ensure my form values are correct? 

I totally understand wanting to keep things simple, but I personally think the library would be much more flexible and intuitive if we could freely modify form values without having to worry about what's rendered/registered on the screen at that time. If there was a way to bulk register with input hidden (like register a whole field array element), that could work too, but I'd rather just have `formValues` work more like a js object that I can modify how I wish.

Do you have any advice on a workaround? I guess with larger forms which are common in enterprise applications, I don't see a way I can't keep every input registered unless I use some hacky approach like quickly mounting everything at the beginning.

**Comment by wdfinch** [comment] 2021-03-01 07:59
I guess the only other thing I can think of is to keep my own copy of unregistered values that I merge with form values to get the actual values but I would rather not do this if I don't have to.

**Comment by wdfinch** [comment] 2021-03-01 08:08
If you want to make sure everything is registered in the view layer, would you be open to an easier way to register inputs maybe by using a `useForm` method and not having to have an input rendered on the screen?

**Comment by bluebill1049** [comment] 2021-03-01 08:23
maybe this example helps? https://codesandbox.io/s/usefieldarray-virtual-input-v9wyw

**Comment by wdfinch** [comment] 2021-03-01 17:55
I see. So this is kinda like using display none. In your case, though you render the controller but hide the input based on some conditions. While this does work in some cases, here are my issues: 

1. In my case, I display the array elements as a text-based list, and then the user clicks on the one they would like to edit by opening a wizard form. I'm still not sure how I could prevent the default values from being dropped if the user decides to edit array element 2 and element 1's inputs were never registered.

2. When my wizard views (groups on inputs) mount, I often have side effects that run as well. If all of these run at the same time (because we are using display none), this can lead to issues and would make things much harder to debug/understand. It also leads to a performance hit because I need to run more logic upfront and render more dom nodes.

I understand wanting to keep arbitrary data out of form values (our metadata discussion). I guess I see two scenarios regarding this:

1. We have metadata.
2. We have form values that haven't been registered yet.

For 1 the solution is to use input hidden and this works fine. For 2 this is where we have issues. I have inputs that all have related controllers that may or may not be registered at some point and I don't want to drop the current default values. Here are some ideas on how I think this could be improved: 

1. `append` currently takes an argument of values. To me, it makes more sense to treat these as default values rather than form values. It also aligns with your goal of keeping arbitrary data out of form values. If append received default values, we could then do a shallow merge with the current default values. This would still meet all your design goals regarding registered inputs and solve my issue of having default values removed and not added. 

2. We have some way to register an input from a helper method rather than having to mount a react component. In my mind, this would kinda be like the `declare` keyword in typescript. We are telling the library, trust us this does have an input it just hasn't been mounted yet. 

I personally think someone like 1 is best and easiest to implement.

If none of this works for you, my workaround will be to keep my own copy of default values. When I run append, prepend, etc. I will update my own copy by merging in the new default values and essentially won't trust the default values provided by `formValues` anymore for the field array. 

This isn't too bad, but I would really prefer it if I could just let the library handle all this. Let me know what you think.

**Comment by bluebill1049** [comment] 2021-03-01 22:29
> append currently takes an argument of values. To me, it makes more sense to treat these as default values rather than form values. It also aligns with your goal of keeping arbitrary data out of form values. If append received default values, we could then do a shallow merge with the current default values. This would still meet all your design goals regarding registered inputs and solve my issue of having default values removed and not added.

I don't mind this solution, however, this creates another problem with `watch` and `useWatch` after append action, which i need to investigate. I will keep you posted.

**Comment by wdfinch** [comment] 2021-03-01 22:34
Ok thanks. You might also need to look at `remove`, `prepend`, etc as they also accept values. I guess all the operations would just need to adjust default values correctly in a shallow way. 

1. add operations => add default values
2. remove operations => remove default values

**Comment by bluebill1049** [comment] 2021-03-02 01:16
After careful consideration, I think I will keep what we have right now, which is only keep two pieces of state:

- `defaultValues` which populate the FieldArray.
- `formValues` which is what's been registered.

let me explain why update `defaultValues` is not going to work out, it works for your reported use case, but it breaks watch/usewatch. 

```
watch(); // will need to return updated value, not the default value, it's going to create a mess if we start to merge default value with action value.

append({ test: 'test' })
```

The previous issue that you reported was spotted one, as I had to maintain another extra state for `append`, `prepend` and `insert` for users who is watch the field Array, by `register` the input during each action, it removes that extra state, which I am pretty happy with it, the registration works for field array, because by nature each useFieldArray is flat, so register works at each action works out. certainly, I wouldn't want to go back to maintain another extra piece of state for those actions, which is good that you discover and found it out.

conclusion, I think we will keep what we have right now, as it would cover 90% of use cases. I hope you understand where I am trying to achieve and the concerns above.

**Comment by wdfinch** [comment] 2021-03-02 01:30
I understand. I guess do you have any advice for me then on what I could do? Essentially I can only show one field array at a time and from that only a slice of the inputs. I can't really mount every input on the screen. What are you're thought on option 2 above? So in other words some way I could bulk register my inputs without having to mount a bunch of components. What do you think about that?

**Comment by bluebill1049** [comment] 2021-03-02 01:36
> So in other words some way I could bulk register my inputs without having to mount a bunch of components.

I think a utility function to call `register` would work? you probably need to write some recursive logic to cater for deeply nested object, but should be achievable. happy to assist if that's the actual problem.

**Comment by wdfinch** [comment] 2021-03-02 01:41
> will need to return updated value, not the default value, it's going to create a mess if we start to merge default value with action value.

Doesn't `watch` already return the default values? I'm not really sure why we need an extra state. I see the logic as follows:

1. Call append
2. Modify the default values
3. Call watch
4. Return `formValues` with the shallow merge of default values

Doing the merge should be as simple as just calling a helper function. In regards to knowing when a change has occurred, we know that default values would only be changed from a finite set of operations (append, remove, etc.). Couldn't we just trigger watch after that? Not trying to argue, I'm just curious why this is difficult.

**Comment by wdfinch** [comment] 2021-03-02 01:47
That could work. Right now register only works as a prop to a component I believe. I'm used to using `<Controller/>` so I don't have as much experience with it. I guess if I could pass an array of field names to some method that could bulk register them all without having to mount them, then it could solve my problem. Otherwise, I will need to just keep my own backup of default values.

**Comment by wdfinch** [comment] 2021-03-02 01:52
> happy to assist if that's the actual problem.

The problem is default values are being removed/not added because I can't register the related input immediately. At least I think that's the issue. The only ways I see to solve it are:

1. Be able to modify default values and stop them from being removed
2. Be able to register inputs in advance without having to mount them all upfront
3. Maintain my own copy of default values that represents values for inputs that haven't been registered

I guess we are looking at 2 now unless you have any other ideas here. 3 will work but I really don't want to do this lol.

**Comment by bluebill1049** [comment] 2021-03-02 02:03
> > will need to return updated value, not the default value, it's going to create a mess if we start to merge default value with action value.
> 
> Doesn't `watch` already return the default values? I'm not really sure why we need an extra state. I see the logic as follows:
> 
> 1. Call append
> 2. Modify the default values
> 3. Call watch
> 4. Return `formValues` with the shallow merge of default values
> 
> Doing the merge should be as simple as just calling a helper function. In regards to knowing when a change has occurred, we know that default values would only be changed from a finite set of operations (append, remove, etc.). Couldn't we just trigger watch after that? Not trying to argue, I'm just curious why this is difficult.


Yes watch will return default value, but after append, it will be one render behind.

```
watch() // one render behind, if registered input value is not updated.

append({ test: 'test' })
```

**Comment by bluebill1049** [comment] 2021-03-02 02:06
> Be able to register inputs in advance without having to mount them all upfront

yes, custom register at `useEffect` is the preferred option

**Comment by wdfinch** [comment] 2021-03-02 02:30
Ok, so with the custom register approach do all the tools exist right now to do this? Is there any way you could post a quick sandbox with an example? I'm not really sure how to do it.

**Comment by wdfinch** [comment] 2021-03-02 02:38
A code snippet would work also. Don't want to take up your time.

**Comment by bluebill1049** [comment] 2021-03-02 03:03
```
React.useEffect(() => {
  register('xxx');

 // or you can write a function to loop through what are the fields that you want to regsiter
}, [register])]
```

above is what i meant to register inputs at `useEffect`.

**Comment by wdfinch** [comment] 2021-03-02 03:13
Ok thanks. Let me try this out and I'll let you know how it goes. Appreciate your help with this.

**Comment by wdfinch** [comment] 2021-03-02 05:11
Ok, so this was able to solve the issue of field array elements being removed. However, I'm not sure how to solve the issue of field array elements not being added. The issue is I cannot register the new field array element inputs until append is called. Once append has been called, the `formValues` passed to append are already removed. I've attached a modified sandbox. As you can see I register the current field array form values on mount, but how could I stop the append function from removing the values pass to it?

https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-pzz1b?file=/src/index.js

Solving the issue of field array element being removed is definitely the bigger issue here so that's good. If the above isn't possible then I can always just keep an object around of the default values and use that as the `defaultValue` prop.

**Comment by bluebill1049** [comment] 2021-03-02 06:56
@wdfinch can you share some more detail on the issue above? thanks for preparing a csb.

**Comment by wdfinch** [comment] 2021-03-02 07:02
Sure so essentially append is run and a new field element is added. I would like to register all the inputs associated with this newly added field element in order to preserve the values passed into append. 

The issue is that as soon as append run and adds the values, they don't appear in the next render cycle. In other words, they are immediately removed because there are no registered inputs yet for them to attached to.

An easy workaround is just to keep a separate copy of the new default values for the field array element somewhere else and use this when input registers (via the default value prop). However, it would be nice if the values used in append did appear. This does kinda break the design goal of not modifying default values + not adding arbitrary values so I get if you don't want to change it. As long as we are not removing field array elements that haven't been mounted, I can work around this issue.

**Comment by bluebill1049** [comment] 2021-03-02 07:09
> Sure so essentially append is run and a new field element is added. I would like to register all the inputs associated with this newly added field element in order to preserve the values passed into append. 

how to reproduce that in your CSB?

> The issue is that as soon as append run and adds the values, they don't appear in the next render cycle. In other words, they are immediately removed because there are no registered inputs yet for them to attached to.

that sounds like a bug, if so i am happy to fix that.

**Comment by wdfinch** [comment] 2021-03-02 07:19
1. So simply click show element. You'll notice that the first field array element which is a default value and has not been registered stays around which is good (because I registered it). However, if you take a look at the second newly added element in the field array, you'll notice that the object is `{name: "will"}`. I would like it to be {name: "will", dog: "spike"} as this is what I just appended.

2. I think this is inline with your design as you aren't modifying default values and you don't want to add `formValues` that aren't associated with a registered input. Let me know what you think.

**Comment by bluebill1049** [comment] 2021-03-02 07:32
> So simply click show element. You'll notice that the first field array element which is a default value and has not been registered stays around which is good (because I registered it). However, if you take a look at the second newly added element in the field array, you'll notice that the object is {name: "will"}. I would like it to be {name: "will", dog: "spike"} as this is what I just appended.

i see, you mean `dog` is missing right? let me take a look at it.

**Comment by bluebill1049** [comment] 2021-03-02 07:36
That's a valid bug... my bad.

**Comment by bluebill1049** [comment] 2021-03-02 07:36
closing this one and opened the other.

**Closed by bluebill1049** 2021-03-02 07:36 UTC
Labels: V7, wont be worked on
