### ISSUE TITLE
Controller requires it's props for custom components

### ISSUE THREAD

**Issue by stramel** [react-hook-form/react-hook-form#1580] opened 2020-05-06 17:53 UTC
**Describe the bug**
When using `Controller` with a custom input component, causes the `Controller` to require the `value` and `onChange` props to be required.

**To Reproduce**
1. Open codesandbox
2. Observe the type errors

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-template-qrtco

**Expected behavior**
I would expect the typings to be smart enough to know if I have already passed the values or to know that the properties are injected.

**Additional context**
Also appears to be an issue with `<input name="test" />`

**Comment by stramel** [comment] 2020-05-06 18:14
I think it would be best to only allow the element version for the `as` prop. This is the easiest way to allow passing of props to the component without having to do hard/weird typescript tricks to make passing the props through work correctly. `react-router` v6 took this approach due the same reason. 

Also, I think we can use an "injector" typing approach to make it easier to develop components that work well with `Controller`. To do this, we can export an interface developers can consume in their components. This lowers the bar to know what components are being setup for them. ie:

```tsx
export interface InjectedControllerProps {
	// Props here
}
```

**Comment by bluebill1049** [comment] 2020-05-06 23:39
@stramel would be able to send a PR around this?

**Comment by bluebill1049** [comment] 2020-05-06 23:40
or perhaps make this fix on V6 branch since @kotarella1110 had made a huge improvement on types.

**Comment by stramel** [comment] 2020-05-07 03:48
Yeah towards the end of this month I can take a look at fixing this. Currently, unable to based on my workload. I think it would be a good v6 fix

**Comment by JReinhold** [comment] 2020-05-12 08:32
> I think it would be best to only allow the element version for the `as` prop. 

Would this mean that passing a function to the `as` prop would no longer work? Something like

```tsx
  <Controller
    control={control}
    as={(controllerProps) => (
      <MyInputComponent
        {...props}
        myNestedProps={{
          value: controllerProps.value ?? [],
          onChange: ({ values }) => controllerProps.onChange(values),
        }}
      />
    )}
    name={name}
  />
```

I think that would be a shame. But maybe what you are saying, is that `as="stringElement"` would no longer work?

**Comment by bluebill1049** [comment] 2020-05-12 08:40
@JReinhold we haven't made any decision or progress on this yet. will keep you posted. DX is super important for this lib, we wouldn't want to sacrifice it.

**Comment by bluebill1049** [comment] 2020-05-23 01:51
I think we had a discussion with @kotarella1110, we will leave as it is due to DX with usage for autocompletion.

we still want to support 

```
<Controller as="input" />
<Controller as={Text} />
```

@kotarella1110 feel free to add your concerns or reasons as well, thanks.

**Comment by stramel** [comment] 2020-05-23 04:18
But that's the issue is the DX isn't good the way it currently stands.

**Comment by bluebill1049** [comment] 2020-05-26 01:13
I think the problem is around typed props like `value` and `onChange` will required users to declare them again which is not greater DX.

**Comment by kotarella1110** [comment] 2020-05-27 03:17
@stramel Can you create this PR? I think we can discuss it after figuring out how this will be fixed.

**Comment by bluebill1049** [comment] 2020-05-27 03:58
> I think it would be best to only allow the element version for the `as` prop. This is the easiest way to allow passing of props to the component without having to do hard/weird typescript tricks to make passing the props through work correctly. `react-router` v6 took this approach due the same reason.

Can you share some examples?

**Comment by bluebill1049** [comment] 2020-05-27 04:07
here is the reference https://github.com/ReactTraining/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md#advantages-of-route-element

FYI @kotarella1110

**Comment by stramel** [comment] 2020-05-27 04:52
I will try to add more information tomorrow after my release.

**Comment by kotarella1110** [comment] 2020-05-27 09:15
@bluebill1049 @stramel I like render props.
`as`/`onChange`/`onBlur`/`onChangeName`/`onBlurName`/`valueName` props are unnecessary and more simple.
I tried to implement this.

```ts
export type ControllerProps<TControl extends Control = Control> = {
  name: FieldName<FieldValuesFromControl<TControl>>;
  rules?: ValidationOptions;
  onFocus?: () => void;
  defaultValue?: unknown;
  control?: TControl;
  children: (data: {
    handleChange: EventFunction;
    handleBlur: EventFunction;
    value: any;
  }) => React.ReactElement;
};
```

```ts
<Controller
  name="textfield"
  onFocus={() => inputRef?.current?.focus()}
  control={control}
  rules={{ required: true }}
>
  {({ handleChange, handleBlur, value }) => {
    console.log(value);
    return <TextField inputRef={inputRef} onChange={handleChange} onBlur={handleBlur} />;
  }}
</Controller>
```

[CodeSandbox](https://codesandbox.io/s/react-hook-form-issue-1580-59soi)

 What do you think?

**Comment by bluebill1049** [comment] 2020-05-27 09:30
I quite like this, this make API a lot simpler as well...

**Comment by bluebill1049** [comment] 2020-05-27 09:31
a counterexample:

```
<Controller as={<TextField />} name="test" control={control} />
```

completely skip the render props.

**Comment by bluebill1049** [comment] 2020-05-27 10:34
hmmm...
`<Controller name="test" control={control} render={(props) => <TextFields {..props} />} />`
vs
`<Controller name="test" control={control} as={<TextFields />} />`

**Comment by bluebill1049** [comment] 2020-05-27 10:47
Take a look at my PR @kotarella1110 @stramel let me know what do you think?

**Comment by stramel** [comment] 2020-05-27 22:48
So Bill posted the link I shared with him using the example of `react-router` v6 and their reasoning behind switching to an element based api instead of component.

I think we can offer a single prop `as`/`render`/`element` to handle the use-cases. Offering multiple props will just cause confusion.

For that single prop, we should be able to support render props or an element.

```
// Supported
<Controller name="test" control={control} render={<TextFields myUniqueProp={state} />} />
<Controller name="test" control={control} render={({onChange, onBlur, ...props}) => <TextFields handleChange={onChange} handleBlur={onBlur} {..props} />} />

// Not Supported
<Controller name="test" control={control} render={TextFields} /> // -> <Controller name="test" control={control} render={<TextFields />} />
<Controller name="test" control={control} render='input' /> // -> <Controller name="test" control={control} render={<input />} />
```

We then don't have to worry about passing props through (ie. `myUniqueProp`) or handling conversion of their prop names (ie. `onBlurKey`). 

The main issue that I see with this currently is instantiating the component without the `value` and `onChange` props. Unless we required the render prop pass through. `(props) => <TextFields {...props} />` or we might be able to do some typescript magic with an interface as I alluded to earlier.

**Comment by bluebill1049** [comment] 2020-05-27 22:55
I like the suggestion above, so we don't lose the flexibility.

**Closed** 2020-06-01 01:36 UTC
Labels: TS, bug, status: working in progress
