### ISSUE TITLE
watch vs. useWatch array length inconsistency when using useFieldArray

### ISSUE THREAD

**Issue by dwiyatci** [react-hook-form/react-hook-form#3329] opened 2020-11-02 22:24 UTC
**Describe the bug**
Not sure if this is a bug/can be improved but... when using `useFieldArray` to insert/remove item to the fields, the resulting output (array) of that `useWatch` doesn't have a consistent length with the array length of updated fields after the insertion/removal.

**To Reproduce**

1. Go to the CSB link, clear the console after render. 
2. Click on "insert" or "remove".
3. See the console. Check the length of the `fields` vs. the length of the `useWatchedItems` on the first render loop.

**Codesandbox link (Required)**
https://codesandbox.io/s/watch-vs-usewatch-field-array-length-inconsistency-bi8it?file=/src/App.jsx:1365-1650

**Expected behavior**
The length of the `fields` and the length of the `useWatchedItems` should be the same on each render cycle.

**Additional context**
When `watch` is used instead of `useWatch` though, the watched array length seems to be consistent with the `fields` array length on each render. 👍

**Comment by dwiyatci** [comment] 2020-11-07 18:38
I'm sorry @bluebill1049, apparently this issue is still reproducible in `v6.11.0`. 🤕

**Comment by bluebill1049** [comment] 2020-11-07 23:10
> I'm sorry @bluebill1049, apparently this issue is still reproducible in `v6.11.0`. 🤕

you may have a cached version: 

<img width="561" alt="Screen Shot 2020-11-08 at 10 10 38 am" src="https://user-images.githubusercontent.com/10513364/98453199-a87f3d00-21aa-11eb-8fb8-43a99d56ba9b.png">

**Comment by dwiyatci** [comment] 2020-11-08 09:37
> > I'm sorry @bluebill1049, apparently this issue is still reproducible in `v6.11.0`. 🤕
> 
> you may have a cached version:
> 
> <img alt="Screen Shot 2020-11-08 at 10 10 38 am" width="561" src="https://user-images.githubusercontent.com/10513364/98453199-a87f3d00-21aa-11eb-8fb8-43a99d56ba9b.png">

Hmm strange... I tried it in a private window and also in my project, still the same results. Even in your screenshot above, you still get `{ index: 0, fields: Array(2), useWatchedItems: Array(3) }`, `{ index: 1, fields: Array(2), useWatchedItems: Array(3) }`, ... 

(**Array(2)** vs. **Array(3)**)

Could it be that I missed something? 🤔

**Comment by bluebill1049** [comment] 2020-11-08 09:57
The last render is correct because we trigger watch updated at useFieldArray's `useEffect`. let me take a look at it, see if we can improve before the `useEffect`.

**Comment by dwiyatci** [comment] 2020-11-08 11:12
So I take it this is just how it works/cannot be improved then, yeah? 'cause when I use `watch` instead of `useWatch`, it's consistent across all renders (not only the last render)...

**Comment by bluebill1049** [comment] 2020-11-08 21:50
because `watch` gets called even before the child component.
order below:

1. fields (re-render)
2. `watch`
3. `useWatch`

**Comment by bluebill1049** [comment] 2020-11-08 21:58
I wouldn't say it can't be improved, but i did try last night and it's not working out...

**Comment by bluebill1049** [comment] 2020-11-08 23:50
Previously its a bug because it didn't return the correct wath value, i will do some investigation with inconsistent watch value. I know the root cause, because useWatch need to trigger another setState to update the value, but worth to do some investigation, if not working then will close this issue.

**Closed** 2020-11-09 08:44 UTC
Labels: enhancement

**Comment by dwiyatci** [comment] 2020-11-09 15:33
Ohh, didn't expect that you'd go the extra mile for this. Was actually already quite satisfied with some workaround, like:

```javascript
const items = useWatch({
    name: 'items',
    defaultValue: fieldArrayItems,
    control,
  });

cons itemsLength = fieldArrayItems.length;
// ...some much more logic that depends on `itemsLength`
```

But it's a great feeling to expect that I'm gonna be able to do this:
```javascript
const items = useWatch({
    name: 'items',
    defaultValue: fieldArrayItems,
    control,
  });

cons itemsLength = items.length;
// ...some much more logic that depends on `itemsLength`
```

Your effort is most appreciated, Bill – as always – thank you soo muucch! :)

**Comment by dwiyatci** [comment] 2021-04-18 09:26
@bluebill1049 This issue seems to be coming in v7. Not a show-stopper though, 'cause I can still drop back to my workaround above. Just wanted to mention it :)

**Comment by bluebill1049** [comment] 2021-04-18 09:47
> @bluebill1049 This issue seems to be coming back in v7. Not a show-stopper though, 'cause I can still drop back to my workaround above. Just wanted to mention it :)

Thanks, @dwiyatci pretty sure what we got for v7 is the expected result. Can you provide some more details?

**Comment by dwiyatci** [comment] 2021-04-18 09:58
Here you go:
https://codesandbox.io/s/watch-vs-usewatch-field-array-length-inconsistency-forked-049vf?file=/src/App.jsx

Just try to insert an item, and observe the length inconsistency of `fields` vs. `useWatchedItems` arrays.

(**Array(3)** vs. **Array(4)**)

**Comment by bluebill1049** [comment] 2021-04-18 10:28
Thanks, ok this is a trade-off we have to live within v7, v7's useWatch is much lighter and faster than v6, we are using subscribe underneath and also we don't invoke getValues on each invocation rather cached value with `useState`, so the order of execution will be flush field array and then trigger useWatch's subscribe before its value gets updated.

1. watch read
2. update (remove)
3. update field array
4. watch return value from useState
5. field array mounted trigger subscribeion 
6. useWatch update with latest value.

**Comment by dwiyatci** [comment] 2021-04-18 11:14
Ah ok, thanks. So you're saying this is expected, right? :)

**Comment by bluebill1049** [comment] 2021-04-18 11:17
> Ah ok, thanks. So you're saying this is expected, right? :)

Yes, the last re-render will bring the updated field values.
