### ISSUE TITLE
TypeError: data.filter is not a function

### ISSUE THREAD

**Issue by nhuzaa** [react-hook-form/react-hook-form#1179] opened 2020-03-09 18:07 UTC
**Describe the bug**
Getting folllowing error message on removal of item in fieldarray 

**Expected behavior**
- Removal of item

**Screenshots**
![image](https://user-images.githubusercontent.com/3519383/76243204-12cc9000-6260-11ea-9524-260781d34b16.png)

**Desktop):**
 - Mac
 - Chrome

**Comment by bluebill1049** [comment] 2020-03-09 20:20
please provide a CSB.

**Comment by tkfnetwork** [comment] 2020-03-10 10:47
I have also come across this issue using `useFieldArray`

The issue comes from `getFieldValueByName(fieldsRef.current, name)` returning the entire values object if it can't find the array for the field.  This object is then passed in to removeArrayAt(theObjectValues, index)` and of course that function is expectig the array of values:

```js
var removeArrayAt = (data, index) => isUndefined(index)
    ? []
    : data.filter((_, i) => (isArray(index) ? index : [index]).indexOf(i) < 0);
```

Firstly there should be a guard in that function to make sure data is an array:

```js
var removeArrayAt = (data, index) => !isArray(data) || isUndefined(index)
    ? []
    : data.filter((_, i) => (isArray(index) ? index : [index]).indexOf(i) < 0);
```

It looks like the root of the issue is in `resetFields`:

```js
const resetFields = (flagOrFields) => {
  if (readFormStateRef.current.dirty) {
    isDirtyRef.current = isUndefined(flagOrFields)     
      ? true
       : getIsFieldsDifferent(flagOrFields, memoizedDefaultValues.current);
    }

  console.log('fieldsRef.current', fieldsRef.current) // { 'myField[0]': 'value-1', 'myField[1]': 'value-2' }

  for (const key in fieldsRef.current) {
    if (isMatchFieldArrayName(key, name) && fieldsRef.current[key]) {
       removeFieldEventListener(fieldsRef.current[key], true);
    }
  }
     
  console.log('after fieldsRef.current', fieldsRef.current) // { }
};
```

From my experiementation, it is completely removing all items in the `fieldsRef.current` for `myField` and not rebuilding them which mean next pass there are no values.

**Comment by bluebill1049** [comment] 2020-03-10 10:52
do you have a codesandbox and with steps to help me reproduce and debug?

**Comment by nhuzaa** [comment] 2020-03-10 18:28
@bluebill1049  
here is the Codesandbox
Please try to delete and item
https://codesandbox.io/s/react-hook-form-nested-fields-2rbfz?fontsize=14&hidenavigation=1&theme=dark

**Comment by bluebill1049** [comment] 2020-03-10 21:06
Thanks for the CSB @nhuzaa the example is quite complex, also i think you are not using it correctly. useFieldArray doesn't support custom register (which i have an issue to update on the website) can you follow the example and see if you reproduce without custom register?

**Comment by bluebill1049** [comment] 2020-03-11 10:25
i think this issue is related to this one: https://github.com/react-hook-form/react-hook-form/issues/1190 closing this one, let's continue on the other ticket.

**Comment by bluebill1049** [comment] 2020-03-11 10:26
FYI: but custom register still won't work with useFieldArray

**Closed by bluebill1049** 2020-03-11 10:25 UTC
Labels: question

**Comment by vi519** [comment] 2021-09-20 08:41
the error occurring because you passing object into filter function , and filter works only on array
