### ISSUE TITLE
issue: No error object and Browser Validation with FormContext

### ISSUE THREAD

**Issue by TylerAPfledderer** [react-hook-form/react-hook-form#7969] opened 2022-03-04 22:43 UTC
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/ecstatic-robinson-6zd7qj

### Steps to reproduce

1. Leave fields empty
2. Hit the "Submit" button to trigger validation errors

### Expected behaviour

No form validation coming from the browser and error messages appearing in the `FormErrorMessage` component of the invalid form pair.

Is there a step I am missing to ensure that errors are passed to the FormContext?

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment] 2022-03-04 22:46
please send an isolated codesandbox for the issue, I simply don't have enough time to go through a project-based codesandbox.

**Comment by bluebill1049** [comment] 2022-03-04 22:46
s

**Comment by bluebill1049** [comment] 2022-03-04 22:46
sorry closed by misclick...

**Comment by bluebill1049** [comment] 2022-03-04 22:50
![Screen Shot 2022-03-05 at 9 49 02 am](https://user-images.githubusercontent.com/10513364/156852481-c1c4b44f-5587-4cda-a807-93b37c10b3db.png)

> formState is wrapped with a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to improve render performance and skip extra logic if specific state is not subscribed to. Therefore make sure you invoke or read it before a render in order to enable the state update.

did a quick scan at your code, i think you are missing this part above https://react-hook-form.com/api/useform/formstate

looking for the rules section, hope that's the root cause otherwise please send a small and isolated CSB.

**Comment by TylerAPfledderer** [comment] 2022-03-04 23:21
Hey @bluebill1049!

Simply invoking via `console.log` per suggested in the docs didn't do anything.

I simplified the CSB as much as possible and removed some TypeScript without throwing errors.

https://codesandbox.io/s/ecstatic-robinson-6zd7qj

**Comment by bluebill1049** [comment] 2022-03-04 23:45
Thanks @TylerAPfledderer that helps.

The following is all you need:

`<VStack noValidate as="form" spacing={4} onSubmit={methods.handleSubmit(onSubmit)}>`

**Comment by TylerAPfledderer** [comment] 2022-03-04 23:56
Oh, thank you! That worked!

I thought the package by default prevented native validation? Is there documentation I am missing that discusses this?

**Comment by bluebill1049** [comment] 2022-03-05 00:10
Is there documentation I am missing that discusses this?

This just defaults browser-level behavior, I don't think it's belongs to react hook form for documentation.

**Closed** 2022-03-05 00:53 UTC
Labels: status: need more detail
