### ISSUE TITLE
Controller always uses default value even if form has existing data for that field

### ISSUE THREAD

**Issue by joe4mg** [react-hook-form/react-hook-form#970] opened 2020-02-04 15:35 UTC
Apologies if this is intended behaviour - I'm keen to hear your thoughts on this one.

I have a dynamic form with fields generated by an API - some fields share the same name. When I replace these fields they revert to their default value.

For my situation it would be preferable if the value persists. Presumably when a Controller unmounts it unregisters and clears the key/value in the form context - I can understand this behaviour but perhaps this clean up should be toggled with a flag or something?

https://codesandbox.io/s/react-hook-form-controller-rhnpq
To re create in codesandbox above:
1. Type some value into the box, click submit to confirm it has added to the form state
2. Click the 'Toggle controller component' button to switch to a different component with a Controller using the same `name`.
3. The previous value is lost and the input displays the default value.

**Comment by bluebill1049** [comment] 2020-02-04 20:38
That's intended behavior if you don't want that sort of behavior maybe consider to use inline `defaultValue` instead.

**Comment by joe4mg** [comment] 2020-02-04 20:48
Thanks for the quick response! Ok I should be able to use the inline `defaultValue`.

One issue i've spotted is if I add a defaultValue on the Controller and the form also has defaults then in the form default will over write but the docs suggest the inline `defaultValue` prop should take precedence/overwrite. 

I've forked my codepen link to demonstrate this https://codesandbox.io/s/react-hook-form-controller-rvw0t

**Comment by bluebill1049** [comment] 2020-02-04 20:50
thanks i will update the doc or if you have time feel free to spend a PR to adjust the doc

**Comment by bluebill1049** [comment] 2020-02-04 20:58
nvm it's correct logic..

**Comment by bluebill1049** [comment] 2020-02-04 20:59
```
const [value, setInputStateValue] = React.useState(
    isUndefined(defaultValue)
      ? get(defaultValuesRef.current, name)
      : defaultValue,
  );
```
inside the controller.

**Comment by bluebill1049** [comment] 2020-02-04 21:10
Ok let me explain the reason why defaultValues over take defaultValue, which i will update the do :)

1. defaultValue get assigned to Controller (useState)
2. register happen after Controller render
3. register check defaultValues exist, if so use it inject the value, (note: it's difficult to track defaultVaue for components or native input) hence why

that's the reason why defaultValues take over

**Comment by joe4mg** [comment] 2020-02-04 21:17
Many thanks for looking in to this (and all your work on this project!). I think I will pass a custom 'defaults' object down to the child component with the `Controller` and apply inline.

If you're open to suggestions it would be great if there was a prop to enable a 'persist value' option on a `Controller` so removing and then re-adding would pick up the previous value rather than default.

**Comment by bluebill1049** [comment] 2020-02-04 21:52
Noted, for now I will leave as it is

**Closed by bluebill1049** 2020-02-04 21:52 UTC
Labels: question

**Comment by getellez** [comment] 2021-10-22 02:23
Nice thread. If I have nested input (using useFieldArray) that doesn't exist in the first render of the form yet and the form does not have a default value for that input (because is nested like 3-level of depth) but it does have a default value inline. When the input is mounted should the inline default value be applied? or should I specify that default value in the default values of the form?
