### ISSUE TITLE
formState not updated on first submit

### ISSUE THREAD

**Issue by JakariaAmin** [react-hook-form/react-hook-form#866] opened 2020-01-20 05:16 UTC
I am trying to use it in React Native App, latest version of react native and react-hook-form installed.
Registered my form inputs following the documents.

React.useEffect(() => {
    register({ name: 'firstName'}, { required: true });
    register({ name: 'lastName'});
  }, [register])

Only problem is the formState is not updated on first form submit. From the 2nd submit and onward it updates fine.

onPress={handleSubmit(onSubmit)}

const onSubmit = data => { console.log(formState) }

It prints isSubmitted = false, submitCount = 0, isValid always false on first submit, even if the form is valid. 

seems like a bug.

Please help.

**Comment by bluebill1049** [comment] 2020-01-20 05:49
can you try to create expo snack, so we can reproduce the issue?

**Comment by mylnikovD** [comment] 2020-01-20 09:30
Hi guys, I'm having the same issue here, I've created a sandbox featuring more or less the same setup as I'm using
https://codesandbox.io/s/cool-cache-tktvt?fontsize=14&hidenavigation=1&theme=dark
The form.isValid is false on the first click, however the values are accessible via getValues().count, as you can see in console, hope this helps to solve it

**Comment by bluebill1049** [comment] 2020-01-20 09:37
curious why are you guys using isValid for submit mode? as right now isValid is made for onChange and onBlur mode.

**Comment by mylnikovD** [comment] 2020-01-20 09:42
That's may be the root of this evil, because I'm using the code from other developer, and he might done this all thing wrong :) Could you please advise how this should be implemented properly?

**Comment by bluebill1049** [comment] 2020-01-20 09:44
I think isValid should be using for onChange or onBlur mode. (sorry i should update the doc) for onSubmit mode your formState will remain invalid until successful submit. I just don't see a good usage of tracking isValid with onSubmit mode. (happy to adjust if anyone can provide a good usage tho).

**Comment by mylnikovD** [comment] 2020-01-20 09:46
So should I change the validation mode to `onChange`? The docs are saying that this will affect performance, does it really do much?

**Comment by bluebill1049** [comment] 2020-01-20 09:50
@mylnikovD we are updating the doc for isValid.

> So should I change the validation mode to `onChange`? The docs are saying that this will affect performance, does it really do much?

Still better than controlled components validation tho, it doesn't trigger re-render each keystroke, but will update errors onChange.

**Comment by mylnikovD** [comment] 2020-01-20 11:05
Anyway, I've just removed this check from onSubmit handler, everything seem to work as I expected now. 
Great thanks for your help nevertheless!

**Comment by bluebill1049** [comment] 2020-01-20 11:09
awesome @mylnikovD thanks for the update. I guess that answer your question as well @JakariaAmin . closing this issue. if still doesn't make sense you can follow up more question or ask at our spectrum channel.

**Closed by bluebill1049** 2020-01-20 11:09 UTC
Labels: status: need more detail
