### ISSUE TITLE
Wizard example doesn't work

### ISSUE THREAD

**Issue by la55u** [react-hook-form/react-hook-form#4221] opened 2021-02-17 12:17 UTC
**Describe the bug**
Wizard (funnel / multi-step) form example throws an error after  submitting step 2. (action is not a function)

**To Reproduce**
Try the Codesandbox link below.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-wizard-form-13yud

**Expected behavior**
Shoud not throw an error.

**Comment by leapful** [comment] 2021-02-17 14:39
@la55u

This is not a bug.

The root cause is from little-state-machine is now upgraded to v4 while the current handling is for v3, it can be fixed by downgrading little-state-machine to v3 or update the handling with API of v4.

Working sample with little-state-machine v4:https://codesandbox.io/s/react-hook-form-wizard-form-forked-sqlhl?file=/src/Step2.js

@bluebill1049 : Could you please update this CSB example with new little-state-machine v4 ?

**Comment by bluebill1049** [comment] 2021-02-17 21:26
Thank you @leapful updated the CSB.

**Closed by bluebill1049** 2021-02-17 21:26 UTC
