### ISSUE TITLE
Can't find variable: name in RN

### ISSUE THREAD

**Issue by saggiyogesh** [react-hook-form/react-hook-form#567] opened 2019-11-26 06:17 UTC
**Describe the bug**
`Can't find variable: name` on upgrding version to `3.28.3`, It was working fine with `3.27.0`

Any changes in API. My Inputs are also configured with `Yup` schema for validations

**Screenshots**
![image](https://user-images.githubusercontent.com/551509/69603264-1dac3d80-1040-11ea-97b2-90f9e0a25c2f.png)

**Comment by bluebill1049** [comment] 2019-11-26 06:24
can you share your code (the bit where you register)?

**Comment by bluebill1049** [comment] 2019-11-26 20:20
i am patching this issue

**Comment by adrianso** [comment] 2019-11-26 22:27
I am also have this issue with both 3.28.4 and 3.28.5. Downgrading to 3.27.0 fixes the issue.

The issue occurs for me only when the debugger is off. When in debug mode, all versions work fine.

Hope that helps.

**Comment by adrianso** [comment] 2019-11-26 22:27
I am also have this issue with both 3.28.4 and 3.28.5. Downgrading to 3.27.0 fixes the issue.

The issue occurs for me only when the debugger is off. When in debug mode, all versions work fine.

Hope that helps.

**Comment by DarkSouls101** [comment] 2019-11-26 22:42
Can you show me the code on how u register field?

**Comment by adrianso** [comment] 2019-11-26 23:04
```
import { TextField } from 'react-native-material-textfield';
import useForm from 'react-hook-form';
```

```
  const { register, setValue, handleSubmit, errors } = useForm({
    defaultValues: {
      email,
      password,
    },
  });
```

```
<TextField
          testID="email"
          value={email}
          label="Email"
          lineWidth={0}
          keyboardType="email-address"
          autoCapitalize="none"
          containerStyle={styles.input}
          inputContainerStyle={styles.inputContainer}
          titleTextStyle={styles.inputTitle}
          labelOffset={{ y0: -6 }}
          tintColor="#231f20"
          returnKeyType="next"
          textContentType="username"
          autoCompleteType="username"
          ref={register({ name: 'email' }, { required: true })}
          onChangeText={text => setValue('email', text, true)}
          error={errors.email && 'Please enter your email'}
        />
```

**Comment by bluebill1049** [comment] 2019-11-26 23:35
@adhrinae i am going to update the doc. it's better to register during `useEffect()` but that's probably not the issue related, but worth to give it a try.

**Comment by bluebill1049** [comment] 2019-11-27 10:41
can you guys try out the latest version too?

**Comment by bluebill1049** [comment] 2019-11-27 20:57
going to close this issue as i have reverted unregister callback, which should fix this issue. i will reopen if you guys still find issues around it.

**Closed by bluebill1049** 2019-11-27 20:57 UTC
Labels: question

**Comment by Dsantacruz** [comment] 2020-01-05 22:46
same problem, some fix???

**Comment by bluebill1049** [comment] 2020-01-05 22:48
are you using `Controller`? @Dsantacruz

**Comment by bluebill1049** [comment] 2020-01-05 22:48
also how us more code @Dsantacruz

**Comment by Dsantacruz** [comment] 2020-01-05 22:55
![WhatsApp Image 2020-01-05 at 4 42 39 PM](https://user-images.githubusercontent.com/8165329/71787340-7e864880-2fe4-11ea-8a67-309635a6a241.jpeg)

**Comment by Dsantacruz** [comment] 2020-01-05 22:58
<img width="579" alt="Captura de Pantalla 2020-01-05 a la(s) 17 57 57" src="https://user-images.githubusercontent.com/8165329/71787375-ef2d6500-2fe4-11ea-9912-9409dfa0b259.png">

**Comment by bluebill1049** [comment] 2020-01-05 23:49
thanks @Dsantacruz for the screenshot, i think i need to see the render part and also not sure if the issue is from react-hook-form from the screenshot.

**Comment by Dsantacruz** [comment] 2020-01-06 00:10
return (
    <Screen py={0} px={0} scroll>
      <ConfirmModal
        visible={showSuccess}
        title="Guardado"
        description="Los datos fueron actualizados exitosamente"
        toggle={() => setShowSuccess(false)}
      />
      <Box
        bg="primary"
        borderBottomLeftRadius={4}
        borderBottomRightRadius={4}
        flexDirection="column"
        justifyContent="center"
        alignItems="center"
        py={5}
      >
        <Photo
          value={watch('picture')}
          onChange={async data => {
            const { path } = await client({
              url: 'uploadImage',
              data,
              contentType: 'multipart/form-data',
            });
            setValue('picture', path);
          }}
        />
        <Text color="white.2" family="bold" fontSize={6}>
          {`${user.firstName || ''} ${user.lastName || ''}`}
        </Text>
        <Text color="white.2" fontSize={2}>
          {user.purchaseTotalCount} compras
        </Text>
      </Box>
      <Box flexDirection="column" px={5} py={6}>
        <Field
          errors={errors}
          label="Nombres"
          name="firstName"
          value={watch('firstName')}
          renderInput={(value, name) => (
            <Input
              family="bold"
              fontSize={3}
              color="primary"
              value={value}
              onChangeText={text => setValue(name, text)}
              onBlur={e => triggerValidation({ name, value: e.nativeEvent.text })}
              borderBottomWidth={1}
              borderBottomColor="primary"
            />
          )}
        />
        <Field
          errors={errors}
          label="Apellidos"
          name="lastName"
          value={watch('lastName')}
          renderInput={(value, name) => (
            <Input
              family="bold"
              fontSize={3}
              color="primary"
              value={value}
              onChangeText={text => setValue(name, text)}
              onBlur={e => triggerValidation({ name, value: e.nativeEvent.text })}
              borderBottomWidth={1}
              borderBottomColor="primary"
            />
          )}
        />
        <Field
          errors={errors}
          label="Correo"
          value={watch('email')}
          name="email"
          renderInput={
            user.email
              ? null
              : (value, name) => (
                  <Input
                    family="bold"
                    fontSize={3}
                    color="primary"
                    value={value}
                    onChangeText={text => setValue(name, text)}
                    onBlur={e => triggerValidation({ name, value: e.nativeEvent.text })}
                    borderBottomWidth={1}
                    borderBottomColor="primary"
                  />
                )
          }
        />
        <Field
          errors={errors}
          label="Número de teléfono"
          value={watch('phone')}
          name="phone"
          renderInput={(value, name) => (
            <Input
              family="bold"
              fontSize={3}
              color="primary"
              value={value}
              onChangeText={text => setValue(name, text)}
              onBlur={e => triggerValidation({ name, value: e.nativeEvent.text })}
              borderBottomWidth={1}
              borderBottomColor="primary"
              keyboardType="phone-pad"
            />
          )}
        />

        <Field
          errors={errors}
          label="Fecha de Nacimiento"
          name="birthday"
          value={watch('birthday')}
          renderInput={(value, name) => (
            <DatePicker
              placeholder="Seleccione"
              value={value}
              onChange={text => {
                setValue(name, text);
                triggerValidation({ name, value: text });
              }}
            />
          )}
        />

        <Button
          title="Actualizar"
          mt={2}
          alignSelf="center"
          loading={formState.isSubmitting}
          disabled={formState.isSubmitting}
          onPress={handleSubmit(onSubmit)}
        />
      </Box>
    </Screen>
  );

**Comment by bluebill1049** [comment] 2020-01-06 00:20
The issue is can't find variable `name`? I don't think that's issue of react-hook-form

`triggerValidation({ name, value: text });` where is the name?
