### ISSUE TITLE
[Bug]: IsValid not causing rerender with setvalue

### ISSUE THREAD

**Issue by steveoh** [react-hook-form/react-hook-form#6572] opened 2021-09-16 22:48 UTC
### Version Number

7.13.0

### Codesandbox/Expo snack

https://codesandbox.io/s/youthful-cohen-ni3cy?file=/src/App.js

### Steps to reproduce

1. Go to codesandbox
2. Click on setvalue button
3. enter text
4. submit button is still disabled
5. perform the click and text in the other order and it works

### Expected behaviour

isvalid should be true regardless of the order the fields are entered

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment] 2021-09-16 22:59
https://user-images.githubusercontent.com/10513364/133696114-fc3025d9-d609-4ada-a03f-055e729c090e.mov

works for me with the latest

**Comment by steveoh** [comment] 2021-09-16 23:07
![isvalid](https://user-images.githubusercontent.com/325813/133696593-21c25fab-4d01-4ee5-8274-bf7adaaf929b.gif)

**Comment by steveoh** [comment] 2021-09-16 23:17
I'm registering a virtual input and resetting it after the form submits.

```js
useEffect(() => {
    register('geometry');
  }, [register]);

  useEffect(() => {
    if (formState.isSubmitSuccessful) {
      reset();
      setValue('geometry', '');
    }
  }, [formState, setValue, reset]);
```

The docs mention

> For controlled components like React-Select which do not expose a ref prop, you will have to reset the input value manually with setValue or connect your component via useController or Controller.

Which I assume applies to virtual inputs also? I'm unsure how to reset the virtual input with `setValue`. If I should do it before reset, or after, and with undefined or null or something else?

**Comment by steveoh** [comment] 2021-09-17 00:25
So in goofying around I re `register('geometry')` after the `reset` and it started to function as I would expect. Does that seems odd to you or does it make any sense?

**Comment by bluebill1049** [comment] 2021-09-17 00:36
can you reproduce the issue at the codesandbox above? https://codesandbox.io/s/youthful-cohen-ni3cy?file=/src/App.js

by using the latest, also default mode is onSubmit, please refer to the doc

<img width="978" alt="Screen Shot 2021-09-17 at 10 36 34 am" src="https://user-images.githubusercontent.com/10513364/133705673-5e371411-83bd-4fd8-bd97-d0267d6f8a4c.png">

**Comment by steveoh** [comment] 2021-09-17 00:46
all = 'onSubmit' confused me. I can't reproduce it, no

**Comment by bluebill1049** [comment] 2021-09-17 01:22
please share a video or steps since you updated the codesandbox with more inputs.

**Comment by bluebill1049** [comment] 2021-09-18 00:21
any udpate?

**Comment by steveoh** [comment] 2021-09-18 15:04
I won't get to it until Monday.

**Comment by steveoh** [comment] 2021-09-20 18:47
https://user-images.githubusercontent.com/325813/134057418-cc0aa36e-0054-4db6-8f9d-aa56a9375b35.mp4

**Comment by bluebill1049** [comment] 2021-09-20 23:50
This got fixed in the last release, this is due to missing register input. https://github.com/react-hook-form/react-hook-form/issues/6581 thanks for the updated video.

**Closed by bluebill1049** 2021-09-20 23:50 UTC
Labels: Status: under investigation

**Comment by bluebill1049** [comment] 2021-09-21 01:03
I don't think `optional` is been registered, it's recommended to register input if you can, but it should work now without `register`.
