### ISSUE TITLE
issue: useEffect Trigger + watch

### ISSUE THREAD

**Issue by zakaoai** [react-hook-form/react-hook-form#7068] opened 2021-11-17 17:08 UTC
### Version Number

7.19.4 -> 7.19.5

### Codesandbox/Expo snack

https://codesandbox.io/s/sparkling-night-i206b

### Steps to reproduce

1 Select a button
2 enter numbers in the new field
3 See that no error message or render has been triggered

4 change version to 7.19.3 of RHF
5 Redo 1 and 2
6 See that error message appear and if you type a correct value a new field appear

### Expected behaviour

Expect that when I type in the input the useEffect is triggered and the validation too

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment] 2021-11-17 22:30
> watch result is optimised for render phase instead of useEffect's deps, to detect value update you may want to use an external custom hook for value comparison.

- wouldn't use watch/useWatch value as `useEffect` dep
- no longer shallow clone the watch result with object, as it mutate immutable objects: issue: https://github.com/react-hook-form/react-hook-form/issues/7013

**Comment by osdiab** [comment] 2021-11-18 12:00
at my company we're trying to retrigger validations when certain fields change, which we thought we should do in a `useEffect()`, though it sounds like with this limitation the recommendation would be to actually just do the deep comparison directly in the render function - is this what you'd recommend?

```
function useRevalidateOnConfigChange(control, triggerRevalidate) {
  const prevConfig = useRef();
  const config = useWatch({control, name: "config"});
  // normally my instinct is to do this in a useEffect hook, but I guess we're not supposed to?
  // and since i moved this to another hook, it would only call the revalidation function on
  // the config changing due to the semantics of useWatch - that correct?
  if (!prevConfig.current || !deepEquals(prevConfig.config, config) {
    prevConfig.current = config;
    triggerRevalidate();
  }
}
```

**Comment by bluebill1049** [comment] 2021-11-18 12:02
@osdiab that's correct, or you can use this hook as well https://github.com/kentcdodds/use-deep-compare-effect made by kent.

**Comment by spoeken** [comment] 2021-11-18 14:49
Hey. Can you guys please help me out here? I've been trying all day to get this working. 
https://codesandbox.io/s/react-hook-form-auto-save-xgulp?file=/src/AutoSave.tsx

Since useEffect no longer works for this I tried to use the `use-deep-compare-effect` package, but nothing happens.

**Comment by osdiab** [comment] 2021-11-18 14:57
@spoeken you need to just not use `useEffect()` at all - put the save call directly in the render function, or if you don't want to do it for rerenders caused by other things, make a separate hook like the example i wrote above, where you once again do it directly in the hook body rather than in a `useEffect()` hook.

Since `useWatch()` still triggers rerenders when the data changes, it'll save on changes as you expect (`useEffect()` evidently doesn't work since on each rerender, the object that it returns is just a mutated version of the same object instance, so `useEffect()`'s shallow-comparison fails to see that anything changed). I agree that this feels dirty and confusing though.

BTW @bluebill1049 how about this as an alternative DX: would it be feasible to have a flag on `useWatch()` where if you pass it in, it actually will return a clone of the object? That would solve my problem, and be a little less dirty-feeling.

**Comment by spoeken** [comment] 2021-11-18 15:44
Thanks a lot @osdiab 💯 I get it now

**Comment by sincraianul** [comment] 2021-11-18 19:01
@spoeken `use-deep-compare-effect` will not work because it doesn't do a deep clone of the object, so you get stuck with the same object as ref.

I've modified the hook to basically do just that and it's a drop-in replacement for your existing code that relies on `useEffect`:

```ts
/**
 * @param value the value to be memoized (usually a dependency list)
 * @returns a memoized version of the value as long as it remains deeply equal
 */
function useDeepCompareMemoize<T>(value: T) {
  const ref = React.useRef<T>(value);
  const signalRef = React.useRef<number>(0);

  if (!deepEqual(value, ref.current)) {
    // this is the missing link, replace with your `cloneDeep` lib of choice
    ref.current = cloneDeep(value);
    signalRef.current += 1;
  }

  return React.useMemo(() => ref.current, [signalRef.current]);
}

export function useDeepCompareEffect(
  callback: EffectCallback,
  dependencies: DependencyList
): UseEffectReturn {
  return React.useEffect(callback, useDeepCompareMemoize(dependencies));
}
```

**Comment by bluebill1049** [comment] 2021-11-18 22:11
> BTW @bluebill1049 how about this as an alternative DX: would it be feasible to have a flag on useWatch() where if you pass it in, it actually will return a clone of the object? That would solve my problem, and be a little less dirty-feeling.

@osdiab sounds like a good idea, would you like to send a feature request.

**Comment by bluebill1049** [comment] 2021-11-19 06:04
> useWatch result is optimised for render phase instead of useEffect's deps, to detect value update you may want to use an external custom hook for value comparison.

https://react-hook-form.com/api/usewatch

![Screen Shot 2021-11-19 at 5 04 46 pm](https://user-images.githubusercontent.com/10513364/142573443-0e45abe0-dd66-40af-9eec-d55aad50ff05.png)

going to close this issue as its expected result.

**Closed by bluebill1049** 2021-11-19 06:04 UTC
Labels: question
