### ISSUE TITLE
Yup resolver validation seems to be unlinked with the form

### ISSUE THREAD

**Issue by Vandell63** [react-hook-form/react-hook-form#2222] opened 2020-07-14 18:06 UTC
**Describe the bug**
Using resolver, the synchronization between the form and/or the schema validation seems to be unlinked.

**To Reproduce**
https://github.com/react-hook-form/resolvers/issues/28
https://github.com/react-hook-form/resolvers/issues/27

**Codesandbox link (Required)**
https://codesandbox.io/s/polished-framework-ofvx8
https://codesandbox.io/s/magical-almeida-j941j?file=/src/App.js

**Expected behavior**
All is on the two stories. I repost here because it seems to be link with the react hook form core. 
I expect to get the form validation the same as the yup validation. 
The first example is a simple form with yup and his `when` to target another value in the schema. Only the max errors respond to his own field. If you change the min value less than the max value we expect to have no more error. 
We can see the `isValid` form trigger properly but the message still there.

For the second example, for me it was the same use case. I inject a different context to the yup context but the form do not reflect the yup validation as expected. All are well explained in those stories.
Hope you can track it easily. Thx in advance :)

**Comment by bluebill1049** [comment] 2020-07-15 00:02
thanks a lot for the detailed issue report.

1) issue one, react hook form focus one field at a time for validation, but you can use `trigger` to trigger `max` input's validation, this explains why it's not working with related field validation. maybe we should include that in the documentation so the user understands and expect the validation behavior.

**Comment by bluebill1049** [comment] 2020-07-15 00:18
2) second issue, you should use context at `useForm` level. it will get cached.
<img width="978" alt="Screen Shot 2020-07-15 at 10 18 37 am" src="https://user-images.githubusercontent.com/10513364/87488781-8e15d680-c684-11ea-928e-c97d9f6a1882.png">

**Comment by Vandell63** [comment] 2020-07-15 08:16
@bluebill1049  when i use context at useForm level, it don't take it at all. The lang property is not injected in yup. In log we can see that the lang property is undefined. 
I tried both ( resolver + useForm ) and the `cache` one still undefined and the other one work like the previous example only in submit

**Comment by bluebill1049** [comment] 2020-07-15 08:21
> @bluebill1049 when i use context at useForm level, it don't take it at all. The lang property is not injected in yup. In log we can see that the lang property is undefined. ( codesandbox updated, https://codesandbox.io/s/magical-almeida-j941j?file=/src/App.js )
> I tried both ( resolver + useForm ) and the `cache` one still undefined and the other one work like the previous example only in submit

It doesn't inject into yup's context, instead you will have to use in the resolver, maybe we should inject that into the yup context and make people's life easier.

```
resolver: (value, context) => {
  // your schema
}
```

**Comment by bluebill1049** [comment] 2020-07-15 08:22
inject context into yup's context would be a PR at the resolver if you interested.

**Comment by Vandell63** [comment] 2020-07-15 08:35
@bluebill1049  thanks, first pr for me i will try :).

**Comment by Vandell63** [comment] 2020-07-16 08:03
@bluebill1049  i don't think it will resolve my initial issue if we inject the context directly even if it is cached right ?
- > https://codesandbox.io/s/magical-almeida-j941j?file=/src/App.js
```
    // QUESTION : How can i trigger the validation with the new context ???
    // I try : trigger, control.rerender()
    // Only when you submit you got the correct validation, but not during input change event
    // I expect to be the form cache that keep the initial schema
```
Should we had `useEffect()`  methods to re-set the resolver when the context change in RHF core ?

**Comment by bluebill1049** [comment] 2020-07-16 08:07
I think it's easier to trigger a validation at `useEffect`, otherwise users will run into memo context and ect.

**Comment by Vandell63** [comment] 2020-07-16 08:37
Yes ( you mean add it to the RHF core ? ) . Because this is the only thing dynamic which is inject into RHF. It works every time on submit, but in every change it will always take the cache information this is why i got those issues.
Do i misunderstood something ? Because in the codesandbox i've already try everything ( all possible method ) to rerender as soon as the lang has change. On submit it's ok, onChange no.

**Comment by bluebill1049** [comment] 2020-07-16 08:57
This is what i meant: https://codesandbox.io/s/focused-banzai-6e12x?file=/src/App.js but we can plug this into yup's context as well.

**Comment by Vandell63** [comment] 2020-07-16 11:11
@bluebill1049  thx / updated -> https://codesandbox.io/s/clever-breeze-lw3dz?file=/src/App.js
I expect when i change the lang that the message disappear. Am i missing something or could we considere it asa  bug when mode and revalidateMode are 'onChange' ?

**Comment by bluebill1049** [comment] 2020-07-16 11:17
what's the step to reproduce? if you can change context, then users will need to trigger the validation, otherwise, it only affects the context.

**Comment by Vandell63** [comment] 2020-07-16 12:27
Simple when i switch To FR i want see the error before submitting again because i expect to have mode onChange. So if context change i want my form to be revalidate and show again new errors [before submitting].

**Comment by bluebill1049** [comment] 2020-07-16 12:29
oh i see, we don't subscribe to the context, let's use `trigger` for use case like that, sometimes less smartness is better and less thing to document too.

**Comment by Vandell63** [comment] 2020-07-16 12:37
Ahahaha yes i did in line 31 and the result is the same !!

**Comment by bluebill1049** [comment] 2020-07-16 12:44
I will follow this up tmr :)

**Comment by bluebill1049** [comment] 2020-07-17 03:29
<img width="1306" alt="Screen Shot 2020-07-17 at 1 29 02 pm" src="https://user-images.githubusercontent.com/10513364/87745537-7cbdfd00-c831-11ea-972a-15839d59c0e4.png">

it's working here for me.

https://codesandbox.io/s/vibrant-glitter-7evjl?file=/src/App.js

**Comment by Vandell63** [comment] 2020-07-17 14:10
Yes it works but only you click on test or submit button ( they do both the same thing ). As i said i would like to have this 
`Simple when i switch To FR i want to see the error before submitting again`
Because the mode has been set `onChange` or `all` you see ?

**Comment by bluebill1049** [comment] 2020-07-17 22:25
That's what I try to explain above, changing the context value is not going to trigger the validation.

1. change context

**Comment by Vandell63** [comment] 2020-07-18 01:58
@bluebill1049  it will be maybe better -> https://www.loom.com/share/fc58cf63bd6541609779927adab686ad

**Comment by bluebill1049** [comment] 2020-07-18 08:27
Thanks, @vadimshvetsov for the video, I clearly understand which you after here and I think my explanation probably not clear enough. This is indented behavior and it's not a bug, you can consider it as a feature request but at this stage, I don't think we want to include more logic into the resolver with context.

So here is what you expect, `context` updated while the user's action, and trigger validation.

```
updateState({ xxx })
trigger('xxx') // get the latest `context` and update validation
```

but what really happened, context update is only taking effect on the next render.

```
updateState({ xxx })
```

**Next render** go into `useForm` -> `context

```
trigger('xxx')
```

`context` **only** gets updated when your component gets a re-render

which explains why my codesandbox works as expected: https://codesandbox.io/s/vibrant-glitter-7evjl?file=/src/App.js

------------------------------------------------------------------

**Solution** 

So how can you fix your validation problem, I will use `useEffect` to trigger that validation when your local state gets updated. 

https://codesandbox.io/s/vibrant-glitter-7evjl?file=/src/App.js

**Conclusion** 

I am going to close this issue as a bug report, in terms of automatically trigger validation due to context change, I am not a big fan of this, it's a tradeoff and how much logic you want to bury inside the resolver, personally I prefer it to be dumb and just doing a mapping job without associated with other responsibility. if you have strong opinion about this, you can submit a feature request and i will tag waiting for the up vote and we can go from there.

**Closed by bluebill1049** 2020-07-18 08:27 UTC
Labels: question

**Comment by Vandell63** [comment] 2020-07-18 09:16
No well it's perfect @bluebill1049  thank you i did not get the rerender flow ( which follow the normal hook load cycle ) and now it is more clear. No need to go further with a feature request after this explanation ( it could be really great for the docs ). 
I'm completely agree with your mindset. 
I would love to have a live session together to help me understand the mindset you made into this library and help you more to contribute for this project.
Thanks again for your time.

**Comment by tafelito** [comment] 2020-08-01 21:03
> inject context into yup's context would be a PR at the resolver if you interested.
> 
> https://github.com/react-hook-form/resolvers/blob/master/src/yup.ts#L54

@bluebill1049 sorry to comment here, but I just saw this comment, and wanted to ask you about this. What's the correct way to pass a value to yup's context? Right now if you use RHF context it's not passed down to yup context. But based on that line it says `"You should not used the yup options context. Please, use the 'useForm' context object instead"`
Also when using context within yupResolver, if abortEarly is not false, then the validation won't ever failed

**Comment by bluebill1049** [comment] 2020-08-02 00:04
hey @tafelito useForm context should pass the context, unless there is bug. do you have a csb to reproduce the issue?

**Comment by tafelito** [comment] 2020-08-02 00:06
just created one based on the one you posted above

https://codesandbox.io/s/magical-almeida-j941j?file=/src/App.js

**Comment by bluebill1049** [comment] 2020-08-02 00:12
it works. use the latest version plz

**Comment by tafelito** [comment] 2020-08-02 00:14
great thanks! I updated RHF but forgot to update the resolvers
