### ISSUE TITLE
Methods of use useFieldArray triggers hooks

### ISSUE THREAD

**Issue by michalbundyra** [react-hook-form/react-hook-form#2773] opened 2020-08-31 07:30 UTC
**Describe the bug**

*Issue since version 6.5.3, version 6.5.2 works as expected (for `append`).*

I need to call `append` in `useEffect` hook, but unfortunately it's not working as I would expect.
To use `append` in hook I need to pass it as dependency and it causes problem. If I am not adding it to dependency list all works as expect, but then I am getting warning in console, that it should be a dependency.

I can have a workaround for that easily with additional state value, but I consider it as a bug, as `setValue` from the form works as expected - see below.

**To Reproduce**
See codesandbox below

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-wrmyj?file=/src/index.js:424-438

Click one of "append", ~"prepend"~ or "delete" and check console output.

**Expected behavior**
All hooks are triggered only once - on loading, but should not be called when field is appended/prepended/removed.

I've checked also how it works with `setValue` from the form:
https://codesandbox.io/s/react-hook-form-v6-setvalue-forked-inyki?file=/src/index.jsx
and here all is fine - when we click "Set First Name Value", which triggers `setValue` the hook is not called, as I would expect.

**Desktop (please complete the following information):**

- OS: macOS
- Browser Safari/Chrome
- Version latest stable

**Comment by bluebill1049** [comment] 2020-08-31 07:52
Please supply the steps to reproduce the issue.

**Comment by michalbundyra** [comment] 2020-08-31 08:16
@bluebill1049 
not sure what I can say more... please see:
- https://codesandbox.io/s/react-hook-form-usefieldarray-forked-wrmyj?file=/src/index.js
- open console output, and you should see:
  - `append "changed"?`
  - `prepend "changed"?`
  - `remove "changed"?`
  (triggered from hooks lines - 22-32).

Now click button "APPEND" and in console you will see additional:
- `append "changed?"
- `remove "changed?"

But I believe it should not be there. Hope it's clearer now.

**Comment by bluebill1049** [comment] 2020-08-31 08:20
oh, it's about to memorise those methods. because those methods get called has `fields` as dep.

**Comment by michalbundyra** [comment] 2020-08-31 08:24
@bluebill1049 right, that's why `prepend` works fine (does not trigger the hook).
Do we need this `fields` dep in `append` and `remove`? I do not know rect-hook-form internal at all.. Any chance it can be refactored somehow so it could work as `prepend`?

**Comment by michalbundyra** [comment] 2020-08-31 08:30
So it was working fine (with `append`) in 6.5.2 and before: https://github.com/react-hook-form/react-hook-form/blob/v6.5.2/src/useFieldArray.ts#L471

Of course adding that dependency was to solve other issues. I hope it can be refactored somehow so we can have the previous behaviour for `append`.

**Comment by bluebill1049** [comment] 2020-08-31 08:34
> So it was working fine (with `append`) in 6.5.2 and before: https://github.com/react-hook-form/react-hook-form/blob/v6.5.2/src/useFieldArray.ts#L471
> 
> Of course adding that dependency was to solve other issues. I hope it can be refactored somehow so we can have the previous behaviour for `append`.

That would cause bugs unfortunately, the one we having in the master is correct. Is there any other way you can check?

**Comment by michalbundyra** [comment] 2020-08-31 08:37
@bluebill1049 

> That would cause bugs unfortunately, the one we having in the master is correct. Is there any other way you can check/work around?

Yeah, as I said in the description, I can find a workaround for my use case with additional state variable, and all is good.

It is not intuitive that it works fine for `prepend` and it's not working for `append`.
I would then expect some bugs in `prepend` as you think `fields` dep is needed in `append`.

**Comment by bluebill1049** [comment] 2020-08-31 08:43
> @bluebill1049
> 
> > That would cause bugs unfortunately, the one we having in the master is correct. Is there any other way you can check/work around?
> 
> Yeah, as I said in the description, I can find a workaround for my use case with additional state variable, and all is good.
> 
> It is not intuitive that it works fine for `prepend` and it's not working for `append`.
> I would then expect some bugs in `prepend` as you think `fields` dep is needed in `append`.

because append doesn't need to aware of what's in the FieldArray.

**Comment by bluebill1049** [comment] 2020-08-31 23:29
I did think about this issue last night. There are two paths, 

1. fully embrace react hooks dep, which we will **need** `fields` and this issue will be addressed in the user's hand.
2. use `ref` to skip that extra dep check, which can potentially lead to issues with future React update (potentially)

I think I am leaning toward options 2 to get over the line and if React introduces changes we will have to go back to option 1. 

any objection?

**Comment by michalbundyra** [comment] 2020-09-01 05:52
@bluebill1049 For the time being I am fine with 2 if it is not causing any other issues (performance, etc...).

It would be nice to avoid ref, but we can do it later as another improvement.

**Closed** 2020-09-01 05:56 UTC
Labels: question

**Comment by bluebill1049** [comment] 2020-09-01 06:02
agreed.
