### ISSUE TITLE
V7 useFieldArray Typescript issue circular reference

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4055] opened 2021-01-30 00:14 UTC
**Describe the bug**
I have a field that's represented as an object in a field array. If the object has a recursive definition, then this will cause a typescript error in `useFieldArray`. V6 did not have this issue.

**To Reproduce**
View the error on line 26

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-controller-template-forked-6j6w3?file=/src/index.tsx:507-520

**Comment by bluebill1049** [comment] 2021-01-30 00:27
```
interface Dog {
  pups: Array<{
    test: string
  }>;
}

interface FieldArrayFormValues {
  name: { value: string; label: string; dog: Dog } | null;
}

interface FormValues {
  test: Array<FieldArrayFormValues>;
}
```

you should do this instead of reference Dog itself.

**Comment by wdfinch** [comment] 2021-01-30 00:42
Thanks for the reply. This doesn't really solve the issue but rather just changes the Dog type to remove the recursion. 

The use case is let's say you have a select input that looks like this. 

```
{
  label: string
  value: string,
  meta?: object
}
```

In this case, I want to optionally associate some extra information with a select input. In one of my use cases, this information happens to be recursively defined. I'm not trying to represent this as an input, but I still want to store it, so when the user chooses an option from the select input, I can see this meta-object and use it in some way.

**Comment by bluebill1049** [comment] 2021-01-30 00:47
yea @wdfinch I aware this is not solving your issue, but this like I suggested above, we are already doing recursive inside, this is not going to work out as far as I know. It works for v6 because there is no recursive lookup, and there is no type of safety with `register` name either.

**Comment by bluebill1049** [comment] 2021-01-30 00:49
If you think this is possible to work around, please take a look at the v7 and PR welcome.

**Comment by wdfinch** [comment] 2021-01-30 00:53
Sorry I misunderstood. Ok, I'll take a look sometime. I guess on my end rather than store the recursive object, I could just store the id of the object which exists in redux, and look it up from there when I need it. Thanks for the help here. Did you want to leave this open or close it?

**Comment by bluebill1049** [comment] 2021-01-30 00:58
Let's leave this open for a while, maybe some TS wizard knows how to work around this potential issue.

**Comment by wdfinch** [comment] 2021-01-30 01:30
Sounds good.

**Comment by leapful** [comment] 2021-02-07 14:52
@bluebill1049 @wdfinch 

Hello,

May I suggest my workaround for this case ? It's a little bit tricky but it worked, the idea is to bypass circular check on array type definition.

```
interface DogArray {
  [key: number]: Omit<Dog, ''>
}

interface Dog {
  pups: DogArray
}
```

https://codesandbox.io/s/react-hook-form-controller-template-forked-7197u?file=/src/index.tsx

**Comment by bluebill1049** [comment] 2021-02-07 23:22
that's interesting! @leapful 👍

**Comment by bluebill1049** [comment] 2021-02-19 07:56
Probably going to close this one, and consider it as a limitation, and document that in the doc.

**Comment by wdfinch** [comment] 2021-02-19 16:31
Sounds good to me.

**Comment by bluebill1049** [comment] 2021-02-21 03:04
<img width="765" alt="Screen Shot 2021-02-21 at 2 04 37 pm" src="https://user-images.githubusercontent.com/10513364/108614342-bef58f80-744d-11eb-8ece-2c2fb2ca6c74.png">

will reference back to this issue and including that in the doc.

**Closed by bluebill1049** 2021-02-21 03:04 UTC
Labels: TS, V7

**Comment by jeffdc** [comment] 2021-04-07 15:16
I failed to find this issue and created what was essentially a duplicate. Copying my thoughts from that one here since this has a more complete conversation:

If this is going to stay this way then I am not going to be able to use this lib anymore, at least not V7. I have too much data that is like this (tree-like) AND I am already familiar with the Omit type to tweak things. I will basically have to double all of my types and change function signatures and write a lot of conversion code to go from the "Omit" type back "up" to the correct type. 

This is a real Bummer as this is a great library. This seems like a severe limitation and I really hope you reconsider.

**Comment by wdfinch** [comment] 2021-04-07 15:38
@kotarella1110 maybe you would have some insight here.

**Comment by wdfinch** [comment] 2021-04-07 16:02
Also you don't need to pass in a generic type to your form in order to use it with tree like data. This is a typescript only issue.

**Comment by jeffdc** [comment] 2021-04-07 16:22
It is indeed a TS only issue. It was introduced with the changes to make the form strongly typed. As I try to see if I can get things working with V7 (my project is TS only) I am puzzling through several type errors that remind me of my days (many years ago) trying to figure out C++ template errors. Errors that span pages of screen.

**Comment by wdfinch** [comment] 2021-04-07 16:29
Your types might need to be adjusted to work in V7. Regarding the tree-like data, is your form actually tree-like, or is it just the data you are trying to store in form values. From values is only designed to hold data that directly correlates to inputs in your form. So if you're trying to store arbitrary data in form values, this is not the recommended use.

**Comment by jeffdc** [comment] 2021-04-07 17:10
The form is not tree-like. The problem is that I have a controlled component that is part of the form (react-bootstrap-typeahead). I need to store the data in this component for it to function correctly (it has a label lookup function that is used to figure out what to display). This component is the "key" to the entire form in that its selected value determines everything else in the form. 

I am running into a lot of other issues with the V7 version that are all related to the new form typings. I need to work on it more to figure out if I need to redesign the way all of these forms work to conform to the V7 constraints or if I need to think about replacing the library entirely.

My forms are all administration (data CRUD) forms and I have built a hook that handles a lot of the details (including wrapping the react-hook-form as well as the "key" field which is the typeahead component that I mentioned above). It was my first React form work and I think it could probably use a revisit, so this is at least motivation to do so. :)

**Comment by leapful** [comment] 2021-04-07 22:55
@jeffdc Could you please provide a codesandbox of your issue using the controlled component ? It will help to find out a workaround to simplify the typing and get rid of type error.

**Comment by jeffdc** [comment] 2021-04-22 16:34
Sorry for the delay on this. I ended up doing a large refactoring to incorporate V7 into my code base. The only real issue that I ran into was this circular reference issue. I got around it by declaring a new Type to use in the UI code that does not have the circular reference and then reassembling stuff on the backend. It is a pain but workable. I can imagine scenarios that are more complicated than mine where it would not be workable. 

Overall I think that V7 is a big improvement over older versions, but I do worry about the "type hoops" that now exist getting in the way of a not insignificant number of use cases.

**Comment by ConneXNL** [comment] 2021-05-12 09:59
Running into the same circular error since v7 here. My form data itself doesn't have circular references but the objects i store in them might.

> From values is only designed to hold data that directly correlates to inputs in your form. So if you're trying to store arbitrary data in form values, this is not the recommended use.
I am a little suprised by this comment. What if my form data holds some kind of rich object and I am using a Controller to select that rich object via a custom select... react-hook-form is not supposed to limit to serializable data or primitive values, is it?

**Comment by naivefun** [comment] 2021-09-08 02:58
I was trying to do a JSON Schema editor and this blocks me since object schema is circular by properties.

**Comment by EliseyMartynov** [comment] 2022-02-22 15:15
That's not going to be reconsidered?

**Comment by Moshyfawn** [comment] 2022-02-22 15:34
Not ATM
From [the RHF docs on `useFieldArray` TS use section](https://react-hook-form.com/api/usefieldarray#rules)
> we do not support circular reference. Refer to this this [Github issue](https://github.com/react-hook-form/react-hook-form/issues/4055) for more detail.

**Comment by bluebill1049** [comment] 2022-02-22 22:11
I think V8 will resolve this issue.

**Comment by Moshyfawn** [comment] 2022-02-22 22:17
> I think V8 will resolve this issue.

Yep, you're right @bluebill1049.
See [this CSB](https://codesandbox.io/s/eloquent-shtern-nm0ipq?file=/src/App.tsx) with RHF 8.0.0-alpha.1

**Comment by bluebill1049** [comment] 2022-02-22 22:22
That's awesome @Moshyfawn thanks to @felixschorer's work on his amazing work with V8! you guys can find out more on this page: https://github.com/react-hook-form/react-hook-form/discussions/7433

**Comment by Moshyfawn** [comment] 2022-02-22 22:29
Yeah, @felixschorer
<img width="503" alt="image" src="https://user-images.githubusercontent.com/16290753/155230286-6eda9912-d7d9-4323-a87d-f0a25c1fb2c1.png">

**Comment by ulziibadrakh-p** [comment] 2022-06-07 02:07
Is there any temporary fix until V8 release?

**Comment by abemedia** [comment] 2022-06-30 18:15
> Is there any temporary fix until V8 release?

Yes: https://github.com/react-hook-form/react-hook-form/issues/4055#issuecomment-950145092

**Comment by Upinwv** [comment] 2022-06-30 21:16
Hook form

--

**Comment by nvmnghia** [comment] 2022-08-23 04:02
Could anyone link the related PR/commit? I want to see the magic myself but can't find it.
