### ISSUE TITLE
issue: Is there any method which returns boolean value if the input value is satisfying all the validations?

### ISSUE THREAD

**Issue by imtheaman** [react-hook-form/react-hook-form#11534] opened 2024-02-20 18:07 UTC
### Version Number

latest ~ V7

### Codesandbox/Expo snack

--question--

### Steps to reproduce

```
const FormSchema = z.object({
    "first_name": z.string({
        required_error: "Name is required",
        invalid_type_error: "Not a valid type"
    }),
    last_name: z.string({
        required_error: "Name is required",
        invalid_type_error: "Not a valid type"
    }),
    gender: z.nativeEnum(GenderEnum, {
        required_error: "Gender is required",
        invalid_type_error: "Not a valid type"
    }),
    dob: z.date({
        required_error: "Date of birth is required.",
    }),
})
```

```
const form = useForm<z.infer<typeof FormSchema>>({
        resolver: zodResolver(FormSchema),
        defaultValues: {
            "first_name": userdata.user.first_name,
            last_name: userdata.user.last_name,
            dob: new Date(userdata.user.dob),
            gender: userdata.user.gender
        },
        disabled: disabled
})
```

```
<FormField
  control={form.control}
  name="first_name"
  render={({ field }) => {
    console.log("FIELD", field);
    return (
      <FormItem className="col-span-2">
        <FormLabel htmlFor="first_name">First Name</FormLabel>
        <FormControl>
         /*  
          *  Ain't there any method like this which returns whether the
          *  input value is satisfying all the validations or not 
          */
          <Input variant={"line"} valid={field.is_valid()} {...field} />
        </FormControl>
        <FormMessage />
      </FormItem>
    );
  }}
/>;
```

### Expected behaviour

there should be a method available like this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtheaman** [comment] 2024-02-20 18:09
#11502

**Comment by Moshyfawn** [comment] 2024-02-20 18:25
Duplicate of #11502

Please don't re-post your question as an issue.

**Closed by Moshyfawn** 2024-02-20 18:25 UTC
