### ISSUE TITLE
defaultValues is not working anymore with 7.8.0

### ISSUE THREAD

**Issue by rpopovici** [react-hook-form/react-hook-form#5499] opened 2021-06-05 09:50 UTC
I am using useForm with controlled(useController) components in react native
Passing defaultValues to useForm is not working anymore with 7.8.0 It was working with 7.7.1
Only defaultValue field works now

**Comment by bluebill1049** [comment] 2021-06-05 09:54
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by bluebill1049** [comment] 2021-06-05 10:14
Just did a quick test and it's working for me: https://snack.expo.io/@bluebill1049/test-usecontroller can you follow up with reproduceable codesandbox or expo snack before I close this issue as couldn't reproduce the problem.

**Comment by rpopovici** [comment] 2021-06-05 10:32
@bluebill1049 this is strange. I was initialising/defaulting the defaultValue to '' in my controlled component and now I have to leave it uninitialised in order to make it work with defaultValues

```
...
const { name, control, defaultValue = '', ...otherProps } = props
const { field } = useController({ control, name, defaultValue })
...
```

**Comment by bluebill1049** [comment] 2021-06-05 10:35
can you share a codesandbox/expo snack? @rpopovici i can take a look at it.

**Comment by rpopovici** [comment] 2021-06-05 10:37
https://snack.expo.io/yqw1AsthU

**Comment by bluebill1049** [comment] 2021-06-05 10:39
> https://snack.expo.io/yqw1AsthU

Why do you need to provide inline `defaultValue` with empty `string`?

**Comment by rpopovici** [comment] 2021-06-05 10:43
I don't need it. I did it out of convenience.. in case you don't provide defaults via defaultValues or defaultValue

**Comment by bluebill1049** [comment] 2021-06-05 11:07
I see, I would change that to `undefined` for `defaultValue`.

<img width="566" alt="Screen Shot 2021-06-05 at 9 04 48 pm" src="https://user-images.githubusercontent.com/10513364/120889683-aa768500-c641-11eb-802c-7ea0e2f08a45.png">

it's either `defaultValue` or `defaultValues`, the inline `defaultValue` is overwritten with `defaultValues` provided and this aligns with the behavior when working with Field Array.

**Comment by simonedelmann** [comment] 2021-06-05 11:44
Hello! I think, I have the same issue with 7.8.0, although I haven't tested with an earlier version.
I have a controlled select, which gets its options as a prop, and I've set `defaultValue` to the first option. But when I want to use that select for editing existing data populated by `defaultValues`, `defaultValue` will be preferred:

```
// Assuming
defaultValue = 'foo'
defaultValues[path] = 'bar'
```

For uncontrolled components 'bar' will be used. For controlled components 'foo' will be used. I would expect them to behave the same.

**Comment by simonedelmann** [comment] 2021-06-05 11:51
Here is an example: https://snack.expo.io/bnbfzHDOk
I Food 

> Just did a quick test and it's working for me: https://snack.expo.io/@bluebill1049/test-usecontroller can you follow up with reproducible codesandbox or expo snack before I close this issue as couldn't reproduce the problem?

I took your example and just added a defaultValue line 16 to demonstrate the problem
```ts
  const { field } = useController({
    control,
    name: 'test',
    defaultValue: 'this-should-not-be-displayed'
  });
```

Of course there should be no defaultValue needed in this case, but for example in my case (select component) I need both `defaultValue` and `defaultValues` (prioritized) for the same field.

**Comment by bluebill1049** [comment] 2021-06-05 12:09
@simonedelmann inline should overwrite `defaultValues` at the `useForm`. This is applied to `useFieldArray` as well, v7.8.0 is the correct behaviour to avoid default value conflict.

```
import React from "react";
import { useForm, useFieldArray } from "react-hook-form";

function App() {
  const { register, control, handleSubmit, reset, trigger, setError } = useForm({
    defaultValues: {
      test: [{ lastName: 'test' }]
    };
  });
  const { fields, append, prepend, remove, swap, move, insert } = useFieldArray({
    control,
    name: "test"
  });
  
  return (
    <form onSubmit={handleSubmit(data => console.log(data))}>
      <ul>
        {fields.map((item, index) => (
          <li key={item.id}>
            <Controller
              render={({ field }) => <input {...field} />}
              name={`test.${index}.lastName`}
              control={control}
              defaultValue={item.lastName} // inline defaultValue is taking over defaultValues.
            />
            <button type="button" onClick={() => remove(index)}>Delete</button>
          </li>
        ))}
      </ul>
      <button
        type="button"
        onClick={() => append({ firstName: "appendBill", lastName: "appendLuo" })}
      >
        append
      </button>
      <input type="submit" />
    </form>
  );
}
```

**Comment by bluebill1049** [comment] 2021-06-05 12:13
hmmm, looks like we used to take `defaultValues` over `defaultValue`... I will adjust that instead.

**Comment by simonedelmann** [comment] 2021-06-05 12:16
@bluebill1049 Thanks for your answer! I would strongly prefer `defaultValues` to override `defaultValue` also for controlled inputs. Otherwise it wouldn't be possible anymore to throw an existing object (e.g. from database) in `defaultValues` and have the whole form state correct. Also I would prefer controlled and uncontrolled inputs to behave as similar as possible. 
Is there maybe a way to add a flag for that?

**Comment by rpopovici** [comment] 2021-06-05 12:21
@bluebill1049 this behaviour is not documented at all(the fact that you need to leave the defaultValue undefined in the controlled component when using hooks) and I find it strange that it needs to be like that. there is no reason for it

@simonedelmann field level defaultValue should override form level defaults. it makes sense to be like this. local overrides global..

**Comment by bluebill1049** [comment] 2021-06-05 12:22
> @bluebill1049 this behaviour is not documented at all(the fact that you need to leave the defaultValue undefined in the controlled component when using hooks) and I find it strange that it needs to be like that. there is no reason for it
> 
> @simonedelmann field level defaultValue should override form level defaults. it makes sense to be like this. local overrides global..

relax and read my comment...

**Comment by bluebill1049** [comment] 2021-06-05 12:26
> @bluebill1049 this behaviour is not documented at all

perhaps it's time for you to help improve the documentation as well. now that this behavior is confirmed and going to be fixed.

**Comment by bluebill1049** [comment] 2021-06-05 12:27
<img width="942" alt="Screen Shot 2021-06-05 at 10 27 13 pm" src="https://user-images.githubusercontent.com/10513364/120891690-2f1ad080-c64d-11eb-8b69-5b9710f90ceb.png">

if everyone is busy, I will follow up on the doc update over the weekend too.

**Closed** 2021-06-05 13:06 UTC
Labels: bug

**Comment by simonedelmann** [comment] 2021-06-05 14:45
I've added a note about setting setting both defaultValue(s). Feel free to use/not use/modify/whatever you want!

**Comment by bluebill1049** [comment] 2021-06-05 22:32
> I've added a note about setting setting both defaultValue(s). Feel free to use/not use/modify/whatever you want!

Thank you @simonedelmann ❤️
