### ISSUE TITLE
useWatch within a nested useFieldArray removing a item just before another causes useWatch go out of sync

### ISSUE THREAD

**Issue by meman** [react-hook-form/react-hook-form#2516] opened 2020-08-07 11:50 UTC
**Describe the bug**
When using useWatch within a nested useFieldArray removing a item just before another causes useWatch go out of sync. For the item its assigned to it does not pick up the changes, however it seems to take those of the next added item.

**To Reproduce**

1. Create a form with a nested useFieldArray
2. Append 2 elements to list
3. Remove the first and type - noticing that the watched prop is not changing
4. Add a element and something in the second item - noticing that both the first and second items watch component seem to be updating

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-nested-arrays-t29u3?file=/src/nestedFieldArray.js

**Expected behavior**
useWatch returns the value of the index/item its assigned too

**Desktop (please complete the following information):**

OS: Mac (Mojave 10.14.6)
Browser: Chrome
Version: 84

**Comment by bluebill1049** [comment] 2020-08-07 12:25
for useFieldArray plz watch the entire array.

**Comment by meman** [comment] 2020-08-07 12:30
Which one? the root array or the nested one?

**Comment by bluebill1049** [comment] 2020-08-07 12:31
Depend on which level of field array, that you want to watch.

**Comment by meman** [comment] 2020-08-07 12:33
so i am looking to watch/use one of the nested values. 

so in this case i want only ```test[${nestIndex}].nestedArray[${k}]```

**Comment by bluebill1049** [comment] 2020-08-07 12:37
the parent would be the safe options because inputs get shuffle and swap position. they are not necessarily getting mount and unmounted, which is reason why if you watch particular input after a shuffle or delete, it will end up targetting on the wrong input with `watch`.

**Comment by meman** [comment] 2020-08-07 13:43
Question then if the parent can also me moved around then i might as well watch the whole tree right?

**Comment by bluebill1049** [comment] 2020-08-07 23:40
yes @meman

**Comment by bluebill1049** [comment] 2020-08-10 23:40
hey @meman just a quick follow up, is the above solution solves your problem?

**Comment by meman** [comment] 2020-08-11 10:19
Hey @bluebill1049, watching the top level array ie the root did help, however i am now battling over rendering. However that is nothing that using memo could not solve

**Comment by bluebill1049** [comment] 2020-08-11 10:23
can you at least isolate that re-render at a single component level with `useWatch`?

**Comment by meman** [comment] 2020-08-11 10:40
UseWatch did not working for me, so i had to use watch

**Comment by bluebill1049** [comment] 2020-08-11 10:42
can you share a codesandbox when `useWatch` not working? we can looking into it.

**Comment by bavicj** [comment] 2020-08-11 12:07
Guys I have similar problem. You can check the codesandbox here: 
[codesandbox](https://codesandbox.io/s/react-hook-form-v6-usewatch-ndv8l?file=/src/App.js)

Each item in array consist of two inputs - one is for entering amount, second is readonly, calculated from the first one.
On the bottom there is component displaying sum of items inputs.

To reproduce:
1. create 3 items and fill their inputs (10, 20, 30). readonly inputs will be calculated to 20, 40, 60
2. remove first item so you end up with inputs 20, 30
3. change last item from 30 to 40. You will see that it will update calculated input of previous item. 

It looks like the index that is used in useWatch is not updated correctly

**Comment by bluebill1049** [comment] 2020-08-11 12:29
Thanks @bavicj will take a look at it.

**Comment by bluebill1049** [comment] 2020-08-11 12:35
Try this @bavicj : https://codesandbox.io/s/react-hook-form-v6-usewatch-ndv8l?file=/src/App.js

**Comment by bavicj** [comment] 2020-08-11 13:00
@bluebill1049 that aint working, after remove of first element, the calculated input is not updated at all
<img width="453" alt="Screenshot 2020-08-11 at 15 00 30" src="https://user-images.githubusercontent.com/3510699/89900012-6f532300-dbe3-11ea-8ad7-b8c9ff6a8f6a.png">

**Comment by bluebill1049** [comment] 2020-08-11 13:02
send wrong link: https://codesandbox.io/s/react-hook-form-v6-usewatch-forked-0mfwr

**Comment by bavicj** [comment] 2020-08-11 13:13
@bluebill1049 still not working :-/
1. Initial state
<img width="439" alt="Screenshot 2020-08-11 at 15 12 01" src="https://user-images.githubusercontent.com/3510699/89901206-12586c80-dbe5-11ea-9fa2-9f9aab97c21d.png">
2. After delete of first item and changing 20 to 200, its calculated field is not recalculated
<img width="458" alt="Screenshot 2020-08-11 at 15 12 08" src="https://user-images.githubusercontent.com/3510699/89901241-1dab9800-dbe5-11ea-97e1-49fe518c4260.png">
3. After changing last item from 30 to 300, upper row items calculated field is recalculated
<img width="464" alt="Screenshot 2020-08-11 at 15 12 12" src="https://user-images.githubusercontent.com/3510699/89901350-43d13800-dbe5-11ea-80c2-26ce37d07e90.png">

**Comment by bluebill1049** [comment] 2020-08-11 13:18
I was looking at the sum value, can you take a look the console log, see if the value is watch correctly.

**Comment by bavicj** [comment] 2020-08-11 13:20
@bluebill1049 well sum value was working correctly from beginning. Problem is in the Item component, displaying of the useWatch property 'actualValue'

**Comment by bluebill1049** [comment] 2020-08-11 13:51
> @bluebill1049 well sum value was working correctly from beginning. Problem is in the Item component, displaying of the useWatch property 'actualValue'

 I think, for now, you will have to watch the entire `FieldArray` with `useWatch` (just as what I suggested above with @meman ) until I figure out how to make it watch properly with items shuffling.

**Comment by bluebill1049** [comment] 2020-08-12 08:37
`useWatch` has been improved: https://codesandbox.io/s/react-hook-form-v6-usewatch-forked-0mfwr?file=/src/App.js

**Comment by levrik** [comment] 2021-01-25 15:07
@bluebill1049 I'm currently trying to get this working properly like in the CodeSandbox posted by you above but `useWatch` is always a bit behind `fields` from `useFieldArray`. I can't get this reproduced in your sandbox even with the latest version of `react-hook-form`.

**Comment by bluebill1049** [comment] 2021-01-25 22:05
> @bluebill1049 I'm currently trying to get this working properly like in the CodeSandbox posted by you above but `useWatch` is always a bit behind `fields` from `useFieldArray`. I can't get this reproduced in your sandbox even with the latest version of `react-hook-form`. I'm just heavily confused right now.

share your not working example.

**Comment by levrik** [comment] 2021-01-26 08:55
@bluebill1049 sadly that's corporate code I can't share. what confuses me most, I've copied the code from your CodeSandbox above to the app. And suddenly the issue is happening. With the same code which is working fine in CodeSandbox. Version is the same, I've also nuked all caches and `node_modules` already.

**Comment by bluebill1049** [comment] 2021-01-26 08:57
> @bluebill1049 sadly that's corporate code I can't share. what confuses me most, I've copied the code from your CodeSandbox above to the app. And suddenly the issue is happening. With the same code which is working fine in CodeSandbox. Version is the same, I've also nuked all caches and `node_modules` already.

are you provided the `defaultValue` with what `useWatch` returned?

**Comment by levrik** [comment] 2021-01-26 09:00
@bluebill1049 no. I'm using the value from `fields` array like in the CodeSandbox. As said. I just copied the code from the codesandbox and it's not properly working when put into our app.

**Comment by bluebill1049** [comment] 2021-01-26 09:07
> @bluebill1049 no. I'm using the value from `fields` array like in the CodeSandbox. As said. I just copied the code from the codesandbox and it's not properly working when put into our app.

hmmm... running the same version?

**Comment by levrik** [comment] 2021-01-26 09:09
@bluebill1049 yes. checked once again. also made sure to upgrade the CodeSandbox to React 17 which we're using.
It's all on the same version now. I just don't get it 😕

**Comment by levrik** [comment] 2021-01-26 09:18
That's the new CodeSandbox which works correctly.
https://codesandbox.io/s/react-hook-form-v6-usewatch-forked-nmwfu?file=/src/App.js
Remove the middle item and you should see `Type` and `Totals` in the console.
In my local setup I'm seeing `Type` and `Number` instead.
Exact same code.

**Comment by levrik** [comment] 2021-01-26 09:38
So. It looks like it's falling back to `defaultValues` here.
But I'm still wondering why this isn't happening for CodeSandbox?

**Comment by levrik** [comment] 2021-01-26 10:27
@bluebill1049 Okay. I've just realized that the CodeSandbox was getting `react-hook-form` from `./src`.
I've changed in import now and now the issue reproduces. When switching back to `./src` it works fine.
This was based on the CodeSandbox posted by you in this thread (so looks like it was an outdated version).
To me it looks like some regression was introduced here?

**Comment by bluebill1049** [comment] 2021-01-26 10:50
Thanks for the investigation and figure this out!

For v6 there are limitation due to the overall design of useFieldArray, especially during the index shuffling, so I would suggest watching the entire field array to get an accurate result. This applies to `watch` API as well, I also checked the src folder in the example, the code is quite behind and it probably leads to other bugs.

https://codesandbox.io/s/react-hook-form-v6-usewatch-forked-e693u

**Comment by levrik** [comment] 2021-01-26 10:53
@bluebill1049 Yeah. I didn't realize that `./src` was used. Then I'll watch the entire array for now although this doesn't seem that ideal to me since this probably results in more re-renders than necessary.
Whatever. Is this something that could be fixed by v7? It sounds like `useFieldArray` is getting a new design there?

**Comment by bluebill1049** [comment] 2021-01-26 10:53
Here is some good news:

one of the major goals is to improve `useFieldArray` and looks like v7 is working great. 

https://codesandbox.io/s/react-hook-form-v6-usewatch-forked-x823p?file=/src/App.js

here is V7 above.

**Comment by bluebill1049** [comment] 2021-01-26 10:55
> @bluebill1049 Yeah. I didn't realize that `./src` was used. Then I'll watch the entire array for now although this doesn't seem that ideal to me since this probably results in more re-renders than necessary.
> Whatever. Is this something that could be fixed by v7? It sounds like `useFieldArray` is getting a new design there?

valid point and concern. I think these should get a proper solution in v7 now.

**Comment by levrik** [comment] 2021-01-26 11:01
@bluebill1049 also when I'm removing `defaultValue` from `useWatch` it seems to work fine in v7. That's great news.
Just curious: Is there a planned release date or date range for v7 already?
I'll apply the suggested workaround of watching the entire array for now and keep some note about updating this when v7 comes out.

**Comment by bluebill1049** [comment] 2021-01-26 11:18
> @bluebill1049 also when I'm removing `defaultValue` from `useWatch` it seems to work fine in v7. That's great news.
> Just curious: Is there a planned release date or date range for v7 already?
> I'll apply the suggested workaround of watching the entire array for now and keep some note about updating this when v7 comes out.

let me try to do something around v6 (see if I can get around this issue) I think we will go into `beta` soon, but the documentation is going to take us sometimes. I don't think we will have much breaking change once we go into `beta` tho.

**Comment by bluebill1049** [comment] 2021-01-26 11:26
looks like it's safer to `watch` or `useWatch` the field array root name in v6. 
eg `test` FieldArray or `test[0].test` NestedFieldArray

**Comment by levrik** [comment] 2021-01-26 12:05
@bluebill1049 thanks a lot for the answers!

**Comment by bluebill1049** [comment] 2021-01-26 12:09
> @bluebill1049 thanks a lot for the answers!

Thank you too for your patient and investigation.

**Comment by levrik** [comment] 2021-01-26 12:40
@bluebill1049 I've just tried watching the entire array root but this comes with a huge performance degradation when typing into text fields part of these array items. I've now came up with kinda an ugly workaround. `useWatch` works in most scenarios. To work around the wrong value in case of array index shifting, I'm now pushing the result of `useWatch` to a `useMemo` which actually calls `getValues` whenever that value changes. `getValues` actually returns the correct value here. This way I'm using the more granular change detection of `useWatch` by making sure to get the right values into my component. It's kinda ugly but it seems to work for now.

**Comment by bluebill1049** [comment] 2021-01-26 21:49
let me take another look at this.

**Comment by bluebill1049** [comment] 2021-01-26 22:53
I think I may have found a workaround: https://codesandbox.io/s/react-hook-form-v6-usewatch-forked-e693u

**Closed** 2021-01-27 02:07 UTC
Labels: enhancement

**Comment by levrik** [comment] 2021-01-27 08:12
@bluebill1049 the CodeSandbox seems to be broken 😅 But thanks a lot! I'll give it a try as soon as it's released.

**Comment by bluebill1049** [comment] 2021-01-27 08:18
> @bluebill1049 the CodeSandbox seems to be broken 😅 But thanks a lot! I'll give it a try as soon as it's released.

<img width="1350" alt="Screen Shot 2021-01-27 at 7 18 07 pm" src="https://user-images.githubusercontent.com/10513364/105962852-66440880-60d4-11eb-9660-883f25e997fc.png">
works for me. can you double check with your cache?

**Comment by levrik** [comment] 2021-01-27 08:22
@bluebill1049 
![image](https://user-images.githubusercontent.com/9491603/105963308-27389780-6081-11eb-8712-25b759bfc42c.png)
This comes up immediately. Also created a fork of the CodeSandbox. Has the same issue.

**Comment by bluebill1049** [comment] 2021-01-27 08:25
> @bluebill1049
> ![image](https://user-images.githubusercontent.com/9491603/105963308-27389780-6081-11eb-8712-25b759bfc42c.png)
> This comes up immediately. Also created a fork of the CodeSandbox. Has the same issue. Also cleared browser cache.

try again in incognito?

**Comment by abdulmateentechbits** [comment] 2022-10-10 08:20
Hi !
I want if user select number of field in select box for example user select only 3 there were 3 dynamic field will be open after it if he fill only first one rest of them have same default value according to first one
here is my code sandbox 
https://codesandbox.io/s/react-hook-form-forked-to7c34?file=/src/App.js
