### ISSUE TITLE
issue: reset with fieldArray does not work correctly in a certain scenario

### ISSUE THREAD

**Issue by quicksnap** [react-hook-form/react-hook-form#8758] opened 2022-07-28 21:21 UTC
### Version Number

7.33.1

### Codesandbox/Expo snack

https://codesandbox.io/s/async-violet-tvqg3p

### Steps to reproduce

1. Open sandbox console.
2. Click "Submit"

or:

1. Change the "catch phrase" value
2. click "submit"

### Expected behaviour

The form should reset with the values returned by the "server". Instead, it will revert to the original form's default value ONLY for the field array. 

The documentation encourages using `reset` within `useEffect`. However, sometimes using `useEffect` is very inconvenient.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quicksnap** [comment] 2022-07-28 21:22
Noted in the sandbox: the use case here is resetting after submission with values returned by the server.

**Comment by quicksnap** [comment] 2022-07-28 21:32
A workaround is to deep clone the value and call `reset` twice: https://codesandbox.io/s/exciting-pond-ytsr5q?file=/src/App.tsx:1834-1898

**Comment by Moshyfawn** [comment] 2022-07-28 22:28
A note: this happens only in case
```jsx
<Controller shouldUnregister />
```

### If you:
1. Submit the form
2. Fire the HMR _(ex. add an empty `console.log` somewhere in the form component)_
### You can see:
The `fields` value is `[undefined]`

**Comment by bluebill1049** [comment] 2022-07-28 22:47
`shouldUnreigster: true` will mutate the defaultValues, something maybe worth to remove in the next major version

<img width="956" alt="Screen Shot 2022-07-29 at 8 47 01 am" src="https://user-images.githubusercontent.com/10513364/181649859-590f32ea-30a1-4601-8cd5-0571728351e5.png">

I would always refer to the call unregister manual, as your use case gets complicated.

**Comment by Moshyfawn** [comment] 2022-07-28 22:53
Wait, but why the input's removed, tho?

**Comment by quicksnap** [comment] 2022-07-28 22:58
I also am confused why this would unregister in this case.

**Comment by bluebill1049** [comment] 2022-07-28 22:58
> Wait, but why the input's been removed, tho?

What do you mean?

**Comment by Moshyfawn** [comment] 2022-07-28 22:59
K, so, how about that: the issue is only present in environment:
- React version is lower than 18.0.0

[Example csb](https://codesandbox.io/s/relaxed-haslett-ql3puw?file=%2Fsrc%2FApp.tsx)

In case of:
- React version >= 18

[Example csb](https://codesandbox.io/s/magical-keller-cj7lf4?file=%2Fsrc%2Findex.tsx)

**Comment by quicksnap** [comment] 2022-07-28 22:59
@bluebill1049 in my example sandbox, why would the unregister logic trigger? It's not being unmounted.

**Comment by bluebill1049** [comment] 2022-07-28 23:00
> I also am confused why this would unregister in this case.

reset does remove all input references, which will need to get all inputs re-register again which will re-run `useEffect` and this all complicates thing on determined if input is "really" unmounted, so this is consider a design flaw.

**Comment by Moshyfawn** [comment] 2022-07-28 23:00
> > Wait, but why the input's been removed, tho?
> 
> What do you mean?

The behavior is only present if `shouldUnregister` is set on `Controller`, but there's no logic that dictates to ever remove the input from the DOM, so the unregister logic should ever fire and potentially mutate the form value

**Comment by quicksnap** [comment] 2022-07-28 23:01
Ah, I see. Do you think this is something that can be improved in the current version? I may be able to help on that.

**Comment by bluebill1049** [comment] 2022-07-28 23:02
@quicksnap I would love to remove that mutate `defaultValues` behavior, I am worried about breaking change 😢 but I think it's definitely a trap for many use cases when users turn it on. Unless we can proof this is bug and need to be fixed.

**Comment by quicksnap** [comment] 2022-07-28 23:03
What determines if this is a bug or not? The behavior seems wrong to me.

**Comment by bluebill1049** [comment] 2022-07-28 23:04
Maybe we should fix it and leave a note in the next minor version on the potential breaking change, so at least users will be aware and know the work around.

**Comment by quicksnap** [comment] 2022-07-28 23:09
Given that there's a workaround (calling reset twice), it could also be deferred to next major version?

**Comment by Moshyfawn** [comment] 2022-07-28 23:12
I've never encountered the behavior. so it's a first for me; maybe because I've switched to React 18, but I'm still confused how React version helps avoid the issue all together lol

Considering, the behavior differs from one React version to the another, I'd consider it a bug, since it's quite unpredictable. As a bug, I'd close it in v7, provided it doesn't completely ruing some v8 feature. Again, it's the first time I'm noticing `reset` actually removes input refs _(yes, I'm a maintainer and I read the code, but I'm inattentive, what of it lol)_.

Now, that said, I haven't even thought about the potential solution. Like, what would be the change and how can it become a potential breaking change. I'd need more time to think about it, sadly

**Comment by bluebill1049** [comment] 2022-07-28 23:23
Thanks, guys, I will get a PR up for the fix over the weekend anyhow, we can take our time on publishing the fix.

**Comment by bluebill1049** [comment] 2022-07-29 22:41
Did a closer look at the issue, we may have to bite the bullet here, as the change may affect `shouldUnregister` at the `useForm` level as well unless we remove unController and register self shouldUnreigster, which is a breaking change for sure... I will mark it as design limation and leave a note in the doc. 🙏

**Closed** 2022-07-29 22:56 UTC
Labels: bug, design limitation
