### ISSUE TITLE
Previously registered field keep validating after unregister

### ISSUE THREAD

**Issue by gabriellemos** [react-hook-form/react-hook-form#4993] opened 2021-04-28 14:27 UTC
**Describe the bug**
I'm having some issues where after unregistering a field and keeping its current value, my form won't submit since all fields are validated when attempting to submit it.

**To Reproduce**

1. Click on 'unregister lastName'
2. Click on 'submit'
3. See error

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-unregister-v6-forked-omllu?file=/src/index.js

**Current behavior**
Even thought lastName was unregistered, form isn't submitted since lastName has invalid values (was registered previously with required: true).

**Expected behavior**
Form should be submited with: _{ firstName: "", lastName: "" }_

**Desktop:**

- OS: Ubuntu 20.04.2 LTS
- Browser Firefox 88.0 (64-bit)

**Additional context**
When unregistering a field, shouldn't its validators be removed? Or am I doing something wrong here? Thanks in advance!

**Comment by bluebill1049** [comment] 2021-04-28 22:36
if you are keeping the `value` then the validation will get kicked in, I suggest you to use `validate` function and skip with validation with a certain condition.

**Comment by domasx2** [comment] 2021-04-29 06:55
Struggling with this as well. I have  scenario where some fields apepar or disapper based on value of a another field.
Fields that are no longer in the form are still getting validated, preventing the submit.   Seem to be no way to configure `register()` or `Control` to unset the value on unmount?

**Comment by bluebill1049** [comment] 2021-04-29 07:43
> Struggling with this as well. I have scenario where some fields apepar or disapper based on value of a another field.
> Fields that are no longer in the form are still getting validated, preventing the submit. Seem to be no way to configure `register()` or `Control` to unset the value on unmount?

That's a different case than what @gabriellemos is reported, skip validating unmounted input will be addressed with this feature PR: https://github.com/react-hook-form/react-hook-form/pull/4785

**Comment by domasx2** [comment] 2021-04-29 10:42
> > Struggling with this as well. I have scenario where some fields apepar or disapper based on value of a another field.
> > Fields that are no longer in the form are still getting validated, preventing the submit. Seem to be no way to configure `register()` or `Control` to unset the value on unmount?
> 
> That's a different case than what @gabriellemos is reported, skip validating unmounted input will be addressed with this feature PR: #4785

Ok thanks, working around by wrapping inputs in another component that explicitly invokes `unregister` on unmount

**Comment by bluebill1049** [comment] 2021-04-29 10:44
> > > Struggling with this as well. I have scenario where some fields apepar or disapper based on value of a another field.
> > > Fields that are no longer in the form are still getting validated, preventing the submit. Seem to be no way to configure `register()` or `Control` to unset the value on unmount?
> > 
> > 
> > That's a different case than what @gabriellemos is reported, skip validating unmounted input will be addressed with this feature PR: #4785
> 
> Ok thanks, working around by wrapping inputs in another component that explicitly invokes `unregister` on unmount

you can use `shouldUnregister` option, I think it will achieve the same.

**Comment by gabriellemos** [comment] 2021-04-29 12:18
> 
> 
> if you are keeping the `value` then the validation will get kicked in, I suggest you to use `validate` function and skip with validation with a certain condition.

It is reasonable to mark this as a bug? Seens logic to me that when unregistering a field, its validator should be removed as well. Is that any way to remove those valitors manualy or my only option is to implement a custom validator with that condition?

Implementing a custom validator with a certain condition wouldn't be an ideal solution since one of our goal using this lib is so we don't have to implement validations like required/min/max/etc. I'll take some time implementing another example at codesandbox to explain better my issue.

**Comment by bluebill1049** [comment] 2021-04-29 12:30
Nope, like I stated above it's not a bug. If u want to keep value it will be validated, if u are going to unmount the input then the feature PR will prevent it been validated, and I think that's one of the solution you are after. Other than that I am closing this issue.

**Closed by bluebill1049** 2021-04-29 12:30 UTC
Labels: question

**Comment by bluebill1049** [comment] 2021-04-29 12:31
For everyone's refeneece #4785 will be merged and release after more testings.

**Comment by gabriellemos** [comment] 2021-04-29 12:37
> 
> 
> Nope, like I stated above it's not a bug. If u want to keep value it will be validated, if u are going to unmount the input then the feature PR will prevent it been validated, and I think that's one of the solution you are after. Other than that I am closing this issue.

yes, that's the solution i'm looking for. Thanks!
