### ISSUE TITLE
Feature Request: Have conditionally required fields

### ISSUE THREAD

**Issue by krnlde** [react-hook-form/react-hook-form#1029] opened 2020-02-13 16:53 UTC
**Is your feature request related to a problem? Please describe.**
I need a field that is always registered, but only under some circumstances required.

**Describe the solution you'd like**
I'd love to have the `register` method check the `required` (and for that matter, every property that can be passed in there) for changes and handle them accordingly.

This would look something like this:

```tsx
const useShippingAddress = watch('use_shipping_address');

// ... some code later

<FormField
  type="checkbox"
  label="I'd like to use a differing shipping address"
  name="use_shipping_address"
  innerRef={register}
/>

<FormField
  type="text"
  label="First name"
  name="shipping_firstname"
  autoComplete="shipping given-name"
  innerRef={register({ required: useShippingAddress })} // <------ This is my request
/>
```

**Additional context**
Right now the change in the `required` property is only recognized when I trigger a revalidation.

Thoughts?

**Comment by bluebill1049** [comment] 2020-02-13 21:03
hey, @krnlde hows going? I think this could just work fine with `validate` function?

**Comment by krnlde** [comment] 2020-02-13 21:22
Hey man! I'm great, thanks for asking :) hope you're doing well too?

The problem is not the validation itself. But if I change the `use_shipping_method` in the example above, the `shipping_firstname` will not be required immediately. Only after submitting. I think I need to produce a codesandbox to clarify the problem :) will do tomorrow

**Comment by krnlde** [comment] 2020-02-14 09:58
Alright, I got the codesandbox:

https://codesandbox.io/s/gracious-raman-r8oq6

To reproduce:
1. See that the form is initially valid in the debug output
2. activate the "Use shipping address" checkbox
3. See that the form is still valid, despite the fact that the firstname field is empty and required when the checkbox is checked.
4. After entering and deleting something in the firstname field it'll show `isValid: false` correctly. Also if you hit Revalidate it'll update the isValid correctly

What I expected was, that after I checked the checkbox the form becomes invalid because its dependent inputs are now required.

**Comment by krnlde** [comment] 2020-02-14 10:02
Aaah, I think I got what you meant with `validate`. I tried that too, but it doesn't work either. Should I create a second codesandbox for that case?

**Comment by bluebill1049** [comment] 2020-02-14 11:14
thanks for the detailed demo and steps to reproduce,  have you considered `triggerValidation`?

**Comment by krnlde** [comment] 2020-02-14 11:16
`triggerValidation` is done when I click the Revalidate button. But I expected it to just work, and not have an asynchronous state until something else changes :D Am I thinking in the wrong direction here?

**Comment by bluebill1049** [comment] 2020-02-14 11:19
I meant when you check on the following step

activate the "Use shipping address" checkbox then trigger the other field's validation to update the isValid. 

Is that what you refer to, or maybe I need to read your demo more carefully.

**Comment by krnlde** [comment] 2020-02-14 11:21
But after I checked the checkbox, the `required` field already gets the value `true`. The problem is, it is not reflected immediately in the `isValid`, only after triggerValidation or changing some state.

**Comment by bluebill1049** [comment] 2020-02-14 11:25
Oh, I see your problem better now, it's almost due to missing an extra re-render. I am in the middle of fixing a bug, I will take a closer with this issue tmr morning 👍

**Comment by krnlde** [comment] 2020-02-14 11:26
So it's a valid bug? Wuhuu :D Didn't expect that.

💯

**Comment by bluebill1049** [comment] 2020-02-14 11:27
I wouldn't confirm it's a bug (or perhaps I can find an alternative solution), let me confirm with you tmr.

**Comment by bluebill1049** [comment] 2020-02-14 12:51
before I go to bed, did a quick test with this: https://codesandbox.io/s/peaceful-river-b660l

**Comment by bluebill1049** [comment] 2020-02-16 23:11
Hey @krnlde just a quick follow up on this issue, did you take a look the example above?

**Comment by bluebill1049** [comment] 2020-02-17 22:22
Going to close this issue for now to keep board clean, feel free to leave more questions if this is not solving ur problem.

**Closed by bluebill1049** 2020-02-17 22:22 UTC
Labels: question

**Comment by krnlde** [comment] 2020-02-18 09:26
Ah sorry, I didn't see that! The workaround with the manual `triggerValidation` at least works, though I don't find it really necessary. I can live with that :) Thank you

**Comment by bluebill1049** [comment] 2020-02-18 09:37
awesome thanks for the update @krnlde
