### ISSUE TITLE
Question about initial values

### ISSUE THREAD

**Issue by dimaqq** [react-hook-form/react-hook-form#721] opened 2019-12-27 04:16 UTC
There's a complex edit form in my project, where I expect my user to edit only a few fields.
When form is submitted I only send the delta (fields changed by the user) to the server.

Current implementation uses `redux-form` and `initialValues` as a prop, that is, the UI polls the server and if some fields were changed (e.g. by another user) and were not touched (by this user), then they are updated in the form and the form knows that these changes were not user input.

Is this something that `react-hook-form` can do?
Is it something that user code should do instead?
What kind of API should be used?

If I'm just blind and the docs have this kind of use case, please accept my apology 🙏

**Comment by bluebill1049** [comment] 2019-12-27 04:23
- if your default values is ready at the render, then you can use `defaultValues`
- if data come from server, then you can use `reset(values)`

**Comment by dimaqq** [comment] 2019-12-27 04:41
`reset` doc says "resets values and errors". 
In my case, I'd want to reset only some values, keep other values and keep the errors... 
So, perhaps this is not it 🤔 

I'll poke `defaultValues` via props and see what that can do...

**Comment by bluebill1049** [comment] 2019-12-27 04:57
you can also use `setValue` if that's the case

**Comment by bluebill1049** [comment] 2019-12-27 08:32
closing this, feel free to ask more questions at our spectrum channel :)

**Closed by bluebill1049** 2019-12-27 08:32 UTC
Labels: question

**Comment by cargallo** [comment] 2019-12-27 16:29
I having similar issue. I'm using react-async. The problem is that useForm doesn't allow using it inside conditional rendering. So I tried using reset but it forces innecesary re-render. I think it could be an exported function called setDefaultValues allowing setting the defaultValues after useForm call, but not forcing a re-render like reset. Not sure if that's possible

```JSX
const defaultValues = {
    name: "",
    email: ""
};

const methods = useForm({ defaultValues: defaultValues, validationSchema: validationSchema });
const { errors, register, watch, handleSubmit, getValues, setValue, reset } = methods;

const { data, error, isLoading } = useAsync({
    promiseFn: loadData,
    id
  })
  if (isLoading) {
    return (
      <Box style={{ display: 'flex', flexGrow: 1, justifyContent: 'center', padding: '3rem', }} >
        <CircularProgress color="secondary" />
      </Box >
    );
  }
  if (error) {
    return <React.Fragment>Hubo un error al recuperar los datos: {error.message}</React.Fragment>
  }
  if (data) {
     .......
  }
```

**Comment by bluebill1049** [comment] 2019-12-27 21:42
@cargallo you can use setValue right?

**Comment by cargallo** [comment] 2019-12-28 16:38
What I finally did was passing register and reset functions to loadData and calling them inside that function after fetching data but before the first rendering of if (data)... BTW I don't love this solution.

![image](https://user-images.githubusercontent.com/13320290/71546514-5197bd00-2976-11ea-8a17-881398be8a3f.png)

![image](https://user-images.githubusercontent.com/13320290/71546569-0d58ec80-2977-11ea-8a89-ce33d44ddabb.png)

**Comment by ccnokes** [comment] 2020-04-02 02:37
(Sorry to weigh in on an old issue but I just ran into this)

I guess the way this behaves now makes sense because that's how React handles it with `input` and `defaultValue`. See https://codesandbox.io/s/async-defaultvalue-uv9no. If you set `defaultValue` to some string to start with, then change it later, it does not update the value of the input. If it's null, then it will. Considering that's how react handles it, I think it makes sense for `react-hook-form` to stay consistent with that. I'll have to try out using `reset`.

**Comment by bluebill1049** [comment] 2020-04-02 02:41
or @ccnokes `setValue` https://react-hook-form.com/api#setValue

**Comment by bluebill1049** [comment] 2020-04-02 02:42
by the way the new reset function allow you to omit reset formState include errors
