### ISSUE TITLE
useFormContext is triggering updates in useEffect

### ISSUE THREAD

**Issue by stramel** [react-hook-form/react-hook-form#324] opened 2019-09-20 20:01 UTC
**Describe the bug**
When using methods coming from `useFormContext` with `useEffect`, it is causing updates.

**To Reproduce**
Console will log hit on each update
https://codesandbox.io/embed/react-hook-form-form-context-ki90u

**Expected behavior**
Should not trigger a re-render

I believe that it is just the accumulation of the props causing a new value each time.

**Comment by bluebill1049** [comment] 2019-09-20 22:03
@stramel the problem is because of this line:

`onChange={e => setValue(e.currentTarget.value)}`

**Comment by stramel** [comment] 2019-09-20 22:07
@bluebill1049 This is just something I threw together to demonstrate the point. You can drop that entire prop and it still happens on the other input.

**Comment by stramel** [comment] 2019-09-20 22:13
Also, since the `useEffect` is specifying the dependencies. Updates to anything other than those dependencies should NOT trigger the update inside the `useEffect`. It currently is.

**Comment by bluebill1049** [comment] 2019-09-20 22:17
I think FormContext API may need a redesign, the current pattern does have a performance issue because when u calling setValue it will trigger re-render which is at the root level.

<FormContext /> should have `useForm` baked inside.

**Comment by bluebill1049** [comment] 2019-09-20 22:29
ok @stramel what about this? i think this issue can be resolved by React.memo, but probably need good documentation to help. i think the api is simple and nice, it's the trigger re-render which sucks. let me put a codesandbox to show you what i mean

**Comment by bluebill1049** [comment] 2019-09-20 22:39
@stramel i think this will help
```
return React.useMemo(
    () => (
      <FormGlobalContext.Provider value={rest as FormContextValues}>
        {children}
      </FormGlobalContext.Provider>
    ),
    []
  );

**Comment by bluebill1049** [comment] 2019-09-20 22:40
going to release a beta version for it

**Comment by bluebill1049** [comment] 2019-09-20 22:41
`3.23.11-beta.1`

**Comment by bluebill1049** [comment] 2019-09-20 22:43
nice~ I tested looks like it's working for me

**Comment by bluebill1049** [comment] 2019-09-20 22:43
let me know on your end, we can release this quick patch

**Comment by bluebill1049** [comment] 2019-09-23 02:10
Should have been fixed in the latest patch

**Closed by bluebill1049** 2019-09-23 02:10 UTC
Labels: question

**Comment by stramel** [comment] 2019-09-23 13:48
@bluebill1049 Sorry, I didn't have a chance to look at this over the weekend. I'm unsure about using the hook `useMemo` in that way. If it works, we can keep it until we can come up with a better way to resolve it.
