### ISSUE TITLE
Controller rules referencing scoped values become stale

### ISSUE THREAD

**Issue by jordrake** [react-hook-form/react-hook-form#851] opened 2020-01-16 15:50 UTC
**Describe the bug**
It seems that Controller 'rules' object is being kept in the initial state that they were set to on first render, including any scoped reference values. We have dynamic rules based on external factors that this bug breaks. I am currently bypassing this issue by setting a composite 'key' prop on the Controller component of all values used within the 'rules' object. 

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-basic-validation-uxx2m

**To Reproduce**
1. Go to codesandbox link
2. Use the button to make the required rule false
3. Press submit
4. Observe that the required rule is being enforced

**Expected behavior**
I would expect rules to update alongside the component. In the above example I would expect there to be no errors when the required rule is set to false.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version 73

**Comment by bluebill1049** [comment] 2020-01-16 20:37
That's actually by design unless we have a better solution for this. `rules` is an object with `useEffect` as a dependency so it will keep getting invoked which is not ideal for performance as it keep registering. maybe build a switch statement for your controller components.

**Comment by bluebill1049** [comment] 2020-01-16 20:52
or perhaps you can use `unregister` API?

**Comment by jordrake** [comment] 2020-01-17 10:35
I think I understand what you mean. You'd have move the responsibility to the user to ensure that `rules` is identity equal (probably via useMemo) if you wanted to put rules in the useEffect dependency here: https://github.com/react-hook-form/react-hook-form/blob/master/src/controller.tsx#L116. This wouldn't be the most obvious interface so I appreciate why you've done it the way you have. I'll have a think to see if I can come up with any solution that solves this issue without impacting the interface.

**Comment by bluebill1049** [comment] 2020-01-17 10:42
> I think I understand what you mean. You'd have move the responsibility to the user to ensure that `rules` is identity equal (probably via useMemo) if you wanted to put rules in the useEffect dependency here: https://github.com/react-hook-form/react-hook-form/blob/master/src/controller.tsx#L116. This wouldn't be the most obvious interface so I appreciate why you've done it the way you have. I'll have a think to see if I can come up with any solution that solves this issue without impacting the interface.

Yea, that's correct. As a library maintainer is always important to stand on users' perspective if I can reduce the amount of complexity, I would prefer to go that route and take the tradeoff. Maybe consider using `unregister` tho.

**Comment by jordrake** [comment] 2020-01-17 13:09
> Maybe consider using `unregister` in your use case tho.

I'm not entirely sure how unregister would solve my issue as the input in question can be re-enabled at any point but I may be misunderstanding the api.

The full problem I'm trying to solve is actually two inputs with the value of one conditionally enabling the other, and if it is enabled then it is required.

See: https://codesandbox.io/s/react-hook-form-basic-validation-u3u0t

Perhaps I'm missing an obvious solution that you may be able to provide. Thank you regardless :)

**Comment by bluebill1049** [comment] 2020-01-17 13:46
oh. why don't u use `validate` function with `getValues()`. you can read the other field value right?

**Comment by JeromeDeLeon** [comment] 2020-01-18 00:42
Why not use `validationSchema`?

**Comment by kotarella1110** [comment] 2020-01-18 16:12
```ts
<Controller
  control={control}
  as={Select}
  name="second"
  disabled={secondDisabled}
  rules={{
    validate: value => {
      const { first } = getValues();
      if (first === "foo") {
        return true;
      }
      if (value === "") {
        return false;
      }
    }
  }}
>
```

**Comment by bluebill1049** [comment] 2020-01-19 07:01
let us know if those answers above are possible alternatives :)

**Comment by bluebill1049** [comment] 2020-01-20 02:11
I am going to close this issue as there are few alternative suggestions above, feel free to ask more questions on this issue tho. We are happy to find solution for you :)

**Closed by bluebill1049** 2020-01-20 02:11 UTC
Labels: question

**Comment by Eviwang** [comment] 2020-05-29 02:21
I want to keep it that way.because the code looks more straightforward. https://codesandbox.io/s/react-hook-form-basic-validation-u3u0t
```
<Controller
          control={control}
          as={Select}
          name="second"
          disabled={secondDisabled}
          rules={{
            required: !secondDisabled  // here.
          }}
        >
          <Select.Option value="hello">Hello</Select.Option>
          <Select.Option value="world">World</Select.Option>
        </Controller>
```

Are there any other solutions?

**Comment by bluebill1049** [comment] 2020-05-29 02:23
@Eviwang use `validate` should solve this issue.

**Comment by Eviwang** [comment] 2020-05-29 02:45
Thank you for the response.

validate has closure problems:
https://codesandbox.io/s/react-hook-form-basic-validation-in3zl?file=/src/index.js

**Comment by bluebill1049** [comment] 2020-05-29 02:49
> Thank you for the response.
> 
> validate has closure problems:
> https://codesandbox.io/s/react-hook-form-basic-validation-in3zl?file=/src/index.js

This is a different CSB now. this is the case where you want to `unregister` at `useEffect`.

1. if drive-by state then just use `unregsiter` at useEffect
2. if drive-by user input, you can use validate combined with `getValues()`

the reason why we cache rules because otherwise, users will have to cache or memo the rules object, without will lead to register controller each render which is not what we want.
