### ISSUE TITLE
Custom validations on multi select not getting Array

### ISSUE THREAD

**Issue by bostrom** [react-hook-form/react-hook-form#248] opened 2019-08-23 12:34 UTC
I'm trying to validate a "select multiple" input using a custom validation in the register callback like so

```
        <select
          name="multiSelect"
          multiple
          ref={register({
            validate: value => Array.isArray(value) && value.length > 1
          })}
        >
          <option value="opt1">Option 1</option>
          <option value="opt2">Option 2</option>
          <option value="opt3">Option 3</option>
          <option value="opt4">Option 4</option>
        </select>
```

However, the `value` passed to the validator function is always a String, the value of which is the topmost selected `option`.

Codesandbox available here https://codesandbox.io/embed/react-hook-form-1m47u

Is this a bug, or am I doing something wrong?

**Comment by bluebill1049** [comment] 2019-08-23 12:42
Thanks for the detailed issue report, verified and it's a bug. I will patch it soon.

**Comment by bluebill1049** [comment] 2019-08-24 02:02
Thanks. this have been fixed: https://codesandbox.io/s/react-hook-form-qefbn

here is the beta version: 3.22.2-beta.7

**Comment by bluebill1049** [comment] 2019-08-24 02:06
This patch should be released soon :) if there is no other issue found

**Comment by bostrom** [comment] 2019-08-26 08:20
Wow, that was fast! 💪 

Thanks!

**Comment by bluebill1049** [comment] 2019-08-26 08:23
Thanks releasing tonight 🤗

**Comment by bluebill1049** [comment] 2019-08-26 09:32
the patch has been released, please close this issue if works fine :)

**Closed** 2019-08-27 13:01 UTC
Labels: bug

**Comment by sandroweb** [comment] 2020-07-07 18:15
> Thanks. this have been fixed: https://codesandbox.io/s/react-hook-form-qefbn
> 
> here is the beta version: 3.22.2-beta.7

Yout CodeSandbox is not exists. 404 error

**Comment by bluebill1049** [comment] 2020-07-07 23:21
@sandroweb what's the issue? the problem is resolved, CSB was limited at the time, so i only had 50 before to manage.

**Comment by sandroweb** [comment] 2020-07-08 18:50
> @sandroweb what's the issue? the problem is resolved, CSB was limited at the time, so i only had 50 before to manage.

I asked yesterday because the solution was not clear for me, but I solve. Thank you!
