### ISSUE TITLE
Controller wrapped component does not update validation rules

### ISSUE THREAD

**Issue by LookRain** [react-hook-form/react-hook-form#1576] opened 2020-05-06 06:43 UTC
**Describe the bug**
Native HTML elements work perfectly with dynamic validation rules (e.g. an input is required under mode A but not required under mode B), however when working with 3rd party libraries and Controller component, the rules do not get updated, it keeps using the original rule supplied to it for validation.

**To Reproduce**
1. Wrap a component library's Input element with `<Controller />`
2. Give it a rule that depends on a boolean state, when state is true, set rule to required, vice versa
3. toggle the boolean state, the validation is not updated(`clearError` wouldn't clear the existing error either)

**Codesandbox link (Required)**
- works ok with native form elements: https://codesandbox.io/s/react-hook-form-get-started-4ywl5?file=/src/index.js:758-884
- **Not** working with Controller component: https://codesandbox.io/s/react-hook-form-custom-input-c9uoz?file=/src/index.js

**Expected behavior**
After updating the validation rule, it should validate with the latest rule instead of the old one.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.15
 - Browser Chrome 81
 - Version React-hook-form 5.5.1

**Comment by bluebill1049** [comment] 2020-05-06 07:05
OK this is expected behaviour for Controller and decision was made from DX's perspective.
`rules` is part of dep for register method inside Controller, and we are caching the rules so users won't have to do the memo.

eg:
without us to cache
`const rules = React.useMemo(() => rules, [])`;

```
<Controller rules={rules} />
```

option 1: https://codesandbox.io/s/gracious-payne-nqphl?file=/src/App.js
option 2: https://codesandbox.io/s/fancy-thunder-dpw1z?file=/src/App.js

**Comment by bluebill1049** [comment] 2020-05-06 07:08
you can read more on this thread as well: https://spectrum.chat/react-hook-form/help/how-to-skip-validation-rules-for-disabled-inputs-using-controller~5b524542-f085-4240-920f-dc893b20aec9

**Comment by LookRain** [comment] 2020-05-06 07:37
I see the reason why rules are cached inside Controller.

However, I have a pretty complex form that needs to use different validation rules for all fields in different modes. Is there any easy way to achieve this?

Thanks!

**Comment by bluebill1049** [comment] 2020-05-06 07:40
is `validate` function helps you? otherwise may be worth using schema for validation.

**Comment by bluebill1049** [comment] 2020-05-06 07:42
did you take a look those two examples? are they helpful?

**Comment by LookRain** [comment] 2020-05-06 08:13
> did you take a look those two examples? are they helpful?

Yes I checked out the 2 examples you gave. The first one doesn't seem to be working, the form never validates even it is enabled.

I tried with using `unregister` on mode change in my form, it worked. However, I need to literally `unregister` every form item, which feels quite hacky to me...

**Comment by bluebill1049** [comment] 2020-05-06 08:16
The first example was actually about the validate function:

```
validate: value => {
  console.log("Enabled:", getValues("check")); // so you can still read other form input's value
  if (!enabled) {
    return true;
  }
  return value !== "Hello" || 'Input cannot be "Hello"';
}
```

**Comment by LookRain** [comment] 2020-05-06 08:20
> The first example was actually about the validate function:
> 
> ```
> validate: value => {
>   console.log("Enabled:", getValues("check")); // so you can still read other form input's value
>   if (!enabled) {
>     return true;
>   }
>   return value !== "Hello" || 'Input cannot be "Hello"';
> }
> ```
The first example doesn't seem to be working, it never validate
![May-06-2020 16-20-06](https://user-images.githubusercontent.com/11829847/81153421-7d2a5400-8fb5-11ea-8658-7fff7dfa3cd6.gif)

**Comment by bluebill1049** [comment] 2020-05-06 08:24
https://codesandbox.io/s/gracious-payne-nqphl?file=/src/App.js

**Comment by LookRain** [comment] 2020-05-06 09:05
> https://codesandbox.io/s/gracious-payne-nqphl?file=/src/App.js

so that means I need to write every rule as a `validate` function, and won't be able to use rules like `required` `max`, etc?

**Comment by bluebill1049** [comment] 2020-05-06 09:19
Yes, if your validation logic is dynamic or you can look into schema validation.

**Comment by LookRain** [comment] 2020-05-06 09:22
> Yes, if your validation logic is dynamic or you can look into schema validation.

Thanks so much for the replies so far! I'll checkout schema based validation :)

**Comment by bluebill1049** [comment] 2020-05-06 09:39
worth to take a look this one as well: https://react-hook-form.com/api#validationResolver

**Comment by bluebill1049** [comment] 2020-05-06 23:39
I am going to close this issue as it's expected behavior, feel free to follow up with more questions tho.

**Closed by bluebill1049** 2020-05-06 23:39 UTC
Labels: question

**Comment by marensas** [comment] 2020-05-29 08:36
![image](https://user-images.githubusercontent.com/18376464/83239024-e873da00-a19f-11ea-8b9f-12d3e4036d60.png)

@bluebill1049  The second example is using unregister() method, which is not the case in my situatino. I need to have it registered in the form + I don't need a required rule, because requiredMode changed to false. How can I avoid caching in this situation?

**Comment by bluebill1049** [comment] 2020-05-29 08:46
> ![image](https://user-images.githubusercontent.com/18376464/83239024-e873da00-a19f-11ea-8b9f-12d3e4036d60.png)
> 
> @bluebill1049 The second example from sandbox is using unregister() method, which is not the case in my situation. I need to have it registered in the form + I don't need a required rule, because requiredMode changed to false. How can I avoid caching in this situation?

`requiredMode` a state or an input on the page.

1.  `requiredMode` is a local state, use unregister in `useEffect`
2.  if it's an input, use `getValues()`

**Comment by edediostoosa** [comment] 2022-02-10 21:49
> Yes, if your validation logic is dynamic or you can look into schema validation.

Actually, im soo interesting on see that behavior using schema validation.
