### ISSUE TITLE
Yup schema re-validation does not remove error on dependent fields

### ISSUE THREAD

**Issue by MikeAmelung** [react-hook-form/react-hook-form#440] opened 2019-11-01 16:14 UTC
**Describe the bug**
When using .when() with yup, and reValidateMode is "onChange", only the field that is changed has its error removed, even if changing that field affects the validity of other fields

**To Reproduce**
1. Go to [Codesandbox](https://codesandbox.io/s/react-hook-form-validation-onchange-70qtf)
2. Click on 'Submit', both validation errors will appear
3. Change one of the inputs, only one validation error will disappear, but the form is now valid

**Codesandbox link**
[Codesandbox](https://codesandbox.io/s/react-hook-form-validation-onchange-70qtf)

**Expected behavior**
Both fields which are now valid would have their errors cleared

**Comment by bluebill1049** [comment] 2019-11-01 21:23
thanks, @MikeAmelung at the moment, we don't support validate dependent fields just yet. I will add that into the todo list tho.

**Comment by bluebill1049** [comment] 2019-11-02 00:18
`react-hook-form@3.26.5-beta.2` lucky it was an easy patch, let me know if that resolves the issue. it will be released in the next patch.

**Comment by MikeAmelung** [comment] 2019-11-02 22:11
@bluebill1049 Looks good to me, thank you!

**Comment by bluebill1049** [comment] 2019-11-02 22:20
fantastic @MikeAmelung thanks for double-checking, please consider star this lib if you find it useful too :) (stars help to grow this lib) 👅

**Comment by bluebill1049** [comment] 2019-11-02 22:20
also, I will release the patch next week as well

**Comment by MikeAmelung** [comment] 2019-11-05 19:44
@bluebill1049 

Found another issue related to this. I updated the [Codesandbox](https://codesandbox.io/s/react-hook-form-validation-onchange-70qtf) with another rule that prevents both fields from being filled at the same time. When doing this, it's possible to get one field into validFieldsRef, but then invalidate it by changing the other field. Even though it is no longer valid, it does not get removed from validFieldsRef, which causes shouldUpdate to return false when editing the field that made it into validFieldsRef.

To see it in action on the [Codesandbox](https://codesandbox.io/s/react-hook-form-validation-onchange-70qtf), click Submit, type something into Mobile Phone (which gets added to validFieldsRef), type something into Home Phone (now you have two errors again), go back and empty Mobile Phone (the errors remain even though it's now valid, because it never re-rendered).

The simplest fix I see is adding something like
```
Object.keys(fieldErrors).map(name => {
    validFieldsRef.current.delete(name);
});
```
to line 397 of useForm.ts

**Comment by bluebill1049** [comment] 2019-11-05 20:10
thanks @MikeAmelung for the detailed issue report. i will take a look at it. :)

**Comment by bluebill1049** [comment] 2019-11-05 23:56
looks like you already found the solution! :) want to send a PR for this?

**Closed** 2019-11-06 04:32 UTC
Labels: enhancement

**Comment by nfabredev** [comment] 2020-05-05 13:50
Hi everyone, not sure if i should open a new issue as i think this is the same problem happening to me too and #440 did not fix the problem in my case. 

Somehow this works with text input as shown in the codesandbox of of Mike in the first post ( and in the tests ), but it doesn't work with html selects.

# Describe the bug
When using .when() or a test which checks the parent value with yup, and reValidateMode is "onChange", only the select that is changed has its error removed, even if changing its selected option affects the validity of other fields

# To Reproduce
Steps to reproduce the behavior:

Go to the Codesandbox
Click on 'Submit', both validation errors will appear ( you can check the console too )
Change one of the select, only one validation error will disappear, **the form is still invalid**
Click submit, this somehow trigger a revalidation and successfully submits the form. The form is valid and the remaining error is cleared.

Codesandbox link
Using `when`: https://codesandbox.io/s/react-hook-form-select-validation-onchange-with-when-vrty2?file=/src/index.js
Using `test` and `this.parent`: https://codesandbox.io/s/react-hook-form-validation-onchange-with-test-mbt7i

Expected behavior
Both errors should be cleared when changing a field both validations depends on.

Both codesandbox are using react-hook-form 4.4.2 but this problem is the same on latest stable 5.6.1 too.
