### ISSUE TITLE
issue: Upgrading from 7.19.5 breaks watch API with useFieldsArray

### ISSUE THREAD

**Issue by mrlubos** [react-hook-form/react-hook-form#7115] opened 2021-11-23 00:50 UTC
### Version Number

7.20.2

### Codesandbox/Expo snack

N/A

### Steps to reproduce

Sorry for missing repro link, I may try to dig into it later. I have a fields array containing selectable objects. Prior to 7.20.0, selecting a field would trigger re-render when using the `watch()` API. This stopped happening after 7.20.0.

### Expected behaviour

watch() re-renders when field array changes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment] 2021-11-23 00:54
can you try the latest patch?

**Comment by mrlubos** [comment] 2021-11-23 00:59
@bluebill1049 Thanks for the quick reply! I am positive I was on 7.20.2, but I can have another go later. I tried to put together a simple example, but couldn't reproduce it quickly, so it might be something more intricate

**Comment by mfferreira** [comment] 2021-11-24 11:06
@mrlubos I'm also having issues with `useFieldsArray` on the latest versions, but more specifically:
When mutation the array, all the elements of the array loose their ID, which I assume is the cause of the re-render.

Can you check if that's the case for you as well?

**Comment by mrlubos** [comment] 2021-11-24 17:03
Hi @mfferreira, I tried checking and my `useFieldsArray()` doesn't lose IDs. However, I learned that I can use `keyName` to specify a different key which might come handy (?) Thank you!

**Comment by bluebill1049** [comment] 2021-11-24 22:21
> @mrlubos I'm also having issues with `useFieldsArray` on the latest versions, but more specifically: When mutation the array, all the elements of the array loose their ID, which I assume is the cause of the re-render.
> 
> Can you check if that's the case for you as well?

If you could supply simple and reproducible codesandbox, I am happy to take a look at it.

**Comment by mfferreira** [comment] 2021-11-25 09:38
> Hi @mfferreira, I tried checking and my `useFieldsArray()` doesn't lose IDs. However, I learned that I can use `keyName` to specify a different key which might come handy (?) Thank you!

Picking another key with `keyName` doesn't really solve the problem for me, because my dataset uses `id`.

An example can be found here: https://github.com/react-hook-form/react-hook-form/issues/7139#issuecomment-979011870

**Comment by bluebill1049** [comment] 2021-11-25 09:47
why can't you just register another input with `id`? 

https://codesandbox.io/s/react-hook-form-usefieldarray-forked-7dpxe?file=/src/index.js

**Comment by mfferreira** [comment] 2021-11-25 10:31
> why can't you just register another input with `id`?
> 
> https://codesandbox.io/s/react-hook-form-usefieldarray-forked-7dpxe?file=/src/index.js

The issue is not registering it. The issue is the `id` properties in the dataset get wiped out. This was not happening in previous versions.

**Comment by bluebill1049** [comment] 2021-11-25 10:48
if you didn't change the `keyName` then it's the expected behavior, the previous version had unexpected behavior.

**Comment by mfferreira** [comment] 2021-11-25 10:59
> if you didn't change the `keyName` then it's the expected behavior, the previous version had unexpected behavior.

Is this the warning note about that?
![Screenshot 2021-11-25 at 11 56 19](https://user-images.githubusercontent.com/882713/143428952-a52a2803-ccfb-493d-8d85-5b635c5c0891.png)

If so, wouldn't it be better to use something less generic and common as `id`? Something like `rhf_id` or something...
I feel like 99% of datasets will have `id` as their default unique key, and thus will have the same issue if they miss this `keyname` collision, like I did.

**Comment by bluebill1049** [comment] 2021-11-25 11:02
This is something to be addressed in the next major (breaking change) version.

**Comment by bluebill1049** [comment] 2021-11-25 11:02
@mrlubos any update on reproducing this issue?

**Comment by mrlubos** [comment] 2021-11-26 15:20
Hi @bluebill1049, not yet! Taking a few days off so won't be working on the code for a while. Are there any upcoming changes that would affect the watch API and hopefully resolve my issue?

**Comment by bluebill1049** [comment] 2021-11-26 22:53
Thanks for the update, no rush at all. no change on `watch/useWatch` API.

**Comment by bluebill1049** [comment] 2021-11-27 23:44
I have improved the doc with what you suggested above @codelover2k please feel free to send us a PR next time.

**Comment by bluebill1049** [comment] 2021-12-02 09:48
any update on this issue?

**Comment by bluebill1049** [comment] 2021-12-02 21:54
will look into this issue once reproducible codesadnobx is supplied.

**Closed by bluebill1049** 2021-12-02 21:54 UTC
Labels: status: need more detail

**Comment by mrlubos** [comment] 2022-01-17 22:49
Hey @bluebill1049! Good news, it seems one of the latest releases fixes this issue! 😃 I still don't know what was causing it, but can't reproduce it in 7.24.0 anymore. I tried on 7.20.4 last I think and it was still there, so something fixed it. Thank you!

**Comment by bluebill1049** [comment] 2022-01-17 22:58
Awesome to heart. 👍

**Comment by mrlubos** [comment] 2022-01-19 20:07
@bluebill1049 I finally managed to isolate the issue! So what changed in `7.20.0` is that index notation no longer works with watch API, but the dot notation works. You can see in the [CodeSandbox](https://codesandbox.io/s/react-typescript-forked-3o584?file=/src/App.tsx) that selecting dot notation items updates the count, whereas index notation doesn't. I can confirm updating the notation in my code fixes the issue. I'm not sure if this was an intentional change, but perhaps it would be worth documenting?

**Comment by Moshyfawn** [comment] 2022-01-19 20:46
There's a section on `register` method that mentions the dot vs bracket notation for field names.
![image](https://user-images.githubusercontent.com/16290753/150210421-4d199482-a518-4edf-a7d4-ca86a4b0017d.png)

But, yeah, it doesn't seem to be mentioned for the controller API (`Controller` / `useController`). Maybe it should be duplicated for the controller as well

**Comment by mrlubos** [comment] 2022-01-19 23:40
Thanks @Moshyfawn! The thing is though, I've been using the bracket syntax since I can remember and it always worked... up until now

**Comment by bluebill1049** [comment] 2022-01-19 23:43
@mrlubos it was marked as a breaking change at V7.
