### ISSUE TITLE
formState.dirty not being updated after field's value changes with @testing-library/react

### ISSUE THREAD

**Issue by carlesba** [react-hook-form/react-hook-form#356] opened 2019-10-08 15:34 UTC
**Describe the bug**

react-hook-form does not update formState parameters when fields get updated inside testing-library tests.

**To Reproduce**

You can reproduce it with the following code:

```jsx
// form.js
import React from 'react';

import {useState} from 'react';

import useForm from 'react-hook-form';

const Form = ({submit}) => {
  const { register, handleSubmit, formState } = useForm({mode: 'onChange'});
  
  const [val, setVal] = useState(false);

  const onSubmit = (data) => {
    setVal(true);
    // formState.dirty === false should be true
    submit(formState.dirty)
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input data-testid="myinput" name="myinput" ref={register} /> {/* register an input */}
      
      <button type="submit" data-testid="login-submit"> Login </button>

      {val && <div data-testid="my-res"> Value Set! </div>}
    </form>
  );
};

export default Form;
```
```jsx
// form.spec.js
import React from 'react';

import { render, cleanup, fireEvent } from '@testing-library/react';

import Form from './form';

require('mutationobserver-shim');

afterEach(cleanup);

describe('form', () => {

  it('tells when submission is dirty', async () => {

    const submit = jest.fn()
    const { getByTestId, findByTestId } = render(<Form  submit={submit}/>);

    const myinput = getByTestId("myinput");

    const submitButon = await findByTestId('login-submit');

    fireEvent.change(myinput, { target: { value: 'set random input' } });

    fireEvent.click(submitButon);

    await findByTestId('my-res')

   // it's being called with false
    expect(submit).toHaveBeenCalledWith(true)
  });

});
```

**Expected behavior**
When submitting, formState.dirty should be true as we've changed the input value.

**Desktop (please complete the following information):**
 - @testing-library/react@9.3.0
 - Version "3.23.18-beta.2"

**Comment by bluebill1049** [comment] 2019-10-09 03:35
I think if you change `fireEvent.input` should work for you.

**Comment by bluebill1049** [comment] 2019-10-09 22:12
I have tested the above solution and it's working. going to close this issue now, feel free to re-open and ask more questions.

**Comment by carlesba** [comment] 2019-10-10 06:41
Thanks for the quick response. I've tried it with `fireEvent.input` but `dirty` is still false. The submitted data is correct though.

**Comment by bluebill1049** [comment] 2019-10-10 06:49
hmm that's strange...

**Comment by bluebill1049** [comment] 2019-10-10 06:50
i will take a look at it again

**Comment by carlesba** [comment] 2019-10-14 07:06
I can't reopen the issue

**Comment by bluebill1049** [comment] 2019-10-14 09:34
I think this is more of react-testing-library question: 

```
// form.js
import React from 'react';
import useForm from 'react-hook-form';

const Form = ({ submit }) => {
  const { register, handleSubmit, formState } = useForm();

  const onSubmit = () => {
    submit(formState.dirty);
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input data-testid="myinput" name="myinput" ref={register} />
      <button type="submit" data-testid="login-submit">
        Login
      </button>
    </form>
  );
};

export default Form;
```

```
// form.spec.js
import React from 'react';

import { render, cleanup, fireEvent, act } from '@testing-library/react';

import Form from './form';

require('mutationobserver-shim');

afterEach(cleanup);

describe('form', () => {

  it('tells when submission is dirty', async () => {

    const submit = jest.fn()
    const { getByTestId, findByTestId } = render(<Form submit={submit}/>);

    const myinput = getByTestId("myinput");

    const submitButton = await findByTestId('login-submit');

    fireEvent.input(myinput, { target: { value: 'set random input' } });

    fireEvent.click(submitButton);

    act(async () => {
      expect(submit).toHaveBeenCalledWith(true)
    })
  });
});
```

I have tested the above and works fine.

**Closed** 2019-10-14 09:36 UTC
Labels: question

**Comment by sgentile** [comment] 2020-08-11 19:56
I'm having same issue - the form I'm testing is inside a component

**Comment by sgentile** [comment] 2020-08-11 19:58
The issue I'm having is with formState.isValid  - I know it's valid when I remove the formState.isValid from disabled of the button, but when I put it on the button, inside the test it still shows it as disabled.

**Comment by mattgabor** [comment] 2020-10-20 21:32
@bluebill1049 we are running into the same issue - our form is also inside of a component. Can this issue be re-opened?

**Comment by bluebill1049** [comment] 2020-10-20 21:40
> @bluebill1049 we are running into the same issue - our form is also inside of a component. Can this issue be re-opened?

can you reproduce this issue in a codesandbox before i re-open this issue?

**Comment by bibekg** [comment] 2020-11-07 19:38
Was having (almost) the same issue. Only difference was I was just using `fireEvent` rather than `fireEvent.change`. Using `fireEvent.input` fixed it for me.

**Comment by bluebill1049** [comment] 2020-11-07 22:13
@bibekg have a read this section: https://react-hook-form.com/faqs#TestingReactHookForm i think it may help on testing.

**Comment by MerlinMason** [comment] 2021-12-15 19:36
I've spent half of today battling with a similar issue, turns out it was painfully simple... hopefully this helps someone else!

In my case I was toggling a checkbox and then trying to check the validation state. Like so:

```js
fireEvent.click(getByLabelText("My label"));
```

However nothing on the `formState` was being updated. The way my form was setup was to only validate onBlur. Changing to the following fixed the issue:

```js
fireEvent.click(getByLabelText("My label"));
fireEvent.blur(getByLabelText("My label"));
```

**Comment by bluebill1049** [comment] 2021-12-15 21:27
thanks @MerlinMason for sharing

**Comment by tedma4** [comment] 2022-05-16 18:02
If your button is still disabled after `formState.isValid` changes to `true`. Try adding a `data-testid` to the button and use `screen.findByTestId`
```
const button = await screen.findByTestId('button-testid')
expect(submitButon).not.toBeDisabled();
