### ISSUE TITLE
issue: nested FieldArray contains invalid entries after deleting item from parent array

### ISSUE THREAD

**Issue by sophie-gg** [react-hook-form/react-hook-form#10711] opened 2023-07-25 17:11 UTC
### Version Number

7.45.2

### Codesandbox/Expo snack

https://codesandbox.io/embed/optimistic-tree-sv4vwp

### Steps to reproduce

1. Go to https://codesandbox.io/embed/optimistic-tree-sv4vwp
2. Click on "See Sprockets for Gizmo 2", which brings up the field array for `gizmos.2.sprockets`
<img width="557" alt="Screenshot 2023-07-25 at 18 00 52" src="https://github.com/react-hook-form/react-hook-form/assets/34109798/2ce92305-775e-475f-a7d7-0e49ba6ea431">

3. Click on "Delete Gizmo 1". Observe that the second table display a mix of values from the previous `gizmos.2.sprockets` and `gizmos.3.sprockets` arrays.
<img width="547" alt="Screenshot 2023-07-25 at 18 01 06" src="https://github.com/react-hook-form/react-hook-form/assets/34109798/90a12d76-ce2c-46cd-9a9f-c5bacf1a4602">

### Expected behaviour

It should contain the elements for `gizmos.2.sprockets` only (which used to be `gizmos.3.sprockets` before the delete operation)

<img width="554" alt="Screenshot 2023-07-25 at 18 01 25" src="https://github.com/react-hook-form/react-hook-form/assets/34109798/2fcf6293-0379-4133-8f18-4340d4ebf097">

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment] 2023-08-24 02:05
I'm trying to debug this one but I haven't been able to pin point the exact cause of the issue yet.

I found that the issue can be reproduced **without deleting** any gizmos entries after "opening" the sprockets list for any of the gizmos. The sprockets list is being merged with the "new" open gizmo sprockets, so on every gizmo index change. This leads me to believe that the issue is with the `register` form method: the form's registering the nested field array entries but never unregisters or unmounts them, but rather merges them with the new list of nested array fields with a different index. `shouldUnregister` doesn't do it either.

**Comment by boonya** [comment] 2023-09-02 09:52
Oh, yeah. I stuck on the same issue in my project. I have a field array where every field contains one more field array + min length validation. When I remove field from root array validation of nested array fails. Because the remaining field from the parrent array does not contain values from nested array on a validation level. But when I debug the real values of remaining field nested values are still presented.
Let me know if you need more details.

**Comment by bluebill1049** [comment] 2023-10-07 00:56
This is a design limitation, when you start to delete that second row, the dual table children inputs will get registered and hence mutate the `formValues`. Work around I think of is not to render the children during the delete action, and remount the child until the delete is completed (`useEffect` the number of total parent nodes is reduced to x amount of number).

**Closed by bluebill1049** 2023-10-07 00:56 UTC
Labels: design limitation
