### ISSUE TITLE
Field arrays lose their focus or position when reset

### ISSUE THREAD

**Issue by aaronjensen** [react-hook-form/react-hook-form#3719] opened 2020-12-17 15:27 UTC
**Describe the bug**
As part of our auto-save mechanism, we reset the form before save so that the default values will be set properly for the next auto save.

The auto save, and therefore the reset, happen on a timer, which means that the user may have a field focused when the save happens.

If the field they have focused is in a field array, then the documented method of using the field `id` as `key` causes the entire array item field to rerender because the `id` is recreated upon reset.

We're using stable keys to work around this, but that may be a bug.

Even with this, if the user has a text input focused when a reset happens and their cursor is somewhere other than the beginning of the field, the cursor will jump to the beginning of the text input. This is not the case for normal inputs, only for field arrays.

The reason appears to be that field arrays actually modify the `value` attribute of the element, which is different than regular fields. I can reproduce this by modifying `value` on a timer without involving react hook form.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-ht83m?file=/src/index.js
2. Click on the first name field and replace the text with "Test"
3. Click "RESET DELAY" and then quickly click on the first name field, positioning your cursor at the end of the word "Test"
4. Wait for the timeout and observe that the cursor jumps to the beginning of the field

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-forked-ht83m?file=/src/index.js

**Expected behavior**
I'd expect the value attribute to not change so that the cursor does not jump. I'd also expect that the field id does not change on reset so it could be used as a stable key, or for the documentation to be updated accordingly.

Thanks!

**Comment by bluebill1049** [comment] 2020-12-17 21:18
Thanks, @aaronjensen don't think there is much we can do on this one with `reset` API.

**Comment by aaronjensen** [comment] 2020-12-17 21:22
Hmm, that's to bad. Are those the only two ways to update a form's notion of default values (in other words, cause the form to think that nothing is dirty?)

Would it be possible for field arrays to work more like normal fields? They don't update the `value` attribute, so it's not clear why field array must.

**Comment by bluebill1049** [comment] 2020-12-17 21:24
Field Array is a lot more trick than normal input, because of the nature of field shuffling, so during the reset action, all the defaultValue is getting refreshed.

**Comment by aaronjensen** [comment] 2020-12-17 21:27
Would it be possible to detect that the value of the field is already what is expected and not do the change? Could you point me to where in the code it's triggering a `value` attribute change?

**Comment by bluebill1049** [comment] 2020-12-17 21:31
We don't trigger `value` attribute change, I believe it's from `defaultValue` update (`fields` object).

**Comment by bluebill1049** [comment] 2020-12-17 21:31
let me know if you can find a solution for this, cause it is not great UX.

**Comment by aaronjensen** [comment] 2020-12-17 23:30
You're right that it's the change of `defaultValue` (I didn't even know that was a real DOM property...). I don't know of a way to fix that other than to not change `defaultValue`. I don't understand how field arrays work well enough to be able to offer a better solution. If the registered ref could be used to control the field the same way it seems to be in regular fields, then I imagine `value` could be set directly, which, for whatever reason, does not move the cursor.

**Comment by bluebill1049** [comment] 2020-12-17 23:34
It's trigger to detect whether `fields` are been updated or completely re-ordered (that's the challenge here). have you tried with setValue directly to the input?

**Comment by aaronjensen** [comment] 2020-12-17 23:35
Yes, that works, but since it doesn't update the default the field is still considered dirty. The field already has the value I want it to have, i'm just trying to mark that field as not dirty.

**Comment by aaronjensen** [comment] 2020-12-17 23:44
It'd be nice if something like this could work https://codesandbox.io/s/react-hook-form-useform-template-forked-t7tkz

I don't need the complexity of useFieldArray, I just need it to be able to respect default value additions for fields that are new to it.

**Comment by bluebill1049** [comment] 2020-12-17 23:47
I guess you can use custom register @aaronjensen, just register those inputs at `useEffect` or by action. like a virtual input.

also maybe worth to send a feature request with `setValue({ shouldUpdateDefault: false })`

**Comment by aaronjensen** [comment] 2020-12-17 23:52
> also maybe worth to send a feature request with `setValue({ shouldUpdateDefault: false })`

I'm not sure I follow this one. It seems like it currently does not change the default when you use `setValue`. What I want is something that changes the default as far as react-hook-form is concerned, but doesn't update the defaultValue attribute, but that wont work w/ the way that things work now.

I guess what I really want is to tell react-hook-form that as of now, all fields are clean (or this specific field is clean) without actually changing any values or defaults. So effectively, `setNotDirty("field")` or `setNotDirty()` for the entire form

**Comment by bluebill1049** [comment] 2020-12-17 23:54
> I'm not sure I follow this one. It seems like it currently does not change the default when you use `setValue`. What I want is something that changes the default as far as react-hook-form is concerned, but doesn't update the defaultValue attribute, but that wont work w/ the way that things work now.

This is what i meant

`setValue('nameOfField', 'value', { shouldUpdateDefault: true })` // then you input is always updated with defaultvalue hence dirty is not updated.

**Comment by aaronjensen** [comment] 2020-12-17 23:55
Got it. Would `setDefault` be more direct? 

Oh and rather than `setNotDirty`, to go along with `clearErrors`, how about `clearDirty`?

**Comment by aaronjensen** [comment] 2020-12-17 23:56
Unless of course there's another typical way for a long-live form... that is, a form that I make a change on, and then save (so it's no longer dirty), then I make another change and it's considered dirty again. It feels like resetting the form is a hack for this.

**Comment by bluebill1049** [comment] 2020-12-18 00:01
we can run an RFC on this topic and post a vote to let the user decide which API makes the most sense.

- shouldUpdateDefault
- shouldClearDirty
- shouldResetDirty

**Comment by bluebill1049** [comment] 2020-12-18 00:02
> Unless of course there's another typical way for a long-live form... that is, a form that I make a change on, and then save (so it's no longer dirty), then I make another change and it's considered dirty again. It feels like resetting the form is a hack for this.

Not sure if I agree with this 100%, you need to info the hook form the updated `defaultValues`, reset make sense to me.

**Comment by aaronjensen** [comment] 2020-12-18 00:13
The problem is they're inherently different things. Take the example from the docs for submit with reset and introduce a delay on save:

https://codesandbox.io/s/react-hook-form-handlesubmit-with-reset-forked-jhpjp

It's no longer usable. If you make a change, then save it, then make another change, that change will be reset.

The *only* thing I want to change after a successful submit is the default values. That's all that's changed, is the basis for the form's dirty computation. 

I could call reset prior to the delay, but then if the save fails, what do I do? I would need to set my default values back to what they originally were, but that has the same problem with undoing any changes I've made to the form.

**Comment by bluebill1049** [comment] 2020-12-18 00:19
I thought the follwing case:

- Form Submit (without change) -> dirty:false
- Form Submit (with change) -> dirty: true
  - send request to pull form data
    - resovled reset the form -> dirty: false  
    - rejected do nothing.

**Comment by aaronjensen** [comment] 2020-12-18 00:21
Yes, exactly, but because "reset the form" resets values, any changes the user made to the form while it's submitting are lost. Try [the example I sent](https://codesandbox.io/s/react-hook-form-handlesubmit-with-reset-forked-jhpjp). Change first name, click Submit, then quickly change last name. Wait and see the change to last name get undone.

**Comment by bluebill1049** [comment] 2020-12-18 00:23
> Change first name, click Submit, then quickly change last name.

I think that's a UX question right?

**Comment by aaronjensen** [comment] 2020-12-18 00:25
Unless I'm missing something, it's a UX that's currently unachievable with react-hook-form. So, I'm not sure I'd consider it a UX question. The desired UX is decided upon, now it's a technical issue. If I could reset default values *without* changing values, I could achieve the desired UX (aside from the original issue in this thread, which will require a different work around)

**Comment by bluebill1049** [comment] 2020-12-18 00:33
`reset({ ...submittedData });` this is always not going to work because you are reset the data from "previous" state, you should always read data from `getValues()` if you want to update as what's in the current view, and if that's change, then you probably should send another request to update user's input.

**Comment by aaronjensen** [comment] 2020-12-18 00:37
> `reset({ ...submittedData });` this is always not going to work because you are reset the data from "previous" state

Right



> you should always read data from `getValues()` if you want to update as what's in the current view

This won't work either, unfortunately, because the desired defaults and and the current values have diverged. 

> then you probably should send another request to update user's input.

Agreed, but it's no longer clear which fields are dirty, plus, in the case where the user has to click save, it's back to the same problem. I can no longer show which fields are dirty, or I reset user's work.

**Comment by aaronjensen** [comment] 2020-12-18 00:39
if `reset` allowed not updating defaults, then I could call reset twice--once to update the values and defaults to the original submission and again to update the values to the current values. This would be a hack, I'd basically be doing A & B then undoing A when I'd rather just do B directly, but at least I cold do it.

**Comment by aaronjensen** [comment] 2020-12-18 00:40
I suppose the way to do it today would be to reset to the submitted values, then call `setValue` for each dirty field to the current value.

**Comment by bluebill1049** [comment] 2020-12-18 00:54
> if `reset` allowed not updating defaults, then I could call reset twice--once to update the values and defaults to the original submission and again to update the values to the current values. This would be a hack, I'd basically be doing A & B then undoing A when I'd rather just do B directly, but at least I cold do it.

hmmm, `defaultValues` is actually the `default`.

**Comment by bluebill1049** [comment] 2020-12-18 00:54
> I suppose the way to do it today would be to reset to the submitted values, then call `setValue` for each field to set it to the current value.
> 
> Is there a way to call `getValues` and get the string keys like `foo[0].bar` rather than the object?

i think you can use `get(getValues(), 'xxx.xxx')`

**Comment by bluebill1049** [comment] 2020-12-18 00:55
by the way, I am trying to figure out a solution here from the lib point of view as well, not trying to against your ideas.

**Comment by aaronjensen** [comment] 2020-12-18 00:57
> hmmm, `defaultValues` is actually the `default`.

What do you mean?

> i think you can use get(getValues(), 'xxx.xxx')

I effectively want to do something like this:

```
      const values = getValues();

      console.log(values);
      reset({ ...submittedData });

      Object.keys(values).forEach((key) => {
        console.log("Setting", key, values[key])
        setValue(key, values[key]);
      });
```

But this doesn't work, the reset appears to win for some reason.



> by the way, I am trying to figure out a solution here from the lib point of view as well, not trying to against your ideas.

Understood, and I very much appreciate your time and engagement. Thank you!

**Comment by aaronjensen** [comment] 2020-12-18 00:59
It works if I wrap the `setValue`s in a timeout, see: https://codesandbox.io/s/react-hook-form-handlesubmit-with-reset-forked-jhpjp?file=/src/index.js

**Comment by bluebill1049** [comment] 2020-12-18 01:00
> What do you mean?

```
reset({
  test: 'test'
})
```

then re-render

`<input ref={register} name="test" />` 

then gets updated and this also updated `default` which compute dirty flags

**Comment by aaronjensen** [comment] 2020-12-18 01:02
> then gets updated and this also updated `default` which compute dirty flags

Yes, that's what I want, though I want to set the default to X and leave the value as Y. Reset's dirty flag computation does what I want, it just sets the value too, which I don't want in this particular instance.

**Comment by bluebill1049** [comment] 2020-12-18 01:07
> > then gets updated and this also updated `default` which compute dirty flags
> 
> Yes, that's what I want, though I want to set the default to X and leave the value as Y. Reset's dirty flag computation does what I want, it just sets the value too, which I don't want in this particular instance.

oh, I see, as a partial one. let me have a look at the working one that you have above.

**Comment by bluebill1049** [comment] 2020-12-18 01:11
<img width="970" alt="Screen Shot 2020-12-18 at 12 10 17 pm" src="https://user-images.githubusercontent.com/10513364/102561915-0009b480-412a-11eb-9e86-3fd3eaf878b2.png">

it works for me without setTimeout, do i miss the step?

fill firstnam -> submit -> change last name 

expect in the screenshot?

**Comment by aaronjensen** [comment] 2020-12-18 01:13
Try the other order, change last name -> submit -> change first name. Your order does work, but this order does not (field array difference, probably)

**Comment by bluebill1049** [comment] 2020-12-18 01:15
<img width="1009" alt="Screen Shot 2020-12-18 at 12 15 39 pm" src="https://user-images.githubusercontent.com/10513364/102562235-c08f9800-412a-11eb-95ac-f739df7a6e87.png">

works as well ^

**Comment by aaronjensen** [comment] 2020-12-18 01:21
oh sorry, it's change first name -> submit -> change `something`

**Comment by bluebill1049** [comment] 2020-12-18 01:26
![Screen Recording 2020-12-18 at 12 23 38 pm](https://user-images.githubusercontent.com/10513364/102562914-2fb9bc00-412c-11eb-939a-72fed97444cb.gif)

ok as well above.

**Comment by aaronjensen** [comment] 2020-12-18 01:32
You have to make the change to `something` before the 3 seconds

**Comment by bluebill1049** [comment] 2020-12-18 01:34
> You have to make the change to `something` before the 3 seconds

it is before the 3 seconds, you can see the last state update is coming after 3 seconds.

**Comment by aaronjensen** [comment] 2020-12-18 02:05
Oh, you're right, but it is showing the bug. `something` reverts to "anything" when it should stay as what you typed. If you add the setTimeout, it will not revert.

**Comment by aaronjensen** [comment] 2020-12-18 02:07
![Uploading CleanShot 2020-12-17 at 20.06.33.gif…]()


See above for a comparison

**Comment by bluebill1049** [comment] 2020-12-18 02:19
hmmm interesting, i will take a deeper look at this.

**Comment by bluebill1049** [comment] 2020-12-18 07:00
Here is a solution that I come up: https://codesandbox.io/s/react-hook-form-handlesubmit-with-reset-forked-vmy4f?file=/src/index.js

The problem is when `reset` invoked all input reference will be removed, and get complete re-registered again, so i used a reducer to solve this problem.

**Comment by aaronjensen** [comment] 2020-12-18 14:55
Interesting. Thanks for that suggestion. Wouldn’t it be a lot more straight forward if there was an api to do exactly what I’m wanting here and set only the default values? Ideally it wouldn’t clear all the refs like reset. Reset is a massive hammer and I just want a surgical strike.

**Comment by bluebill1049** [comment] 2020-12-18 21:43
> Interesting. Thanks for that suggestion. Wouldn’t it be a lot more straight forward if there was an api to do exactly what I’m wanting here and set only the default values? Ideally it wouldn’t clear all the refs like reset. Reset is a massive hammer and I just want a surgical strike.

Agree, this will be considered in the next major update, probably would involve breaking change with the `reset` API.

**Comment by bluebill1049** [comment] 2020-12-21 23:53
Going to close this issue, we will address this issue at v7, @aaronjensen please take a look at the proposal and let me know your thoughts: `reset` API section

https://github.com/react-hook-form/react-hook-form/discussions/3714

**Comment by aaronjensen** [comment] 2020-12-22 00:12
I don't understand how what is proposed in that section addresses this. Would I mutate `formState` myself? That seems significantly worse, but maybe I'm not understanding the proposal.

**Comment by bluebill1049** [comment] 2020-12-22 00:41
`reset: (values?: Record<string, any>, { formState: Partial<FormState>, shouldUnregister: boolean }) => void`

- you can skip unregistering (actually we may that option, so inputs never get `unregistered` automatically)
- instead of omitting state update, now you can reset partially 

```
reset(values, {
  formState: {
     ...formState,
     isDirty: true,
  },
  shouldUnregister: false,
})
```

let me know your thoughts, it's good to have those conversations and feedbacks. feel free to leave comments in that discussion channel as well, so everyone can see the concerns and we can fix accordingly.

**Closed** 2020-12-29 00:00 UTC
Labels: enhancement

**Comment by dudiharush** [comment] 2021-05-02 14:28
Hi @bluebill1049 i'm also experiencing this same problem of loosing a focus on a field that is a part of an array, after i call reset
What is the solution for that?

**Comment by bluebill1049** [comment] 2021-05-05 07:14
> Hi @bluebill1049 i'm also experiencing this same problem of loosing a focus on a field that is a part of an array, after i call reset
> What is the solution for that?

reset will basically refresh the entire field array, if you can do individual input with `setValue` it will not loose its focus.
