### ISSUE TITLE
issue: isSubmitted true after reset

### ISSUE THREAD

**Issue by wilav-dev** [react-hook-form/react-hook-form#8844] opened 2022-08-14 01:29 UTC
### Version Number

7.34.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-hook-form-reset-v7-forked-ys76uk?file=/src/index.js

### Steps to reproduce

1. Go to Codesandbox
2. Open console
3. Enter first name and submit form
4. onsubmit I'm resetting form but isSubmitted is not being updated to false

### Expected behaviour

isSubmitted should be false after reset using keepIsSubmitted false

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment] 2022-08-14 03:31
Duplicate of #8741

**Closed by Moshyfawn** 2022-08-14 03:31 UTC
