### ISSUE TITLE
Fields inside `FieldArray` are being unregistered at unmount even with `shouldUnregister: false` option

### ISSUE THREAD

**Issue by thelmagali** [react-hook-form/react-hook-form#4075] opened 2021-02-01 14:30 UTC
**Describe the bug**
I have three inputs. Two of them are always displayed, but the last one is only displayed when an "Expand" button is clicked.
To not lose the third input information, I use `shouldUnregister: false` option in `useForm`. That works fine for nested object or shallow objects, but when it comes to FieldArray, it does not work. Please follow the steps below and let me know if I misunderstand the functionality or there is something I missed.

Thanks in advance. 

**To Reproduce**
1. Click "Expand" button
2. Type anything in the third input of **Object inside Field Array** and **Object without field array** sections.
3. Click the "Condense" button
4. Click the "Expand" button again. There you will see that the typed input is still present for the **Object without field array** section, but it's gone in the **Object inside Field Array** sections.

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-forked-wiu1m?file=/src/index.js

**Expected behavior**
I expect the third input to not lose information in both **Object without field array** and **Object inside Field Array** sections after clicking "Condense" and then "Expand" again.

**Screenshots**
<img width="851" alt="Screen Shot 2021-02-01 at 11 27 28" src="https://user-images.githubusercontent.com/3956073/106471565-867f1900-6480-11eb-9398-6c5885557e20.png">
<img width="857" alt="Screen Shot 2021-02-01 at 11 28 14" src="https://user-images.githubusercontent.com/3956073/106471638-9991e900-6480-11eb-8de0-de073e4cde41.png">
<img width="850" alt="Screen Shot 2021-02-01 at 11 28 43" src="https://user-images.githubusercontent.com/3956073/106471696-aa425f00-6480-11eb-8f1e-6d9cf05e4d26.png">
<img width="818" alt="Screen Shot 2021-02-01 at 11 29 07" src="https://user-images.githubusercontent.com/3956073/106471747-b9c1a800-6480-11eb-8d2e-207cd2a1dbb5.png">

**Comment by bluebill1049** [comment] 2021-02-01 22:39
<img width="677" alt="Screen Shot 2021-02-02 at 9 38 55 am" src="https://user-images.githubusercontent.com/10513364/106526892-7d528280-653a-11eb-8373-bef40e6198c3.png">

hello there, looks like you forgot to save the codesandbox?

**Comment by thelmagali** [comment] 2021-02-02 12:40
Hi! Apologies. Now it's saved: https://codesandbox.io/s/react-hook-form-usefieldarray-forked-wiu1m?file=/src/index.js

**Comment by bluebill1049** [comment] 2021-02-02 22:00
no worries, will check it out.

**Comment by bluebill1049** [comment] 2021-02-03 01:06
Hook form useFieldArray is uncontrolled, if you want to do conditional inputs, you will have to use useWatch or watch:

https://codesandbox.io/s/react-hook-form-controller-template-forked-qxomn?file=/src/index.js

the fields object will always return input's `defaultValue`

**Comment by bluebill1049** [comment] 2021-02-03 01:14
here is another way to get around this issue: https://codesandbox.io/s/react-hook-form-usefieldarray-forked-32d60

**Comment by thelmagali** [comment] 2021-02-03 12:20
Ok, so it's normal behavior. I will try what you mentioned. Thank you Bill for the quick response!

**Comment by bluebill1049** [comment] 2021-02-05 22:12
Going to close this issue as it's expected behavior.

**Closed by bluebill1049** 2021-02-05 22:12 UTC
Labels: question
