### ISSUE TITLE
issue: Cannot append when useFieldArray's value is string of array

### ISSUE THREAD

**Issue by doppelgunner** [react-hook-form/react-hook-form#11475] opened 2024-02-03 11:16 UTC
### Version Number

7.49.3

### Codesandbox/Expo snack

https://codesandbox.io/s/cranky-wood-qd2w5f?file=/src/App.js

### Steps to reproduce

1. Go to https://codesandbox.io/s/cranky-wood-qd2w5f?file=/src/App.js
2. Click on add field 2 times
3. see error

### Expected behaviour

Should be able to add multiple fields. Right now you need to type in a value first on the last input field before you can append another field with empty string value. It works if we append with value string though `append('some value')`. 

Also, another problem is when you delete, it will delete all fields with empty value. To reproduce this:
1. append -> type in field
2. append -> type in field
3. append -> type in field
4. remove all texts on all fields 
5. click the delete button
6. see error -> all fields get deleted

The current hack right now is to:
- wrap the string to object so instead of:
`['value 1', 'value 2']`

I used:
- `[ {value: 'value1'}, {value: 'value2'}]`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment] 2024-02-03 11:35
looks like your CSB is broken?

**Comment by Moshyfawn** [comment] 2024-02-03 15:27
Duplicate of #11306

**Closed** 2024-02-03 15:27 UTC
Labels: question
