### ISSUE TITLE
When a field array becomes empty it's removed from the form

### ISSUE THREAD

**Issue by vangelov** [react-hook-form/react-hook-form#3051] opened 2020-10-01 07:28 UTC
**Describe the bug**
If you have a form with field array containing an element, when you remove the element and submit the form the resulting object does not contain the array at all.

**To Reproduce**

1. Go to https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek
2. Click on DELETE
3. Click on SUBMIT
4. The log shows `{}` instead of `{ test: [] }`

**Codesandbox link (Required)**
https://codesandbox.io/s/react-hook-form-usefieldarray-template-q0jek

**Expected behavior**
The log should show`{ test: [] }`

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser Safari
- Version 14.0

**Comment by bluebill1049** [comment] 2020-10-01 07:30
expected behavior by default (`shouldUnregister: true`), because inputs all get removed:

The next minor update is what you after.
https://github.com/react-hook-form/react-hook-form/pull/3027

**Comment by vangelov** [comment] 2020-10-01 07:36
That was fast, thank you :)

**Comment by bluebill1049** [comment] 2020-10-01 07:37
should be released in the next couple days 👍

**Closed by bluebill1049** 2020-10-01 07:37 UTC
Labels: feature request
