### ISSUE TITLE
Typescript build failing because of 'react-native' import

### ISSUE THREAD

**Issue by kobber** [react-hook-form/react-hook-form#369] opened 2019-10-14 13:52 UTC
**Describe the bug**
After upgrading to `3.24.0` our Typescript build is failing. This is caused by the typings importing `'react-native'`, which we're not using in our project.

```
ERROR in [at-loader] ./node_modules/react-hook-form/dist/types.d.ts:2:30
    TS2307: Cannot find module 'react-native'.

ERROR in [at-loader] ./node_modules/react-hook-form/dist/useForm.d.ts:2:30
    TS2307: Cannot find module 'react-native'.
```

**To Reproduce**
I'm assuming this happens for every Typescript based project that doesn't use `'react-native'`.

**Expected behavior**
The package should not have a dependency on `'react-native'`.

**Comment by bluebill1049** [comment] 2019-10-14 20:45
oops, that's my bad. I will patch that.

**Comment by bluebill1049** [comment] 2019-10-14 20:50
can you please test out this beta version? `3.24.1-beta.1`

**Comment by kobber** [comment] 2019-10-15 09:09
> can you please test out this beta version? `3.24.1-beta.1`

Ran `npm install react-hook-form@3.24.1-beta.1`, but it didn't seem to make a difference.

I'm still seeing `import * as ReactNative from 'react-native';` on line `2` of `dist/useForm.d.ts`.

**Comment by bluebill1049** [comment] 2019-10-15 09:40
thanks, strange I have already include react native peer dependency

**Comment by bluebill1049** [comment] 2019-10-15 09:45
also, I have tried on my own ts project, it's working fine with the latest version as well.

**Comment by bluebill1049** [comment] 2019-10-15 09:46
what's this `at-loader`?

**Comment by bluebill1049** [comment] 2019-10-15 09:52
can you make your at-loader not resolving node_module folder?

**Comment by kobber** [comment] 2019-10-15 11:16
I tried solving the problem by manually installing `react-native` and `@types/react-native`, and while this fixed the `Cannot find module 'react-native'` bug, it introduced other compile errors with duplicated global definitions.

I don't believe a web based project should have a dependency on `react-native` at all. Could the things required for react-native support be moved out somehow? Either to a separate package or a subfolder like so:
```ts
import useForm from "react-hook-form/react-native";
```

**Comment by bluebill1049** [comment] 2019-10-15 11:20
because react-hook-form is universal it supports type for both react and react-native. did you try to exclude node_module for at-loader?

**Comment by bluebill1049** [comment] 2019-10-15 11:29
let me know before I investigate other options for you

**Comment by bluebill1049** [comment] 2019-10-15 11:34
@barrymay could you please double-check on your end as well? I couldn't reproduce this issue.

**Comment by kobber** [comment] 2019-10-15 11:55
I'm already excluding `node_modules` in `tsconfig.json`, so that shouldn't be the problem.

Could you try adding `@types/react-native` to the list of peer dependencies?

**Comment by bluebill1049** [comment] 2019-10-15 12:00
> I'm already excluding `node_modules` in `tsconfig.json`, so that shouldn't be the problem.
> 
> Could you try adding `@types/react-native` to the list of peer dependencies?

Yes, i can. (not sure it will solve the problem)

but the error is coming from webpack loader:
``` 
ERROR in [at-loader] ./node_modules/react-hook-form/dist/types.d.ts:2:30
    TS2307: Cannot find module 'react-native'.
```

**Comment by kobber** [comment] 2019-10-15 12:57
Okay, the conclusion as of now is this: Installing `react-native` and `@types/react-native` _does_ solve the problem. Except that now I have `react-native` in my project, and the global types included in `react-native` is causing errors like this one: 
```
Duplicate identifier 'XMLHttpRequestResponseType'.
```

**Comment by waynebloss** [comment] 2019-10-15 15:50
I was surprised when I was reading through the code the other day, that I found `import * as ReactNative from 'react-native';` in 2 files just to use a single type definition from that package.

- in [useForm](https://github.com/react-hook-form/react-hook-form/blob/21284b3b03c048382a7bf3fff9ab76cb8144833c/src/useForm.ts#L638)
- in [types.ts](https://github.com/react-hook-form/react-hook-form/blob/0a8094363beb036a325b8e780778ec80ae99e961/src/types.ts#L29)

Since [Typescript has duck-typing](https://medium.com/@ajay.bhosale/typescript-and-duck-typing-7b3d7bb6f03c) why not just copy the type definition into your own project?

I was trying to find another project that has both `react` and `react-native` types imported for the same build but I couldn't find one. I don't think it's common practice but I'm not positive. Is there another example of this?

**Comment by bluebill1049** [comment] 2019-10-15 21:40
I am waiting for feedback from @barrymay worst case we will remove it and replace with any for react native

**Comment by bluebill1049** [comment] 2019-10-16 20:30
thanks @barrymay

**Comment by barrymay** [comment] 2019-10-17 02:53
As noted in my comments to the PR, I don't see react-native being pulled into a project by yarn / npm because of this reference.  The react-native reference being used in the react-hook-form project is for internal typings only. (The PR is not to fix this, but as a tangential followup to it)

**Comment by bluebill1049** [comment] 2019-10-17 02:55
I still believe it's a webpack build config issue, which is not related to this package. I will keep an eye on this issue, if more people report this as an issue I will remove react-native out from this library.

**Comment by barrymay** [comment] 2019-10-17 02:57
I agree - @kobber if you can post a reproducible example on GitHub or elsewhere so we can look, that would be helpful

**Comment by bopfer** [comment] 2019-10-17 03:19
For what it's worth.  I am seeing the same issue in my web-only project and I have held off on upgrading to 3.24.0 for now:

```
$ tsc -p tsconfig.json
../../../node_modules/react-hook-form/dist/types.d.ts:2:30 - error TS2307: Cannot find module 'react-native'.

2 import * as ReactNative from 'react-native';
                               ~~~~~~~~~~~~~~

../../../node_modules/react-hook-form/dist/useForm.d.ts:2:30 - error TS2307: Cannot find module 'react-native'.

2 import * as ReactNative from 'react-native';
```

Tomorrow I will see if I can create a reproducible example.

**Comment by bluebill1049** [comment] 2019-10-17 03:21
hmm ok, @bopfer thanks for the update. looks like we may need to remove `react-native`...

**Comment by barrymay** [comment] 2019-10-17 13:14
@bluebill1049 on further looking, I can't figure out why my environment isn't complaining, but @bopfer  and @waynebloss are right. 

The handleSubmit is now dependent on the ReactNative type injected in the project, and for some reason, my environment is ignoring it and loosing the typing around the returned function, just expecting an any. 

It would likely need some refactoring to get this exactly right, but for the moment, I agree to allow an any for the ReactNative.GestureResponderEvent case (with a TODO comment to fix it longer term).

If you want me to make the change, I will.

**Comment by barrymay** [comment] 2019-10-17 13:19
(for all I know, it may be a difference between yarn and npm - I use yarn myself)

**Comment by barrymay** [comment] 2019-10-17 16:04
ah, thanks! - generally speaking I always turn skipLibCheck false so you don't get impacted by lib problems (happens too often) ;). Still good to raise

**Comment by bluebill1049** [comment] 2019-10-18 04:48
@bopfer could you please help test out this version `3.24.1-beta.4`?

**Comment by bopfer** [comment] 2019-10-18 05:25
Looks good! No more `react-native` errors.

**Comment by bluebill1049** [comment] 2019-10-18 05:52
lovely going to publish it now @bopfer thanks

**Closed** 2019-10-18 05:55 UTC
Labels: dependency
