### ISSUE TITLE
issue: validate is called twice if isValid used

### ISSUE THREAD

**Issue by gituser3000** [react-hook-form/react-hook-form#7879] opened 2022-02-21 20:07 UTC
### Version Number

7.27.1

### Codesandbox/Expo snack

https://codesandbox.io/s/react-playground-forked-r1vnns?file=/index.js

### Steps to reproduce

1. Go to ['sandbox'](https://codesandbox.io/s/react-playground-forked-r1vnns?file=/index.js)
2. Click on console
3. type one symbol into field
4. See 2 console.logs . One on validation start and one after promise resolve

Same with default mode (on submit), changing input after submit

### Expected behaviour

One validate call, since two calls run two async validations (network requests?).

https://github.com/react-hook-form/react-hook-form/discussions/6959 seems related

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment] 2022-02-21 22:03
This is expected behavior. The first one is from field level, the second validation is form level. I will take look at it see if we can optimise somehow, but most likely it will stay as it is.

**Comment by bluebill1049** [comment] 2022-02-21 22:30
we used to have an internal state to track valid fields, however, it cause a lot of edge cases (bug fix) and somehow conflicted with field vs form level validation results, hence why we decide to split field and form level. so isValid will always flush down the whole form validation and abort early if any error is found. I think we will keep it as it is for now, as far it's not causing any bug and be stable. What you can do is perhaps have that logic in side your app to mark so the promise wouldn't run again if the field is already valid. (if call that extra validation impact your customer experience) I am going to close this issue for now, as it's intended unless more users report such perf issue and we can revisit for better solution.

**Closed by bluebill1049** 2022-02-21 22:30 UTC
Labels: question

**Comment by gituser3000** [comment] 2022-02-22 08:36
@bluebill1049 probably we should write about this in documentation?

**Comment by Moshyfawn** [comment] 2022-02-22 08:38
You can create a PR with a change you want to see related to this issue report. We'll review it and potentially include in the docs
