### ISSUE TITLE
OnBlur validation fails on required checkbox on Safari and Firefox

### ISSUE THREAD

**Issue by bpallares** [react-hook-form/react-hook-form#1079] opened 2020-02-21 19:33 UTC
**Describe the bug**
When a form is on `OnBlur` mode and has a required input of type `checkbox`, the form validation fails (`isValid` does not get updated) on Firefox and Safari but works correctly on Chrome

**To Reproduce**

1. Open the Codesandbox link on Chrome and Firefox
2. Click on checkbox
3. `isValid` gets updated on chrome but not in Firefox

**Codesandbox link**
https://codesandbox.io/s/icy-leaf-2bubt

**Expected behavior**
Same behavior across all browsers. More specifically, `isValid` should be `true` on both Firefox and Safari when all required fields ( in this case a checkbox ) are checked or filled.

**Desktop (please complete the following information):**

- MacOS: 10.15.3

* Browser
  * Chrome : 80.0.3987.116 
  * Firefox : 73.0.1
  * Safari : 13.0.5

- Version 4.9.7

**Additional Notes**

if `type="checkbox"` is switched to `type="text"` validation will work as expected across all browsers

**Comment by bpallares** [comment] 2020-02-21 21:30
Can't reproduce the bug in a windows machine.

**Comment by bluebill1049** [comment] 2020-02-21 21:34
can you please read the value before the render?

`console.log(formState.isValid)`

**Comment by bluebill1049** [comment] 2020-02-21 21:34
<img width="1056" alt="Screen Shot 2020-02-21 at 7 45 11 pm" src="https://user-images.githubusercontent.com/10513364/75073739-30a2b100-554e-11ea-87cf-420dd02a7999.png">

**Comment by bluebill1049** [comment] 2020-02-21 21:35
let me know if there is still an issue.

**Comment by stramel** [comment] 2020-02-21 23:32
@bluebill1049 What do you mean by the image you posted?

I can confirm the issue on Mac OSX with Firefox. However, I can get it to properly work by tabbing instead of clicking off the input. 

As basic as this example is, I wouldn't expect it to fail or need a `validationContext` to properly work.

**Comment by bluebill1049** [comment] 2020-02-21 23:35
oops, wrong image... @stramel 
<img width="986" alt="Screen Shot 2020-02-22 at 8 34 42 am" src="https://user-images.githubusercontent.com/10513364/75080089-11f8e600-555f-11ea-8cd7-b4e781e5d29b.png">

**Comment by stramel** [comment] 2020-02-21 23:41
@bluebill1049 That makes a bit more sense but even doing a `console.log(formState.isValid)` before the render doesn't seem to fix it. https://codesandbox.io/s/crazy-chaum-gzmyn

**Comment by bluebill1049** [comment] 2020-02-21 23:46
I think this is at (firefox) browser level. looks like firefox is not trigger onBlur event when clicking away.

**Comment by bluebill1049** [comment] 2020-02-21 23:46
https://bugzilla.mozilla.org/show_bug.cgi?id=756028

**Comment by bluebill1049** [comment] 2020-02-21 23:47
https://bugzilla.mozilla.org/show_bug.cgi?id=756028

**Comment by bluebill1049** [comment] 2020-02-21 23:49
closing this issue :)

**Closed** 2020-02-21 23:48 UTC
Labels: question

**Comment by stramel** [comment] 2020-02-21 23:58
That's fair... but unfortunate...

**Comment by bpallares** [comment] 2020-02-22 01:03
Thanks for the help @stramel @bluebill1049 !

**Comment by stramel** [comment] 2020-02-22 05:39
Here is the Safari bug (13 years): https://bugs.webkit.org/show_bug.cgi?id=13724
