### ISSUE TITLE
V7: Issue with nested field array in tabbed form

### ISSUE THREAD

**Issue by ymor** [react-hook-form/react-hook-form#4812] opened 2021-04-15 13:33 UTC
**Describe the bug**
When using a nested field array within a tabbed layout.  The fieldarray seems to be missing items for a period of time until you trigger a re-render. 

**To Reproduce**

1. Using this sandbox https://codesandbox.io/s/tabs-with-nested-field-array-ci2bz?file=/demo.tsx
2. Click Append Page then select the new page tab.
3. Click Append Sub Page a couple of times.
4. Click the first tab and then click the second tab again. All the sub pages have disappeared.
5. Click Add sub page again (on the second tab) you will now see all the previous created sub pages and the new one

**Codesandbox link (Required)**
https://codesandbox.io/s/tabs-with-nested-field-array-ci2bz?file=/demo.tsx

**Expected behavior**
On revisiting a tab the correct items should be displayed.

**Desktop :**

- OS: Windows
- Browser: Chrome
- Version: 89

**Additional context**
We did take a look at the tabbed form example.  But we want our users to freely move between tabs and submit as a whole rather than it being a wizard style form.

**Comment by mbretter** [comment] 2021-04-16 12:15
I can confirm, that there is something wrong when using Tabs.
I recently upgraded from v6 and all my form using tabs stopped working.
When switching the tab, the input fields on the the activated tab, have the values from the prior open tab, it does not fill the values from the form data.

**Comment by mbretter** [comment] 2021-04-16 12:20
just an additional info, I have watched the form values using watch, the initial data looks like:
```
{
de: {name: "Holländisch"},
en: {name: "Dutcha"},
fr: {name: "D"}
}
```
after typing/changing the input value for the field "name", only the changed value is returned:

```
{
de: {name: "HolländischX"},
}
```
all other subobjects have been removed.

**Comment by bluebill1049** [comment] 2021-04-16 14:21
can you share a video on this one?

**Comment by mbretter** [comment] 2021-04-16 14:32
sure:

https://user-images.githubusercontent.com/1787808/115040070-5668e300-9ed1-11eb-9d50-70afc34a1527.mp4

**Comment by mbretter** [comment] 2021-04-16 14:33
https://user-images.githubusercontent.com/1787808/115040171-6f719400-9ed1-11eb-90f1-f1cd023e0646.mp4

**Comment by mbretter** [comment] 2021-04-16 14:34
https://user-images.githubusercontent.com/1787808/115040382-ab0c5e00-9ed1-11eb-90ae-74bad2acb967.mp4

**Comment by bluebill1049** [comment] 2021-04-16 23:59
thanks @mbretter i was refer to the issue CSB. if you have an issue reproduce it so i can see what's in the code as well.

**Comment by mbretter** [comment] 2021-04-17 05:42
https://codesandbox.io/s/sharp-cloud-48n07?file=/src/App.js

**Comment by bluebill1049** [comment] 2021-04-17 07:51
> https://codesandbox.io/s/sharp-cloud-48n07?file=/src/App.js

<img width="577" alt="Screen Shot 2021-04-17 at 5 51 13 pm" src="https://user-images.githubusercontent.com/10513364/115105995-82559880-9fa5-11eb-9903-947a8638fc75.png">

there only a single input.

**Comment by mbretter** [comment] 2021-04-17 10:54
ok, the issue with watch was my misunderstanding.

This is a CSB with rhf6
https://codesandbox.io/s/thirsty-hooks-k0oo4?file=/src/App.js
When switching the tab it shows correctly the corresponding name.

When doing the same with rhf7, the "English" name remains on the "de" tab. If posting the form the value of the "de" field is English.
Just by switching the tabs, without changing the input field.

I have updated the CSB and added a submit button on both examples.

**Comment by bluebill1049** [comment] 2021-04-17 11:30
This is the same issue that just got merged when inputs get unmounted value gets retained.

**Comment by ymor** [comment] 2021-04-17 11:53
@bluebill1049  Just to check are you awaiting further information from me regarding the original logged issue?  I can look at recording a video of the issue if you've not been able to recreate it in the sandbox.

**Comment by bluebill1049** [comment] 2021-04-17 12:03
> @bluebill1049 Just to check are you awaiting further information from me regarding the original logged issue? I can look at recording a video of the issue if you've not been able to recreate it in the sandbox.

i think your issue is the same @mbretter sharing the same form between tabs, and you expect the value to be removed while changing tabs. if you can confirm that, then i will close this issue. it's not a bug, but we will have a new feature to resolve htis.

**Comment by ymor** [comment] 2021-04-17 12:09
Ah no, I expect the values to be there.  I expect that after I create a new tab, add two sub pages to the second tab.  Then swap to the first tab and then back to the second tab, I should see my two sub page controls straight away.  At the moment they only reappear when you add another subpage (re-render essentially).

**Comment by bluebill1049** [comment] 2021-04-17 12:13
> Ah no, I expect the values to be there. I expect that after I create a new tab, add two sub pages to the second tab. Then swap to the first tab and then back to the second tab, I should see my two sub page controls straight away. At the moment they only reappear when you add another subpage (re-render essentially).

please share a detailed video clip for the behaviour if you can, i couldn't reproduce the issue.

**Comment by ymor** [comment] 2021-04-17 12:23
![NestedFieldArray](https://user-images.githubusercontent.com/2701844/115113022-0f85f680-9f80-11eb-9bc7-8c22dcf89ee5.gif)
Hope this helps!  Let me know if you require anything further.

**Closed** 2021-04-18 00:05 UTC
Labels: Status: under investigation, status: need more detail
