### ISSUE TITLE
issue: shouldFocusError false value is not working

### ISSUE THREAD

**Issue by amansharmaagami** [react-hook-form/react-hook-form#7531] opened 2022-01-14 10:41 UTC
### Version Number

7.20.2

### Codesandbox/Expo snack

No link

### Steps to reproduce

Just create a form with having yup resolver with a schema.

### Expected behaviour

My form is always scrolling when I do change the input.

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment] 2022-01-14 11:08
Can't reproduce. Please, see [this codesandbox](https://codesandbox.io/s/wizardly-feynman-7du8e) and try editing the code to closer match your use-case

**Comment by bluebill1049** [comment] 2022-01-14 11:14
thank you @Moshyfawn closing: https://github.com/react-hook-form/react-hook-form/issues/2848

**Closed by bluebill1049** 2022-01-14 11:14 UTC
Labels: Status: under investigation
