### ISSUE TITLE
7.44.2 fails to build with react-scripts 4.0.3

### ISSUE THREAD

**Issue by uclaeamsavino** [react-hook-form/react-hook-form#10484] opened 2023-06-01 21:55 UTC
### Version Number

7.44.2

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/old-leftpad-wwojcx?welcome=true

### Steps to reproduce

1. Fresh install with react-scripts 4.0.3 on node 14 or node 16
2. npm run build 

FYI - I rolled back to reach-hook-form 7.43.1 and the problem went away. So it's something between those two versions.  

### Expected behaviour

Build succeeds.

### Relevant log output

```shell
npm notice 
➜  workspace git:(master) ✗ npm run build

> react-hook-form-v7-js-template@1.0.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

./node_modules/react-hook-form/dist/index.esm.mjs
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment] 2023-06-01 21:57
Duplicate of #10465

**Comment by uclaeamsavino** [comment] 2023-06-01 21:58
Argh - sorry, I thought I searched. I guess there's no way to delete.

**Closed by Moshyfawn** 2023-06-01 21:57 UTC

**Comment by Moshyfawn** [comment] 2023-06-01 21:59
No worries! Just pointing to some info / workaround on the topic and that we're already looking into it
