### ISSUE TITLE
issue: Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by kadirosmanust** [react-hook-form/react-hook-form#10465] opened 2023-05-30 08:46 UTC
### Version Number

7.44.2

### Codesandbox/Expo snack

-

### Steps to reproduce

When I want to build my app on CRA. I got an error
`
Creating an optimized production build...
Failed to compile.
./node_modules/react-hook-form/dist/index.esm.mjs
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)
`

### Expected behaviour

Build

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kola-Kola** [comment] 2023-05-30 09:25
Thanks to reporting this issue, I have the problem too I use `7.20.5`

**Comment by pellehol** [comment] 2023-05-30 09:46
Same problem with 7.44.2.

**Comment by WangXBruc** [comment] 2023-05-30 10:11
same problem with 7.44.2, lower version is fine

**Comment by bluebill1049** [comment] 2023-05-30 10:23
Honestly, not sure of the root cause of this issue and hence couldn't fix the problem. It generally felt like not related to the library, but I have tagged it as help and wanted to see if anyone else has some clue.

**Comment by JatinAntier** [comment] 2023-05-30 10:57
getting same error in version 7.32.1

**Comment by alisha-sq** [comment] 2023-05-30 11:01
> Are you guys using CRA?

yes

**Comment by bluebill1049** [comment] 2023-05-30 11:21
I think this is an issue related to CRA instead of this libaray.

**Comment by FareedGuru** [comment] 2023-05-30 11:21
My issue was resolved by just removing ^ sign from my old version,

**Comment by alisha-sq** [comment] 2023-05-30 11:23
> My issue was resolved by just removing ^ sign from my old version,

which exact version you are using? 
but using the old version we miss new improvements added to the library

**Comment by Kola-Kola** [comment] 2023-05-30 11:25
> > My issue was resolved by just removing ^ sign from my old version,
> 
> which exact version you are using? by using the old version, we will miss new improvements added to the library

For me, I use `7.27.5` I remove `^` and now I use same version of my package.json `7.20.5` the problem is also on this version

**Comment by FareedGuru** [comment] 2023-05-30 11:26
> > My issue was resolved by just removing ^ sign from my old version,
> 
> which exact version you are using? by using the old version, we will miss new improvements added to the library

 I am using  "react-hook-form": "7.22.3",

**Comment by jjrdevspace01** [comment] 2023-05-30 11:27
does seem to relate to the ^ - for me "^7.33.1" fails but "7.33.1" works ok

**Comment by kadirosmanust** [comment] 2023-05-30 11:27
I downgraded for now and the problem is solved, but it needs to be fixed.

Currently using : "react-hook-form": "7.43.9",

**Comment by JatinAntier** [comment] 2023-05-30 11:37
Yeah after remove ^ my build is creating on server.

**Comment by sglover98** [comment] 2023-05-30 17:07
Removing the "^" worked for me. For those of you who don't read the thread the dev working on this has not been able to find the root cause. 

I started experiencing this issue 2 days ago after the release of React-Hooks-forms 7.44.2. I would assume that all versions before that are fine to use. 

Original
"react-hook-form": "^7.24.1"

New 
"react-hook-form": "7.24.1"

**Comment by bluebill1049** [comment] 2023-05-31 03:06
Could we identify which version caused this issue?

**Comment by Moshyfawn** [comment] 2023-05-31 03:28
Someone needs to throw together their environment reproduction for us to be able to identify the issue. The reported versions vary, so there's a good chance it's an external tool related issue.

**Comment by Moshyfawn** [comment] 2023-05-31 03:33
What React version are ya'all running?

**Comment by ChanYangYu** [comment] 2023-05-31 04:27
> What React version are ya'all running?

I'm using version 17.0.2 of React.
And here are the other dependencies
```
"@craco/craco": "6.4.3",
"react-router-dom": "5.2.1",
"react-scripts": "4.0.1",
```

**Comment by Moshyfawn** [comment] 2023-05-31 05:12
So, it seems like it's simply a stale known CRA issue with a potential work around like in https://github.com/framer/motion/issues/1307#issuecomment-955877279.

facebook/create-react-app#10356

I'm a bit confused as to why it's come up at this time, thought, if that's the case.

**Comment by alisha-sq** [comment] 2023-05-31 05:28
Hey @bluebill1049 

this issue is caused because of the usage of .mjs files. I had seen this in many react packages, this needs a minor change.

adding reference from a package that had resolved this issue:
https://github.com/GoogleChromeLabs/react-adaptive-hooks/pull/41

Could you please verify whether we could do that for our react-hook-form to overcome the issue of using a legacy version of this library?

**Comment by Alex-Lima84** [comment] 2023-05-31 14:51
I had the same issue 

> Removing the "^" worked for me. For those of you who don't read the thread the dev working on this has not been able to find the root cause.
> 
> I started experiencing this issue 2 days ago after the release of React-Hooks-forms 7.44.2. I would assume that all versions before that are fine to use.
> 
> Original "react-hook-form": "^7.24.1"
> 
> New "react-hook-form": "7.24.1"

I had the same issue and this solution worked for me. Thank you.

**Comment by mtr1990** [comment] 2023-05-31 16:52
I had the same issue using for next-app-dir

```js
"next": "^13.4.4",
"react-hook-form": "^7.44.2"
```
NODE: v16.19.1
NPM : 8.19.3

<img width="948" alt="Screenshot 2023-05-31 at 23 47 01" src="https://github.com/react-hook-form/react-hook-form/assets/13531993/88b82052-3001-4924-9a1c-cb3344eb2635">

**Comment by jadam** [comment] 2023-05-31 21:58
build on our QA environment started failing to today with, 
_node: 16.x 
npm install -legacy-peer-deps

_Creating an optimized production build...
Failed to compile.

./node_modules/react-hook-form/dist/index.esm.mjs
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)_

 "react-hook-form": "^7.8.1",  

Changed in package.json  :   

"react-hook-form": "7.8.1",_

Same fix worked, previous build a week ago was working fine not sure what's the cause either.

**Comment by bluebill1049** [comment] 2023-05-31 22:43
Could someone test the RC version and see which one breaks? it could be a deps update.

- 7.44.0-rc.4
- 7.44.0-rc.3
- 7.44.0-rc.2
- 7.44.0-rc.1

**Comment by Moshyfawn** [comment] 2023-05-31 22:50
Sorry, can't repro the issue, hence can't test the rc version 😔

**Comment by Moshyfawn** [comment] 2023-05-31 23:06
K, so, I was able to reproduce the issue. Here's [a repository](https://github.com/Moshyfawn/rhf-deps-test) and **it is** reproducible when running the `start` command. Here's [a codesandbox](https://codesandbox.io/p/github/Moshyfawn/rhf-deps-test/main?file=/src/App.js:10,41&workspaceId=3996f20b-a51c-44e7-9e78-688f175fb918) with [the reproduction](https://github.com/Moshyfawn/rhf-deps-test)

**Comment by Moshyfawn** [comment] 2023-05-31 23:16
[v7.44.0-next.0](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.44.0-next.0) **breaks**, [v7.43.9 ](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.43.9)**doesn't**

**Comment by Moshyfawn** [comment] 2023-05-31 23:17
So, it gotta be something to do with the new `Form` component & how it relies on the React API.

**Comment by domosedov** [comment] 2023-06-01 06:27
Next.js build failed

```
./node_modules/.pnpm/react-hook-form@7.44.2_react@18.2.0/node_modules/react-hook-form/dist/index.esm.mjs
Attempted import error: 'useState' is not exported from 'react' (imported as 'React').

Import trace for requested module:
./node_modules/.pnpm/react-hook-form@7.44.2_react@18.2.0/node_modules/react-hook-form/dist/index.esm.mjs
./node_modules/.pnpm/@hookform+resolvers@3.1.0_react-hook-form@7.44.2/node_modules/@hookform/resolvers/zod/dist/zod.mjs
```

```
"next": "13.4.4"
"react-hook-form": "7.44.2"
"@hookform/resolvers": "^3.1.0"
```

**Comment by cvaught001** [comment] 2023-06-01 21:56
Quick solution for DevOps and Developers as mentioned above would be to pin your dependency version for the time being while this gets sorted out. Remove your '^' indicating latest version in your package.json and go to a previous version.

**Closed** 2023-06-01 22:52 UTC
Labels: status: under investigation

**Comment by Moshyfawn** [comment] 2023-06-01 22:58
Alright, ya'all, the new [v7.44.3](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.44.3) release should fix the issue. Try it and report if there's an issue
