### ISSUE TITLE
Component is rendering twice when using validationSchema

### ISSUE THREAD

**Issue by Rodrigo816** [react-hook-form/react-hook-form#1107] opened 2020-02-26 16:08 UTC
**Describe the bug**
When I use validationSchema the component renders two times. I'm using React Native.

**To Reproduce**
1. Go to https://snack.expo.io/SyPpIMNNU
2. Open the console and check it renders two times
this is a simple demo.

**Expected behavior**
Component should render only one time.

**Version**
react: 16.9.0
react-native: 0.61.5,
react-hook-form: 4.9.3
 yup: 0.28.0

**Comment by bluebill1049** [comment] 2020-02-26 21:03
I couldn't get that expo link to work (maybe try codesandbox). Could you provide more detail?  when it's double re-render?

**Comment by bluebill1049** [comment] 2020-02-26 21:17
try to remove all hook form code, the expo itself re-render twice.

**Comment by Rodrigo816** [comment] 2020-02-27 10:59
Hello,

Sorry I didn't check the default behavior of expo.

I made a demo to Illustrate the behavior.
https://github.com/Rodrigo816/ReactHookFormDemo

You can run the project by 
` npm install`
`react-native run-android`

I'm also gonna paste the code here:

```
import React from 'react';
import {TextInput, Button, View} from 'react-native';
import {useForm, Controller} from 'react-hook-form';
import * as yup from 'yup';

const App = () => {
  const {handleSubmit, control, errors} = useForm({
    validationSchema: yup.object().shape({
      firstName: yup
        .string()
        .label('Name')
        .required(),
    }),
  });

  const onSubmit = formData => {
    console.log('Form Data', formData);
  };

  const onChange = args => {
    return {
      value: args[0].nativeEvent.text,
    };
  };

  console.log('The component App was been render');
  return (
    <View style={{marginTop: 40}}>
      <Controller
        as={
          <TextInput
            style={{borderWidth: 1, height: 80}}
            placeholder="your name"
          />
        }
        control={control}
        name="firstName"
        onChange={onChange}
      />
      <Controller
        as={<TextInput style={{borderWidth: 1, height: 80}} />}
        control={control}
        name="lastName"
        onChange={onChange}
      />
      <Button title="Submit" onPress={handleSubmit(onSubmit)} />
    </View>
  );
};

export default App;

```

I think there is nothing wrong with the code.

![hooks](https://user-images.githubusercontent.com/12116265/75438345-4eee1f80-5947-11ea-8ad5-bfcdf6d31323.png)

You also had a similar issue on the past: https://github.com/react-hook-form/react-hook-form/issues/704
I tested on the web and works fine but on react-native is not working as intended.

I hope you understand my concerns.

**Comment by bluebill1049** [comment] 2020-02-29 08:03
<img width="836" alt="Screen Shot 2020-02-29 at 7 02 48 pm" src="https://user-images.githubusercontent.com/10513364/75603805-1b1d2080-5b26-11ea-9ce5-39c685677292.png">

```
import React from 'react';
import {TextInput, Button, View} from 'react-native';
import {useForm, Controller} from 'react-hook-form';
import * as yup from 'yup';


let counter = 0;

const App = () => {
  const {handleSubmit, control, errors} = useForm({
    validationSchema: yup.object().shape({
      firstName: yup
        .string()
        .label('Name')
        .required(),
    }),
  });

  const onSubmit = formData => {
    console.log('Form Data', formData);
  };

  const onChange = args => {
    return {
      value: args[0].nativeEvent.text,
    };
  };

  counter++;

  console.log('The component App was been render', counter);
  return (
    <View style={{marginTop: 40}}>
      <Controller
        as={
          <TextInput
            style={{borderWidth: 1, height: 80}}
            placeholder="your name"
          />
        }
        control={control}
        name="firstName"
        onChange={onChange}
      />
      <Controller
        as={<TextInput style={{borderWidth: 1, height: 80}} />}
        control={control}
        name="lastName"
        onChange={onChange}
      />
      <Button title="Submit" onPress={handleSubmit(onSubmit)} />
    </View>
  );
};

export default App;
```

Couldn't reproduce the issue above. closing

**Comment by bluebill1049** [comment] 2020-02-29 08:03
if anyone having similar issue let me know.

**Closed by bluebill1049** 2020-02-29 08:03 UTC
Labels: Status: under investigation, react-native

**Comment by Rodrigo816** [comment] 2020-03-02 11:05
Its weird, I tested the your code on my friend pc and still renders two times.
I don't get what could be causing this.

**Comment by bluebill1049** [comment] 2020-03-02 11:07
very strange, I spend quite a bit of m time try to reproduce such behavior but couldn't.

**Comment by Rodrigo816** [comment] 2020-03-02 11:12
you used expo right?

**Comment by bluebill1049** [comment] 2020-03-02 11:12
yes i did
