### ISSUE TITLE
 [TypeScript] Export useForm return types

### ISSUE THREAD

**Issue by ManAnRuck** [react-hook-form/react-hook-form#296] opened 2019-09-06 07:40 UTC
**Is your feature request related to a problem? Please describe.**
Passing for example the register function from useForm to a child component with typescript isn't easy without exported register type

**Describe the solution you'd like**
i want to pass some return values (for example watch, setValue, register, …) to a child component.
But currently i can't access the watch type to add this as type definition for a prop.
is it possible to export the types like on this image?

<img width="777" alt="Bildschirmfoto 2019-09-05 um 10 37 52" src="https://user-images.githubusercontent.com/2183135/64409969-50224c00-d08a-11e9-9350-c39dcbe8f2e9.png">

**Comment by ManAnRuck** [comment] 2019-09-06 17:02
@bluebill1049 do you have an idea/hint to solve it? I wanted to create a PR but I really have no idea how it could work with nested functions 🙈

**Comment by bluebill1049** [comment] 2019-09-06 21:36
what do you mean nested function? 🤔

**Comment by stramel** [comment] 2019-09-07 17:47
@ManAnRuck 	Can you provide a codesandbox? You might be able to do something like this as a workaround for now, `Pick<ReturnType<typeof useForm>, 'register'>`.

**Comment by ManAnRuck** [comment] 2019-09-08 08:29
<img width="582" alt="Bildschirmfoto 2019-09-08 um 09 36 28" src="https://user-images.githubusercontent.com/2183135/64485098-31ec5580-d21c-11e9-8d66-e702b35ae056.png">
@stramel thanks, but I have some errors with this workaround.
I currently not so familiar with CodeSandbox but I try to prepare this 😅
https://codesandbox.io/s/react-hook-form-get-form-values-fxufd?fontsize=14

@bluebill1049 I mean I don't know how it works with typescript to get the ReturnTypes of generic functions.

**Comment by stramel** [comment] 2019-09-08 21:29
@ManAnRuck 	You're providing an object to your typing. 

You would want to do something like this,
`type ChildInputProps = Pick<ReturnType<typeof useForm>, "register">;` 
or
`interface ChildInputProps extends Pick<ReturnType<typeof useForm>, "register"> {}`

**Comment by ManAnRuck** [comment] 2019-09-09 07:06
thanks @stramel 
I tried both your examples, but both return me
```ts
{
  register: any
}
```
<img width="767" alt="Bildschirmfoto 2019-09-09 um 08 59 39" src="https://user-images.githubusercontent.com/2183135/64509899-0a12f580-d2e1-11e9-8966-16b19365100e.png">

I'm not sure if I can use the FormContext for my case. I want do prepare ant.design inputs to work in multiple forms. (ref doesn't work with antd)

**Comment by bluebill1049** [comment] 2019-09-14 05:10
hmmm looks like I couldn't sort this one out as well :( @stramel you able to give more suggestions?

**Comment by lemcii** [comment] 2019-09-26 14:21
I'm currently doing similar, but using `useFormContext` instead, to get access to `register`

**Comment by bluebill1049** [comment] 2019-09-27 03:57
@ManAnRuck hope @lemcii 's answer helps you abit :)

**Comment by stramel** [comment] 2019-09-27 14:03
@ManAnRuck or @lemcii can you provide a way to reproduce getting `any`? When I tried what I suggested, it properly resolved to the function typing.

**Comment by bluebill1049** [comment] 2019-09-29 13:16
going to close this as we have some suggestion from above, feel free to re-open if those r not helpful.

**Closed by bluebill1049** 2019-09-29 13:16 UTC
Labels: help wanted

**Comment by mr-bjerre** [comment] 2019-10-31 12:34
As far as I can tell I am trying to achieve the same thing.

I want to create my own typescripted UI input components. However this doesn't work

```typescript
type ChildInputProps = Pick<ReturnType<typeof useForm>, "register">
const TextInput: React.FC<{
    register: ChildInputProps
}> = ({register})  => {
    return <input name={'abc'} ref={register}/>
};
```

Any help is much appreciated

**Comment by Motoxpro** [comment] 2019-12-08 03:02
Just wanted to add this here in case someone else stumbles on it.

I wanted to create a custom interface with a few useForm props so I need to get them individually.

Here is what I did:

```
interface ExtendedDateTimePickerProps {
  reactHookFormProps?: {
    register: ReturnType<typeof useForm>['register'];
    setValue: ReturnType<typeof useForm>['setValue'];
  };
  pickerType: 'date' | 'dateTime' | 'time';
}
```

Thanks for the great library!!

**Comment by bluebill1049** [comment] 2019-12-08 03:14
awesome @Motoxpro thanks for helping and share your finding!

**Comment by chris-fran** [comment] 2020-03-14 19:49
Seems to me like it would be easier if we could just import the typings directly from the library, rather than manually doing this hack, though

**Comment by tomerds** [comment] 2020-11-25 11:58
UseFormMethods['register']

**Comment by bluebill1049** [comment] 2020-11-25 21:54
all types are exported from this lib. 👍 

here is the list of official documented types: https://react-hook-form.com/ts
